### ISSUE TITLE
wts, what am I doing wrong

### ISSUE THREAD

**Issue by timpiperseek** [vincentarelbundock/marginaleffects#1004]
so if I do the following

```
require(estimatr)
fit <- lm_robust(ctr_exp ~ flight + ctr_pre , df_robust, weights = impressions_exp, clusters = url)
summary(fit)

require(marginaleffects)
predictions(fit,  variables = 'flight', wts='impressions_exp', newdata = df_robust[,c('flight','ctr_pre','impressions_exp')] )
```

I get the following error. 
```
Error: The `wts` argument must be a numeric vector of length 548, or a string which matches a column name in `newdata`. If you did not supply a `newdata` explicitly, `marginaleffects` extracted it automatically from the model object, and the `wts` variable may not have been available. The easiest strategy is often to supply a data frame such as the original data to `newdata` explicitly, and to make sure that it includes an appropriate column of weights, identified by the `wts` argument.
```

what am I doing wrong? I feel like this should work.

**Comment by vincentarelbundock** [comment]
Does `impressions_exp` have 548 non-`NA` values in it?

**Comment by timpiperseek** [comment]
The following returns 0
```
sum(is.nan(df_robust$impressions_exp))
```

But technically the impressions_exp vector only has a length of 274, only half of 548

**Comment by vincentarelbundock** [comment]
I was asking about `NA`, not `nan`...

But what is your dataset dimension then? Maybe try to subset it and do listwise deletion before fitting your model and before trying `marginaleffects` just to see what happens.

**Comment by vincentarelbundock** [comment]
Feel free to keep commenting if you can supply more details and a minimal reproducible example. As it stands, I don't have enough information to diagnose the problem.
