### ISSUE TITLE
`avg_comparisons()` not working when predictor is also response variable

### ISSUE THREAD

**Issue by winterstat** [vincentarelbundock/marginaleffects#1006]
I use `brms` to run my models, and when I have data with missing values, I use the `brms::mi()` function. This means that the resulting models are multivariate, and predictors for which data are imputed are also response variables of their own imputation model. The example below is taken from the `brms::mi()` documentation.

```
library(brms)
library(marginaleffects)

data("nhanes", package = "mice")

bform <- bf(bmi | mi() ~ age * mi(chl)) +
  bf(chl | mi() ~ age) + set_rescor(FALSE)


fit_imp <- brm(bform, data = nhanes)
```

Using `avg_comparisons()` for a predictor that is solely a predictor (e.g., age) works great:

```
avg_comparisons(fit_imp, variables = list(age = 1))

Group Term Contrast Estimate 2.5 %  97.5 %
   bmi  age       +1    -3.13 -5.99 -0.0357
   chl  age       +1    28.55  2.12 54.8092

Columns: term, group, contrast, estimate, conf.low, conf.high 
Type:  response 
```

But when I try to get a comparison for `chl`, I get the following error:

```
avg_comparisons(fit_imp, variables = list(chl = 1))
Error: There are no valid predictor variables. Please make sure your model includes predictors and
  use the `variables` argument.
```

Searching the repository, I can see that this error is part of the `sanitize_variables()` function, and the comment with it suggests that you can't get average marginal effects for response variables. Is that true even if they are predictors of other response variables too?

Updated to add: If I run the following code, I do get output for both predictors:

```
> avg_comparisons(fit_imp2, variables = list(age = 1, chl = 1))

 Group Term Contrast Estimate     2.5 %  97.5 %
   bmi  age       +1  -3.0303 -6.029348  0.0885
   chl  age       +1  28.4620  2.168379 55.0138
   bmi  chl       +1   0.0458 -0.000131  0.0947
   chl  chl       +1   0.0000  0.000000  0.0000

Columns: term, group, contrast, estimate, conf.low, conf.high 
Type:  response 
```

Thanks!

**Comment by vincentarelbundock** [comment]
Thanks a lot for the detailed bug report and example.

I confirm that I can replicate the problem on my computer, and will look into it as soon as I find some time.

**Comment by vincentarelbundock** [comment]
Should now work with the Github version:

``` r
library(brms)
library(marginaleffects)
data("nhanes", package = "mice")
bform <- bf(bmi | mi() ~ age * mi(chl)) + bf(chl | mi() ~ age) + set_rescor(FALSE)
fit <- brm(bform, data = nhanes)

avg_comparisons(fit)
# 
#  Group Term Contrast Estimate    2.5 %  97.5 %
#    bmi  age       +1  -3.0457 -5.94406  0.0313
#    chl  age       +1  28.2003  1.42116 55.4872
#    bmi  bmi       +1   0.0000  0.00000  0.0000
#    chl  bmi       +1   0.0000  0.00000  0.0000
#    bmi  chl       +1   0.0465  0.00161  0.0929
#    chl  chl       +1   0.0000  0.00000  0.0000
# 
# Columns: term, group, contrast, estimate, conf.low, conf.high 
# Type:  response
```
