### ISSUE TITLE
Standard Error From Sandwich Package Not Supported for fixest estimate in avg_slope function

### ISSUE THREAD

**Issue by mayanlei123** [vincentarelbundock/marginaleffects#1008]
Hello,

I'm trying to get robust standard error estimates (presumably through sandwich package) for average marginal effect using avg_slope function for a model estimated using fixest package (fixglm).  Even though on your website it says models estimated from "fixest" package is supported, and the sandwich package also says models estimated using "fixest" is supported, when I run the avg_slope command specifying vcov = "HC3" or vcov = ~clustervar, it returns a warning message of the following: 

"Unable to extract a variance-covariance matrix using this `vcov` argument. Standard errors are computed using the default variance instead. Perhaps the model or argument is not supported by the `sandwich` or  `clubSandwich` packages. If you believe that the model is supported by one of these two packages, you can open a feature request on Github. "

Could you please kindly check and see why robust standard errors are not supported by "fixest"?

Here is a sample code of what I'm doing:

mod = feglm(D_AT_LEAST_1 ~ 
                                                 FAC_AGE_REC + 
                                                 FAC_SEX + 
                                                 FAC_RACE_REC + 
                                                 D_FULL_DUAL + 
                                                 FAC_D_PLAN_TYPE + 
                                                 FAC_OREC                                              
                                                 | as.factor(ST_CNTY_CD), TEMP_DAT_REG_YEAR, family="binomial")

AME1 = avg_slopes(mod, newdata = DAT_AME, vcov=~as.factor(ST_CNTY_CD))
AME2 = avg_slopes(mod, newdata = DAT_AME, vcov="HC3")

**Comment by vincentarelbundock** [comment]
I don't believe that sandwich does infact support fixest models.

With fixest, it should be sufficient to specify the type of vcov you want when fitting the model, in fixest's own functions.

You can try different values there and will probably see that SEs change in margibaleffects automatically.

**Comment by vincentarelbundock** [comment]
Notice that the estimates are the same but the standard errors differ:

``` r
library(fixest)
library(marginaleffects)
mod_iid <- feols(mpg ~ hp, mtcars)
mod_clu <- feols(mpg ~ hp, mtcars, vcov = ~carb)

avg_slopes(mod_iid)
# 
#  Term Estimate Std. Error     z Pr(>|z|)    S   2.5 %  97.5 %
#    hp  -0.0682     0.0101 -6.74   <0.001 35.9 -0.0881 -0.0484
# 
# Columns: term, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high 
# Type:  response
avg_slopes(mod_clu)
# 
#  Term Estimate Std. Error     z Pr(>|z|)    S   2.5 %  97.5 %
#    hp  -0.0682      0.014 -4.86   <0.001 19.7 -0.0958 -0.0407
# 
# Columns: term, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high 
# Type:  response
```
