### ISSUE TITLE
plot_predictions - intercept level

### ISSUE THREAD

**Issue by Lefty2021** [vincentarelbundock/marginaleffects#1012]
Hi, the non conditioned categorical variables shouldn't stay in the intercept level by default? 

Eg, 

Data to model - var_1 as a character or factor get the same issue
`inputData <- mtcars %>% 
  select(var_1 = vs,  var_2 = hp,  mpg)  %>% 
  mutate(var_1 = ifelse(var_1 == 0, 2, var_1),  var_1= as.character(var_1), 
         )`

`inputData %>% str`
The model 
`lm1 <- lm(mpg ~ var_1 + var_2 ,
          data = inputData)`

summary(lm1) 
The intercept contains the level == 1 from var_1 
`inputData$var_1 %>% contrasts()`

But the default (not included in condition) plot has the var_1 in the level "2" and not on intercept. Should this be happening? 
`plot_predictions(lm1, condition = list('var_2', 'var_1' = '1')) +
  plot_predictions(lm1, condition = list('var_2', 'var_1' = '2')) +
  plot_predictions(lm1, condition = list('var_2')) 
`
![image](https://github.com/vincentarelbundock/marginaleffects/assets/88385159/80c91259-8483-41d4-8578-6c5fd9d64b3e)

Note that by purpose I changed the levels of the `vs` from 0-1 to 1-2. When the 0-1 is used the issue won't appear and the plot_prediction will show the intercept level - 0
Also, in case of more than 2 levels I couldn't find the above issue

**Comment by vincentarelbundock** [comment]
I think I see what you mean.

But this is the expected behavior. Please read this part of the `plot_predictions()` documentation carefully:

![Screenshot 2024-02-02 092851](https://github.com/vincentarelbundock/marginaleffects/assets/987057/02b7a0ab-a58e-4543-8674-e0a4119164e5)

**Comment by vincentarelbundock** [comment]
The case you are showing now is different than the previous one. Earlier, `marginaleffects` had no way of guessing the user's intention; we could not know what was the "intercept" -- 1 or 2.

In your new example, the variable is a factor, and presumably the reference level of that factor is meaningful. In that case, I think I agree that a more natural default would be to return the reference level as the default category.

I opened a separate issue with a more targeted issue to consider this specific change here:  https://github.com/vincentarelbundock/marginaleffects/issues/1013

If I implement the change in that other issue, the defaults will also change automatically in `plot_predictions()` as you would expect.

**Comment by Lefty2021** [comment]
The data, modelling and output is exactly the same when I open this. I didn't use the sjPlot at the beginning, indeed. But the issue it's the same. 

>  we could not know what was the "intercept" 
`plot_predictions` get the model which provides the intercept level 

Also, once again (as I noted in the first post) when your levels are [0, 1] it does shows the intercept level 
I replicate the script from the 1st post but I change the levels to [0, 1] 
`
inputData <- mtcars %>%  select(var_1 = vs,  var_2 = hp,  mpg)  %>%  
  mutate(#var_1 = ifelse(var_1 == 0, 2, var_1),  
         var_1= as.character(var_1),  )
lm1 <- lm(mpg ~ var_1 + var_2 , data = inputData)
plot_predictions(lm1, condition = list('var_2', 'var_1' = '0')) + plot_predictions(lm1, condition = list('var_2', 'var_1' = '1')) + plot_predictions(lm1, condition = list('var_2'))  

![image](https://github.com/vincentarelbundock/marginaleffects/assets/88385159/06b8c1ac-151f-41dd-b4e1-8bf113c01d04)

`

**Comment by vincentarelbundock** [comment]
>



> The data, modelling and output is exactly the same when I open this. I didn't use the sjPlot at the beginning, indeed. But the issue it's the same.
> 
> > we could not know what was the "intercept"
> > `plot_predictions` get the model which provides the intercept level
> 
> Also, once again (as I noted in the first post) when your levels are [0, 1] it does shows the intercept
 
It does *not* show the intercept. It shows the *mode*, but the two happen to coincide. The most frequent value in of `mtcars$vs` is 0.

When you do  `ifelse(var_1 == 0, 2, var_1)`, you flip the direction and the most frequent value in `var_1` is `2`.
