### ISSUE TITLE
Named hypotheses

### ISSUE THREAD

**Issue by kylebutts** [vincentarelbundock/marginaleffects#1018]
I am wondering if it's possible to have custom named hypotheses in `hyptoheses` and `predictions` using a named vector. With verbose variable names, it ends up printing really poorly (e.g. average post-treatment effect for 5 post-periods). I would want to rename it to `avg_post` or something?
``` r
predictions(
    mod,
    hypothesis = "(b2 - b1) / (b3 - b2) = 0",
    newdata = datagrid(am = 0:1, vs = 0:1))
#> 
#>               Term Estimate Std. Error      z Pr(>|z|)   S 2.5 % 97.5 %
#>  (b2-b1)/(b3-b2)=0    -8.03         17 -0.473    0.636 0.7 -41.3   25.2
#> 
#> Columns: term, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high 
#> Type:  response
```

``` r
predictions(
    mod,
    hypothesis = c("test1" = "(b2 - b1) / (b3 - b2) = 0"),
    newdata = datagrid(am = 0:1, vs = 0:1))
#> 
#>   Term Estimate Std. Error      z Pr(>|z|)   S 2.5 % 97.5 %
#>  test1    -8.03         17 -0.473    0.636 0.7 -41.3   25.2
#> 
#> Columns: term, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high 
#> Type:  response
```

This could also be used with `Arbitrary functions: FUN`

**Comment by vincentarelbundock** [comment]
Oooh, that's a cool idea!

Frankly, I'm not sure when I'll have time to look at it (crazy at work these days), but it definitely should be on the wishlist.

It might just be a matter of changing a couple lines in this function (not 100% sure): https://github.com/vincentarelbundock/marginaleffects/blob/main/R/get_hypothesis.R#L243
