### ISSUE TITLE
Contrasts between multiple categories

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/marginaleffects#1024]
Contrasts between multiple categories. For example:

> What is the difference between average predictions for Gear = 3 or Gear = 4, and Gear =5?

Current, this is difficult to achieve, because the whole `marginaleffects` infrastructure is built to compute functions of *one or two* predictions. It *is* possible to achieve, by using a `data.frame` for custom aggregations in the `predictions` function.

For example, we start by estimating a simple model and computing predictions for each category of `gear`, holding `drat` at its mean:

``` r
library(marginaleffects)
m <- lm(mpg ~ factor(gear) * drat, mtcars)

p <- predictions(m,
  newdata = datagrid(gear = unique, drat = range))
p
# 
#  gear drat Estimate Std. Error    z Pr(>|z|)    S 2.5 % 97.5 %
#     3 2.76     15.4       2.02 7.60   <0.001 44.9 11.41   19.3
#     3 4.93     19.6       8.05 2.44   0.0147  6.1  3.86   35.4
#     4 2.76     12.4       5.77 2.15   0.0313  5.0  1.11   23.7
#     4 4.93     32.9       4.10 8.03   <0.001 49.9 24.88   40.9
#     5 2.76     17.1       7.03 2.43   0.0151  6.1  3.31   30.9
#     5 4.93     25.2       6.24 4.03   <0.001 14.1 12.92   37.4
# 
# Columns: rowid, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, mpg, gear, drat 
# Type:  response
```

Then, we create a `data.frame` of custom group labels, and use it to compute the average prediction of the 3-4 and 5 groups, using the `by` argument:

``` r
by <- expand.grid(
  gear = unique(p$gear),
  drat = unique(p$drat)) |>
  transform(by = sprintf(
      "(Drat = %.1f; Gear = %s)",
      drat,
      ifelse(gear == 5, "4 or 5", "5")))

p <- predictions(m,
  newdata = datagrid(gear = unique, drat = range),
  by = by)
p
# 
#                           By Estimate Std. Error    z Pr(>|z|)    S 2.5 % 97.5 %
#  (Drat = 2.8; Gear = 5)          13.9       3.06 4.55   <0.001 17.5  7.91   19.9
#  (Drat = 4.9; Gear = 5)          26.3       4.51 5.82   <0.001 27.3 17.42   35.1
#  (Drat = 2.8; Gear = 4 or 5)     17.1       7.03 2.43   0.0151  6.1  3.31   30.9
#  (Drat = 4.9; Gear = 4 or 5)     25.2       6.24 4.03   <0.001 14.1 12.92   37.4
# 
# Columns: estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, by 
# Type:  response
```

Finally, we continue building by calling the `hypothesis` argument for pairwise contrasts between our group-averaged predictions:

``` r
p <- predictions(m,
  newdata = datagrid(gear = unique, drat = range),
  by = by,
  hypothesis = "pairwise")
p
# 
#                                                       Term gear drat Estimate Std. Error      z Pr(>|z|)   S  2.5 % 97.5 %
#  (Drat = 2.8; Gear = 5) - (Drat = 4.9; Gear = 5)              3 2.76   -12.37       6.76 -1.831   0.0671 3.9 -25.61  0.872
#  (Drat = 2.8; Gear = 5) - (Drat = 2.8; Gear = 4 or 5)         3 4.93    -3.18       7.66 -0.415   0.6779 0.6 -18.20 11.838
#  (Drat = 2.8; Gear = 5) - (Drat = 4.9; Gear = 4 or 5)         4 2.76   -11.26       6.95 -1.620   0.1053 3.2 -24.88  2.365
#  (Drat = 4.9; Gear = 5) - (Drat = 2.8; Gear = 4 or 5)         4 4.93     9.19       8.35  1.100   0.2714 1.9  -7.18 25.558
#  (Drat = 4.9; Gear = 5) - (Drat = 4.9; Gear = 4 or 5)         5 2.76     1.11       7.70  0.145   0.8849 0.2 -13.98 16.212
#  (Drat = 2.8; Gear = 4 or 5) - (Drat = 4.9; Gear = 4 or 5)    5 4.93    -8.07      12.63 -0.639   0.5228 0.9 -32.83 16.686
# 
# Columns: rowid, term, gear, drat, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, mpg 
# Type:  response
```

**Comment by vincentarelbundock** [comment]
Lots of great examples with matrix contrasts here from @mattansb

https://gist.github.com/mattansb/417f2c5be1059ce44729175cc90eb0bb?permalink_comment_id=4902712#gistcomment-4902712

**Comment by vincentarelbundock** [comment]
@mattansb The development version of `marginaleffects` on Github is not much more flexible in accepting custom functions in the `hypothesis` argument of all its functions. This is an extremely powerful strategy, but it can be tedious to create appropriate labels or apply functions by subgroups.

Thus, I have created a `specify_hypothesis()` function. This is a helper that returns a function which can then be passed to the `hypothesis` argument for complex aggregation or hypothesis testing. This is powerful, because it not only allows differences, but also any user-supplied function to compare estimates.

Admittedly, this still feels like a power user feature, but I like it because it's sooooo flexible. I'm keen to get feedback and suggestions on how to make this easier more intuitive. At least the machinery is all there now.

Tutorial here: https://marginaleffects.com/vignettes/hypothesis.html#functions

I recommend reading the "Functions" section from the top before getting to `specify_hypothesis()`.

**Comment by mattansb** [comment]
Oh way cool! Thanks @vincentarelbundock !
