### ISSUE TITLE
Higher order derivatives

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/marginaleffects#1025]
Might be nice? Velocity?

Probably very hard to implement given the current framework. 

I do not think that I will have the bandwidth to implement this anytime soon. If someone knows the `marginaleffects` code base well and has a *very specific* idea of how to implement this, I would be happy to discuss.

**Comment by Sandhu-SS** [comment]
Hi, 
It's a good idea but unlike prediction i.e., ```f(x)```,  R packages do no provide functions to compute derivatives ```f'(x)```. Differentiation of functions is rather tedious. Below I show an example of polynomial which is simple to differentiate by just following the *power rule*. 

I think ```marginaleffects::slopes()``` already provides velocity curve by means of partial derivative w.r.t to the predictor (typically age in growth studies)


``` r
suppressPackageStartupMessages({
  suppressWarnings({
    library(ggplot2)
    library(dplyr)
  })
}) 


set.seed(20)
x <- seq(from=1, to=20, by=0.1)
n <- length(x)
y <- 10 + 1 * I(x^1) + 1 *  I(x^2) + 1 *  I(x^3) - 0.035 *  I(x^4)
e <- rnorm(n, mean=0, sd=2)
y <- y + e

data <- cbind.data.frame(y, x)

# Fit cubic polynomial model
model <- lm(y ~  poly(x, degree = 3, raw = TRUE), data = data)

# Get distance curve i.e,  f(x)
mdis <- marginaleffects::predictions(model)

# Get velocity curve i.e,  f'(x)
mvel <- marginaleffects::slopes(model,  variables = c("x"))


# Now create polynomial design matrix manually and then estimate distance and 
# velocity curves manually by differentiating the polynomial equation via power rule

# polynomial design matrix - same as poly(x, degree = 3, raw = TRUE)
# Explicitly create cons column as well 
xmat <- cbind (1, x, x^2, x^3)
colnames(xmat) <- c('cons', 'x1', 'x2', 'x3')

# Fit model
model <- lm(y ~ 0 + xmat, data = data)

# Get distance curve f(x)
fx <- xmat %*% coef(model)

# Now differentiating polynomial equation for first derivative
# Note that intercept is not included in first derivative  
# For ease of handling %*% multiplication without sub setting  matrix, 
# the cons is assigned 0 value which is same as excluding this term 
# The polynomial terms are differentiated via power rule - x^n = n*x^n-1
# 1*x^1-1 -> 1*x^0 -> 1

vmat <- cbind (0, 1, 2*x^1, 3*x^2)
colnames(vmat) <- c('cons', 'x1', 'x2', 'x3')
vx <- vmat %*% coef(model)

# Now plot distance curves obtained via marginaleffects::predictions and manual method
data %>% ggplot(., aes(x = x)) +
  geom_line(aes(y = fx), color = 'green') + 
  geom_line(aes(y = mdis$estimate), color = 'red') +
  labs(title = "Distance, f (x)")
```

![](https://i.imgur.com/bZnPxnL.png)

``` r



# Now plot velocity curves obtained via marginaleffects::slopes and manual method
data %>% ggplot(., aes(x = x)) +
  geom_line(aes(y = vx), color = 'green') + 
  geom_line(aes(y = mvel$estimate), color = 'red') + 
  labs(title = "Velocity, f '(x)")
```

![](https://i.imgur.com/Oha3Qhk.png)

<sup>Created on 2024-02-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by vincentarelbundock** [comment]
The slopes() function in marginaleffects computes the first derivative of the outcome equation. See the vignette on slopes.

**Comment by vincentarelbundock** [comment]
Yes, slopes() computes the first derivative.

**Comment by Sandhu-SS** [comment]
But I think function itself is not differentiated but rather distance curve is numerically differentiated to get the velocity curve. But it seems reasonable considering the fact that ```marginaleffects``` supports more that 100 models and it is not possible to write ```f'(x)``` for all of them.

**Comment by vincentarelbundock** [comment]
Yes, it's a numerical not a symbolic derivative.
