### ISSUE TITLE
Lme Objects, Robust Standard Errors and avg_predictions()

### ISSUE THREAD

**Issue by mprimbs** [vincentarelbundock/marginaleffects#1028]
Dear Team,

I'm estimated a mixed-effects model with nlme::lme() and want to use marginaleffects::avg_predictions() on the lme object.

After running the code:

ModelWeek1 <- nlme::lme(IAT_Score ~ BeginProtests_f + age_centred + genderIdentity_f,
random = (~ 1 | STATE),
data = df_propensity_wts,
na.action = "na.omit",
control = lmerControl(optimizer = "bobyqa", calc.derivs = FALSE),
weights = ~1/wts)

avg_predictions(ModelWeek1,
variables = "BeginProtests_f",
wts = "wts",
vcov = "HC3")

I get the following warning message:

Warning message:
Unable to extract a variance-covariance matrix using this vcov argument. Standard errors are computed using the default variance
instead. Perhaps the model or argument is not supported by the sandwich or clubSandwich packages. If you believe that the
model is supported by one of these two packages, you can open a feature request on Github.

I looked at the sandwich help pages and it seems that lme objects are supported (https://rdrr.io/cran/clubSandwich/man/vcovCR.lme.html).

Hence, I`m contacting you here to see whether I'm doing something wrong and/or how to use avg_predictions() successfully with robust standard errors.

Best Regards,

Max

**Comment by vincentarelbundock** [comment]
HC3 is provided by `sandwich`, so you have to check that package to make sure it is supported. 

You may want to try a different type of errors supported by `clubSandwich` (ex: "CR0") or some clustered version. Or you can first generate a variance covariance matrix with `clubSandwich` and your model, and then feed that matrix to the `vcov` argument.

**Comment by mprimbs** [comment]
Thanks! Generating a variance covariance matrix with vcovCR and then feeding it to vcov worked.

**Comment by mprimbs** [comment]
It does not seem possible to directly use "CR0" for the vcov argument or to use the vcovCR argument or something of the sorts directly

**Comment by vincentarelbundock** [comment]
great!
