### ISSUE TITLE
Response scale for logistic regression returns unexpected CI

### ISSUE THREAD

**Issue by strengejacke** [vincentarelbundock/marginaleffects#1029]
For following example, the predicted values are both on the response scale (probabilities), but the CI differ. Is this intentional, or did I miss something? I thought for `type = "response"`, CI would also be on the probability scale.

``` r
dat2 <- data.frame(
  sex = c("m", "w", "w", "m", "w", "w", "m", "w", "w", "m", "m", "w", "w"),
  smoking = c(0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1),
  age = c(10, 45, 50, 40, 45, 12, 14, 55, 60, 10, 14, 50, 40)
)
m3 <- glm(smoking ~ sex, data = dat2, family = binomial("logit"))

marginaleffects::avg_predictions(m3, by = "sex", type = "response")
#> 
#>  sex Estimate Std. Error    z Pr(>|z|)    S  2.5 % 97.5 %
#>    m     0.20      0.179 1.12    0.264  1.9 -0.151  0.551
#>    w     0.75      0.153 4.90   <0.001 20.0  0.450  1.050
#> 
#> Columns: rowid, sex, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, rowid_dedup 
#> Type:  response
marginaleffects::avg_predictions(m3, by = "sex", type = "invlink(link)")
#> 
#>  sex Estimate Pr(>|z|)   S  2.5 % 97.5 %
#>    m     0.20    0.215 2.2 0.0272  0.691
#>    w     0.75    0.178 2.5 0.3771  0.937
#> 
#> Columns: rowid, sex, estimate, p.value, s.value, conf.low, conf.high, rowid_dedup 
#> Type:  invlink(link)
```

**Comment by vincentarelbundock** [comment]
The first is a symmetric interval built using standard errors computed directly on the response scale.

The second is obtained by computing a symmetric interval on the link scale and backtransforming the bounds.

It is normal and expected that these will differ.

**Comment by strengejacke** [comment]
I see. Is there a use case for the first example? The CIs are apparently "incorrect", because they indicate negative probabilities.
What would we the "best" or "correct" `type` for glm's, including Poisson? Always `invlink(link)`?

**Comment by vincentarelbundock** [comment]
Yes, that's what it's default.

But AFAIK there is no straightforward analogous strategy for more complex quantities like slopes or contrasts.

**Comment by strengejacke** [comment]
Ok, I understand. Is there an overview for which models the default is set to `invlink(link)`? I would need to know (for my package) for which models the option `"response"` needs to be changed to `invlink(link)`.

**Comment by vincentarelbundock** [comment]
The type_dictionary file all the defaults.

**Comment by strengejacke** [comment]
Is that accessible from other packages (i.e. exported)?

**Comment by strengejacke** [comment]
Else, I would simply copy that data into my code (and update every now and then)

**Comment by vincentarelbundock** [comment]
No it's internal. But it's basically only glm and gam.

**Comment by strengejacke** [comment]
Ok, thanks!

**Comment by strengejacke** [comment]
Not sure if this is related, but is the documentation regarding this topic outdated?

https://marginaleffects.com/vignettes/uncertainty.html#standard-errors-and-intervals-for-predictions

> The predictions() function can compute the confidence intervals in two ways. If the following conditions hold:
>
> * The user sets: type = "response"
> * The model class is glm
> * The transform argument is NULL
> 
> then predictions() will first compute estimates on the link scale, and then back transform them using the inverse link function supplied by insight::link_inverse(model) function.

**Comment by vincentarelbundock** [comment]
Thanks, you're right this is out of date. Updated here: 6aface679ebee57f3a305fe0c1edb9ac47244475
