### ISSUE TITLE
False-positive warning about missing variable

### ISSUE THREAD

**Issue by urisohn** [vincentarelbundock/marginaleffects#1031]
Here i report two issues arising when marginaleffects::slopes() is applied to a GAM model

Issue 1: If the smoothing degree 'k' is provided as a variable set outside the call, a false-positive warning of missing variable is given. I provide an example below.
Issue 2: not sure if this is a bug or an intended behavior: the slopes() command prints underneath the resulting object the list of variables it supposedly contains, but it includes variables it does not contain. 

I am using CRAN's v0.18.0 (installation from github gave errors)

The example below showcases both:

```
 set.seed(123)
  n=500
  xn=rep(c(1,2,3),n)
  levels=sort(unique(xn))
  labels=c('low','med','high')
  x=factor(xn,levels=levels,labels=labels)  
  z=sample(c(1,2,3,3,4,4,5,5,6,7,7,7,7),size=length(x),replace=TRUE)
  y.raw=xn*z
  e=rnorm(length(x),sd=sd(y.raw))
  y=y.raw+e
  data=data.frame(x,y,z)


  #Will not prouce warning with marginaleffects
    model1 = try(mgcv::gam(y~s(z,by=x,k=3)+x, data=data),silent=TRUE )

  #WILL produce warning about k 
    k=3
    model2 = try(mgcv::gam(y~s(z,by=x,k=k)+x, data=data),silent=TRUE ) 

  #Grid for predicting
    zs=unique(z)
    ux=unique(x)
  
  nd = expand.grid(z=zs,x=ux)

  #No warning
    marginaleffects::slopes(model1, newdata = nd,by='z')
    
  #YES warning
    marginaleffects::slopes(model2, newdata = nd,by='z')
```

Issue 1 is the warning the last line produces.
Issue 2 is that both marginaleffects calls list as columns "predicted_lo, high, predicted" but they are not outputted

**Comment by vincentarelbundock** [comment]
Thanks for the reports.

I escalated the first issue upstream in the `insight` package: <https://github.com/easystats/insight/issues/851> I’m not sure what the solution is over there, but I can confirm that the warning is harmless and should have no effect on numerical results in `marginaleffects`.

What do you mean by “it includes variables it does not contain”?

In this example, the extra columns are not printed but they are available using standard accessors like `$`:

``` r
library(marginaleffects)

m <- lm(mpg ~ qsec * hp, data = mtcars)
s <- slopes(m)
s
# 
#  Term Estimate Std. Error     z Pr(>|z|)    S  2.5 %  97.5 %
#  hp    -0.0850     0.0109 -7.79   <0.001 47.1 -0.106 -0.0636
#  hp    -0.0959     0.0112 -8.56   <0.001 56.3 -0.118 -0.0739
#  hp    -0.1269     0.0145 -8.74   <0.001 58.5 -0.155 -0.0984
#  hp    -0.1430     0.0172 -8.33   <0.001 53.5 -0.177 -0.1094
#  hp    -0.0959     0.0112 -8.56   <0.001 56.3 -0.118 -0.0739
# --- 54 rows omitted. See ?avg_slopes and ?print.marginaleffects --- 
#  qsec  -0.7257     0.4195 -1.73   0.0836  3.6 -1.548  0.0964
#  qsec  -3.6689     0.7573 -4.84   <0.001 19.6 -5.153 -2.1847
#  qsec  -1.9342     0.4810 -4.02   <0.001 14.1 -2.877 -0.9914
#  qsec  -5.0528     1.0344 -4.88   <0.001 19.9 -7.080 -3.0254
#  qsec  -0.6477     0.4217 -1.54   0.1245  3.0 -1.474  0.1788
# Columns: rowid, term, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted_lo, predicted_hi, predicted, mpg, qsec, hp 
# Type:  response

s$predicted_hi |> head()
# [1] 23.48738 23.11357 24.20882 21.49819 16.88221 21.76873
```

**Comment by vincentarelbundock** [comment]
FYI, you can set a global option to disable pretty printing and see all columns all the time. See `?print.marginaleffects`

**Comment by urisohn** [comment]
1. Neat, thanks, still amazes me the community collaboration around github. 

2. Yeah, the columns don't bother me,just seemed like an unexpected default.

3.FWIW, you can extract the variables with base R, don't know if this will work for all the models you use

```
x=rnorm(100)
z=rnorm(100)
y=x*z+rnorm(100)
g1=mgcv::gam(y~s(x,k=3)+s(z,k=3))
all.vars(g1$formula)

```

just throwing it out there, if you knew about it and does not work for you, no need to reply.

Many thanks again.
