### ISSUE TITLE
Calculation of Odds Ratios (OR) using avg_predictions vs. avg_comparisons

### ISSUE THREAD

**Issue by selveny** [vincentarelbundock/marginaleffects#1032]
I'm trying to get the odds ratio of the effect of the experimental condition compared to the control condition. When calculating the odds ratio via the predictions resulting from avg_predictions() the result (1.746) is different compared to using avg_comparisons() (1.76), why is that the case? Thanks for helping :)

```{r}

data_long_ggps %>% 
  select(Username, ContentName, subcategory, APIDS, APIDS_Dec, IsCorrectlyProcessed)

```

# A tibble: 7,680 × 6
   Username ContentName          subcategory APIDS APIDS_Dec IsCorrectlyProcessed
      <dbl> <chr>                <chr>       <fct> <chr>                    <int>
 1        1 sha24581_0000029273… fixedblade… Mit   hit                          0
 2        1 gun10037_0000024772… revolver    Mit   hit                          1
 3        1 gun10545_0000024382… silencer    Mit   hit                          1
 4        1 gun10545_BAGGAGE_20… silencer    Mit   hit                          1
 5        1 too24131_0000026174… tools       Mit   hit                          1
 6        1 gun10709_BAGGAGE_20… pistol      Mit   hit                          1
 7        1 t0001274_BAGGAGE_20… miscellane… Mit   hit                          1
 8        1 gun10012_BAGGAGE_20… specialgun  Mit   hit                          1
 9        1 t0001010_0000025032… silencer    Mit   hit                          1
10        1 gun10337_BAGGAGE_20… 3d-printed  Mit   hit                          1
# ℹ 7,670 more rows
# ℹ Use `print(n = ...)` to see more rows

```{r}

glmm_ggps

```

Generalized linear mixed model fit by maximum likelihood (Laplace  Approximation)
 [glmerMod]
 Family: binomial  ( logit )
Formula: IsCorrectlyProcessed ~ APIDS + APIDS_Dec + APIDS:APIDS_Dec +  
    (1 | Username) + (APIDS | ContentName) + (1 | subcategory)
   Data: data_long_ggps
      AIC       BIC    logLik  deviance  df.resid 
 3712.356  3774.874 -1847.178  3694.356      7671 
Random effects:
 Groups      Name        Std.Dev. Corr 
 ContentName (Intercept) 3.1276        
             APIDSMit    1.3466   -0.78
 Username    (Intercept) 0.7666        
 subcategory (Intercept) 1.6992        
Number of obs: 7680, groups:  ContentName, 120; Username, 64; subcategory, 15
Fixed Effects:
           (Intercept)                APIDSMit           APIDS_Decmiss  
                2.9192                  1.2418                 -0.8509  
APIDSMit:APIDS_Decmiss  
               -2.1009 

 

```{r}

pred_avg <- avg_predictions(glmm_ggps,
                by = c("APIDS"),
                type = "response")

pred_avg

```

 APIDS Estimate Std. Error    z Pr(>|z|)     S 2.5 % 97.5 %
  Ohne    0.760     0.0380 20.0   <0.001 292.7 0.685  0.834
  Mit     0.847     0.0317 26.7   <0.001 518.3 0.784  0.909

Columns: APIDS, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high 
Type:  response 

```{r}

(pred_avg$estimate[2] / (1 - pred_avg$estimate[2])) /
  (pred_avg$estimate[1] / (1 - pred_avg$estimate[1]))

```

[1] 1.745628

```{r}

avg_comparisons(glmm_ggps,
  variables = "APIDS",
  comparison = "lnoravg",
  transform = "exp")

```
  

Term                   Contrast Estimate Pr(>|z|)    S 2.5 % 97.5 %
 APIDS ln(odds(Mit) / odds(Ohne))     1.76   <0.001 18.3  1.39   2.22

Columns: term, contrast, estimate, p.value, s.value, conf.low, conf.high, predicted_lo, predicted_hi, predicted 
Type:  response 

```{r}

sessionInfo()

```

R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=German_Switzerland.utf8  LC_CTYPE=German_Switzerland.utf8    LC_MONETARY=German_Switzerland.utf8
[4] LC_NUMERIC=C                        LC_TIME=German_Switzerland.utf8    

time zone: Europe/Zurich
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] AzureStor_3.7.0        AzureAuth_1.3.3        odbc_1.3.5             DBI_1.1.3              psych_2.3.9           
 [6] lme4_1.1-34            Matrix_1.6-1.1         lubridate_1.9.3        forcats_1.0.0          stringr_1.5.0         
[11] dplyr_1.1.3            purrr_1.0.2            readr_2.1.4            tidyr_1.3.0            tibble_3.2.1          
[16] ggplot2_3.4.4          tidyverse_2.0.0        marginaleffects_0.18.0

loaded via a namespace (and not attached):
 [1] gtable_0.3.4      xfun_0.40         insight_0.19.8    lattice_0.21-8    tzdb_0.4.0        vctrs_0.6.4       tools_4.3.1      
 [8] generics_0.1.3    curl_5.1.0        parallel_4.3.1    fansi_1.0.5       blob_1.2.4        pkgconfig_2.0.3   checkmate_2.3.0  
[15] data.table_1.14.8 lifecycle_1.0.3   farver_2.1.1      compiler_4.3.1    textshaping_0.3.7 munsell_0.5.0     mnormt_2.1.1     
[22] httpuv_1.6.12     htmltools_0.5.6.1 yaml_2.3.7        crayon_1.5.2      later_1.3.1       AzureRMR_2.4.4    pillar_1.9.0     
[29] nloptr_2.0.3      MASS_7.3-60       boot_1.3-28.1     nlme_3.1-162      tidyselect_1.2.0  digest_0.6.33     stringi_1.7.12   
[36] labeling_0.4.3    splines_4.3.1     fastmap_1.1.1     grid_4.3.1        colorspace_2.1-0  cli_3.6.1         magrittr_2.0.3   
[43] utf8_1.2.4        withr_2.5.1       backports_1.4.1   promises_1.2.1    scales_1.3.0      rappdirs_0.3.3    bit64_4.0.5      
[50] timechange_0.2.0  rmarkdown_2.25    httr_1.4.7        bit_4.0.5         ragg_1.2.6        hms_1.1.3         AzureGraph_1.3.4 
[57] evaluate_0.22     knitr_1.44        rlang_1.1.1       Rcpp_1.0.11       glue_1.6.2        vroom_1.6.4       jsonlite_1.8.7   
[64] rstudioapi_0.15.0 minqa_1.2.6       R6_2.5.1          systemfonts_1.0.5

**Comment by vincentarelbundock** [comment]
If you supply a minimal reproducible example using public data like mtcars, I'll try to help if I can find time.

**Comment by selveny** [comment]
thank you so much, here is an example using mtcars.. why are the calculated odds ratios not equal?

Load packages
```{r}

library("marginaleffects")
library("tidyverse")

```


```{r}

avg_comparisons(model,
  variables = "vs",
  comparison = "ratioavg")

```


prepare data
```{r}

df <- mtcars %>% 
  as_tibble(rownames = "car")

```


estimate logistic mixed model
```{r}

model <- glmer(
  am ~ vs + scale(drat) +
    (1 | car),
  family = "binomial",
  df
)

```


get average predictions as probabilities
```{r}

pred <- avg_predictions(model,
                by = "vs",
                type = "response")

```


calculate odds ratio "by hand"
```{r}

(pred$estimate[1] / (1 - pred$estimate[1])) /
  (pred$estimate[2] / (1 - pred$estimate[2]))

```
odds ratio = 0.5009931


get odds ratios by using avg_comparisons
```{r}

avg_comparisons(model,
  variables = "vs",
  comparison = "lnoravg",
  transform = "exp",
  type = "response")

```
odds ratio = 0.304

**Comment by selveny** [comment]
thank you so much, here is an example using mtcars.. I don't understand why the odds ratios calculated at the end are unequal?

Load packages
```{r}

library("marginaleffects")
library("tidyverse")

```


prepare data
```{r}

df <- mtcars %>% 
  as_tibble(rownames = "car")

```


estimate logistic mixed model
```{r}

model <- glmer(
  am ~ vs + scale(drat) +
    (1 | car),
  family = "binomial",
  df
)

```


get average predictions as probabilities
```{r}

pred <- avg_predictions(model,
                by = "vs",
                type = "response")

```


calculate odds ratio "by hand"
```{r}

(pred$estimate[1] / (1 - pred$estimate[1])) /
  (pred$estimate[2] / (1 - pred$estimate[2]))

```
odds ratio = 0.5009931


get odds ratios by using avg_comparisons
```{r}

avg_comparisons(model,
  variables = "vs",
  comparison = "lnoravg",
  transform = "exp",
  type = "response")

```
odds ratio = 0.304

**Comment by vincentarelbundock** [comment]
# Equivalence between `avg_comparisons` and `avg_comparisons`

Say we estimate a simple logit regression and want to compute the average log-odds ratio associated with a change from 0 to 1 on the `vs` variable. We can proceed as follows using the `comparisons()` function:

``` r
library(marginaleffects)
mod <- glm(am ~ vs + scale(drat), family = binomial, mtcars)

avg_comparisons(mod,
    variables = "vs",
    comparison = "lnoravg",
    type = "response")
# 
#  Term              Contrast Estimate Std. Error     z Pr(>|z|)   S 2.5 % 97.5 %
#    vs ln(odds(1) / odds(0))   -0.901      0.368 -2.45   0.0143 6.1 -1.62  -0.18
# 
# Columns: term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted_lo, predicted_hi, predicted 
# Type:  response
```

We can specify the function to compare “hi” predictions to “lo” predictions manually and get the same results:

``` r
fun <- function(hi, lo) log((mean(hi) / (1 - mean(hi))) / (mean(lo) / (1 - mean(lo))))

comparisons(mod,
    variables = "vs",
    comparison = fun,
    type = "response")
# 
#  Term Contrast Estimate Std. Error     z Pr(>|z|)   S 2.5 % 97.5 %
#    vs     1, 0   -0.901      0.368 -2.45   0.0143 6.1 -1.62  -0.18
# 
# Columns: term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted_lo, predicted_hi, predicted 
# Type:  response
```

The same results can be obtained using the `predictions()` function. First, we replicate the entire dataset, and substitute the values of `vs`. Then, we make predictions. Finally, we compute the log odds ratios:

``` r
dat0 <- transform(mtcars, vs = 0)
dat1 <- transform(mtcars, vs = 1)

p0 <- predictions(mod, newdata = dat0, type = "response")
p1 <- predictions(mod, newdata = dat1, type = "response")

fun(p1$estimate, p0$estimate)
# [1] -0.9006949
```

Notice that the following command gives us a different result. This is because instead of duplicating the full dataset, and computing the “hi” and “lo” as the mean predictions over the full data, we only compute the averages on the subsets of rows where `vs` is 0 or 1, respectively:

``` r
p <- avg_predictions(mod, by = "vs", type = "response")
fun(p$estimate[2], p$estimate[1])
# [1] 0.6931472
```

Which is equivalent to:

``` r
dat0 <- subset(mtcars, vs == 0)
dat1 <- subset(mtcars, vs == 1)

p0 <- predictions(mod, newdata = dat0, type = "response")
p1 <- predictions(mod, newdata = dat1, type = "response")

fun(p1$estimate, p0$estimate)
# [1] 0.6931472
```
