### ISSUE TITLE
Inconsistency between plot_predictions() and avg_predictions() for glmer model

### ISSUE THREAD

**Issue by huftis** [vincentarelbundock/marginaleffects#1035]
I’m seeing a (for me) strange inconsistency between `plot_predictions()` and `avg_predictions()` for a certain glmer model. I observe this problem with both the latest CRAN version (0.18.0) and the development version.

Here’s a simple reproducible example (mimicking my real data):

``` r
library(marginaleffects)
library(tidyverse)
library(lme4)

set.seed(125)
n = 500
d = tibble(
  cluster = 1:n,
  cluster_effect = runif(n, 0, .2),
  diagnosis = sample(1:3, n, replace = TRUE)
)
d$diagnosis_fac = factor(LETTERS[d$diagnosis])
d2 = d[rep(1:n, each = 6), ]
d2$case_control = rep(c(0, 1, 1, 1, 1, 1), times = n)
d2$prob = .2 + d2$cluster_effect + d2$diagnosis * d2$case_control / 10
d2$outcome = rbinom(n * 6, 1, prob = d2$prob)

# The model is wrong, but that’s not important
# (it converges and provides reasonable estimates)
mod = glmer(outcome ~ case_control * diagnosis_fac +
  (1 | cluster), family = "binomial", data = d2)

plot_predictions(mod,
  condition = list(case_control = unique, diagnosis_fac = unique),
  type = "response"
)
```

![](https://i.imgur.com/TCp9ID3.png)

Note that the predicted value for ‘B’ (green) for `case_control` equal to 1 is clearly > 0.5.

However, the corresponding average prediction is less than 0.5 (it’s 0.489):

``` r
avg_predictions(mod, variables = c("case_control", "diagnosis_fac"), type = "response")
#> 
#>  case_control diagnosis_fac Estimate Std. Error     z Pr(>|z|)     S 2.5 %
#>             0             B    0.279     0.0342  8.14   <0.001  51.1 0.212
#>             0             C    0.291     0.0370  7.88   <0.001  48.1 0.219
#>             0             A    0.284     0.0354  8.01   <0.001  49.6 0.214
#>             1             B    0.489     0.0180 27.22   <0.001 539.4 0.454
#>             1             C    0.613     0.0186 32.89   <0.001 785.8 0.576
#>             1             A    0.372     0.0179 20.84   <0.001 318.0 0.337
#>  97.5 %
#>   0.346
#>   0.364
#>   0.353
#>   0.524
#>   0.649
#>   0.407
#> 
#> Columns: case_control, diagnosis_fac, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high 
#> Type:  response
```

Now I have two hypotheses for the reason for the mismatch:

1) It’s because some random-effect stuff that’s handled differently by default in the two functions.
2) There is some ‘transform then back-transform’ stuff related to the outcome scale (link vs. response) going on behind the scenes.

However, for hypothesis 1, the effect of the random effects on the estimates is *really small*:

``` r
d2$pred0 = predict(mod, type = "response", re.form = ~0)
d2$pred_ran = predict(mod, type = "response")
mean_re = mean(ranef(mod)$cluster$`(Intercept)`)
d2 %>%
  group_by(case_control, diagnosis_fac) %>%
  summarise(
    prob_0 = mean(pred0), # Ignore random effects
    prob_ran = mean(pred_ran), # Include random effects
    prob_avg_ran = mean(plogis(qlogis(pred0 + mean_re))) # Use the *average* random effect
  )
#> `summarise()` has grouped output by 'case_control'. You can override using the
#> `.groups` argument.
#> # A tibble: 6 × 5
#> # Groups:   case_control [2]
#>   case_control diagnosis_fac prob_0 prob_ran prob_avg_ran
#>          <dbl> <fct>          <dbl>    <dbl>        <dbl>
#> 1            0 A              0.283    0.284        0.283
#> 2            0 B              0.278    0.279        0.278
#> 3            0 C              0.291    0.291        0.291
#> 4            1 A              0.372    0.373        0.372
#> 5            1 B              0.489    0.489        0.489
#> 6            1 C              0.613    0.612        0.613
```

Also note that the results agree with the `avg_predictions()` function, but not with `plot_predictions()`.

For hypothesis 2, note that both the `plot_predictions()` and the `avg_predictions()` call use `type = "response"`, so all calculations *should* be done on the original scale, not the link scale. And even if they *were* done on the link scale, this would have a very small effect (as the estimated probabilities are far away from 0 or 1):

``` r
# Let’s use predictions() instead of predict() this time.
d_preds = predictions(mod, type = "response")
d_preds %>%
  group_by(case_control, diagnosis_fac) %>%
  summarise(
    prob_notrans = mean(estimate), # Original scale
    prob_backtrans = plogis(mean(qlogis(estimate))) # Link scale
  )
#> `summarise()` has grouped output by 'case_control'. You can override using the
#> `.groups` argument.
#> # A tibble: 6 × 4
#> # Groups:   case_control [2]
#>   case_control diagnosis_fac prob_notrans prob_backtrans
#>          <dbl> <fct>                <dbl>          <dbl>
#> 1            0 A                    0.284          0.283
#> 2            0 B                    0.279          0.278
#> 3            0 C                    0.291          0.290
#> 4            1 A                    0.373          0.372
#> 5            1 B                    0.489          0.489
#> 6            1 C                    0.612          0.613
```

Again, the results agree with `avg_predictions()` functions, not with `plot_predictions()`. So what is `plot_predictions()` doing to get these (strange) estimates?! 🤔

```r
sessionInfo()
#> R version 4.3.2 (2023-10-31)
#> Platform: x86_64-suse-linux-gnu (64-bit)
#> Running under: openSUSE Tumbleweed
#> 
#> Matrix products: default
#> BLAS:   /usr/lib64/R/lib/libRblas.so 
#> LAPACK: /usr/lib64/R/lib/libRlapack.so;  LAPACK version 3.11.0
#> 
#> locale:
#>  [1] LC_CTYPE=nn_NO.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=nn_NO.UTF-8        LC_COLLATE=nn_NO.UTF-8    
#>  [5] LC_MONETARY=nn_NO.UTF-8    LC_MESSAGES=nn_NO.UTF-8   
#>  [7] LC_PAPER=nn_NO.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=nn_NO.UTF-8 LC_IDENTIFICATION=C       
#> 
#> time zone: Europe/Oslo
#> tzcode source: system (glibc)
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#>  [1] lme4_1.1-35.1               Matrix_1.6-5               
#>  [3] lubridate_1.9.3             forcats_1.0.0              
#>  [5] stringr_1.5.1               dplyr_1.1.4                
#>  [7] purrr_1.0.2                 readr_2.1.5                
#>  [9] tidyr_1.3.1                 tibble_3.2.1               
#> [11] ggplot2_3.5.0               tidyverse_2.0.0            
#> [13] marginaleffects_0.18.0.9001
#> 
#> loaded via a namespace (and not attached):
#>  [1] styler_1.10.2     utf8_1.2.4        generics_0.1.3    lattice_0.22-5   
#>  [5] stringi_1.8.3     hms_1.1.3         digest_0.6.34     magrittr_2.0.3   
#>  [9] evaluate_0.23     grid_4.3.2        timechange_0.3.0  fastmap_1.1.1    
#> [13] R.oo_1.26.0       R.cache_0.16.0    R.utils_2.12.3    backports_1.4.1  
#> [17] fansi_1.0.6       scales_1.3.0      cli_3.6.2         rlang_1.1.3      
#> [21] R.methodsS3_1.8.2 splines_4.3.2     munsell_0.5.0     reprex_2.1.0     
#> [25] withr_3.0.0       yaml_2.3.8        tools_4.3.2       tzdb_0.4.0       
#> [29] checkmate_2.3.1   nloptr_2.0.3      minqa_1.2.6       colorspace_2.1-0 
#> [33] boot_1.3-30       vctrs_0.6.5       R6_2.5.1          lifecycle_1.0.4  
#> [37] fs_1.6.3          MASS_7.3-60.0.1   insight_0.19.8    pkgconfig_2.0.3  
#> [41] pillar_1.9.0      gtable_0.3.4      data.table_1.15.2 glue_1.7.0       
#> [45] Rcpp_1.0.12       xfun_0.42         tidyselect_1.2.0  rstudioapi_0.15.0
#> [49] knitr_1.45        farver_2.1.1      nlme_3.1-164      htmltools_0.5.7  
#> [53] labeling_0.4.3    rmarkdown_2.25    compiler_4.3.2
```

<sup>Created on 2024-02-29 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by vincentarelbundock** [comment]
I don`t think it is either of those explanations. Please read the documentation carefully for the `condition` and `by` arguments in `plot_predictions()`, and for the `variables` argument in `predictions()`.

**Comment by huftis** [comment]
Hmm, I have now read and reread the documention, but I’m afraid I’m only more confused. :/

According to the documentation, predictions are made on a user-specified grid,
with other variables set to their means/modes. The model only has two variables, and I specify both variables in `condition`, so there are no third variable to held at its mean/mode.
*Except* the random intercept (`cluster` variable). But if this is held at its mean (`mean(ranef(mod)$cluster$`(Intercept)`) = 0.0004367`), we actually *don’t* get the estimate
shown in `plot_predictions()` (as I have shown earlier).

I don’t know how to extract the estimates from `plot_predictions()`, but they look very similar to estimates from `predictions()` (not `avg_predictions()`) using the `newdata` argument:

```r
preds = predictions(mod,
  newdata = datagrid(case_control = unique, diagnosis_fac = unique),
  type = "response"
)
preds$estimate[5] # Estimate for B1
#> [1] 0.5169197
```

I *think* I have figured out how to calculate this manually. I had to set all variable in the dataset to my chosen values (`B` and `1`), but only calculate the average of the first *six* rows/observations (or just use the value of the first row, which is equivalent, since they all belong to the *first* cluster):

```r
d2_nd = d2
d2_nd$diagnosis_fac[]="B"
d2_nd$case_control=1

pred3 = predict(mod, newdata=d2_nd, type = "response")
mean(pred3[1:6])
#> [1] 0.5169197
```

But this would mean that predictions depend not only on the model and on the data, but on the order of the observations in the data?

For example, the following data and models are equivalent:

```
d2_rev = d2[nrow(d2):1, ]
mod = glmer(outcome ~ case_control * diagnosis_fac +
  (1 | cluster), family = "binomial", data = d2)
mod_rev = glmer(outcome ~ case_control * diagnosis_fac +
  (1 | cluster), family = "binomial", data = d2_rev)
```

The coefficients are identical (except for numerical inaccuracy in the last decimal places)

```r
all.equal(fixef(mod), fixef(mod_rev))
#> [1] TRUE
```

But the conditional estimates are very different:

```r
predictions(mod,
  newdata = datagrid(case_control = unique, diagnosis_fac = unique),
  type = "response"
)
#> 
#>  case_control diagnosis_fac Estimate Std. Error     z Pr(>|z|)     S 2.5 %
#>             0             A    0.306     0.0371  8.25   <0.001  52.5 0.233
#>             0             B    0.301     0.0359  8.38   <0.001  54.1 0.231
#>             0             C    0.314     0.0387  8.12   <0.001  50.9 0.238
#>             1             A    0.398     0.0184 21.68   <0.001 343.8 0.362
#>             1             B    0.517     0.0180 28.69   <0.001 599.1 0.482
#>             1             C    0.639     0.0182 35.19   <0.001 898.9 0.603
#>  97.5 % cluster
#>   0.379       1
#>   0.371       1
#>   0.390       1
#>   0.434       1
#>   0.552       1
#>   0.675       1
#> 
#> Columns: rowid, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, outcome, cluster, case_control, diagnosis_fac 
#> Type:  response
predictions(mod_rev,
  newdata = datagrid(case_control = unique, diagnosis_fac = unique),
  type = "response"
)
#> 
#>  case_control diagnosis_fac Estimate Std. Error     z Pr(>|z|)     S 2.5 %
#>             0             A    0.299     0.0366  8.16   <0.001  51.4 0.227
#>             0             B    0.293     0.0354  8.29   <0.001  52.9 0.224
#>             0             C    0.306     0.0382  8.03   <0.001  49.9 0.232
#>             1             A    0.390     0.0182 21.37   <0.001 334.2 0.354
#>             1             B    0.508     0.0180 28.17   <0.001 577.4 0.473
#>             1             C    0.631     0.0183 34.39   <0.001 858.7 0.595
#>  97.5 % cluster
#>   0.370     500
#>   0.363     500
#>   0.381     500
#>   0.425     500
#>   0.543     500
#>   0.667     500
#> 
#> Columns: rowid, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, outcome, cluster, case_control, diagnosis_fac 
#> Type:  response
```

How can this way of calculating stuff¹ – i.e., to use the *first* random intercept/effect when calculating conditional predictions – make any sense?

On the other, using the *average* random intercept/effect (which will almost always be very close to 0), which is implied by the documentation as I read it (*‘All variables whose values are not specified explicitly are treated as usual by datagrid(), that is, they are held at their mean or mode’*), *would* be reasonable. (And it will result in almost the same estimates as when using `re.form = ~0`.)

¹ I’m sorry if I have misunderstood how things are actually calculated.

<sup>Created on 2024-02-29 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by vincentarelbundock** [comment]
>  But if this is held at its mean (`mean(ranef(mod)$cluster$`(Intercept)`) = 0.0004367`), 

For clusters, we take the mode, not the mean. If there are multiple modes, the first one is chosen by default. This is arbitrary and may not be what you care about or want.

> I don’t know how to extract the estimates from `plot_predictions()`, 

Use `draw=FALSE`

> How can this way of calculating stuff¹ – i.e., to use the _first_ random intercept/effect when calculating conditional predictions – make any sense?

In this case, I do *not* actually think that it makes much sense. However, `marginaleffects` supports 100+ model types, and the defaults will usually provide reasonable estimates in most models. For consistency, every model is treated the same. In mixed-effects models, you probably want to specify the actual levels that you care about manually when making predictions.

Alternatively (maybe even better), would be to estimate a bayesian model and to marginalize. That way, the uncertain estimates will account for the random component. There is a short bit in one of the vignettes about this.
