### ISSUE TITLE
Feature request for hypothesis argument

### ISSUE THREAD

**Issue by andymilne** [vincentarelbundock/marginaleffects#1043]
When computing differences in differences – e.g., one is interested in how the effect of a treatment differs between groups – I have successfully used the hypothesis argument in `avg_predictions()`. These typically result in an output where odd rows are when `treatment = 0`, and even rows where `treatment = 1`. However, building an appropriate contrast matrix for the hypothesis argument to subtract odd rows from even rows is a bit tedious, particularly when the "raw" output of `avg_predictions` has many rows. One option is to use `hypothesis = "sequential"`, but that also subtracts even from odd rows. Is it worth considering a "sequentialskip" or similarly named string that will subtract only odd from even? Or maybe a more general way of specifying, within the hypothesis argument, a short vector like `c(-1, 1)` and allowing that to repeat across all rows of the raw output – it could even do that automatically if the specified vector is shorter than the total number of rows?

**Comment by vincentarelbundock** [comment]
Thanks for raising the issue. It would help me a lot to see something more concrete. Would.uou be able to supply a minimal reproducible example with a public dataset (ex mtcars or one from the Rdatasets archive)?

I think that recycling short vectors into long ones is very dangerous. But I'm working on related issues now and I'm sure there's a clean solution.

**Comment by andymilne** [comment]
Here is some code to make this more concrete. I will send the csv file by email.

```
library(brms)
library(marginaleffects)
library(dplyr)

options(mc.cores = parallel::detectCores ()) # run on multiple cores

# Four educational interventions. The test score is Score out of a max possible
# MaxScore. Trtmnt is the teaching intervention. TstTm indicates whether it is a
# pre- or post-test. The remainder are participant-level covariates.
dt <- read.csv("prepostdatasim.csv")
dt |> 
  mutate(across(where(is.character), as.factor)) |>
  mutate(across(c(ID, Ltrcy, OthrLngKnwldg), as.factor)) ->
  dt

mdl <- 
  brm(
    Score | trials(MaxScore) ~ 
      TstTm + TstTm:Trtmnt * 
      (Gndr + Ltrcy + OthrLngKnwldg + Age) +
      (1 | ID),
    data = dt,
    family = beta_binomial(link = logit),
    prior = set_prior("student_t(3, 0, 2.5)", class = "Intercept") +
      set_prior("student_t(3, 0, 2.5)", class = "b") +
      set_prior("gamma(1, 0.01)", class = "phi", lb = 0),
    # backend = "cmdstanr",
    # threads = threading(12)
  )
mdl

# Predictions 1
avg_predictions(
  mdl,
  variables = "Trtmnt",
  by = c("Trtmnt", "TstTm"),
  conf_level = 0.95,
)

# It's OK to build the "even_minus_odd_rows" contrast matrix required to
# subtract odd from even rows because there are only 12 rows

# Pre-post change for each Cndtn
even_minus_odd_rows <- matrix(
  c(
    -1,  0,  0,  0,
    1,  0,  0,  0,
    0, -1,  0,  0,
    0,  1,  0,  0,
    0,  0, -1,  0,
    0,  0,  1,  0,
    0,  0,  0, -1,
    0,  0,  0,  1),
  nrow = 8, ncol = 4, byrow = TRUE,
  dimnames = list(
    c(1,2,3,4,5,6,7,8),
    c(
      "A",
      "B",
      "C",
      "D")) 
)

prd_mdl <- 
  avg_predictions(
    mdl,
    variables = "Trtmnt",
    by = c("Trtmnt", "TstTm"),
    hypothesis = even_minus_odd_rows,
    conf_level = 0.95,
  )
prd_mdl

# Predictions 2
# But, here, when the data are being subdivided into more groups, the 
# even_minus_odd_row matrix would be rather large (48 x 24) and so hard to 
# construct manually. Obviously, if more covariates are used for by, it gets
# even larger,
prd_mdl <- 
  avg_predictions(
    mdl,
    variables = "Trtmnt",
    by = c("Trtmnt", "Ltrcy", "OthrLngKnwldg", "TstTm"),
    # hypothesis = cntrsts2,
    conf_level = 0.95,
  )
prd_mdl
```

**Comment by andymilne** [comment]
Hi Vincent

I have posted some code to GitHub. Here is the required csv file. Thank you for thinking about this FR.

Andy

￼

**Comment by vincentarelbundock** [comment]
I don't see an attachment. Also, is it not possible to make a simpler minimal working example rather than a long to estimate brms model?

https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example/5963610#5963610

**Comment by andymilne** [comment]
The model only takes about 10 seconds to compile and 5 seconds to fit. Not sure what happened to the csv file – here’s a link to download: https://www.dynamictonality.com/prepostdatasim.csv 

Andy Milne

**Comment by vincentarelbundock** [comment]
OK, I think I understand what you mean, and I am working on a feature that will allow you to do this easily: We will soon be able to apply a `hypothesis` by subgroup of the data. So you will be able to apply `hypothesis="sequential"` *within* each value of `cyl` in this simpler example:

```r
mod <- lm(mpg ~ factor(cyl) * factor(am), mtcars)
avg_predictions(mod, variables = "am", by = c("cyl", "am"))

 cyl am Estimate Std. Error     z Pr(>|z|)     S 2.5 % 97.5 %
   4  0     22.9      1.751 13.08   <0.001 127.5  19.5   26.3
   4  1     28.1      1.072 26.19   <0.001 499.7  26.0   30.2
   6  0     19.1      1.516 12.61   <0.001 118.8  16.2   22.1
   6  1     20.6      1.751 11.75   <0.001 103.4  17.1   24.0
   8  0     15.0      0.875 17.19   <0.001 217.7  13.3   16.8
   8  1     15.4      2.144  7.18   <0.001  40.4  11.2   19.6
```

**Comment by andymilne** [comment]
Wonderful -- that's a nice intuitive way of dealing with this! Noting, of course, that each subgroup of the data may be uniquely identified only by a combination of factors.

**Comment by vincentarelbundock** [comment]
Yep.

Closing this in favor of: https://github.com/vincentarelbundock/marginaleffects/issues/1038
