### ISSUE TITLE
Feature request: subsetting model data

### ISSUE THREAD

**Issue by ngreifer** [vincentarelbundock/marginaleffects#1045]
Hi chief,

I have a (selfish) request that I don't think would be too hard to implement. The feature is to allow subsetting of the model data used in `avg_cpomparisons()`, etc., without supply an argument to `newdata`. For example, if I want to estimate the ATT using g-computation, I normally have to do
```r
data("lalonde", package = "MatchIt")
fit <- lm(re78 ~ treat * (age + educ), data = lalonde)

avg_comparisons(fit, variables = "treat", newdata = subset(lalonde, treat == 1))
```
A problem with this is that this requires me to supply a new dataset, when the dataset used to fit the model is already extracted from the model object. This becomes important when the original dataset is missing components that are added by the fitting function, such as a `(weights)` column for weights used in the fitting (e.g., by `svyglm()`). In my case, weights don't always exist in the model data; they can be supplied externally, and `svyglm()` automatically appends them to the data that is eventually extracted inside `avg_comparisons()`.

For example, let's say I have an external vector of weights `w` that doesn't exist in `d`, and I use `svyglm()` to fit the model.

```r
library(survey)
w <- runif(614)
des <- svydesign(~1, weights = w, data = lalonde)
fit <- svyglm(re78 ~ treat * (age + educ), design = des)
```
If I use `avg_comparisons()`, I need to set `wts = "(weights)"` to ensure the weights are used to compute the weighted means. Obviously `"(weights)"` doesn't exist as a variable in `lalonde`. I can run

```r
avg_comparisons(fit, variables = "treat", wts = "(weights)")
```

But if I want to subset to get the ATT, I get an error when using `newdata` because `"(weights)"` isn't in `newdata`.
```r
avg_comparisons(fit, variables = "treat", wts = "(weights)",
                newdata = subset(lalonde, treat == 1))
## Error
```

My proposal is a `subset` argument that is evaluated in the environment of the dataset extracted from the model, just how `subset` or `model.frame()` work. That is, I would want to run
```r
avg_comparisons(fit, variables = "treat", wts = "(weights)", subset = treat == 1)
```
This can be accomplished using the machinery within `subset.data.frame()`, i.e.,
```r
subset0 <- function(x, subset) {
    e <- substitute(subset)
    r <- eval(e, x, parent.frame())
    x[r,]
}
```
Thank you for considering!

**Comment by vincentarelbundock** [comment]
How about this?

```r
avg_comparisons(fit, newdata = subset(treat == 1))
```

where internally we would capture the unevaluated `subset()` function call and insert `x=newdata` if `x` is not explicitly given by the user.

This sounds esoteric, but it's really the same thing we currently do with `datagrid()`, where the implicit

```r
avg_comparisons(fit, newdata = datagrid(treat = 1))
```

is actually replaced internally by the more explicit:

```r
avg_comparisons(fit, newdata = datagrid(treat = 1, newdata = newdata))
```

So the machinery is all there. My guess is it would be pretty easy to implement by modifying the weird quosure stuff in here: https://github.com/vincentarelbundock/marginaleffects/blob/main/R/sanitize_newdata.R#L1

**Comment by ngreifer** [comment]
That sounds like it could work. Although I thought the first argument to `datagrid()` would be the model fit, not the dataset, so you would need to capture whether `subset()` or `datagrid()` was supplied and then switch which would be supplied as the first argument. For some more esoteric R reasons, it could also be dangerous to use `subset()` in case the user supplies `base::subset()` not realizing `subset()` is a reserved, unevaluated expression as used here or if the user is more used to using `dplyr::filter()` and is confused about why it doesn't work here or if the user supplies other arguments to `subset()` (i.e., `select`, which would be invalid here). I think it would prevent more errors and require less obscure quosuring to just have a separate argument that is evaluated within the environment of the dataset rather than special and potential fragile syntax. I feel the same about `datagrid()` but I think there is less danger with it. Also it might be desirable to supply both an argument to `newdata` and a `subset` argument, which subsets that data (e.g., because `datagrid()` creates a full cross of its arguments and a user might not want all of them, but you can't wrap `datagrid()` in `subset()` and supply it without the model as the first argument to one of your functions). I know you hate adding more arguments, but subsetting is a pretty fundamental one (e.g., it's in all modeling functions, and Stata offers it via `if` in all functions) (but I'm sure everyone feels that way about their feature requests ;)).

**Comment by vincentarelbundock** [comment]
Well I'm thinking about using the "real" `base::subset()`, so the other arguments like `select` should work as expected. And perhaps we could also allow `dplyr::filter`. I guess there might be weird corner cases for that one person who inevitably inserts a crazy pipeline inline in the function (arrrgh!).

I also take your point about this being pretty fundamental and present `lm()`, but I'll need to think about it and explore.

**Comment by vincentarelbundock** [comment]
This is now merged in `main`. Internally, we only process the call if the function `subset()` or `filter()`, with or without namespace, and when there is a single argument.

Frankly, I think this works well enough as a simple shortcut like what motivated your initial query. This was super easy to implement, so that's another bonus. Finally, I don't really have a big problem with requiring people to be more explicit if they want more complicated things. This is a shortcut.

It's a cool one, though. Thanks for the suggestion!

``` r
library(marginaleffects)
library(tinytest)
library(dplyr)
data("lalonde", package = "MatchIt")
fit <- lm(re78 ~ treat * (age + educ), data = lalonde)

k = avg_comparisons(fit, variables = "treat", newdata = subset(lalonde, treat == 1))$estimate
z = avg_comparisons(fit, variables = "treat", newdata = subset(treat == 1))$estimate
x = avg_comparisons(fit, variables = "treat", newdata = base::subset(treat == 1))$estimate
y = avg_comparisons(fit, variables = "treat", newdata = filter(treat == 1))$estimate
w = avg_comparisons(fit, variables = "treat", newdata = dplyr::filter(treat == 1))$estimate

expect_equal(k, x)
```

    ----- PASSED      : <-->
     call| expect_equal(k, x) 

``` r
expect_equal(k, y)
```

    ----- PASSED      : <-->
     call| expect_equal(k, y) 

``` r
expect_equal(k, w)
```

    ----- PASSED      : <-->
     call| expect_equal(k, w) 

``` r
expect_equal(k, z)
```

    ----- PASSED      : <-->
     call| expect_equal(k, z)
