### ISSUE TITLE
Feature request: automatic extraction of weights from fitted model

### ISSUE THREAD

**Issue by ngreifer** [vincentarelbundock/marginaleffects#1046]
Back with another suggestion related to weights. When we fit a model with weights and want to use `avg_predictions()`, etc., to compute the weighted means, we need to supply the name of the weights variable in the dataset to `wts` or a vector containing the weights. But the weights are already in the model; I'm thinking it might be easy to allow users to set `wts = TRUE` to automatically extract the weights in the model using, e.g., `insight::get_weightit()` or `stats::weights()`. I think the default should be what it is now (no weights used even if included in the model fit), but I think it is worth having it as an option. In Stata, `margins` automatically applies weights used to fit the model when computing averages; the user has to turn this off by setting `, noweights`. I think it's okay to have the default here be different from Stata, but I think it would also be beneficial to have a simple argument that automatically extracts the weights already present within the object rather than requiring the user to have to specify the name of the weights variable. This would be especially useful when the weights variable is not in the supplied dataset, but is in the model, e.g., with `svyglm()`, which appends a `"(weights)"` variable to the model frame, typically invisible to the user.

It might be that setting `wts = TRUE` only works when `newdata` is not supplied. This goes kind of in combination with #1045.

For example, I'm imagining a user could call
```r
avg_comparisons(fit, variables = "treat", wts = TRUE, subset = treat == 1)
```
to compute a weighted ATT without ever having to supply the dataset again or known the name of the weights column in the dataset (if it's even there).

**Comment by vincentarelbundock** [comment]
I like this a lot, but might not have the bandwidth to implement and test very soon.

For later reference, I'm optimistic that a slight tweak to this function (and documentation) would do the trick:

https://github.com/vincentarelbundock/marginaleffects/blob/51f8fe6def297dce5ac772880b709da4f23cdf20/R/sanitize_newdata.R#L93

**Comment by ngreifer** [comment]
I agree that this could be easy, but I'll let you be the judge of that :) I think adding
```r
if (isTRUE(wts)) wts <- insight::get_weights(model)
```
in `sanitize_newdata()` would do it.

**Comment by vincentarelbundock** [comment]
https://github.com/vincentarelbundock/marginaleffects/pull/1050
