### ISSUE TITLE
Support for SSN2 models

### ISSUE THREAD

**Issue by morgan-sparks** [vincentarelbundock/marginaleffects#1052]
This is just a request for support for the SSN2 package. 

https://cran.r-project.org/web//packages//SSN2/index.html

Worked examples can be found here:

https://usepa.github.io/SSN2/articles/introduction.html

Thanks for the great package!!

**Comment by vincentarelbundock** [comment]
Thanks for the suggestion!

The entire premise of the `marginaleffects` is that we (1) build two data frames that differ in some crucial respect, (2) make predictions based on those two data frames, and (3) compare the resulting predictions.

Much of the reason why the package is convenient is that step 1 is typically very annoying, and that we can make that part very easy for users.

AFAICT, the `SSN2` package does *not* accept standard data frames as input for `predict()`. Instead, it requires some special spatial objects. Therefore, none of the machinery that we have in place to create the prediction frames will be relevant here.

In that context, I'm not really sure what role the package plays...
