### ISSUE TITLE
Why does `bootstrap_rsample` require the `boot` package?

### ISSUE THREAD

**Issue by ramorel** [vincentarelbundock/marginaleffects#1053]
Curious as to why `bootstrap_rsample()` requires the `boot` package to run? I do not see any `boot` dependencies in the function, but maybe I've missed them. I'm currently in a situation where I cannot install the `boot` package for my instance of R and notice that the `inferences()` function errored out at the `bootstrap_rsample()` step, so looked into the code and found that `bootstrap_rsample()` checks for `boot` in the 7th line. Is this intentional?

```
bootstrap_rsample <- function(model, INF_FUN, ...) {

    # attached by `inferences()`
    conf_type <- attr(model, "inferences_conf_type")
    checkmate::assert_choice(conf_type, choices = c("perc", "bca"))

   insight::check_if_installed("boot")

    ...
}
```

**Comment by vincentarelbundock** [comment]
Thanks. Good call, I don't think we need this here. Must be cruft from a refactor or someting. Removed here: https://github.com/vincentarelbundock/marginaleffects/commit/e469ba9e460cc761ae765e082f340c34fec704d8
