### ISSUE TITLE
Support for Spatial Regression Models

### ISSUE THREAD

**Issue by mprimbs** [vincentarelbundock/marginaleffects#1067]
Good Evening,

I was wondering whether anyone suceeded in calculating marginal effects for spatial regression models, for example with lagsarlm() from spdep. The function creates sarlm objects that do not work with marginaleffects. 

If nobody ever did that, please consider this a request to add support for spatial regressions (spdep supports spatial lag and spatial error models) to marginaleffects :) 

Best Regards,

Max

**Comment by vincentarelbundock** [comment]
Thanks for the feature request. I appreciate that you took the time to look at the package and write this up.

As you note, the input format for predictions in spatial models is *very* different from the standard data frames that `marginaleffects` supports and manipulates. Supporting spatial models would require a completely different (and parallel) software architecture on the backend.

To be honest, I am extremely unlikely to implement that myself. However, I would be more than happy to provide guidance and review code if anyone wants to implement this and submit a Pull Request. See also my response here: https://github.com/vincentarelbundock/marginaleffects/issues/1052#issuecomment-2007468457
