### ISSUE TITLE
Support: `lqmm`

### ISSUE THREAD

**Issue by Sueleaf** [vincentarelbundock/marginaleffects#1072]
Hi!
I'm currently working on linear quantile mixed model using the 'lqmm' package. When I used plot_prediction() and predictions() commands to obtain the marginal effect, R returned error saying marginaleffects wasn't support this model. 
I have checked the issues, and it seemed that no request for supporting the lqmm model (or other linear quantile mixed model) was made. So I am wonding if the marginaleffects package could support lqmm model, and it would be great!

Here is a sample code for the not support error.
```
library(lqmm) # linear quantile regression with mixed effect
library(marginaleffects)
packageVersion("marginaleffects")
> [1] ‘0.18.0.9004’
# Test example
set.seed(123)
M <- 50
n <- 10
test <- data.frame(x = runif(n*M,0,1), group = rep(1:M,each=n))
test$y <- 10*test$x + rep(rnorm(M, 0, 2), each = n) + rchisq(n*M, 3)
fit.lqmm <- lqmm(fixed = y ~ x, random = ~ 1, group = group,
                 data = test, tau = 0.5, nK = 11, type = "normal")
fit.lqmm
# predict.lqmm(fit.lqmm)

# marginal effect
plot_predictions(fit.lqmm, by = "x")
> Error: Models of class "lqmm" are not supported.
marginaleffects::predictions(fit.lqmm)
> Error: Models of class "lqmm" are not supported.
```

**Comment by vincentarelbundock** [comment]
Thank you very much for raising this issue. I am very interested in supporting this model. 

Unfortunately, I do not know the package, I am not very familiar with linear quantity mixed models, and I do not have a lot of free time currently.

It might be relatively easy to implement following the guidelines here: https://marginaleffects.com/vignettes/extensions.html

My guess is that the main challenge will be to compute estimates of uncertainty. That will probably be easy to do for fixed effects, but to produce estimates that take into account random effects might not be as straightforward. It would require:

+ `vcov()` method that returns a full matrix, not just for FE. It doesn't look like `lqmm` provides that (I could be wrong).
+ `set_coef()` method (see link above) that modifies the coefficients inside the model object to make different predictions for different groups.

For now, I will mark this as "Help Wanted" and link to this discussion in the main feature request thread.

Thanks and sorry I can't provide immediate support.

**Comment by Sueleaf** [comment]
Hi Vince!

Thanks for your quick response and your guides! I'll try to figure it out how to do that in lqmm. If the right final results was obtained, I would try to post it in this issue.

Thanks again for your help!
