### ISSUE TITLE
Integrating out random effects fails when group variable is a factor (This because```datagrid(...)``` fails)

### ISSUE THREAD

**Issue by Sandhu-SS** [vincentarelbundock/marginaleffects#1077]
Hi, 

When group variable (such as ```firm``` in the example below) is a factor variable, the ```datagrid(..)```, and hence the ```marginaleffects``` functions fail when new levels are passed. 

Note that various ```brms``` functions such as ```brms::posterior_epred()``` work fine regardless of whether the group variable (```firm```) is an integer or a factor.

# Get data
```
dat <- read.csv("https://vincentarelbundock.github.io/Rdatasets/csv/plm/EmplUK.csv")
dat$x <- as.numeric(dat$output > median(dat$output))
dat$y <- as.numeric(dat$emp > median(dat$emp))
# Note that group variable 'firm' is an integer
dat_firm_integer <- dat
str(dat_firm_integer)
# Convert group variable 'firm' to a factor
dat_firm_factor <- dat
dat_firm_factor$firm <- as.factor(dat_firm_factor$firm)

```

# Fit models
```
mod_firm_integer <- brm(y ~ x + (1 | firm), data = dat_firm_integer, 
                        backend = "cmdstanr", family = "bernoulli",
                        chains = 1, iter = 1000)


mod_firm_factor <- brm(y ~ x + (1 | firm), data = dat_firm_factor, 
                       backend = "cmdstanr", family = "bernoulli",
                       chains = 1, iter = 1000)

```

# Works when 'firm' is an integer
```
predictions(
  mod_firm_integer,
  newdata = datagrid(x = 0:1, firm = -1:-100),
  allow_new_levels = TRUE,
  sample_new_levels = "gaussian",
  by = "x")

# This because datagrid works for integer group variable integer 
head(datagrid(model = mod_firm_integer, x = 0:1, firm = -1:-100))

```

# Fails when 'firm' is a factor
```
predictions(
  mod_firm_factor,
  newdata = datagrid(x = 0:1, firm = -1:-100),
  allow_new_levels = TRUE,
  sample_new_levels = "gaussian",
  by = "x")

# This because datagrid works for integer group variable integer 
head(datagrid(model = mod_firm_factor, x = 0:1, firm = -1:-100))

```

# Note that brms functions works when form is an integer or a factor
```
nd_integer <- expand.grid(x = 0:1, firm = -1:-100)
nd_factor <- expand.grid(x = 0:1, firm = as.factor(-1:-100))

head(brms::posterior_epred(mod_firm_factor, newdata = nd_integer, allow_new_levels = T))

head(brms::posterior_epred(mod_firm_factor, newdata = nd_factor, allow_new_levels = T))

```

**Comment by vincentarelbundock** [comment]
This is one area where I disagree with the `brms` developers. The main reason I like working with factors for ID variables is that they are stricter than integers.

In your first example, 1 is level 1. In your second example, -1 silently becomes level 1. This can lead to errors.

I understand how it would be useful in this very particular use case (for one modeling package, and one options -- new levels). But I find the error important for nearly all other use cases.

Since there is an easy workaround (use integers or characters), I will not fix this.

Sorry!
