### ISSUE TITLE
Suppressing column names in output

### ISSUE THREAD

**Issue by krakac24** [vincentarelbundock/marginaleffects#1093]
I'm currently using your package to estimate marginal effects in a vignette (specifically, the avg_comparisons() function). I've noticed below the table of quantitative results is a list of column names. I've gotten feedback from some editors that it can be confusing when they don't match the column names in the table, which happens on occasion. Is there a way to suppress that list of column names and just print the table with quantitative results? Thanks so much, and I'm happy to provide an example if that would help.

**Comment by vincentarelbundock** [comment]
Every print option is availble to be set using a global option. See the function signature:

https://marginaleffects.com/man/print.marginaleffects.html

Also, you can use the `modelsummary` package to produce much nicer looking tables:

https://marginaleffects.com/vignettes/tables.html
