### ISSUE TITLE
Inconsistent with Stata results

### ISSUE THREAD

**Issue by ZhihaoMa** [vincentarelbundock/marginaleffects#1094]
I've observed inconsistency between the results from Marginaleffects and those from Stata for the logit model. I conducted an analysis using the dataset "womenwk" as an example. The analysis results and dataset are attached. It's evident that there are variations in the estimate results (e.g, coeff of _married_), especially notable when accounting for Marginal Effects at means.

![R_results2](https://github.com/vincentarelbundock/marginaleffects/assets/49115309/4557b4cb-d9dd-4fa4-a24e-f71e335eb94f)
![Stata_results2](https://github.com/vincentarelbundock/marginaleffects/assets/49115309/582dd1e6-8f9d-42a2-8f96-adb2b4a3c0e1)
![R_results](https://github.com/vincentarelbundock/marginaleffects/assets/49115309/e83f79f6-7d58-480c-b191-f4181602eb63)
![Stata_results](https://github.com/vincentarelbundock/marginaleffects/assets/49115309/7daf5e71-18ed-4b57-82b4-9bacbc9cfd63)
[womenwk.dta.zip](https://github.com/vincentarelbundock/marginaleffects/files/15040571/womenwk.dta.zip)

**Below is my R code:**

_library(readstata13)
library(fixest)
library(modelsummary)
library(marginaleffects)_

_dat <- read.dta13("womenwk.dta")
mod <- femlm(work ~ age + married + children + education, dat, family = "logit")
summary(mod)
avg_slopes(mod, by = TRUE)
slopes(mod, newdata = "mean")_

**Below is my Stata code:**

_use "womenwk.dta", clear
logit work age education married children
margins,dydx(*)
margins,dydx(*) atmeans_

**Comment by ZhihaoMa** [comment]
> My guess is that Stata takes the partial derivative with respect to the married variable, which makes no sense given that it is binary (categorical). If you try with Stata again while specifying that this is a categorical variable, I bet a dollar you'll get very similar results.

Thanks for your quick response. Following your suggestion, I removed the "married" variable from the regression and reran the code. Their AME results are very close but the results of ME at means remain different.  I'm not sure whether there's an issue with my code or if the two packages calculate these metrics differently.

**Comment by vincentarelbundock** [comment]
When automatically computing the mean of an integer variable, `marginaleffects` returns rounded integers rather than numbers with decimal. In your dataset, the variables are explicitly defined as integers, so `marginaeffects` respects that:

``` r
library(readstata13)
library(fixest)
library(modelsummary)
library(marginaleffects)

dat <- read.dta13("womenwk.dta")
sapply(dat, class)

           c1        c2         u         v    county       age education   married 
    "numeric" "numeric" "numeric" "numeric" "numeric" "integer" "integer" "integer" 
     children    select  wagefull      wage        lw      work       lwf 
    "integer" "numeric" "numeric" "numeric" "numeric" "numeric" "numeric" 
```

You could replicate the Stata results nearly exactly by specifying
manually:

``` r
mod <- glm(work ~ age + married + children + education, dat, family = binomial)
slopes(mod, newdata = datagrid(
    age = 36.208,
    education = 13.084,
    married = .6705,
    children = 1.6445
))

          Term Contrast  age education married children Estimate Std. Error     z
     age          dY/dX 36.2      13.1    0.67     1.64   0.0115    0.00142  8.08
     children     dY/dX 36.2      13.1    0.67     1.64   0.1518    0.00938 16.19
     education    dY/dX 36.2      13.1    0.67     1.64   0.0195    0.00370  5.28
     married      1 - 0 36.2      13.1    0.67     1.64   0.1546    0.02703  5.72
     Pr(>|z|)     S   2.5 % 97.5 %
       <0.001  50.4 0.00871 0.0143
       <0.001 193.4 0.13342 0.1702
       <0.001  22.8 0.01226 0.0268
       <0.001  26.5 0.10159 0.2075

    Columns: rowid, term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, age, education, married, children, predicted_lo, predicted_hi, predicted, work 
    Type:  response 
```

Or by setting the variables to numeric type:

``` r
dat <- transform(dat,
    education = as.numeric(education),
    married = as.numeric(married),
    age = as.numeric(age),
    children = as.numeric(children))

mod <- glm(work ~ age + married + children + education, dat, family = binomial)
slopes(mod, newdata = "mean")


          Term Contrast Estimate Std. Error     z Pr(>|z|)     S   2.5 % 97.5 %
     age          dY/dX   0.0102    0.00135  7.56   <0.001  44.4 0.00754 0.0128
     children     dY/dX   0.1343    0.00808 16.62   <0.001 203.6 0.11849 0.1502
     education    dY/dX   0.0173    0.00339  5.10   <0.001  21.5 0.01063 0.0239
     married      1 - 0   0.1546    0.02703  5.72   <0.001  26.5 0.10159 0.2075

    Columns: rowid, term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted_lo, predicted_hi, predicted, age, married, children, education, work 
    Type:  response 
```

**Comment by ZhihaoMa** [comment]
Adding to my earlier inquiry, I've encountered an additional issue regarding ME at mean. When attempting to estimate ME at mean based on the results of a regression that includes a set of fixed effects, I received the following error message:

Error: The function supplied to the `comparison` argument must accept two numeric
  vectors of predicted probabilities of length 0, and return a single numeric value
  or a numeric vector of length 0, with no missing value.
In Addition: Warning message:
In formals(fun) : argument is not a function

When I exclude these fixed effects or estimate AME, the issue disappears. How can I resolve this error?

Thanks a lot!

**Comment by vincentarelbundock** [comment]
I answered your earlier query already.

I cannot diagnose your new question without a reproducible example.

**Comment by ZhihaoMa** [comment]
Thank you for your previous response. I apologize for any confusion in my earlier messages. To provide more clarity, here is the code snippet:

_library(readstata13)
library(fixest)
library(modelsummary)
library(marginaleffects)_

_dat <- read.dta13("XXXX.dta")_

_m0 <- femlm(Y ~ X, dat, family = "logit", cluster=c("group_m") )
avg_slopes(m0, by = TRUE) #successfully report results
slopes(m0, newdata = "mean") #successfully report results_

_m1 <- femlm(Y ~ X | FE_1 + FE_2, dat, family = "logit", cluster=c("group_m"))
avg_slopes(m1, by = TRUE) #successfully report results
slopes(m1, newdata = "mean") #fail to report results_

I'm open to starting a new issue if you think it's necessary. This code demonstrates the issue I'm facing with the slopes() function when estimating **marginal effects at the mean** with **high-dimension fixed effects** included. If you have any insights on how to resolve this error, I would greatly appreciate it. Thank you for your help.

**Comment by vincentarelbundock** [comment]
Thanks, but it is really hard to diagnose without a fully reproducible example using public data.

**Comment by vincentarelbundock** [comment]
For instance, this seems to work:

``` r
library(fixest)
library(marginaleffects)

packageVersion("marginaleffects")
```

    [1] '0.19.0.1'

``` r
dat <- transform(trade, Euros = ifelse(Euros > median(Euros), 1, 0))
mod <- femlm(Euros ~ dist_km + Year | Destination + Origin, family = "logit", data = dat)

avg_slopes(mod)
```


        Term  Estimate Std. Error     z Pr(>|z|)     S     2.5 %   97.5 %
     Year     0.006088   4.29e-04  14.2   <0.001 149.1  0.005247  0.00693
     dist_km -0.000242   1.63e-05 -14.9   <0.001 163.4 -0.000274 -0.00021

    Columns: term, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high 
    Type:  response 

``` r
slopes(mod, newdata = "mean")
```


        Term  Estimate Std. Error      z Pr(>|z|)   S    2.5 % 97.5 %
     Year     0.003447    0.03084  0.112    0.911 0.1 -0.05700 0.0639
     dist_km -0.000137    0.00124 -0.110    0.912 0.1 -0.00258 0.0023

    Columns: rowid, term, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted_lo, predicted_hi, predicted, dist_km, Year, Destination, Origin, Euros 
    Type:  response

**Comment by ZhihaoMa** [comment]
Thanks for your reply. The problem doesn't seem to be caused simply by the fact that I added two fixed effects. Do you think it would still be helpful if I provided the results stored in the object _m1_?

**Comment by vincentarelbundock** [comment]
It would be useful to have the full data and code to replicate the error exactly as you see it. This is what I mean by "reproducible example."

Please read the "Getting Help" section of the website:

https://marginaleffects.com/vignettes/help.html#getting-help

**Comment by vincentarelbundock** [comment]
resolved over email. no bug found.
