### ISSUE TITLE
Possible typo in Tutorials > Predictions

### ISSUE THREAD

**Issue by zhengchencai** [vincentarelbundock/marginaleffects#1098]
Hello,

Thanks a lot for developing this very useful tool. I was reading the documentation and trying to use ```epred_draws``` and ```stat_lineribbon``` from tidybayes to replicate what was done in the documentation. In this way, I could understand what is exactly done by the plot function and the difference between "condition" and "by". 

There might be a typo in https://marginaleffects.com/vignettes/predictions.html, I guess you meant "The predictions displayed by the [plot_predictions()](https://marginaleffects.com/man/plot_predictions.html) function with the **by** argument", not **condition**

> Marginal Adjusted Predictions The predictions displayed by the [plot_predictions()](https://marginaleffects.com/man/plot_predictions.html) function with the **condition** argument can be said to be “conditional” in the sense that they are conditional on the values of the predictors in a constructed grid of values. The same function can also plot “marginal” predictions. The underlying process is to (1) compute predictions for each observation in the actually observed dataset, and then (2) average these predictions across some variable(s). This is equivalent to plotting the avg_predictions(model, by='z') call.

From what I understand, what "condition" does is to first get all the typical values of each variable in the data except for the one specified by "variable", then make predictions. This means all of the new values of the "variable" are associated with the same values of all the other variables. This is like [marginal effects at user-specified or representative values](https://www.andrewheiss.com/blog/2022/05/20/marginalia/#marginal-effects-at-the-mean-the-default-in-emmeans). For scalar variables in "condition", it will be defined as 50 data points from min to max, and all other variables are kept at their typical value. 

https://github.com/vincentarelbundock/marginaleffects/blob/08ccb23f1867192e66b00cee342b33f4f1fd5224/R/sanitize_condition.R#L87

Option "by" on the other hand does not take typical values from the data, but gets prediction for all rows of the data (from model or new). Then they are averaged w.r.t the variables defined by option "by". This is like [group average marginal effects](https://www.andrewheiss.com/blog/2022/05/20/marginalia/#marginal-effects-at-the-mean-the-default-in-emmeans) with groups defined with "by".

**Comment by vincentarelbundock** [comment]
Thanks a lot for reading the docs in such detail, and for reporting this confusion. I appreciate it.

This commit https://github.com/vincentarelbundock/marginaleffects/commit/d033eee261d00740c179adbf52c74daed246e6eb clarifies the paragraph.

It might not be updated immediately on the website, but it will be there the next time I render and build the whole thing.

Thanks again!

**Comment by vincentarelbundock** [comment]
And yes, from what you describe, it sounds like you correctly understood what the two arguments do.

**Comment by zhengchencai** [comment]
Thanks a lot for the confirmation. The package is really great !
