### ISSUE TITLE
plot_predictions: "wts" argument without "by"

### ISSUE THREAD

**Issue by anthonykevins** [vincentarelbundock/marginaleffects#1101]
Thanks very much for all of your hard work on this great package. 

I have a quick question about the use of survey weights with `plot_predictions` that I was hoping you might be able to assist with.

In particular, I was wondering whether the warning "With models of this class, it is normally good practice to specify weights using the `wts` argument" returned by plot_predictions: 
1. only actually applies to cases with a "by" argument; or 
2. indicates that plot_predictions is incapable of incorporating weights in instances without a "by" argument.

Here's a MWE to explain the background for my question:

`library(stevedata)`
`library(survey)`
`library(marginaleffects)`
`toy_data <- ESS10NO`  
`d_design <- svydesign(ids =~ 0, weights =~ dweight, data = toy_data)`
`reg_results <- svyglm(formula = lrscale ~ agea * hinctnta + eduyrs + polint, 
                      data = toy_data, design = d_design)`
`pred_values <- plot_predictions(reg_results, condition = list(agea = 25:65, hinctnta = c(3, 7)))`

This returns the warning "With models of this class, it is normally good practice to specify weights using the `wts` argument. Otherwise, weights will be ignored in the computation of quantities of interest."

If I then add a "wts" argument, however,...

`
pred_values <- plot_predictions(reg_results, condition = list(agea = 25:65, hinctnta = c(3, 7)), 
                                wts = toy_data$dweight)
`

... this returns the error "The `wts` argument requires a `by` argument."

It is my understanding that the analysis I'm attempting to conduct does not require a "by" argument, but if I do add one... 

`
pred_values <- plot_predictions(reg_results, condition = list(agea = 25:65, hinctnta = c(3, 7)), 
                                wts = toy_data$dweight, by = toy_data$hinctnta)
`

... this returns the error "Assertion on 'by' failed: Must be of type 'character' (or 'NULL'), not 'double'".
 
As such, I was hoping to clarify whether weights are actually being ignored in the above code, and if they are, whether it is possible to incorporate them without including a "by" argument. 

I hope that's clear, but please do just let me know if any additional information would be of use.

**Comment by vincentarelbundock** [comment]
Thanks for the report.

You're right, this warning is only relevant when the `by` argument is used. I just pushed a change to Github to remove the extraneous warning.

In `plot_predictions()` I recommend you use `wts="hinctnta"` rather than the vector. This allows handling of missing values more gracefully.

In `plot_predictions()` you cannot use both the `condition` and `by` arguments together. The error should not be more self-explanatory.

**Comment by anthonykevins** [comment]
That's very helpful, thanks so much! Hope to say hello/thanks in person one day at a polisci conference :)

**Comment by vincentarelbundock** [comment]
That would be great!
