### ISSUE TITLE
Request for plot_comparisons choosing number of columns or rows when printing

### ISSUE THREAD

**Issue by Crismoc** [vincentarelbundock/marginaleffects#1106]
Bug reports must include:

1. *Concise* description of the bug
2. *Minimal* reproducible example using publicly available data and the bare minimum code and libraries needed to reproduce the bug.
    - Consider using the `mtcars` dataset which is distributed by default with `R`, or one of the [CSV files from the RDatasets archive.](https://vincentarelbundock.github.io/Rdatasets/articles/data.html)
3. `sessionInfo()` output

Make sure you are running the *latest development version* of `marginaleffects` and its dependencies: https://marginaleffects.com/#installation

**Comment by vincentarelbundock** [comment]
See `?print.marginaleffects`
