### ISSUE TITLE
`newdata = subset()` with multiple imputation

### ISSUE THREAD

**Issue by ngreifer** [vincentarelbundock/marginaleffects#1117]
Trying to estimate the ATT after multiple imputation using g-computation:

``` r
library(marginaleffects); library(mice)
data("lalonde_mis", package = "cobalt")

imp <- mice(lalonde_mis, print = FALSE)

est <- with(imp, lm(re78 ~ treat * (age + educ + re74)))

avg_predictions(est, variables = "treat",
                newdata = subset(treat == 1))
#> Error: object 'treat' not found
```

<sup>Created on 2024-05-05 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

I think ideally, the `subset()` functionality would apply to each imputed dataset, which should be extractable from the `mira` object. This is the source of the bug observed [here](https://stats.stackexchange.com/q/646546/116195).

**Comment by vincentarelbundock** [comment]
Thanks for the report. 

FWIW, I disagree with the characterisation of this as a "marginaleffects bug". This package does not supply any subsetting or filtering functionality at all, and offering this feature feels out of scope given that there are already subset() and filter() alternatives.

The real problem is that mice does not supply a subset.mira() method, and I think that that is where this should be fixed. 

The mice author is very responsive, and I'm sure he would consider this seriously if someone submitted a PR.

**Comment by ngreifer** [comment]
Fair enough, I deleted my comment saying so. I assumed `subset()` was applied to the data extracted from the model. I know `marginaleffects` is capable of extracting that data since it has to do before supplying internally to `datagrid()` for constructing the counterfactual grid (i.e., in `process_imputation()`). I assumed that for multiply imputed data, it should be straightforward to supply the `susbet()` call to each imputed dataset, but it looks like the `subset()` call is maybe applied too early. Is that not so? I don't think there should be a `subset.mira()` method because `mira` is a list of regression models.

**Comment by vincentarelbundock** [comment]
Hmm, I can't really remember the logic right now, but things happen in `process_imputation()`:

https://github.com/vincentarelbundock/marginaleffects/blob/main/R/comparisons.R#L331

https://github.com/vincentarelbundock/marginaleffects/blob/main/R/imputation.R#L1

**Comment by ehei7** [comment]
Thank you for bringing up this issue. Has the discussion now moved to another page? I'd like to know where to check if there is a fix for this in the future.

**Comment by vincentarelbundock** [comment]
Yes, this is the right issue to follow progress. However, I don't personally have time to work on this now, so I can't promise quick developments. Also, it's not clear to me exactly what can/should be done within `marginaleffects` to solve this.

If I were you, I'd try to do this more manually:

1. Estimate your models in each dataset separately
2. Apply `avg_slopes()` to each of your models. The `newdata=subset()` syntax should work if you feed the function one dataset at a time.
3. Pool the results with `mice::pool()`

This is all pretty easy, and will be much faster than waiting for a resolution here.

Sorry I can't have a ready made solution for you now.

**Comment by vincentarelbundock** [comment]
I looked into this and all the solutions I can think of at the moment would add a lot of code complexity on the backend. I would be happy to consider pull requests if someone comes up with a solution, but it would have to be pretty simple and easy to maintain.

In the meantime, I added a short example of what I suggested above to the multiple imputation vignette. It's in the `.qmd` file now and will be on the website the next time I build it.

https://github.com/vincentarelbundock/marginaleffects/commit/7a89e33ec280378c4a3c9037058da51265a45d94

Thanks for raising the issue.

**Comment by ASKurz** [comment]
Circling back to @ngreifer's original example, is the `by` argument a valid workaround? 

```
avg_predictions(est, 
                variables = "treat",
                by = "treat")
```
```
 treat Estimate Std. Error    t Pr(>|t|)     S 2.5 % 97.5 %      Df
     0     6564        340 19.3   <0.001 274.1  5898   7230 1563518
     1     6623        572 11.6   <0.001 100.7  5503   7744  176997

Type:  response 
Columns: treat, estimate, std.error, s.value, df, statistic, p.value, conf.low, conf.high 
```

That is, would it be okay to just interpret the second row as the ATT?

**Comment by ngreifer** [comment]
Unfortunately not for `avg_predictions()`. For `avg_comparisons()`, yes, i.e.,
```
avg_comparisons(est, variables = "treat", by = "treat")
```
```
 treat Estimate Std. Error      t Pr(>|t|)   S 2.5 % 97.5 %  Df
     0     -202        728 -0.278    0.781 0.4 -1632   1228 599
     1      809        643  1.258    0.209 2.3  -454   2071 572

Term: treat
Type:  response 
Comparison: 1 - 0
```
The `1` row is the ATT and the `0` row is the ATC. For `avg_predictions()`, the predictions are already split on the `by` variable, and the predictions are computed in the entire dataset, so those are the predictions you would get corresponding to the ATE.

To get the ATT, you need to manually perform the analysis on each fitted model. Additionally, you need to rename the `treat` column to `term` to use `pool()`.

```
pool(lapply(est$analyses, function(x) {
  a <- avg_predictions(x, variables = "treat",
                       newdata = subset(treat == 1))
  names(a)[names(a)=="treat"] <- "term"
  a
})) |> summary()
```
```
  term estimate std.error statistic       df      p.value
1    0 5540.400  387.6272  14.29311 447.8879 1.899718e-38
2    1 6349.144  512.7719  12.38200 603.9485 1.539530e-31
```
These are the average predictions that are contrasted to compute the ATT. The `0` row is the mean expected potential outcome under control for the treated units, and the `1` row is the mean expected potential outcome under treatment for the treated units, which is equal to the observed mean for the treated units.

**Comment by ASKurz** [comment]
Ha! Okay, that was a copy/paste goof on my end. I meant `avg_comparisons()`.

**Comment by ASKurz** [comment]
Anyway, thank you for the confirmation. This seems like a nice shortcut compares to the manual solution.

**Comment by ngreifer** [comment]
I'm working on a fix to this that seems quite promising. Should be ready to review in a few days.

**Comment by huftis** [comment]
Just a thought: Subsetting with imputed data seems dangerous. If the variable(s) you’re subsetting are complete (i.e., non-missing), I think it’s OK. And I guess the treatment variable will usually be complete, at least for interventional studies (but not necessarily for observational studies).

But *in general*, values for the subset variables may be missing for some rows (that’s why we’re doing imputation). And then the values will be imputed differently in the different imputation (e.g., for patient/row 13, the value of `treat` will be 1 in some imputed datasets and 0 in others). So the subsets of the imputed data will have different number of rows. And then you can’t average these subsets.

**Comment by ngreifer** [comment]
@huftis I don't know if that's true; I'd be curious to see some simulation evidence of that. In any case, usually the treatment variable isn't missing in causal inference applications, so I still think this is a useful feature, even if it isn't valid in all circumstances. Lots of values produced by this package and others don't have valid interpretations, but that doesn't mean we should omit those features. It's (at least partly) the responsibility of the analyst to know whether the operation they're performing is statistically valid.

**Comment by huftis** [comment]
> [@huftis](https://github.com/huftis) I don't know if that's true; I'd be curious to see some simulation evidence of that. In any case, usually the treatment variable isn't missing in causal inference applications, so I still think this is a useful feature, even if it isn't valid in all circumstances.

I agree that it’s useful. And I *think* it should be OK if the variable you’re subsetting doesn’t have any missing data. But perhaps there could be a check to ensure this? I don’t know if this is possible to easily implement, as subset expressions can be complicated. But at least a partial check could be to check if the resulting prediction data frames all have the same number of rows. (This is similar to the check that functions like `drop1()` for regression models do.)

**Comment by huftis** [comment]
> I'm still not convinced it's invalid to combine estimates across multiply datasets when the subsetting variable has missingness. Do you have any evidence for that claim? I know it sounds reasonable, but I don't know if it's actually true. It would only make sense to produce a warning if there were actually something invalid about it.

I’m not sure if I was explaining my thinking good enough. I was assuming that you were calculating *predictions* first. If you have 3-row dataset with these values (and other variables)

```
id  trt
1     0
2    NA
3     1
```

and generate multiple imputations, one might look like this:

```
id  trt
1     0
2     0
3     1
```

and another like this

```
id  trt
1     0
2     1
3     1
```

Averaging the predictions (using `avg_predictions()`) wouldn’t be a problem. But if you subset the imputations with `trt == 1`, how are you actually doing this? You’re left with one dataframe with one row (containing observation 3) and one with two rows (containing observation 2 and 3), or basically one vector with one prediction and one vector with two predictions. And you can’t take averages of vectors of different sizes.

But perhaps you are thinking that for each row, you take the average of all imputations *that happen to have* `trt == 1`? So you basically get data frames which look like this:.

```
id  trt
1     0
2   0/1
3     1
```

And the `avg_predictions()` for the subset should be based on *none* of the row-1 predictions, *some* of the row-2 predictions and *all* of the row-3 predictions?

Another (but obviously not good!) solution would be to base the subset on the values of the `trt` variable that `predictions()` actually *output*. I’m not very familiar with how `marginaleffects` handle multiple imputations, but it seems that `predictions()` just uses the values in the *first* imputation:

``` r
library(reprex)
library(mice)
library(marginaleffects)
data("lalonde_mis", package = "cobalt")
lalonde_mis[524,]
#>     treat age educ   race married nodegree re74 re75     re78
#> 524     0  26    9 hispan      NA        1   NA    0 2862.356
set.seed(6)
imp <- mice(lalonde_mis, print = FALSE)
complete(imp, 1)[524,] # These values are used included in predictions()
#>     treat age educ   race married nodegree   re74 re75     re78
#> 524     0  26    9 hispan       0        1 587.78    0 2862.356
complete(imp, 2)[524,]
#>     treat age educ   race married nodegree     re74 re75     re78
#> 524     0  26    9 hispan       0        1 391.8534    0 2862.356
complete(imp, 3)[524,]
#>     treat age educ   race married nodegree     re74 re75     re78
#> 524     0  26    9 hispan       1        1 9708.167    0 2862.356

est <- with(imp, lm(re78 ~ treat * (married+re74)))
as.data.frame(predictions(est)[524,])
#>     rowid estimate std.error   s.value     re78 treat married   re74         df
#> 524   524 5701.236  2058.063 0.1628149 2862.356     0       0 587.78 0.03316328
#>     statistic   p.value      conf.low    conf.high
#> 524  2.770195 0.8932804 -3.232788e+41 3.232788e+41
```

The value of `married` and `re74` is identical to the values in `complete(imp, 1)[524,]`.

**Comment by ngreifer** [comment]
I understand what you're saying. I agree this is an issue for `predictions()` and `comparisons()`, but I'm primarily concerned with `avg_predictions()` and `avg_comparisons()`. As long as at least one unit is in each subset in each imputation, there should be no problems with the `avg_*` functions. The `avg_*` results are computed within each imputed dataset separately and then pooled, not by pooling individual predictions/comparisons across imputed datasets and computing the average of the pooled predictions. So in one imputation, the `avg_predictions()` results may come from 100 units, and in another imputation, the `avg_predictions()` results may come from 120 units. This isn't a problem because each estimate is a consistent estimate of the average conditional prediction, all of which are then across imputations pooled to arrive at a single final estimate.

I wonder if `predictions()` should throw an error if the number of quantities to be pooled differ across imputations. For example, for the predictions, if one imputation has 100 predicted values and another has 120 predicted values, it's not clear how pooling should work. I don't know if methodologists have solved this problem. My intuition is that it should be fine to pool estimates across only those imputations in which that estimate occurs, adjusting the number of imputations used in the pooling formula to correspond to the number of imputations in which that estimate occurs.
