### ISSUE TITLE
`get_predict.svyglm()` throws "NAs introduced by coercion" when data row names are not integers

### ISSUE THREAD

**Issue by ngreifer** [vincentarelbundock/marginaleffects#1131]
These line in `get_predict.svyglm()` causes warning "NAs introduced by coercion" when the rownames in the original dataset are not integers:

https://github.com/vincentarelbundock/marginaleffects/blob/7a89e33ec280378c4a3c9037058da51265a45d94/R/methods_survey.R#L79-L83

Reprex:

``` r
data("lalonde", package = "MatchIt")
rownames(lalonde)[1:5]
#> [1] "NSW1" "NSW2" "NSW3" "NSW4" "NSW5"

fit <- survey::svyglm(re78 ~ treat, design = survey::svydesign(~1, weights = ~1, data = lalonde))

p <- marginaleffects::get_predict(fit, newdata = lalonde)
#> Warning in get_predict.svyglm(fit, newdata = lalonde): NAs introduced by
#> coercion
```

<sup>Created on 2024-05-29 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by vincentarelbundock** [comment]
thanks for the report. should be fixed on github
