### ISSUE TITLE
Typo in Get Started page

### ISSUE THREAD

**Issue by Stucklog** [vincentarelbundock/marginaleffects#1142]
Search "some some" on the Get Started page on https://marginaleffects.com/ to find the typo. Cheers.

**Comment by Stucklog** [comment]
Also in the following paragraph: "to" instead of "two"

**Comment by vincentarelbundock** [comment]
Thanks, I appreciate you taking the time to note these!

Should be fixed on Github, but it'll be on the website only when I re-build it next time.
