### ISSUE TITLE
Support: `endorse`

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/marginaleffects#1144]
Hello! Since endorsement experiments are very useful for gauging people's opinions on contentious issues whilst removing social desirability bias, I think that it would be nice to add the option for using this package with the 'endorse' package in R. This is especially important since converting the endorsement model to another type of model could distort the results.

_Originally posted by @cmellman in https://github.com/vincentarelbundock/marginaleffects/discussions/1143_

**Comment by vincentarelbundock** [comment]
Unfortunately, the `predict.endorse()` method supplied by this package does not support hierarchical models, so `marginaleffects` cannot support those models until the functionality is supplied upstream.

Moreover, I encountered some difficulty executing `predict(fit)` on some of the models in the documentation. As such, I'm not sure it's worth investing a ton of time to support this package.

I'd be happy to provide guidance if someone else wants to contribute code. The key would be to create a `get_predict.endorse()` which returns a data.frame and an attribute with a matrix of posterior draws.

Similar code: https://github.com/vincentarelbundock/marginaleffects/blob/main/R/methods_brms.R

Tutorial on writing extensions: https://marginaleffects.com/vignettes/extensions.html

**Comment by cmellman** [comment]
Would there be a way to, nevertheless, accommodate for non-hierarchical versions of endorse models? Additionally, if this cannot occur, what suggestions would you have in terms of resources that I can use to run predictions on them (that can also accommodate for variable lambdas)?

**Comment by vincentarelbundock** [comment]
yes, there definitely would be a way to accommodate. A code contributor would simply have to follow the two links I posted above and ask questions after, if they don't know what to do. I would be happy to provide guidance. Unfortunately, I don't have time to do the whole work for a package that only can be half-way supported.

**Comment by cmellman** [comment]
I don't really know how to start. I tried something along the lines of this: endorseFULL <- endorse(Y = Y, data = data_slvk, identical.lambda = FALSE, covariates = TRUE, formula.indiv = formula( ~ age + gender + education + is_capital + ideology + income + DemPolGrievence + PolicyPolGrievence + EUPolGrievence + EconGrievenceRetro + EconGrievenceProspInd + EconGrievenceProspAgg + NatPride + NativeRights + NativeJobs + DemonstrateNational + LawOrder + Chauvinism + ChristianSchool + DemonstrateTrad + GayNeighbor+ GayPartner+ ForNeighbor + ForPartner + Ukraine), hierarchical = FALSE)

model <- endorseFULL

MASS::mvrnorm
#' @include get_predict.R
#' @rdname get_predict
#' @export
get_predict.endorse <- function(model,
                                newdata = insight::get_data(model),
                                type = "response",
                                ndraws = 1000,
                                ...) {
    
    # Check if the model is hierarchical
    if (model$hierarchical) {
        stop("Hierarchical models are not supported for prediction in endorse package.", call. = FALSE)
    }
    
    # Ensure newdata is properly handled
    if (is.null(newdata)) {
        newdata <- insight::get_data(model)
    }
    
    # Get point estimates
    point_estimates <- predict(model, newdata = newdata, ...)
    
    # Generate posterior draws
    posterior_draws <- generate_posterior_draws(model, newdata, ndraws)
    
    
    if (nrow(point_estimates) != nrow(newdata)) {
        warning("The dimensions of the predictions do not match the dimensions of newdata. This may indicate that newdata is not being respected by the endorse package.", call. = FALSE)
    }
    
    
    if ("rowid_internal" %in% colnames(newdata)) {
        idx <- newdata[["rowid_internal"]]
    } else if ("rowid" %in% colnames(newdata)) {
        idx <- newdata[["rowid"]]
    } else {
        idx <- 1:nrow(newdata)
    }
    
    
    out <- data.frame(
        rowid = idx,
        group = "main_marginaleffect",
        estimate = as.vector(point_estimates)
    )
    
    
    attr(out, "posterior_draws") <- posterior_draws
    
    return(out)
}


generate_posterior_draws <- function(model, newdata, ndraws) {
  
    params <- model$delta  # Assuming 'delta' contains the model parameters
    
    
    vcov_matrix <- model$vcov  # Assuming 'vcov' contains the variance-covariance matrix
    
    
    param_draws <- MASS::mvrnorm(n = ndraws, mu = params, Sigma = vcov_matrix)
    
    
    X <- model.matrix(model$formula.indiv, data = newdata)
    linear_predictors <- X %*% t(param_draws)
    
   
    response_draws <- plogis(linear_predictors)
    
    return(response_draws)
}
