### ISSUE TITLE
avg_predictions and avg_comparisons cannot find variable used to predict a distributional parameter in brms

### ISSUE THREAD

**Issue by andymilne** [vincentarelbundock/marginaleffects#1147]
In this brms model, the variable `cyl` is used to predict the `disc` parameter of the cumulative distribution. When running `avg_predictions()`, marginaleffects cannot find this variable even when supplying the original data frame as `newdata`. With `avg_comparisons()`, `cyl` is found only if the `newdata` argument is used. The `cyl` variable is included in the data saved with the model, so the `newdata` argument shouldn't be required.

In the repro below, you will find that only the final example works.

```
data("mtcars")

mdl <- 
  brm(
    bf(carb ~ gear * vs) +
      lf(disc ~ 0 + mo(cyl)),
    data = mtcars,
    family = cumulative("probit"),
    prior = set_prior("normal(0, 1)", class = "b") +
      set_prior("normal(0, 1)", dpar = "disc"),
  )

avg_predictions(
  mdl,
  variables = "vs",
  by = c("vs", "gear"),
  # newdata = mtcars,
  type = "link"
)

avg_predictions(
  mdl,
  variables = "vs",
  by = c("vs", "gear"),
  newdata = mtcars,
  type = "link"
)

avg_comparisons(
  mdl,
  variables = "vs",
  by = c("vs", "gear"),
  # newdata = mtcars,
  type = "link"
)

avg_comparisons(
  mdl,
  variables = "vs",
  by = c("vs", "gear"),
  newdata = mtcars,
  type = "link"
)

```

**Comment by vincentarelbundock** [comment]
Thanks for the report. I tracked it down to an upstream issue in the `insight` package. I opened an issue there. Once that upstream behavior is fixed, `marginaleffects` should behave as expected automatically.

https://github.com/easystats/insight/issues/896
