### ISSUE TITLE
Is avg_comparisons() appropriate when the predictor in variables is within-subject?

### ISSUE THREAD

**Issue by andymilne** [vincentarelbundock/marginaleffects#1150]
Conceptually, g-computation (counterfactual comparisons) make sense when the focal variable (i.e,. the variable used in the `variables` argument) is between-subject. But does it make sense when the variable is within-subject? I may well be wrong, but my intuition suggests it is not appropriate to have counterfactual predictions in the latter scenario. If my intuition is correct, this would be important because users naturally gravitate to `avg_comparisons()` rather than using the `hypothesis` argument within `avg_predictions()` (which, assuming there is no `variables` argument used in `avg_predictions()`, produces non-counterfactual predictions) because the former is easier to do and a non-expert user will likely be unaware that they are actually performing different calculations. 

A common example of a within-subject variable where this might be problematic is an indicator for whether a test is pre or post and one is interested in comparing (within-subject) pre-post changes by different (between-subject) interventions/treatments. It seems that the treatment variable can sensibly go in the `variables` argument but not pre-post. But I suspect a user (myself included when initially modelling such data) might put pre-post into the `variables` argument of `avg_comparisons()`, and treatment into the `by` argument. My intuition tells me that this is wrong. Treatment should be counterfactually predicted by going into the `variables` argument of `avg_predictions()`, then the `hypothesis` argument (or other post-processing such as `brms::hypothesis()` in a Bayesian setting) is used to make the (non-counterfactual) pre-post comparison.

It's quite possible I have this all wrong and counterfactual comparisons are generally unproblematic for within-subject predictors. But I wanted to raise this as something worth thinking about.

**Comment by vincentarelbundock** [comment]
I don't really see a problem, but this is something you probably want to discuss with a local statistician. Alternatively, you could post on Cross Validated (describing the actual quantities rather than referring to R commands).

Let's keep this issue tracker for bug reports and feature requests.
