### ISSUE TITLE
Feature Request: Support for model class "averaging" from MuMIn::model.avg() in R

### ISSUE THREAD

**Issue by Telis15** [vincentarelbundock/marginaleffects#1154]
Thank you for building a fantastic package!

I am currently trying to explore the marginal effects of predictors across a suite of top models and averaged models that I created in the MuMIn package with dredge() and model.avg().

I don't know everything involved, but as far as I can tell, that package's predict.averaging() works well and will hopefully allow for straightforward support for that model class ("averaging").

Below is a simple working example using the starwars data from tidyverse. Please let me know if there is any other information that would be helpful.

```r
library(MuMIn)
library(tidyverse)
library(marginaleffects)

# starwars dataset from tidyverse
data(starwars)

# Create dataframe with no missing values for predictors and response
dat <- starwars %>% 
  select(height, skin_color, homeworld, mass) %>% 
  na.omit()

# Create global model
mod <- lm(height ~ skin_color + homeworld + mass, data = dat, na.action = "na.fail")

# Rank all possible models and keep any with delta AIC < 20 as top models
modlist <- get.models(dredge(mod), subset = delta < 20)

# Predicting for a single model
summary(modlist[[3]])
plot_predictions(modlist[[3]], condition = "mass")

# Model averaging across top models
avgmod <- model.avg(modlist, fit = TRUE)
summary(avgmod)

# Base predict
predict(avgmod)

# Trying marginaleffects
plot_predictions(avgmod, condition = "mass")
````

**Comment by vincentarelbundock** [comment]
Interesting. My intuition is that these will be *very* hard to support.

I'm not in front of a computer now, but curious. Does the newdata argument work in predict() ?

**Comment by Telis15** [comment]
I just gave it a try, and yes, newdata worked as expected.

**Comment by vincentarelbundock** [comment]
Cool. I'll take a look when I find time

**Comment by Telis15** [comment]
I appreciate it!

I wish I knew enough about R and statistics to be more helpful. But I appreciate folks like you!

**Comment by vincentarelbundock** [comment]
I am interested in this, but may require some help, as I don't know this package at all. For now, I will be closing this issue to keep the issue tracker clean, and consolidating it with the other model support requests in this issue:

https://github.com/vincentarelbundock/marginaleffects/issues/49

The main steps to support this would be:coefficients

First, add the model class to `R/sanity_model.R`

Second, add a file called `R/methods_MuMIn.R` with three mehtods: `get_vcov()`, `get_coef()`, `set_coef()`. Examples below.

The one tricky thing I can't figure out is that `model$coefficients` is a matrix with two rows, and I'm not sure we have to take the derivative with respect to which set of coefficients: "full" or "subset". To support this, I would probably need a package expert to test different versions of the implementation.


```r
#' @rdname get_vcov
#' @export
get_vcov.averaging <- function(model, ...) {
    stats::vcov(model)
}


#' @rdname get_coef
#' @export
get_coef.averaging <- function(model, ...) {
    stats::coef(model)
}


#' @include set_coef.R
#' @rdname set_coef
#' @export
set_coef.averaging <- function(model, coefs, ...) {
    out <- model
    out$coefficients[1, ] <- coefs
    return(out)
}
```
