### ISSUE TITLE
`vcov` argument in `hypotheses` with an `lme` object.

### ISSUE THREAD

**Issue by RafRomB** [vincentarelbundock/marginaleffects#1160]
Hi,

I am using `nlme` package to build some lineal mixed models (because of some functionalities this package has compared to `lme4`), and using `hypotheses` function to make some contrasts about the coefficient of the resulting fixed effects of the model.

I have found that trying to specify the `vcov` argument when the model has been fitted with the `lme` function from the package `nlme`, results in the following error:

`Error: Satterthwaite and Kenward-Roger corrections are only available for linear mixed effects models.`

This error does not appear if the model is fit with the `lmer` function from the `lme4` package, so I guess that the `hypotheses` function does not recognize the model fit by `lme` as a mixed effect model.

Below there is a simple example:

```
library(nlme)
library(lme4)
library(marginaleffects)

data("mtcars")
mtcars$cyl <- as.factor(mtcars$cyl)

mod <- lme(mpg ~ hp + wt, random = ~1|cyl, data = mtcars)
summary(mod)

hypotheses(mod, hypothesis = "b2=b3", vcov = "satterthwaite") # Results in error

mod.lmer <- lmer(mpg ~ hp + wt +(1|cyl), data = mtcars)
summary(mod.lmer)

hypotheses(mod.lmer, hypothesis = "b2=b3", vcov = "satterthwaite") # No error
``` 
Additionally, when using the model fitted by `lmer`, the output from the `hypotheses` function is exactly the same independently if the `vcov` argument is specified or not, so I am not sure if it is actually doing something about the uncertainty of the estimates...

Here is my `sessioninfo()` for your reference:

```
R version 4.4.1 (2024-06-14)
Platform: x86_64-pc-linux-gnu
Running under: Ubuntu 22.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0 
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=nb_NO.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=nb_NO.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=nb_NO.UTF-8      
 [8] LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=nb_NO.UTF-8 LC_IDENTIFICATION=C       

time zone: Europe/Oslo
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] marginaleffects_0.21.0.3 lme4_1.1-35.3            Matrix_1.7-0             nlme_3.1-165            

loaded via a namespace (and not attached):
 [1] backports_1.5.0   lattice_0.22-5    splines_4.4.1     generics_0.1.3    nloptr_2.0.3      grid_4.4.1        data.table_1.15.4 compiler_4.4.1    boot_1.3-30       tools_4.4.1       checkmate_2.3.1  
[12] minqa_1.2.6       Rcpp_1.0.12       MASS_7.3-60       insight_0.20.1 
```

**Comment by vincentarelbundock** [comment]
Sorry, this kind of model is not supported. Only `lme4` models are, IIRC.

To add support, the `insight` package would need to add support upstream. Specifically, this function should return degrees of freedom for every observation:

```r
insight::get_df(mod, data = mtcars, type = "satterthwaite", df_per_observation = TRUE)
```

Feel free to open a new issue if/when `insight` supports the model you need.
