### ISSUE TITLE
'group' unclear in plot vignette

### ISSUE THREAD

**Issue by friendly** [vincentarelbundock/marginaleffects#1162]
Minor nit:
In the plot vignette, section _Groups and categorical outcomes_, you might point out that `group` is a variable constructed for the categorical response by the `prediction()` function. Otherwise it's a bit of a head-scratcher to figure out where that comes from.

**Comment by vincentarelbundock** [comment]
Thanks a lot for reading and making this suggestion. I agree the text wasn't clear. I just added a sentence here: https://github.com/vincentarelbundock/marginaleffects/commit/716831a1d4b8213f759eb62916cf355702376114

> In the resulting data frame, the `group` column identifies level of the categorical response.

This is now on Github and the website should be updated in a few weeks when I get back to the office and can run the build script again.
