### ISSUE TITLE
Points in plot_predictions do not seem to be correct

### ISSUE THREAD

**Issue by friendly** [vincentarelbundock/marginaleffects#1165]
What are the points in `plot_predictions()`, i.e., how are they calculated?
They do not seem to be correct in the example below.

```
library(effects)  # effect plots
library(marginaleffects)
data(Prestige, package="carData")
Prestige$type <- factor(Prestige$type, levels=c("bc", "wc", "prof")) #  just reorder levels

prestige.mod2 <- lm(prestige ~ education + women +
                      log(income)*type, data=Prestige)
plot_predictions(prestige.mod2, condition = "education", points = .4)
```
The points don't show the same trend as the fitted regression line.

![prestige-margeffects-educ](https://github.com/user-attachments/assets/91ac3969-fc0b-4096-83cf-3a4b9ac61488)

For comparison, I use the effects package, and plot the partial residuals

```
predictorEffects(prestige.mod2, ~ education,
                 residuals = TRUE) |>
  plot(partial.residuals = list(pch = 16, col="blue"),
       id=list(n=4, col="black"))
```

This looks more like it should:

![prestige-effects-educ](https://github.com/user-attachments/assets/4d2e6be7-9baf-48bf-93b2-6d58361f126c)

Also: it does not seem clear to me from the docs how I can change the color, shape, etc. of the points or the fitted line.

**Comment by vincentarelbundock** [comment]
There is currently no support for computing and displaying residuals in `marginaleffects`. (There are indirect ways to get them, but nothing documented or easy.) This is one area where `effects` is still clearly superior. The points that you are seeing are just raw data points, not residuals.

You can verify this by adding the points manually. This also allows you to chang ehte shape/color easily (the beauty of `ggplot2`!):

``` r
library(effects)  # effect plots
library(ggplot2)
library(marginaleffects)
data(Prestige, package="carData")
Prestige$type <- factor(Prestige$type, levels=c("bc", "wc", "prof"))

prestige.mod2 <- lm(prestige ~ education + women + log(income)*type, data=Prestige)

plot_predictions(prestige.mod2, condition = "education") +
  geom_point(data = Prestige, aes(education, prestige), shape = 3, alpha = .5, color = "blue")
```

![](https://i.imgur.com/HpzFfDE.png)

Some more thoughts on why `plot_predictions()` has very few arguments: https://marginaleffects.com/vignettes/faq.html#more-plot-customization I’d be happy to consider counter-arguments, etc.

**Comment by friendly** [comment]
I'd argue that showing the raw data points is misleading -- and this is what these plots (and for other terms in this model) shows.
Individual level predicted values for the response, given the 'other' variable is more sensible

**Comment by friendly** [comment]
On plot customization: Your approach of minimizing plot arguments in favor of using ggplot customization is OK, but you would make this easier by including some examples of doing this throughout the documentation, not just in what amounts to a footnote.

**Comment by vincentarelbundock** [comment]
Agreed.

I added a clear warning to the definition of the `points` argument.

I have also linked to [the Customization section](https://marginaleffects.com/vignettes/plot.html#customization) at the bottom of the visualization sections of both the Predictions and the Comparisons vignettes.

**Comment by vincentarelbundock** [comment]
Thanks!
