### ISSUE TITLE
`datagrid(grid_type = "counterfactual")` should retain all columns in `newdata`

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/marginaleffects#1175]
Thanks for this really nice package! In my own package I have a simple implementation but it would be amazing if I could switch that out to use `marginaleffects` and get support for all these model types.

We are doing discrete time survival modelling with logistic regression and we want to compare the survival probabilities over time. To do this I predict the probability of survival ("response") at each time and take the cumulative product within each id. Then I can average the probabilities at each time within each treatment groups.

I thought it might be possible to insert this `cumprod` step into the marginaleffects workflow. If I try with `predictions()` and a hypothesis function, I don't get the 'id' column, so I don't know which values to aggregate.

Should this be possible?

```r
library(marginaleffects)
library(dplyr)
library(tidyr)
set.seed(2024)
dat <- tibble(
  id = 1:10,
  assigned_treatment = rbinom(10, 1, 0.5),
  x2 = rpois(10, 3),
  outcome_t = rpois(10, lambda = 10 + x2/2 + 3 * assigned_treatment)
) 
dat <- expand_grid(dat, time = 0:15)
dat <- dat |> 
  mutate(
    outcome = if_else(time == outcome_t, 1, 0)
  ) |> 
  filter(time <= outcome_t) |> 
  select(-outcome_t)

my_model <- glm(outcome ~ assigned_treatment + x2 + time,
           data = dat,
           family = binomial)

dg <- datagrid(
  newdata = dat[dat$time == 0,],
  time = 0:10,
  grid_type = "counterfactual"
)

hyp_fun <- function(x, draws) {
  browser() # x doesn't contain 'id' column
  # try to calculate cumprod of predictions here?
  data.frame(term = 1, estimate = 1)
}

predictions(
  model = my_model,
  newdata = dg,
  type = "response",
  variables =  list(assigned_treatment = 0:1),
  hypothesis = hyp_fun
)
```

_Originally posted by @gravesti in https://github.com/vincentarelbundock/marginaleffects/discussions/1174_

**Comment by vincentarelbundock** [comment]
@gravesti Can you try again with version 0.21.0.6 from Github? I just pushed a change that should make this work.

BTW, a more efficient alternative is to specify `assigned_treatment` in the `datagrid()` function rather than in `variables`. Right now, you running the "duplication" code twice instead of just once.

**Comment by gravesti** [comment]
Thanks @vincentarelbundock, with the update it works and thanks for the tip about `variables`.
Can the results of `predictions()` be reused, eg, in `comparisons()` for efficiency's sake?
Also, am I abusing the hypothesis function for this purpose?

**Comment by vincentarelbundock** [comment]
Great!

No, the results cannot be re-used, unfortunately. I tried something along those lines at some point, and it was a mess (and dangerous).

No, you're not abusing at all. This is exactly what I implemented this argument for!

Depending on what your final function looks like, it might be possible to implement a shortcut directly in `marginaleffects`, so you could use the formula interface. For example:

```r
predictions(..., hypothesis = ~ cumprod | id)
```

**Comment by gravesti** [comment]
For predictions on each row I have:
```r
hyp_fun <- function(x, draws) {
  x2 <- x[order(assigned_treatment, id, time), ][, surv := cumprod(1-estimate) , by = c("id", "assigned_treatment")]
  data.frame(term = "survival", estimate = x2$surv)
}
```

But in principle I'm interested in the aggregated results. Currently in my package I return results like `x3` and `x4` below.
If I want both of these should I just combine them in one big return data.frame with appropriate term labels?

```r
hyp_fun_agg <- function(x, draws) {
  # calculate survival over time per id and treatment
  x2 <- x[order(assigned_treatment, id, time), ][, surv := cumprod(1-estimate) , by = c("id", "assigned_treatment")]
  
  # average survival over time per treatment
  x3 <- x2[, .(mean_surv = mean(surv)), by = c("time", "assigned_treatment")]
  
  # difference in average survival over time
  x4 <- merge(
    x3[assigned_treatment == 0, .(mean_surv0 = mean_surv, time)],
    x3[assigned_treatment == 1, .(mean_surv1 = mean_surv, time)],
    by = "time"
  )[, risk_diff := mean_surv1 - mean_surv0]
  
  data.frame(
    term = paste0("risk difference at t=", x4$time),
    estimate = x4$risk_diff
  )
}
```

**Comment by vincentarelbundock** [comment]
I don't see why not. Is this giving you the expected results?
