### ISSUE TITLE
Get the marginal effects for a bayesian ordinal model

### ISSUE THREAD

**Issue by OmidGhasemi21** [vincentarelbundock/marginaleffects#1180]
Hi Vincent,

Is there a way to get the average marginal effects for a categorical predictor and interaction terms? `avg_predictions` return predictions for each level of the DV. Is it possible to get AME for ordinal models? `emmeans` gives AME with a warning that it ignores threshold parameters. If not possible, any recommendation on how to report the interactions? 

```r
library(tidyverse)
library(marginaleffects)
library(emmeans)


mod_brm <- brm(
  formula = rating ~  temp * contact, 
  data = wine, 
  family = cumulative("logit")
)

fixef(mod_brm)
#                      Estimate   Est.Error     Q2.5      Q97.5
# Intercept[1]        -1.4330676 0.5410254 -2.57424337 -0.4448815
# Intercept[2]         1.1522273 0.5087267  0.21270188  2.1851685
# Intercept[3]         3.3889918 0.6268812  2.23982325  4.6909120
# Intercept[4]         5.0096353 0.7484167  3.60353125  6.5506550
# tempwarm             2.3306294 0.7045632  0.96628080  3.7566691
# contactyes           1.3640113 0.6525531  0.09912555  2.6365059
# tempwarm:contactyes  0.3838981 0.9213822 -1.34938608  2.2909748


avg_predictions(mod_brm, by = "temp")
#Group temp Estimate   2.5 % 97.5 %
# 1 cold   0.1324 0.05136 0.2491
# 1 warm   0.0141 0.00340 0.0455
# 2 cold   0.4613 0.32317 0.6050
# 2 warm   0.1320 0.05985 0.2330
# 3 cold   0.3151 0.20637 0.4407
# 3 warm   0.3810 0.26912 0.5145
# 4 cold   0.0591 0.02165 0.1288
# 4 warm   0.2773 0.15898 0.4169
# 5 cold   0.0172 0.00441 0.0504
# 5 warm   0.1802 0.08043 0.3084
```

**Comment by vincentarelbundock** [comment]
Hi Omid,

What do you mean exactly by "AME for a categorical predictor and interactions"? 

These are not agreed upon terms or unambiguous quantities. Can you define them mathematically, or at least describe the steps to compute them?

**Comment by OmidGhasemi21** [comment]
Well, I am looking for posterior predictions for each level of the categorical variables. If I am correct, I want to get the predicted Y for each level of b1, b2, and b3 (imagine that we have an interaction term as well):

<img width="211" alt="Screenshot 2024-07-25 at 9 10 09 pm" src="https://github.com/user-attachments/assets/567b9630-88c1-4418-88dc-8ec1be3d3ef1">

Basically, I want the same thing that we get from avg_predictions() for a linear or glm model. If it is not possible and we get predictions for each of the dependent variable group, is there an intuitive way to plot the interaction?

Thanks.

**Comment by vincentarelbundock** [comment]
Sure, juste add another variable name in by=c().

(BTW, I recommend to call those "marginal predictions" not "marginal effects")

**Comment by OmidGhasemi21** [comment]
Thanks, Vincent. That is the issue. This`avg_predictions(mod_brm, by = c("temp","contact"))` gives me the marginal predictions for each of the Likert dependent var levels. Can we get overall marginal predictions (ignoring the threshold and Group parameters)?

**Comment by vincentarelbundock** [comment]
Still not clear what you mean by "overall". Average, sum? 

In any case, the beautiful thing about Bayesian models is that you can extract the posterior draws with posteriordraws() and then take any sum or average you want. Then you can take quantiles of the distribution of draws to create intervals.

See the Bayesian vignette. That's your best bet.
