### ISSUE TITLE
Question regarding the default value of `type` argument in `plot_prediction()` and `plot_comparison()`.

### ISSUE THREAD

**Issue by giakhang1906** [vincentarelbundock/marginaleffects#1202]
Consider:
``` r
library(tidymodels)
library(marginaleffects)

fit_height <- linear_reg() |> 
  set_engine("lm") |> 
  fit(height ~ sex, data = x)
 
plot <- plot_predictions(fit_height, 
                        condition = "sex")

plot_comparisons(fit_height, 
                variables = "sex",
                type = "numeric", 
                condition = "sex")
#>Not works if argument `type` is not specified
```

<sup>Created on 2024-08-29 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

Why the default value for `plot_predictions()` is NULL why for `plot_comparisons()` is response and it requires to specify the argument as numeric, prob, class while in `plot_predictions()` we dont have to. Is it more convenient if we also set the default value for `plot_comparisons()` to NULL as well?

**Comment by vincentarelbundock** [comment]
Thanks for catching this inconsistency. It's a very good point.

I have pushed a fix to the development version on Github, and will release a new version with this fix to CRAN in the next few weeks.

Thanks for taking the time to write a detailed example too!
