### ISSUE TITLE
Joint hypotheses test vcov option

### ISSUE THREAD

**Issue by kennchua** [vincentarelbundock/marginaleffects#1214]
I've noticed that when conducting a joint hypothesis test with `lm` model as input, the supplied vcov argument is ignored. This is not an issue for other hypothesis tests AFAICT.   

For example:

```
library(mtcars)
library(marginaleffects)
library(sandwich)

# lm
model_lm <- lm(mpg ~ wt + vs + am, 
               data = mtcars)

# Joint test - all the same
hypotheses(model_lm, joint = c("wt", "vs", "am"))
hypotheses(model_lm, joint = c("wt", "vs", "am"),
           vcov = "HC1")
hypotheses(model_lm, joint = c("wt", "vs", "am"),
           vcov = sandwich::vcovHC(model_lm, type = "HC1"))


```

**Comment by vincentarelbundock** [comment]
Thanks for raising the issue. I really appreciate that you took the time to craft a reproducible example.

This should now be fixed in the dev version on Github.
