### ISSUE TITLE
Simulating marginal treatment effects or estimands

### ISSUE THREAD

**Issue by abduazizR** [vincentarelbundock/marginaleffects#1217]
Hi

Thank you so much for the awesome package. I am wondering if it's possible to utilize marginaleffects either directly or indirectly to simulate a "true" marginal treatment effect or estimand that you can benchmark your estimators against. For conditional effects, it's relatively easier to simulate the true coefficients, but I think it's not the same for marginal effects, and Monte Carlo integration might be essential.

Any suggestions would be really helpful.

Thanks

**Comment by vincentarelbundock** [comment]
No, I don't think so, unfortunately.
