### ISSUE TITLE
Intercept-only models return `NaN` with `avg_*()`

### ISSUE THREAD

**Issue by vbrazao** [vincentarelbundock/marginaleffects#1230]
Not sure if this is a bug or by design, but I seem to be encountering the same issue @ASKurz reported here: https://github.com/vincentarelbundock/marginaleffects/issues/1021 when using a multinomial model. 

```
library(nnet)
library(marginaleffects)

dat <- data.frame(
  response = sample(c("A", "B", "C"), size = 100, prob = c(.2, .2, .6), replace = TRUE)
)

model <- nnet::multinom(
  formula = response ~ 1,
  data = dat, 
  trace = FALSE
)

marginaleffects::predictions(
  model
)
```
```
Results:

 Group Estimate Std. Error    z Pr(>|z|)    S 2.5 % 97.5 %
     A     0.15     0.0357  4.2   <0.001 15.2 0.080  0.220
     A     0.15     0.0357  4.2   <0.001 15.2 0.080  0.220
     A     0.15     0.0357  4.2   <0.001 15.2 0.080  0.220
     A     0.15     0.0357  4.2   <0.001 15.2 0.080  0.220
     A     0.15     0.0357  4.2   <0.001 15.2 0.080  0.220
--- 290 rows omitted. See ?avg_predictions and ?print.marginaleffects --- 
     C     0.59     0.0492 12.0   <0.001 107.7 0.494  0.686
     C     0.59     0.0492 12.0   <0.001 107.7 0.494  0.686
     C     0.59     0.0492 12.0   <0.001 107.7 0.494  0.686
     C     0.59     0.0492 12.0   <0.001 107.7 0.494  0.686
     C     0.59     0.0492 12.0   <0.001 107.7 0.494  0.686
Columns: rowid, group, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, response 
Type:  probs 
```

However,

```
marginaleffects::avg_predictions(
  model
)
```

Results:

```
 Group Estimate Std. Error   z Pr(>|z|)   S 2.5 % 97.5 %
     A      NaN        NaN NaN       NA NaN   NaN    NaN
     B      NaN        NaN NaN       NA NaN   NaN    NaN
     C      NaN        NaN NaN       NA NaN   NaN    NaN

Columns: group, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high 
Type:  probs 
```

My plan was to use the `hypothesis` argument to compare the predicted proportions to expected proportions (from domain knowledge), but I got stuck here. Not sure if my approach is simply wrong or `marginaleffects` should be able to produce this...

**Comment by vbrazao** [comment]
just for a test, I tried the same with a simpler model:

```
dat_bin <- dat |> 
  dplyr::mutate(
    A = ifelse(response == "A", 1, 0)
  )

model_bin <- glm(
  formula = A ~ 1,
  data = dat_bin
)
```

and the pattern was the same! `predictions()` generates predictions, but `avg_predictions` outputs NaNs. (In this particular case, even the estimate was NaN). So it seems to be generalized behavior for intercept-only models!

**Comment by vincentarelbundock** [comment]
Thanks for the report @vbrazao 

I tried to look at this a bit and can't quite figure out what is going on with intercept-only model. I'll come back to it when I find some time. Sorry for the problems!

**Comment by vincentarelbundock** [comment]
Thanks a lot for the report. Should be fixed on Github now. I plan to release to CRAN in the next few weeks.
