### ISSUE TITLE
Error of av_slopes after glm, logit 

### ISSUE THREAD

**Issue by mwindzio** [vincentarelbundock/marginaleffects#1238]
I get an error message after av_slopes. I guess it has to with the class of the data object, since I don't get the message using different data. 

error in rbindlist(lo, fill = TRUE) : 
  Class attribute on column 2 of item 4 does not match with column 2 of item 1.

The error occurs in line 23, the data will be read online. Do you know what the Problem could be?
All the best,
Michael
#####################

pacman::p_load(dplyr, haven, marginaleffects, margins,blorr)

rm(list = ls())

Ess_kurz <- read_dta("http://www.barkhof.uni-bremen.de/~mwindzio/Ess_kurz.dta")

head(Ess_kurz$trstprl)
head(Ess_kurz$voteneu)
head(Ess_kurz$gndr)
head(Ess_kurz$dscrgrp)

Ess_kurz$female <-Ess_kurz$gndr - 1
Ess_kurz$discriminated <-Ess_kurz$dscrgrp*-1+2

table(Ess_kurz$discriminated, Ess_kurz$dscrgrp)

Ess_kurzn <- Ess_kurz %>% select(voteneu, trstprl, eduyrs, female, discriminated)
Ess_kurzn <- Ess_kurzn %>% na.omit()

Ess_kurzn <- data.frame(Ess_kurzn)
voting <- glm(voteneu ~ trstprl + eduyrs + female+ discriminated, family =binomial( link="logit"), data = Ess_kurzn)
summary(voting)
#avg_slopes(voting) # AMEs marginaleffects => here, the error occurs
summary(margins(voting))
blr_rsq_mckelvey_zavoina(voting) # MeKelvey & Zavoina R2
exp(voting$coefficients) # Odds Ratios

**Comment by vincentarelbundock** [comment]
Thanks for the report. This should be fixed in version 0.23.0.2 on Github.
