### ISSUE TITLE
Benchmarking docs

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/marginaleffects#1248]
@etiennebacher 

The new benchmarking action is *super* cool. I am very, very pleased with this new addition. Thanks so much!

I think the only two things I'd be curious about are:

1. How to trigger the action again on an existing PR (see my attempt https://github.com/vincentarelbundock/marginaleffects/pull/1244)
2. Would it be possible to "document" or to describe the workflow in a just a few bullet points. My guess is that people would be interested in a detailed tutorial, but if we at least have some bullet points, I could take care of writing the long form version eventually.

**Comment by etiennebacher** [comment]
Thanks! I think 1 is already addressed, and for 2 I can write a document explaining how this works and how to update the benchmarks. Can you assign this issue to me?
