### ISSUE TITLE
Bootstrap inference fails wrapped inside of a function passing arguments to the model

### ISSUE THREAD

**Issue by nremenyi** [vincentarelbundock/marginaleffects#1257]
I am estimating a linear model, and trying to use "inferences" with bootstrap method to get confidence interval on an estimated interaction effect. I would like to wrap the procedure into a function and pass flexible formulas / data set, etc to the function. The bootstrap "inferences" fails. I know it is an experimental function but is there a way to fix it with creating some local variables before calling "inferences"?

#### Bootstrap on glm interaction estimate
mod = glm(formula = mpg ~ am * vs, data = mtcars)
int_eff = avg_comparisons(
  model = mod, 
  variables = "am",
  type = "response",
  hypothesis = c(-1, 1),
  by = "vs") 
int_eff = int_eff %>% 
  inferences(method = "boot", R = 100, conf_type = "perc")
int_eff
 Estimate Std. Error 2.5 % 97.5 %
     2.93       2.65 -3.78   7.82

get_int_eff = function(formula, data, boot = FALSE){
  
  mod = glm(formula = formula, data = data)
  int_eff = avg_comparisons(
    model = mod, 
    variables = "am",
    type = "response",
    hypothesis = c(-1, 1),
    by = "vs") 
  if (boot){
    int_eff = int_eff %>% 
      inferences(method = "boot", R = 100, conf_type = "perc")
  }
  
  return(int_eff)
  
}

#### Without bootstrap it works inside a function
get_int_eff(formula = "mpg ~ am * vs", data = mtcars)
 Estimate Std. Error    z Pr(>|z|)   S 2.5 % 97.5 %
     2.93       2.54 1.15    0.249 2.0 -2.05   7.91

#### With bootstrap it fails inside a function
get_int_eff(formula = "mpg ~ am * vs", data = mtcars, boot = TRUE)
Error in str2lang(s) : argument must be a character string

sessionInfo()
R version 4.3.3 (2024-02-29 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22621)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: America/Chicago
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] marginaleffects_0.23.0 dplyr_1.1.4            data.table_1.16.0     

loaded via a namespace (and not attached):
 [1] backports_1.5.0   utf8_1.2.4        R6_2.5.1          tidyselect_1.2.1  magrittr_2.0.3   
 [6] glue_1.7.0        tibble_3.2.1      pkgconfig_2.0.3   generics_0.1.3    lifecycle_1.0.4  
[11] cli_3.6.3         fansi_1.0.6       vctrs_0.6.5       withr_3.0.1       compiler_4.3.3   
[16] boot_1.3-29       rstudioapi_0.16.0 tools_4.3.3       checkmate_2.3.2   pillar_1.9.0     
[21] Rcpp_1.0.13       crayon_1.5.3      rlang_1.1.4       insight_0.20.5

**Comment by nremenyi** [comment]
Adding "assign("formula", formula, envir = parent.frame())" seems to resolve the problem, or similarly "assign("family", family, envir = parent.frame())" if we use family, but I am not sure if there is better way to do it.

get_int_eff = function(formula, data, boot = FALSE){
  
  assign("formula", formula, envir = parent.frame())

  mod = glm(formula = formula, data = data)
  int_eff = avg_comparisons(
    model = mod, 
    variables = "am",
    type = "response",
    hypothesis = c(-1, 1),
    by = "vs") 
  if (boot){
    int_eff = int_eff %>% 
      inferences(method = "boot", R = 100, conf_type = "perc")
  }
  
  return(int_eff)

}

**Comment by vincentarelbundock** [comment]
Thanks a lot for raising this issue. Unfortunately, this has come up before and I don't have a great solution. If someone comes along with an idea, I'll be **super** happy to review a pull request.

In the meantime, I'll add your example to the FAQ on the website and close this issue.

Sorry for the complications.
