### ISSUE TITLE
Cant access to vignettes

### ISSUE THREAD

**Issue by Mizhou991204** [vincentarelbundock/marginaleffects#1261]
Bug reports must include:

1. *Concise* description of the bug
2. *Minimal* reproducible example using publicly available data and the bare minimum code and libraries needed to reproduce the bug.
    - Consider using the `mtcars` dataset which is distributed by default with `R`, or one of the [CSV files from the RDatasets archive.](https://vincentarelbundock.github.io/Rdatasets/articles/data.html)
3. `sessionInfo()` output

Make sure you are running the *latest development version* of `marginaleffects` and its dependencies: https://marginaleffects.com/#installation

**Comment by Mizhou991204** [comment]
Hello, I am a new for marginal effects. It is great! However, recently I cant get access to https://marginaleffects.com/vignettes/brms.html, it report 404 not found. Can you help me to check it? Thank you!

**Comment by vincentarelbundock** [comment]
Its in the Bayes vignette on Bonus content on the main page.
