### ISSUE TITLE
FR: Option to reduce size of margineffects return objects

### ISSUE THREAD

**Issue by grantmcdermott** [vincentarelbundock/marginaleffects#1267]
Apologies in advance if I'm overlooking something here...

By default, `marginaleffects` objects retain a large amount of information about the original model as attributes. This includes a copy (copies?) of the original data.

Of course, retaining this information is valuable (necessary even) for a number of post-processing methods. But it comes at the cost of being memory intensive, particularly when the original data + model objects themselves are large. This trade-off is particularly acute for functions like `avg_slopes()`, where the core result is usually a small data frame of slope coefficients.

MWE:

``` r
library(marginaleffects)
data("diamonds", package = "ggplot2")

mod = lm(price ~ carat * clarity * cut, diamonds)
mfx = avg_slopes(mod)

# This object is over half a gigabyte...

print(object.size(mfx), units = "Mb")
#> 550.4 Mb

# Most of that size is  taken up by ancillary attributes like the original data and model call 

aa = names(attributes(mfx))
data.frame(size = sapply(aa, \(a) format(object.size(attr(mfx, a)))))
#>                                                   size
#> names                                        920 bytes
#> row.names                                     96 bytes
#> original                               481589424 bytes
#> class                                        264 bytes
#> newdata_explicit                              56 bytes
#> newdata_matrix_columns                        48 bytes
#> newdata_character_levels                     208 bytes
#> newdata_variable_class                       608 bytes
#> newdata_marginaleffects_variable_class       608 bytes
#> newdata_newdata_explicit                      56 bytes
#> newdata_newdata_matrix_columns                48 bytes
#> newdata_newdata_character_levels             208 bytes
#> newdata_newdata_variable_class               608 bytes
#> call                                    47728096 bytes
#> type                                         120 bytes
#> model_type                                   112 bytes
#> model                                   47726248 bytes
#> variables                                  13368 bytes
#> jacobian                                   14288 bytes
#> vcov                                       64024 bytes
#> comparison                                   112 bytes
#> conf_level                                    56 bytes
#> by                                            56 bytes


# Simple example of excising the "suprlus" attributes

for (a in setdiff(aa, c("names", "row.names", "class"))) attr(mfx, a) = NULL

# After this attribute excising, we retain the same core information of the slope coefficients...

mfx
#> 
#>     Term                     Contrast Estimate Std. Error     z Pr(>|z|)     S
#>  carat   mean(dY/dX)                      8771       12.4 706.3   <0.001   Inf
#>  clarity mean(IF) - mean(I1)              4115       99.3  41.5   <0.001   Inf
#>  clarity mean(SI1) - mean(I1)             1584       73.4  21.6   <0.001 340.9
#>  clarity mean(SI2) - mean(I1)              891       74.1  12.0   <0.001 108.3
#>  clarity mean(VS1) - mean(I1)             2454       73.8  33.2   <0.001 801.9
#>  clarity mean(VS2) - mean(I1)             2204       73.4  30.0   <0.001 655.4
#>  clarity mean(VVS1) - mean(I1)            3515       79.2  44.4   <0.001   Inf
#>  clarity mean(VVS2) - mean(I1)            3212       75.4  42.6   <0.001   Inf
#>  cut     mean(Good) - mean(Fair)           507       45.0  11.3   <0.001  95.6
#>  cut     mean(Ideal) - mean(Fair)          920       42.1  21.9   <0.001 350.1
#>  cut     mean(Premium) - mean(Fair)        757       42.5  17.8   <0.001 233.1
#>  cut     mean(Very Good) - mean(Fair)      731       42.6  17.1   <0.001 216.3
#>  CI low CI high
#>    8746    8795
#>    3920    4309
#>    1440    1728
#>     746    1036
#>    2309    2598
#>    2060    2348
#>    3360    3670
#>    3064    3360
#>     419     595
#>     838    1003
#>     674     840
#>     647     814
#> 
#> Columns: term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted_lo, predicted_hi, predicted

# ... but at a five orders of magnitude (!) reduction in size...

print(object.size(mfx), units = "Kb")
#> 4.9 Kb
```

<sup>Created on 2024-11-02 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

Could we perhaps add an argument for returning a "lean"  `marginaleffects` object that strips these ancillary attributes, similar to `fixest::feols(..., lean = TRUE)` ?

Thanks for considering.

P.S. Semi-related to #1198, since it is about effective memory management of large models. But this is focused on the `marginaleffects` return object.

**Comment by grantmcdermott** [comment]
P.S. I should add that I'm happy to put in a PR if this sounds useful. But I'm guessing that you want the final say on the "bare minimum" attributes that should be retained.

**Comment by vincentarelbundock** [comment]
Thanks for the suggestion. This sounds like a good idea.

I would consider a `marginaleffects_lean` global option, but not an argument. The only tricky thing is that `hypotheses()` will not longer work when applied to the "lean" objects. This would be easy to implement:

* At the bottom of `comparisons()` and `predictions()`, check the global option and delete the heavy attributes. The heaviest are probably `newdata`, `model`, and `jacobian`.
* At the start of `hypotheses()`, check if the object is of class "slopes", "comparisons", or "predictions". Then, check if the heavy attributes are present, and raise an informative error if appropriate.
* Document the global option in `man-roxygen/options.R`. This should note that some features may no longer work on lean objects, such as `hypotheses()`, but also things `vcov(mfx_object)` which require the jacobian.

**Comment by grantmcdermott** [comment]
> I would consider a `marginaleffects_lean` global option, but not an argument. 

Why not an argument? Personally, I think it would be advantageous to be able to control this behavior per model (as well as at the global level).

Similarly, on the package development front, I'd like for users to be able to pass `etwfe::emfx(..., lean = TRUE)` in my etwfe package... Although I suppose I could hack this by calling and reverting the global option internally.

**Comment by vincentarelbundock** [comment]
> Why not an argument? Personally, I think it would be advantageous to be able to control this behavior per model (as well as at the global level).
> 
> Similarly, on the package development front, I'd like for users to be able to pass `etwfe::emfx(..., lean = TRUE)` in my etwfe package... Although I suppose I could hack this by calling and reverting the global option internally.

Right, I understand. But one of my key design decisions for `marginaleffects` is to keep the user interface ultra-simple and approachable. IMHO, this is a cool feature, but it is very niche. My guess is it's going to be used by <1% of users. So I don't think it is worth increasing the main interface with that.

As you note, there are easy workaround for package developers: just capture and restore the global option `on.exit()`.

**Comment by grantmcdermott** [comment]
Got it, thanks. I'll aim to put in a PR soon.

**Comment by vincentarelbundock** [comment]
that would be awesome, thanks!
