### ISSUE TITLE
Pooling fails for `avg_comparisons()` after multiple imputation with `transform` specified

### ISSUE THREAD

**Issue by ngreifer** [vincentarelbundock/marginaleffects#1269]
When pooling estimates after multiple imputation (e.g., using `avg_comparisons()` on a `mira` object), an error is thrown if `transform` is supplied. See below:

``` r
library(mice)
library(marginaleffects)

data("lalonde_mis", package = "cobalt")

imp <- mice(lalonde_mis, print = FALSE)

# Logistic regression
fits <- with(imp, glm(treat ~ age + married, family = binomial))

# Mean difference okay
avg_comparisons(fits, variables = "married")
#> Warning in get.dfcom(object, dfcom): Infinite sample size assumed.
#> 
#>  Estimate Std. Error     t Pr(>|t|)    S  2.5 % 97.5 %   Df
#>     -0.27     0.0372 -7.25   <0.001 40.8 -0.343 -0.197 2920
#> 
#> Term: married
#> Type:  response 
#> Comparison: mean(1) - mean(0)
#> Columns: term, contrast, estimate, std.error, s.value, predicted_lo, predicted_hi, predicted, df, statistic, p.value, conf.low, conf.high

# Pooling fails with transform
avg_comparisons(fits, variables = "married",
                comparison = "lnratioavg",
                transform = "exp")
#> Warning in get.dfcom(object, dfcom): Infinite sample size assumed.
#> Error: The output does not include a `std.error` column. Some models do not
#>   generate standard errors when estimates are backtransformed (e.g., GLM
#>   models). One solution is to use `type="response"` for those models.
```

<sup>Created on 2024-11-02 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

Note adding `type="response"` does not help. This is not an issue for non-imputed data. I feel that pooling should occur before the `transform` step anyway, with `transform` applied to the pooled output, so it should not be searching for the `std.error` column after transformation. Thanks for looking into this :)

**Comment by vincentarelbundock** [comment]
@ngreifer can you try this PR and tell me if it works as expected?

https://github.com/vincentarelbundock/marginaleffects/pull/1275

**Comment by ngreifer** [comment]
Looks to be working fine to me! Thanks for the fix.

**Comment by vincentarelbundock** [comment]
merged in `main`

**Comment by vincentarelbundock** [comment]
Re-opening because the fix appears to break confidence intervals:

``` r
library(mice)
library(marginaleffects)
data("lalonde_mis", package = "cobalt")
imp <- mice(lalonde_mis, print = FALSE, seed = 48103)
fits <- with(imp, glm(treat ~ age + married, family = binomial))
avg_comparisons(fits,
  variables = "married",
  comparison = "lnratioavg",
  transform = "exp")
#> 
#>  Estimate Pr(>|t|)   S    2.5 %   97.5 %    Df
#>     0.338    0.262 1.9 1.08e-14 1.06e+13 0.494
#> 
#> Term: married
#> Type:  response 
#> Comparison: ln(mean(1) / mean(0))
#> Columns: term, contrast, estimate, s.value, predicted_lo, predicted_hi, predicted, df, p.value, conf.low, conf.high
```

**Comment by vincentarelbundock** [comment]
The issue appears to be related to what I believe is a breaking change in the computation of `df` on the `mice` side. Reported here:

https://github.com/amices/mice/issues/683

We could ignore `df` and just use `qnorm()` as a workaround.

**Comment by vincentarelbundock** [comment]
Adding `df.residual` methods "solves" this for model classes where an appropriate method is defined: https://github.com/vincentarelbundock/marginaleffects/pull/1299

However, `mice::pool()` will still generate nonsense confidence intervals when `df.residual()` returns an error or `NULL`.

**Comment by ngreifer** [comment]
Maybe set those `df.residual`s to `Inf` as a workaround?

**Comment by vincentarelbundock** [comment]
That's a very good idea. Thanks!

https://github.com/vincentarelbundock/marginaleffects/commit/f829090037784d59a37452eda314fb9b41472ddb
