### ISSUE TITLE
Can't find the brms zoo

### ISSUE THREAD

**Issue by avehtari** [vincentarelbundock/marginaleffects#1271]
Googling "marginaleffects brms" gives link 
https://marginaleffects.com/vignettes/brms.html
which gives 404. Going to https://marginaleffects.com/ shows now a book web page, and I was not able to find the brms zoo anywhere.

**Comment by vincentarelbundock** [comment]
Apologies for the change.

The website is now structured as an online book. The first sections will match a printed book that I am currently writing for CRC.

The extra vignettes like the one you link to will be hosted in the "Bonus section" part of the book. You can find it in the index on the left-hand side, or here directly:

https://marginaleffects.com/bonus/brms.html

**Comment by vincentarelbundock** [comment]
I added a more informative 404 page with a pointer to look at the sidebar.

**Comment by avehtari** [comment]
Ah, the Section was titled "Bayes" and not "brms" which explains I couldn't find it from the table of contents. Thanks for the pointing where to find it, and the 404 page is now better, too.
