### ISSUE TITLE
`type = "quantile"` for *survreg*  objects does not work when specifying probabilities.

### ISSUE THREAD

**Issue by strengejacke** [vincentarelbundock/marginaleffects#1272]
In `survival::predict.survreg()`, you can pass a `p` argument when `type = "quantile"`, to define the probabilities of the quantiles. However, this argument cannot be passed in *marginaleffects*, as it is considered as `p_adjust` due to partial matching:

``` r
library(survival)
library(marginaleffects)
fit <- survreg(Surv(time, status) ~ ph.ecog + age + sex, lung,dist="weibull")

predict(fit, newdata = datagrid(model = fit, by = "sex"))
#>        1        2 
#> 355.5274 545.6826
predict(fit, newdata = datagrid(model = fit, by = "sex"), type = "quantile", p = 0.5)
#>        1        2 
#> 271.9563 417.4132

avg_predictions(fit, variables = "sex")
#> 
#>  sex Estimate Std. Error    z Pr(>|z|)     S 2.5 % 97.5 %
#>    1      372       32.0 11.6   <0.001 101.1   309    435
#>    2      556       26.3 21.1   <0.001 325.5   504    607
#> 
#> Type:  response 
#> Columns: sex, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high
avg_predictions(fit, variables = "sex", type = "quantile", p = 0.5)
#> Error in sanity_equivalence_p_adjust(equivalence, p_adjust): Assertion on 'p_adjust' failed: Must be element of set {'holm','hochberg','hommel','bonferroni','BH','BY','fdr','none'}, but types do not match (numeric != character).
```

<sup>Created on 2024-11-15 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by vincentarelbundock** [comment]
Oh, good catch! Score one for long argument names.

I might deprecate the `p_adjust` argument altogether in  favor of a more comprehensive solution based on the `multcomp` package. Will look at this when i find time. Thanks!

relevant: https://github.com/vincentarelbundock/marginaleffects/issues/1169

**Comment by vincentarelbundock** [comment]
Should be fixed https://github.com/vincentarelbundock/marginaleffects/commit/c828f4562c39c3254ec137d36cdab218efd2cdb3

Sorry for the delay. I had to make infrastructure changes, implement new features, and deprecate an argument to make this work.
