### ISSUE TITLE
Data column named "group" causes issues for `predictions(..., by = ...)`

### ISSUE THREAD

**Issue by RoelVerbelen** [vincentarelbundock/marginaleffects#1281]
Similar story to the python version, as metioned and addressed [here](https://github.com/vincentarelbundock/pymarginaleffects/issues/90). `group` is a quite common name in a data set. Maybe consider using `.group` etc for internal variable names?

``` r
library(dplyr)
library(readr)
library(marginaleffects)

diamonds  <- read_csv("https://raw.githubusercontent.com/vincentarelbundock/Rdatasets/master/csv/ggplot2/diamonds.csv")

model <- lm(price ~ cut, data = diamonds)

# Works
predictions(model, newdata = diamonds, by ="cut")
#> 
#>        cut Estimate Std. Error     z Pr(>|z|)   S 2.5 % 97.5 %
#>  Ideal         3458       27.0 128.0   <0.001 Inf  3405   3510
#>  Premium       4584       33.8 135.8   <0.001 Inf  4518   4650
#>  Good          3929       56.6  69.4   <0.001 Inf  3818   4040
#>  Very Good     3982       36.1 110.4   <0.001 Inf  3911   4052
#>  Fair          4359       98.8  44.1   <0.001 Inf  4165   4552
#> 
#> Type:  response 
#> Columns: cut, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high

# Create column named group
diamonds["group"] <- diamonds["color"]

# Unexpected results
predictions(model, newdata = diamonds, by = "cut")
#> 
#>  Group     cut Estimate Std. Error     z Pr(>|z|)   S 2.5 % 97.5 %
#>      E Ideal       3458       27.0 128.0   <0.001 Inf  3405   3510
#>      E Premium     4584       33.8 135.8   <0.001 Inf  4518   4650
#>      E Good        3929       56.6  69.4   <0.001 Inf  3818   4040
#>      I Premium     4584       33.8 135.8   <0.001 Inf  4518   4650
#>      J Good        3929       56.6  69.4   <0.001 Inf  3818   4040
#> --- 25 rows omitted. See ?print.marginaleffects --- 
#>      G Good        3929       56.6  69.4   <0.001 Inf  3818   4040
#>      G Fair        4359       98.8  44.1   <0.001 Inf  4165   4552
#>      J Fair        4359       98.8  44.1   <0.001 Inf  4165   4552
#>      I Fair        4359       98.8  44.1   <0.001 Inf  4165   4552
#>      D Fair        4359       98.8  44.1   <0.001 Inf  4165   4552
#> Type:  response 
#> Columns: group, cut, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high
```

<sup>Created on 2024-11-22 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by vincentarelbundock** [comment]
@RoelVerbelen thanks for raising this issue. You are right: this is inconvenient, and a `.` prefix would have been smart.

Unfortunately, this would be a big breaking change, so I don't intend to change the name of the column now. In the grand scheme of things, this is surely an inconvenience for users, but not a big one. So I'll live with this rather than breaking people's codes that rely on the `group` name. 

Sorry to disappoint.

**Comment by RoelVerbelen** [comment]
No worries, @vincentarelbundock, I understand there are already too many dependencies on the current naming convention. @LamAdr was also rightly worried [the assertion introduced in the python version](https://github.com/vincentarelbundock/pymarginaleffects/pull/92) might be blocking unproblematic situations, so just something to be aware of as a user (by them finding this github ticket potentially).

Cheers
