### ISSUE TITLE
Condition Values in "plot_predictions"

### ISSUE THREAD

**Issue by stevenmejia805509** [vincentarelbundock/marginaleffects#1287]
Hello, 

Can you please add the argument "condition_values" to the plot_predictions?

I want to plot predictive margins for specified values of my independent variable, rather than across ranges. 

So:

plot_predictions(model, condition = "x",
condition_values = " 1 2 3 4 5")

Thanks!

**Comment by vincentarelbundock** [comment]
This is already possible with the `condition` argument. Please read the documentation in `?plot_prediction`
