### ISSUE TITLE
using avg_comparisons, how to specify contrast between all levels

### ISSUE THREAD

**Issue by domazetoskai12** [vincentarelbundock/marginaleffects#1288]
Hello,

I am using avg_comparisons to explore contrasts between variables. My code is: avg_comp_matchcondition <- avg_comparisons(fit, variables = "Match", by = "Condition", comparisons="all", re_formula=NA, ndraws=2000)

From my understanding, comparisons="all" should allow comparisons across all levels of the Match variable, including contrasting the same level (e.g., mean (x) - mean(x)) along different levels of my Condition variable. Can someone please clarify how I can get this kind of same-level comparison specified in the formula above?

I am new to this, so apologies if this is rather silly or obvious.

Many thanks.

**Comment by vincentarelbundock** [comment]
No.

1. There is no `comparisons` (plural) argument.
2. The `comparison` (singular) argument does something different. See the documentation here for detail: `?comparisons`
3. Not sure I understand exactly what you want, but maybe call `avg_predictions()` with the `hypothesis` argument.
4. Here are some tips on asking good questions about software: https://marginaleffects.com/bonus/help.html#getting-help
