### ISSUE TITLE
How to recode `emmeans::pairs()` using `marginaleffects `

### ISSUE THREAD

**Issue by perlatex** [vincentarelbundock/marginaleffects#1289]
Sorry,  because no one replied the [post](https://forum.posit.co/t/how-to-recode-emmeans-pairs-using-marginaleffects/194995), I had to seek help here.

I am a big fan of the marginaleffects package and really appreciate its concise and easy-to-understand syntax. Whenever I encounter the emmeans function, I prefer to convert it into marginaleffects to study it. However, I recently came across this code, and I’m stuck—I can’t figure out how to proceed. The problem is as follows:

```r
library(tidyverse)
library(lme4)
library(emmeans)
library(marginaleffects)

d <- mtcars %>% 
  as_tibble() %>% 
  select(cyl, vs, am, gear, carb) %>% 
  mutate(cyl = cyl > 6)

m <- lme4::glmer(
  cyl ~ vs * am + (1 | gear / carb),
  data     = d, 
  family   = binomial
)

m %>%
  emmeans::emmeans(specs = ~ vs + am, type = "response") %>%
  pairs(infer = T, adjust = "tukey") %>%
  as.data.frame()
```

![ask](https://github.com/user-attachments/assets/4e893248-d564-4522-9c54-29edbd4f990b)

## I can recode first line

```r
m %>%
  emmeans::emmeans(specs = ~ vs + am, type = "response") %>%
```

as
```
library(marginaleffects)
m %>% 
  marginaleffects::predictions(
    newdata = datagrid(vs = unique, am = unique),
    type    = "response",
    re.form = NA
  ) %>% 
  as_tibble() 
```

## but  I can’t figure out the second line. 
```
m %>%
  emmeans::emmeans(specs = ~ vs + am, type = "response") %>%
  pairs(infer = T, adjust = "tukey")   #<<
```

Could you please give me some help? 
Thank you once again for your amazing package.

**Comment by vincentarelbundock** [comment]
Sorry, I am not an emmeans expert, and I don't know what this emmeans command does. 

Since this website is for bug reports and feature requests, not general help,  I will close the issue.
