### ISSUE TITLE
Stata `pwcompare`

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/marginaleffects#129]
https://twitter.com/fmarcondesmd/status/1454835579854761988

https://www.stata.com/manuals/rmarginspwcompare.pdf

> How about Stata’s “margins, dydx() pwcompare” to obtain average marginal effects of a diff-in-diff model?

> d <- svyglm(y ~ x+t + x*t, family= quasibinomial, na.action= na.omit)  Where x is indicator control vs treatment group, t is indicator variable for before vs after policy took effect.

> I  think the comment above gets at the 1st difference, but I was wondering if we can get the diff-in-diff average marginal effect (2nd difference), that is, (y(treatment, after) - y(control, after)) - (y(treatment, before) - y(control, before))

**Comment by vincentarelbundock** [comment]
The next version of `marginaleffects` (available now on Github) will include the `comparisons()` function which can do pairwise comparisons (contrasts) between adjusted predictions. I believe that this fulfills the main feature request in this Issue.

```r
library(marginaleffects)
dat <- mtcars
dat$gear <- factor(dat$gear)
mod <- lm(mpg ~ gear, data = dat)

comparisons(mod, contrast_factor = "pairwise") |> tidy()
    ##   term contrast  estimate std.error statistic      p.value   conf.low conf.high
    ## 1 gear    4 - 3  8.426667  1.823417  4.621361 3.812306e-06  4.8528357 12.000498
    ## 2 gear    5 - 3  5.273333  2.431222  2.169005 3.008230e-02  0.5082254 10.038441
    ## 3 gear    5 - 4 -3.153333  2.506046 -1.258290 2.082869e-01 -8.0650942  1.758428
```


Note that Stata appears to allow users to specify another “group” variable to compare adjusted predictions to arbitrary groups. This is kind of neat, but it would be complicated to implement, so unless there is strong demand – and perhaps some help – I will not implement that in the short/medium run.

**Comment by marcondesfel** [comment]
Hi,

Thanks for your post. Is it possible to get the different of the difference
(2nd difference) using the “pairwise option?

Thanks,

Felippe

**Comment by vincentarelbundock** [comment]
Just to clarify what you need, imagine we have a model like this on
which we compute adjusted predictions for some values of the regressors:

``` r
library(marginaleffects)
mod <- lm(mpg ~ hp * factor(cyl), data = mtcars)

pred <- predictions(mod, newdata = datagrid(cyl = mtcars$cyl))
pred <- pred[pred$cyl,]
```

When we call `comparisons()`, we are taking the pairwise differences
between the adjusted predictions across the `cyl` levels. These two
things are equivalent:

``` r
pred$predicted |> diff()
```

    ## [1]  0.1168672 -3.5664407

``` r
comparisons(mod,
            variables = "cyl",
            contrast_factor = "sequential",
            newdata = datagrid())
```

    ##    rowid term contrast comparison std.error       hp cyl
    ## 1:     1  cyl    6 - 4  0.1168672  3.503749 146.6875   8
    ## 2:     1  cyl    8 - 6 -3.5664407  2.138523 146.6875   8

What you want is the analogous pairwise comparisons, but for marginal
effects instead of predictions? So you want this:

``` r
mfx <- marginaleffects(mod,
                       variables = "hp",
                       newdata = datagrid(cyl = mtcars$cyl))
mfx <- mfx[order(mfx$cyl),]
mfx$dydx |> diff()
```

    ## [1]  0.105162619 -0.006630853

Am I understanding you correctly?

Does this example fill your need?

**Comment by vincentarelbundock** [comment]
Still haven't had a great idea for how to implement this. Sorry, but I'll rule it out of scope.

If you have a specific idea for implement or (even better) want to submit code, feel free to open a new issue.

**Comment by vincentarelbundock** [comment]
Sorry this comes so late @marcondesfel , and you have probably moved on by now, but here's a vignette section on how to do pairwise differences between contrasts (diff-in-diff): https://vincentarelbundock.github.io/marginaleffects/articles/hypothesis.html#pairwise-contrasts-difference-in-differences

This only works on the development version of `marginaleffects` from Github. It will be available in the next version on CRAN, coming out in the next couple weeks.
