### ISSUE TITLE
type="invlink" Argument Causes Warning with Non-NULL hypothesis in avg_predictions and hypotheses

### ISSUE THREAD

**Issue by pvsundar** [vincentarelbundock/marginaleffects#1292]
### IN THE REPLICATION CODE FOR R:
**Bug Description**
When using the avg_predictions and hypotheses functions with a non-NULL hypothesis argument, a warning is issued about the type="invlink" argument not being available. This warning occurs because the type argument is automatically changed to "response" when hypothesis is not NULL or a single numeric value.

Steps to Reproduce
Run the following code:

R

preds_hypo <- avg_predictions(m,
  by = c("democracy"),
  vcov = ~continent,
  hypothesis = "revpairwise"
) %>%
  mutate(
    estimate_pp = round(estimate * 100, 1),
    p_nice = fmt_pvalue(p.value),
    p_nice_eq = fmt_pvalue_p(p.value)
  )

preds_hypo_regime <- bind_rows(
  autocracy = hypotheses(preds_regime_eqdr_estimands, "b3 = b4"),
  democracy = hypotheses(preds_regime_eqdr_estimands, "b1 = b2"),
  .id = "democracy"
) %>%
  mutate(
    estimate_pp = round(estimate * 100, 1),
    p_nice = fmt_pvalue(p.value),
    p_nice_eq = fmt_pvalue_p(p.value)
  ) %>%
  split(~democracy)

**# Observe the warning messages:**
Warning messages:
1: The type="invlink" argument is not available unless hypothesis is NULL or a single number. The value of the type argument was changed to "response" automatically. To suppress this warning, use type="response" explicitly in your function call.
# Expected Behavior
The function should either:
Accept the type="invlink" argument without warnings when a non-NULL hypothesis is used.
Provide clear documentation stating that type="invlink" is incompatible with certain hypothesis values.
# Actual Behavior
The type argument is automatically changed to "response", and a warning is displayed.

** Proposed Fix**
The issue can be resolved by explicitly setting type="response" in function calls when using a non-NULL hypothesis. Below is the updated code:

R
Copy code
# Fix for avg_predictions
preds_hypo <- avg_predictions(m,
  by = c("democracy"),
  vcov = ~continent,
  hypothesis = "revpairwise",
  type = "response"
) %>%
  mutate(
    estimate_pp = round(estimate * 100, 1),
    p_nice = fmt_pvalue(p.value),
    p_nice_eq = fmt_pvalue_p(p.value)
  )

# Fix for hypotheses
preds_hypo_regime <- bind_rows(
  autocracy = hypotheses(preds_regime_eqdr_estimands, "b3 = b4", type = "response"),
  democracy = hypotheses(preds_regime_eqdr_estimands, "b1 = b2", type = "response"),
  .id = "democracy"
) %>%
  mutate(
    estimate_pp = round(estimate * 100, 1),
    p_nice = fmt_pvalue(p.value),
    p_nice_eq = fmt_pvalue_p(p.value)
  ) %>%
  split(~democracy)
This explicitly specifies type="response" to avoid the warning and aligns with the function's fallback behavior.

### Environment
RStudio Version: 2024.09.1+394 "Cranberry Hibiscus" Release (a1fe401fc08c232d470278d1bc362d05d79753d9, 2024-11-03)
Operating System: Windows 10 (64-bit)
Browser Engine: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2024.09.1+394 Chrome/124.0.6367.243 Electron/30.4.0 Safari/537.36
Quarto Version: 1.5.57
R Version: 4.4.1 (2024-06-14 ucrt)

**Comment by vincentarelbundock** [comment]
Thanks for the report. 

The current behavior is intentional, and it is reasonably well documented here: https://marginaleffects.com/r/man/predictions.html#prediction-types

Feel free to propose an alternate (specific) wording of that documentation if you think it could be improved. I'll be very happy to consider an improvement.
