### ISSUE TITLE
"lean" objects are missing print attributes

### ISSUE THREAD

**Issue by grantmcdermott** [vincentarelbundock/marginaleffects#1295]
Hey @vincentarelbundock,

I'm busy preparing a new submission of `etwfe` for CRAN, which depends on the latest (0..24.0) version of `marginaleffects`. However, I was a little caught out by the new print method, which IMO make its harder to see how things have been aggregated by "hiding" grouping variables.

E.g. The [running example](https://grantmcdermott.com/etwfe/index.html#quickstart-example) that I use on the `etwfe` website previously printed as follows:

```r
emfx(mod, type = "event")
#> 
#>  event Estimate Std. Error     z Pr(>|z|)    S   2.5 %   97.5 %
#>      0  -0.0332     0.0134 -2.48    0.013  6.3 -0.0594 -0.00701
#>      1  -0.0573     0.0172 -3.34   <0.001 10.2 -0.0910 -0.02373
#>      2  -0.1379     0.0308 -4.48   <0.001 17.0 -0.1982 -0.07751
#>      3  -0.1095     0.0323 -3.39   <0.001 10.5 -0.1729 -0.04619
#> 
#> Term: .Dtreat
#> Type:  response 
#> Comparison: mean(TRUE) - mean(FALSE)
#> Columns: term, contrast, event, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted_lo, predicted_hi, predicted
```

With the `marginaleffects` 0.24.0 update, the leading `"event"` column (with is created by calling `emfx(..., by = "event)` internally) is dropped:

```r
emfx(mod, type = "event")
#>
#> Estimate Std. Error     z Pr(>|z|)    S  CI low  CI high
#> -0.0332     0.0134 -2.48    0.013  6.3 -0.0594 -0.00701
#> -0.0573     0.0172 -3.34   <0.001 10.2 -0.0910 -0.02373
#> -0.1379     0.0308 -4.48   <0.001 17.0 -0.1982 -0.07751
#> -0.1095     0.0323 -3.39   <0.001 10.5 -0.1729 -0.04619
#> 
#> Term: .Dtreat
#> Comparison: TRUE - FALSE
#> Columns: term, contrast, event, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high
```
Unfortunately, this means that it is harder to interpret the result out of the gate.

I realise that this isn't a _huge_ deal and I can think of workarounds on my side (where the `by` information is integral to interpreting the output). But I'm surprised by the change and wanted to understand if I'm missing something.

**Comment by vincentarelbundock** [comment]
Thanks for the report. This was *not* intentional, and I agree that the grouping variables should be printed by default.

Will look into reinstating this when I find some time.

**Comment by grantmcdermott** [comment]
Hold the phone!

I just realised the issue and, what's more, it's my fault via #1268. It only occurs when `getOption("marginaleffects_lean")` is `TRUE`.

The _tl;dr_ fix is that we shouldn't delete the `by` attribute along with the other attributes here. I'll submit a PR shortly. Sorry for the alarm and churn.
