### ISSUE TITLE
plot_prediction point / line color bug

### ISSUE THREAD

**Issue by dmcglinn** [vincentarelbundock/marginaleffects#1297]
Just discovered your package and I love it! I found a minor bug and wanted to let you know: 

```r
library(marginaleffects)
data(iris)
m <- lm(Sepal.Length ~ Sepal.Width + Petal.Length + Species, data = iris)
plot_predictions(m, condition = c('Sepal.Width', 'Species'), points = 1)
```
produces this plot: 
![image](https://github.com/user-attachments/assets/dea76ec5-4baa-4ea6-84f3-b92e8f447e8d)

as you can see the colors of the regression line are not matching up with the colors of the points.

**Comment by vincentarelbundock** [comment]
Ooof!

Thanks a lot for the report. I can replicate it on my computer. Clearly a bug.

I tried to fix but couldn't quite figure it out before "real work" kicked in. Will look into it as soon as I find some time.

Thanks!

**Comment by vincentarelbundock** [comment]
I was having major problems isolating the bug. But I think I’ve now figured out that it is *not* a bug, but rather a weird quirk of the `iris` dataset.

First, we check the means of the dependent variable by Species:

``` r
aggregate(Sepal.Length ~ Species, data = iris, FUN = mean)
#>      Species Sepal.Length
#> 1     setosa        5.006
#> 2 versicolor        5.936
#> 3  virginica        6.588
```

The mean of `setosa` is lowest, so we should expect raw `setosa` data points to be lower in the plot than others.

Now, recall what `plot_predictions(m, condition=)` does: Make predictions for different values of the x-axis and grouping variable, while holding all other variables at their means.

This is equivalent to creating a data frame by hand, and making predictions on it:

``` r
m <- lm(Sepal.Length ~ Sepal.Width + Petal.Length + Species, data = iris)

grid <- data.frame(
  Species = unique(iris$Species),
  Sepal.Width = mean(iris$Sepal.Width),
  Petal.Length = mean(iris$Petal.Length))

transform(grid, yhat = predict(m, newdata = grid))
#>      Species Sepal.Width Petal.Length     yhat
#> 1     setosa    3.057333        3.758 6.626637
#> 2 versicolor    3.057333        3.758 5.670824
#> 3  virginica    3.057333        3.758 5.232539
```

Now, suddenly, the (conditional) prediction for `setosa` is *higher* than the average of raw data points.

Frankly, I’ve never seen anything like that. But it does indeed seem to be what the data and model say. And the fact that `plot_predictions()` plots a fitted line in a different order than the raw data points seems “correct.”

``` r
library(marginaleffects)
plot_predictions(m, condition = c("Sepal.Width", "Species"), points = 1)
```

![](https://i.imgur.com/inB3NIE.png)

**Comment by dmcglinn** [comment]
Wow! Sorry to have sent you on a bit of a goose chase. But I'm glad there is a logical explanation even if it is weird.
