### ISSUE TITLE
I met a issue in using comparision func

### ISSUE THREAD

**Issue by ARCCer** [vincentarelbundock/marginaleffects#1312]
Hello, I using feols function to estimate the impact of treatment in the experiment while controlling for the date:
model <- feols (y~treat| date, data=data)
and when I use comparison function to estimate the marginal effects of treat :
comparison(model, variables='treat', new_data= data)
R raise  errors like :
Error in rbindlist(lo, fill = TRUE, ignore.attr = TRUE) : 
  unused argument (ignore.attr = TRUE)

I'm not sure about the reason, and I've changed the type of treat variable such as int and category but the problem still exists. I do not sure if this this error is raised by marginaleffects package or the fixest package? 
great thanks for the resolution

**Comment by vincentarelbundock** [comment]
Please install.theblatest version of the data.table package, restart R, and try again.
