### ISSUE TITLE
unexpected default axis labelling in plot_cme()

### ISSUE THREAD

**Issue by alexanderfurnas** [vincentarelbundock/marginaleffects#149]
When plotting the cme from a fixest regression, as follows:
`m1  <- feols(DV ~ IV_numeric*IV_factor | group, data = data)

plot_cme(m1, effect = "IV_numeric", condition = c("IV_factor"))
`
the y axis label in the returned plot reads "Marginal effect of DV" rather than "Marginal effect of IV_numeric on DV" as I would have expected

**Comment by vincentarelbundock** [comment]
Right. This was fixed a few days ago. Should be fine if you use the Github devel version:

```r
remotes::install_github("vincentarelbundock/marginaleffects")
```

https://github.com/vincentarelbundock/marginaleffects/commit/d2b0f76dffde22373818e6c7678f81348a547561
