### ISSUE TITLE
`emmeans::emtrends`: distinct trends for each outcome level

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/marginaleffects#173]
I would like to estimate a model with categorical outcome and use
`emmeans::emtrends` to compute a distinct slope for each outcome level.

For example, in this logistic regression model, I expect the `Type`
variable to have a different effect on the probability of each of the
levels of the `Sat` variable. However, `emtrends` only reports a single
value:

``` r
library(MASS)
library(emmeans)
data(housing, package = "MASS")

mod <- polr(Sat ~ Infl + Freq, data = housing)

emtrends(mod, specs = ~Freq, var = "Freq")
```

    ##  Freq Freq.trend     SE  df asymp.LCL asymp.UCL
    ##  23.3     0.0131 0.0141 Inf   -0.0145    0.0408
    ## 
    ## Results are averaged over the levels of: Infl 
    ## Confidence level used: 0.95

When using the `margins` command in `Stata`, I get a different \(dy/dx\)
for each level of the outcome. Same with `marginaleffects`:

``` r
library(marginaleffects)

marginaleffects(mod, type = "probs", variables = "Freq") |> summary()
```

    ## Average marginal effects 
    ##    type  Group Term     Effect Std. Error  z value Pr(>|z|)      2.5 %
    ## 1 probs   High Freq  2.901e-03  0.0030698  0.94513  0.34459 -0.0031153
    ## 2 probs    Low Freq -2.880e-03  0.0030371 -0.94826  0.34300 -0.0088324
    ## 3 probs Medium Freq -2.145e-05  0.0004106 -0.05224  0.95834 -0.0008262
    ##      97.5 %
    ## 1 0.0089181
    ## 2 0.0030726
    ## 3 0.0007833
    ## 
    ## Model type:  polr 
    ## Prediction type:  probs

Note that the results seem to make sense substantively: the `Freq`
coefficient is negative but not statistically significant, which
suggests that as `Freq` increases, the probability of `High` should
increase and the probability of `Low` should decrease.

**Comment by vincentarelbundock** [comment]
Maybe @mattansb has an idea?

**Comment by mattansb** [comment]
Can you explain a bit about what an effect conditional on the levels of the outcome even means? I can't seem to wrap my head around it...

I feel like it *should* be this…. But it fails…

``` r
emtrends(mod, specs = ~Sat, var = "Freq", mode = "prob")
#> 
#> Re-fitting to get Hessian
#> Error in emmeans(object = new("emmGrid", model.info = list(call = polr(formula = Sat ~ : Irregular reference grid: Marginal means cannot be determined.
#> You can possibly fix this with the 'force_regular' function.
```

So… Maybe?

``` r
emmeans(mod, ~ Freq | Sat, mode = "prob",
        cov.reduce = list(Freq = \(v) mean(v) + c(-1, 1) * 0.001 * range(v))) |> 
  contrast(method = "pairwise") |> 
  update(by = NULL)
#> 
#> Re-fitting to get Hessian
#> Note: adjust = "tukey" was changed to "sidak"
#> because "tukey" is only appropriate for one set of pairwise comparisons
#>  contrast                            Sat     estimate       SE  df z.ratio
#>  23.3442222222222 - 23.4332222222222 Low     2.58e-04 2.75e-04 Inf   0.938
#>  23.3442222222222 - 23.4332222222222 Medium  2.83e-06 3.82e-05 Inf   0.074
#>  23.3442222222222 - 23.4332222222222 High   -2.61e-04 2.81e-04 Inf  -0.927
#>  p.value
#>   0.7231
#>   0.9998
#>   0.7300
#> 
#> Results are averaged over the levels of: Infl 
#> P value adjustment: sidak method for 3 tests
```

<sup>Created on 2022-01-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by vincentarelbundock** [comment]
Thanks for looking!

> Can you explain a bit about what an effect conditional on the levels of the outcome even means? I can't seem to wrap my head around it...

In my example, there are 3 outcome levels (Low, Medium, High) and 1 continuous regressor (Freq). Think of three distinct curves:

1. Freq on x-axis and Pr(Sat=Low) on y-axis
2. Freq on x-axis and Pr(Sat=Medium) on y-axis
3. Freq on x-axis and Pr(Sat=High) on y-axis

These curves are obviously different, because Freq will increase the probability of some outcomes and decrease the probability of some others.

My question: How can I estimate the slopes of those 3 curves using `emmeans::emtrends`? (The curves could be on the link scale, obviously.)

The contrasts you show are very close to what I am looking for: they measure the predicted change in the outcome for a small change in Freq, but they are not quite slopes. To get the slopes we can either:

1. Take a numerical derivative (which is what `marginaleffects` does)
2. Normalize the contrast, by dividing it by the *h* gap: f(x+h) - f(x))/h [(which is what the `emmeans::emtrends` documentation says it does -- see `delta.var`).](https://rdrr.io/cran/emmeans/man/emtrends.html)

**Comment by mattansb** [comment]
Okay, I had a mistake in the prev example. Here’s the correct dumb way to do it:

``` r
h <- 0.001 * diff(range(housing$Freq))

emmeans(mod, ~ Freq | Sat, mode = "prob",
        cov.reduce = list(Freq = \(v) mean(v) + c(h, 0))) |> 
  contrast(method = "pairwise", scale = 1/h) |> 
  update(by = NULL, adjust = "none")
#> 
#> Re-fitting to get Hessian
#>  contrast                            Sat     estimate      SE  df z.ratio
#>  23.4302222222222 - 23.3472222222222 Low    -2.90e-03 0.00309 Inf  -0.938
#>  23.4302222222222 - 23.3472222222222 Medium -3.18e-05 0.00043 Inf  -0.074
#>  23.4302222222222 - 23.3472222222222 High    2.93e-03 0.00316 Inf   0.927
#>  p.value
#>   0.3482
#>   0.9410
#>   0.3537
#> 
#> Results are averaged over the levels of: Infl
```

---

Maybe @rvlenth can chime in and tell us why this doesn't work (or what the correct way to do it with `emtrends`):

``` r
emtrends(mod, specs = ~Sat, var = "Freq", mode = "prob")
#> 
#> Re-fitting to get Hessian
#> Error in emmeans(object = new("emmGrid", model.info = list(call = polr(formula = Sat ~ : Irregular reference grid: Marginal means cannot be determined.
#> You can possibly fix this with the 'force_regular' function.
```

**Comment by vincentarelbundock** [comment]
This is fantastic, thanks so much!

**Comment by rvlenth** [comment]
So far, what I can tell is that, *after* differencing, we have this just before calling `emmeans()`:
```
Browse[2]> RG@grid
     Sat   Infl     Freq .wgt.
1    Low    Low 23.34722    24
2 Medium    Low 23.34722    24
3   High    Low 23.34722    24
4    Low   High 23.34722    24
5 Medium   High 23.34722    24
6   High   High 23.34722    24
7    Low Medium 23.43022    24
8 Medium Medium 23.43022    24
9   High Medium 23.43022    24
```
That is, we have one value of `Freq` with Low and High `Infl`, and another with Medium `Infl`. Why that is true is a mystery.

**Comment by vincentarelbundock** [comment]
Thanks for looking into it and for your great work on `emmeans`!

**Comment by rvlenth** [comment]
This has turned out to be a thorny issue, and it's in **emmeans** not here. So I created a new issue on the **emmeans** issues page -- https://github.com/rvlenth/emmeans/issues/327.

**Comment by mattansb** [comment]
Thanks Russell!
