### ISSUE TITLE
Support: `brglm2::bracl`

### ISSUE THREAD

**Issue by Jyasmeen** [vincentarelbundock/marginaleffects#186]
thank you for this package. I'm working with adjacent category logistic model from brglm2 package and need to calculate marginal effects, can you please provide support for bracl model?

**Comment by vincentarelbundock** [comment]
Thanks, I will look into it.

**Comment by vincentarelbundock** [comment]
Support for models estimated by `brglm2::bracl` is now in the
development version of `marginaleffects`. 

**_Please be careful!_** I am not aware of another software package that is capable of computing marginal effects for these models, so I have no benchmark against which to compare the numerical accuracy of the results. In principle, I think that things should be working well, as I am using the same mathematical/computational machinery as for other validated models. Still, caution is warranted.

You can use the new version by installing it from github:

``` r
library(remotes)
install_github("vincentarelbundock/marginaleffects")
```

Then, restart `R` completely and make sure the development version
0.3.1.9000 is installed:

``` r
packageVersion("marginaleffects")
```

    ## [1] '0.3.1.9000'

``` r
library(MASS)
library(brglm2)
library(marginaleffects)

data("stemcell", package = "brglm2")
dat <- stemcell
mod <- bracl(research ~ as.numeric(religion) + gender, weights = frequency,
             data = dat, type = "ML")

marginaleffects(mod, type = "probs") |> summary()
```

    ## Average marginal effects 
    ##            Group     Term      Contrast    Effect Std. Error z value  Pr(>|z|)
    ## 1     definitely   gender female - male -0.018803   0.021577 -0.8715   0.38351
    ## 2 definitely not   gender female - male  0.004817   0.013425  0.3588   0.71974
    ## 3 definitely not religion               -0.033914   0.008067 -4.2043 2.619e-05
    ## 4       probably   gender female - male  0.031838   0.076748  0.4148   0.67826
    ## 5       probably religion               -0.025781   0.046773 -0.5512   0.58150
    ## 6   probably not   gender female - male -0.017852   0.067123 -0.2660   0.79027
    ## 7   probably not religion               -0.047347   0.040239 -1.1766   0.23934
    ##      2.5 %   97.5 %
    ## 1 -0.06109  0.02349
    ## 2 -0.02150  0.03113
    ## 3 -0.04972 -0.01810
    ## 4 -0.11858  0.18226
    ## 5 -0.11745  0.06589
    ## 6 -0.14941  0.11371
    ## 7 -0.12621  0.03152
    ## 
    ## Model type:  bracl 
    ## Prediction type:  probs

``` r
predictions(mod, type = "probs") |> head()
```

    ##   rowid  type      group predicted  std.error   research religion gender
    ## 1     1 probs definitely 0.1856241 0.01388391 definitely        1 female
    ## 2     2 probs definitely 0.2809685 0.01320819 definitely        2 female
    ## 3     3 probs definitely 0.3973427 0.02304801 definitely        3 female
    ## 4     4 probs definitely 0.1988501 0.01756279 definitely        1   male
    ## 5     5 probs definitely 0.3000624 0.01700305 definitely        2   male
    ## 6     6 probs definitely 0.4214316 0.02674048 definitely        3   male
    ##   (weights)
    ## 1        34
    ## 2        41
    ## 3        58
    ## 4        21
    ## 5        30
    ## 6        64

**Comment by Jyasmeen** [comment]
Thank you! It worked and it's perfect.


Best Regards,
Yasmeen Jamali
Doctorante en Démographie à l'IDUP
