### ISSUE TITLE
Support: `mgcv::gamm`

### ISSUE THREAD

**Issue by tomwenseleers** [vincentarelbundock/marginaleffects#187]
Aside from the mgcv gam models, which are supported, do you think it would also be possible to support gamm mixed models?

**Comment by vincentarelbundock** [comment]
At first glance this looks difficult the `mgcv` package supplies neither a `predict` nor a `vcov` method for `gamm` objects. Without predictions, we can see how the outcome changes with changes in the regressors. Without variance covariance matrix, we can't estimate the uncertainty.

Frankly, I have no experience with this package, and too little with this class of models.  I see that the object is just a list with two submodels of classes `lme` and `gam` (it's a mixed model after all!). What is the relevant prediction? Which coefficients and vcov enter the calculation for uncertainty?

``` r
library(mgcv)
dat <- gamSim(6,n=200,scale=.2,dist="poisson")
mod <- gamm(y~s(x0)+s(x1)+s(x2),family=poisson,
            data=dat,random=list(fac=~1))

predict(mod)
```

    ## Error in UseMethod("predict"): no applicable method for 'predict' applied to an object of class "c('gamm', 'list')"

``` r
vcov(mod)
```

    ## Error in UseMethod("vcov"): no applicable method for 'vcov' applied to an object of class "c('gamm', 'list')"
