### ISSUE TITLE
Support: `scam` standard errors (waiting for upstream developer)

### ISSUE THREAD

**Issue by tomwenseleers** [vincentarelbundock/marginaleffects#188]
Aside from the mgcv gam models, which are supported, do you think it would also be possible to support shape-constrained spline scam models (library(scam)) (they should be similar to gam models) ?

**Comment by vincentarelbundock** [comment]
I created a branch on Git with preliminary support for `scam` models.
You can try it by following the example pasted below.

Remaining issues:

1.  The `emmeans` and `margins` packages do not
2.  The `vcov()` function cannot extract a variance-covariance matrix
    from objects of class `scam`. This means we can’t compute standard
    errors or confidence intervals.
3.  More complicated question:

`scam` model object hold two sets of coefficients: `model$coefficients`
and `model$coefficients.t`. The values of `predict(model)` are
determined by the values of `model$coefficients.t`, which looks a lot
like the other one, but with some coefficients exponentiated.

To compute standard errors, the numerical derivative function needs to
manipulate the coefficients and see how predictions change. So we
manipulate `coefficients.t`we need to compute the Jacobian. Then we
multiply the Jacobian by the variance-covariance matrix to get the
standard errors.

Is there a scale issue where I need to match the coefficients that match
the variance covariance matrix? If `vcov()` gives me a matrix that
matches `coefficients`, can I use it with `coefficients.t`?

Install the feature branch:

``` r
remotes::install_github("vincentarelbundock/marginaleffects@scam")
```

``` r
library(scam)
library(marginaleffects)

set.seed(4)
n <- 200
x1 <- runif(n) * 6 - 3
f1 <- 3 * exp(-x1^2) # unconstrained term
x2 <- runif(n) * 4 - 1;
f2 <- exp(4 * x2) / (1 + exp(4 * x2)) # monotone increasing smooth
y <- f1 + f2 + rnorm(n) * .5

dat <- data.frame(x1 = x1, x2 = x2, y = y)
mod <- scam(y ~ s(x1, bs = "cr") + s(x2, bs = "mpi"), data = dat)

mfx <- marginaleffects(mod)
```

    ## Warning in sanitize_vcov(model, vcov): Unable to extract a variance-covariance
    ## matrix from model of class "scam" using the `stats::vcov` function. The `vcov`
    ## argument was switched to `FALSE`. Please supply a named matrix to produce
    ## uncertainty estimates.

``` r
summary(mfx)
```

    ## Average marginal effects 
    ##   Term Effect
    ## 1   x1 0.1389
    ## 2   x2 0.2730
    ## 
    ## Model type:  scam 
    ## Prediction type:  response

``` r
predictions(mod, newdata = datagrid(x1 = 0:1, x2 = -1:1))
```

    ##   rowid     type predicted x1 x2
    ## 1     1 response  2.896042  0 -1
    ## 2     2 response  1.215281  1 -1
    ## 3     3 response  3.369014  0  0
    ## 4     4 response  1.688253  1  0
    ## 5     5 response  3.762177  0  1
    ## 6     6 response  2.081415  1  1

**Comment by vincentarelbundock** [comment]
`scam` support is now merged in the main development branch. You can install it from Github.

Standard errors do not work because `scam` objects do not let us call `vcov()` to get a variance-covariance matrix.

On 2022-01-09 I sent an email to the `scam` developer to ask if they would be willing to add this as a feature in future versions of the package. `marginaleffects` has to wait for upstream changes.

**Comment by vincentarelbundock** [comment]
Response from the author is encouraging:

> Actually, one of the elements of the returned 'scam' object is 'Vp.t' which is an estimated covariance matrix for the reparametrized parameters, 'model$coefficients.t'. 
> So possibly 'model$Vp.t' will serve as vcov...?
