### ISSUE TITLE
Support mblogit multinomial mixed models

### ISSUE THREAD

**Issue by tomwenseleers** [vincentarelbundock/marginaleffects#189]
The latest version of emmeans also supports mblogit (library(mclogit)) multinomial mixed models. Do you think it might be possible to also support those in marginaleffects ?

**Comment by vincentarelbundock** [comment]
Models estimated by `mclogit::mblogit` are now supported by
the development version of `marginaleffects`. You can try it by
installing it from github:

``` r
library(remotes)
install_github("vincentarelbundock/marginaleffects")
```

Then, restart `R` completely and make sure the development version
0.3.1.9000 is installed:

``` r
packageVersion("marginaleffects")
```

    ## [1] '0.3.1.9000'

``` r
library(MASS)
library(mclogit)
library(marginaleffects)

data("housing", package = "MASS")
dat <- housing
dat$x <- rnorm(nrow(dat))
mod <- mblogit(Sat ~ Infl + Type + Cont + x, weights = Freq, data = dat)

predictions(mod) |> head()
```

    ##   rowid     type group predicted  std.error    Sat   Infl  Type Cont          x
    ## 1     1 response   Low 0.5294407 0.04525346    Low    Low Tower  Low  1.1667755
    ## 2     2 response   Low 0.3305396 0.03495652 Medium    Low Tower  Low -0.8572867
    ## 3     3 response   Low 0.5159281 0.04259643   High    Low Tower  Low  0.9273718
    ## 4     4 response   Low 0.1744366 0.02459326    Low Medium Tower  Low -0.9484402
    ## 5     5 response   Low 0.1533365 0.02356343 Medium Medium Tower  Low -1.1496456
    ## 6     6 response   Low 0.3009231 0.03127888   High Medium Tower  Low  0.3468397
    ##   (weights) Freq
    ## 1        21   21
    ## 2        21   21
    ## 3        28   28
    ## 4        34   34
    ## 5        22   22
    ## 6        36   36

``` r
marginaleffects(mod) |> summary()
```

    ## Average marginal effects 
    ##     Group Term          Contrast   Effect Std. Error  z value   Pr(>|z|)
    ## 1    High Cont        High - Low  0.03767    0.02294   1.6418 0.10063244
    ## 2    High Infl        High - Low  0.24463    0.03086   7.9280 2.2204e-15
    ## 3    High Infl      Medium - Low  0.07303    0.02522   2.8954 0.00378648
    ## 4    High Type Apartment - Tower -0.09447    0.02978  -3.1726 0.00151069
    ## 5    High Type    Atrium - Tower -0.08768    0.03925  -2.2338 0.02549934
    ## 6    High Type   Terrace - Tower -0.24468    0.03488  -7.0152 2.2962e-12
    ## 7    High    x                    0.09704    0.01419   6.8365 8.1124e-12
    ## 8     Low Cont        High - Low -0.11782    0.02171  -5.4272 5.7235e-08
    ## 9     Low Infl        High - Low -0.28081    0.02744 -10.2331 < 2.22e-16
    ## 10    Low Infl      Medium - Low -0.16425    0.02582  -6.3623 1.9870e-10
    ## 11    Low Type Apartment - Tower  0.14260    0.02570   5.5498 2.8601e-08
    ## 12    Low Type    Atrium - Tower  0.05392    0.03349   1.6103 0.10734184
    ## 13    Low Type   Terrace - Tower  0.17755    0.03412   5.2036 1.9543e-07
    ## 14    Low    x                    0.10399    0.01293   8.0397 8.8818e-16
    ## 15 Medium Cont        High - Low  0.08015    0.02143   3.7406 0.00018361
    ## 16 Medium Infl        High - Low  0.03618    0.02818   1.2838 0.19921981
    ## 17 Medium Infl      Medium - Low  0.09121    0.02405   3.7932 0.00014871
    ## 18 Medium Type Apartment - Tower -0.04813    0.02571  -1.8717 0.06124685
    ## 19 Medium Type    Atrium - Tower  0.03376    0.03598   0.9381 0.34818785
    ## 20 Medium Type   Terrace - Tower  0.06714    0.03589   1.8706 0.06140672
    ## 21 Medium    x                   -0.20102    0.01452 -13.8463 < 2.22e-16
    ##        2.5 %    97.5 %
    ## 1  -0.007300  0.082632
    ## 2   0.184154  0.305110
    ## 3   0.023596  0.122471
    ## 4  -0.152839 -0.036111
    ## 5  -0.164606 -0.010746
    ## 6  -0.313046 -0.176322
    ## 7   0.069217  0.124855
    ## 8  -0.160363 -0.075268
    ## 9  -0.334599 -0.227029
    ## 10 -0.214845 -0.113650
    ## 11  0.092242  0.192967
    ## 12 -0.011710  0.119552
    ## 13  0.110673  0.244420
    ## 14  0.078635  0.129335
    ## 15  0.038153  0.122145
    ## 16 -0.019058  0.091421
    ## 17  0.044083  0.138344
    ## 18 -0.098529  0.002269
    ## 19 -0.036769  0.104280
    ## 20 -0.003209  0.137485
    ## 21 -0.229475 -0.172566
    ## 
    ## Model type:  mblogit 
    ## Prediction type:  response
