### ISSUE TITLE
`get_contrasts` step size: `minmax`, `iqr`, `sd`, `2sd`, 2 element vector of numeric values

### ISSUE THREAD

**Issue by langbe** [vincentarelbundock/marginaleffects#193]
Discrete changes would be a nice addition to this package, i.e. the same functionality as the argument `change` in `margins::dydx` provides. Or is this already possible (I could not identify how)?

**Comment by vincentarelbundock** [comment]
This is an excellent idea! And it should be extremely easy to implement, as all the right machinery is already available behind the scenes.

The main issues relate to user interface. Two possibilities:

1. Add a `step` argument to `marginaleffects`. When this `NULL`, we get the current results. Alternatively, users can give a numeric value or a string like `iqr`, `minmax`, `sd`.
    - Pro: Simple and Easy
    - Con: Complicates the `marginaleffects` interface with something is not *exactly* a marginal effect (it's a contrast)
2. Make available a new user-facing function specifically for contrasts
    - Pro: Future proof because it gives us a place where we can eventually implement more complicated contrasts as in `emmeans`
    - Con: What do we call it? `contrasts` is a base R function. `contrast` is available (but used by `emmeans`), but all of the other functions of the `{marginaleffects}` package are in plural form (e.g., `predictions`, `marginalmeans`). Also, this puts related concepts in separate functions.

Thoughts?

**Comment by langbe** [comment]
Thanks. Initially I thought 1. would be better, but I think 2. is better suited - it's more generic and it should/can be available to all prediction types.
