### ISSUE TITLE
print summary + dplyr::select bug

### ISSUE THREAD

**Issue by msonderegger** [vincentarelbundock/marginaleffects#200]
Hi Vincent,

I was trying to play with how a summary of `marginaleffects` objects is printed, and found a bug:

```
library(dplyr)
library(marginaleffects)
mod <- glm(am ~ hp * wt, data = mtcars, family = binomial)
mfx <- marginaleffects(mod)
summary(mfx) %>% select(term, estimate, conf.low, conf.high)
```

This gives:
```
Average marginal effects 
  Term    Effect    CI low    CI low
1   hp  0.002654 -0.001151  0.006458
2   wt -0.435727 -0.635690 -0.235764
```

Note "CI low" on the last column.   

Thanks for this excellent package!

- Morgan

**Comment by vincentarelbundock** [comment]
Thanks for giving it a spin Morgan!

`summary` is designed for printing. If you want to manipulate the summary by selecting columns -- as you do in this example -- you should call `tidy` instead.

**Comment by vincentarelbundock** [comment]
To be clear, there is definitely a bug here (thanks for the report!!), but thé `tidy` rec stands.

**Comment by vincentarelbundock** [comment]
Thanks again for reporting. The bug has been fixed in commit
<https://github.com/vincentarelbundock/marginaleffects/commit/4c15d2de042f7e7a8b58ec25f657b90923540a96>

CRAN does not like it when we release new versions too frequently, so
this will likely be published officially in 3-4 weeks. In the meantime,
you can install the devel version from Github:

``` r
library(remotes)
install_github("vincentarelbundock/marginaleffects")
```

Restart R entirely, then:

``` r
library("dplyr")
library("marginaleffects")

mod <- glm(am ~ hp * wt, data = mtcars, family = binomial)
mfx <- marginaleffects(mod)
summary(mfx) %>%
    select(term, estimate, conf.low, conf.high)
```

    ## Average marginal effects 
    ##   Term    Effect    CI low   CI high
    ## 1   hp  0.002654 -0.001151  0.006458
    ## 2   wt -0.435727 -0.635690 -0.235764
    ## 
    ## Model type:  
    ## Prediction type:

**Comment by msonderegger** [comment]
Got it, thanks!
