### ISSUE TITLE
Model request

### ISSUE THREAD

**Issue by LuceroGG** [vincentarelbundock/marginaleffects#201]
New model request 

type of model: LmerModLmerTest from lmerTest::lmer

lmerTest::lmer
"This function overloads lmer from the lme4-package (lme4::lmer) and adds a couple of slots needed for the computation of Satterthwaite denominator degrees of freedom. All arguments are the same as for lme4::lmer and all the usual lmer-methods work."

[Here](https://raw.githubusercontent.com/LuceroGG/mydata/main/RequestNewModelRscript.R) is an R script with the data, and showing that default functions work.

Hope this is possible,

-Cindy

**Comment by LuceroGG** [comment]
It is working now, I updated it from Github on my personal computer. I am contacting the administrator to do the same in the research center cluster. 

Thank you!

> summary(marginals)
Average marginal effects 
       Term          Contrast    Effect Std. Error z value   Pr(>|z|)      2.5 %   97.5 %
1  Age_days                    0.001008  0.0002111  4.7743 1.8035e-06  0.0005941 0.001421
2       Sex             M - F -0.004046  0.0102318 -0.3954    0.69255 -0.0240997 0.016008
3 Treatment HighFat - Control -0.007716  0.0113223 -0.6815    0.49555 -0.0299075 0.014475

Model type:  lmerModLmerTest 
Prediction type:  response

**Comment by vincentarelbundock** [comment]
Fantastic!
