### ISSUE TITLE
Unable to extract predictions for fixest IV models with fixed effects

### ISSUE THREAD

**Issue by karldw** [vincentarelbundock/marginaleffects#208]
Thanks for the great package! I ran across an issue where it fails to extract predictions for a fixest model that has both IV and FE terms.

``` r
reg <- fixest::feols(Sepal.Width ~ Petal.Length | Species | Sepal.Length ~ Petal.Width, data = iris)

marginaleffects::marginaleffects(reg)
#> Error in get_predict.fixest(model = model, newdata = newdata_tmp, type = type, : 
#> Unable to extract predictions from a model of type `fixest`. 

```

If I run this without the fixed effects (`Sepal.Width ~ Petal.Length | Sepal.Length ~ Petal.Width`), it works.

**Comment by vincentarelbundock** [comment]
Alternatively, you can also call:

```r
marginaleffects::marginaleffects(reg, newdata = iris)
```

**Comment by karldw** [comment]
Thanks! 

Maybe worth noting: when `variables=` is not specified, the CRAN version of `marginaleffects(reg, newdata = iris)` only returns the `Petal.Length` term by default, but requesting `Sepal.Length` works: `marginaleffects(reg, variables = "Sepal.Length", newdata = iris)`. 
With the updated `insight` version, it defaults to returning rows for both `Sepal.Length` and `Petal.Length`.
