### ISSUE TITLE
lm_lin from estimatr-package

### ISSUE THREAD

**Issue by wuttkea** [vincentarelbundock/marginaleffects#209]
Heello, we'd like to use -marginaleffects- to show predicted means from an experiment.
You support lm_robust and iv_robust from the estimatr package. Would it be possible to also include support for lm_lin from the same package?
The package vignette is here:
https://declaredesign.org/r/estimatr/reference/lm_lin.html

**Comment by wuttkea** [comment]
My more capable co-authors just told me that marginaleffects does seem to work with lm_lin. Maybe you'd want to add the function to your list of supported models.

**Comment by vincentarelbundock** [comment]
Ah yes! I think that `lm_lin()` is just a wrapper that transforms the regressors and then uses `lm_robust()`.

I added it to the list, but I have not tested it or checked numerical accuracy against other packages.
