### ISSUE TITLE
A question totally unrelated to multinomial models, nothing to see here

### ISSUE THREAD

**Issue by DominiqueMakowski** [vincentarelbundock/marginaleffects#214]
<sup>*Okay so I'm whispering so that the other easystats folks don't know I'm still pursuing on this lead despite their good advice... donc on garde ca entre nous!*</sup>

Imagine the following brms model:

``` r
library(brms)
library(ggplot2)

m <- brm(Species ~ Sepal.Length, 
         data=iris, 
         family=categorical(link="logit", refcat = "setosa"),
         algorithm = "meanfield") 

modelbased::estimate_relation(m, at="Sepal.Length", length = 30) |> 
  ggplot(aes(x = Sepal.Length, y = Predicted)) +
  geom_ribbon(aes(ymin=CI_low, ymax=CI_high, fill = Response), alpha=0.2) +
  geom_line(aes(color = Response))
```

![](https://i.imgur.com/L6DENPi.png)

<sup>Created on 2022-02-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Can I compute the first-order derivative, i.e., marginal linear effect, for these 3 curves using marginaleffects?

**Comment by vincentarelbundock** [comment]
Is this what you are looking for? I'm just eyeballing, but the slopes look right, that is, they cross zero at the top/bottom of the prediction curves. 

``` r
library(brms)
library(ggplot2)
library(patchwork)
library(marginaleffects)

m <- brm(Species ~ Sepal.Length,
         data = iris,
         family = categorical(link = "logit", refcat = "setosa"),
         algorithm = "meanfield")
pred <- predictions(m)

p1 <- ggplot(pred, aes(x = Sepal.Length,
                 y = predicted,
                 ymin = conf.low,
                 ymax = conf.high,
                 fill = group)) +
    geom_ribbon(alpha = .2) +
    geom_line(aes(color = group))

mfx <- marginaleffects(m)

p2 <- ggplot(mfx, aes(x = Sepal.Length,
                y = dydx,
                ymin = conf.low,
                ymax = conf.high,
                fill = group)) +
    geom_ribbon(alpha = .2) +
    geom_line(aes(color = group))

p1 / p2
```

![](https://i.imgur.com/NBPdgVB.png)

**Comment by DominiqueMakowski** [comment]
Yes that's exactly what I needed, thanks a lot! emmeans doesn't seem able to produce that... we might want to use marginaleffects as a backend for modelbased at least for this kind of stuff

**Comment by strengejacke** [comment]
<sup><i>Surtout si l'on considère que c'est précisément la solution que j'ai proposée !</i></sup>

**Comment by DominiqueMakowski** [comment]
Follow-up question because my prediction plot looks like this:

![image](https://user-images.githubusercontent.com/8875533/154378128-6a6e71bc-c23b-40f8-91dc-263c9386a612.png)

but the derivative plot like this lol:

![image](https://user-images.githubusercontent.com/8875533/154378182-464e0a28-9fa8-4cad-874f-3edac4ef7ef5.png)


I didn't find in the doc a way to change how the draws are summarized, as well as the current default. I'm interested in median&HDI

**Comment by vincentarelbundock** [comment]
My brain is fried at the moment, so I can't give you a detailed answer. But I believe that the default should be median and HDI. 

The relevant code should be in `R/methods_brms.R`, which allows you to pass arguments to `rstantools` functions via the `...`. Also see here for median and HDI:

https://github.com/vincentarelbundock/marginaleffects/blob/main/R/marginaleffects.R#L204

You may consider calling `marginaleffects()` and then passing the resulting object to `posteriordraws()` which should return all the raw draws. You can then summarize them as you see fit.
