### ISSUE TITLE
rev-dep issues with _insight_

### ISSUE THREAD

**Issue by strengejacke** [vincentarelbundock/marginaleffects#215]
This test fails with the latest GitHub version... _insight_ needs to be updated within the next 12 days, so my question is, if you would be prepared to submit an update?

```
── Error (test-pkg-survival.R:14:5): coxph vs. Stata ───────────────────────────
    Error in `model.frame.default(data = newdata, formula = ~x + strata(sex), 
        na.action = function (object, ...) 
        object, xlev = list(`strata(sex)` = c("sex=0", "sex=1")))`: factor strata(sex) has new levels 0, 1
    Backtrace:
         ▆
      1. ├─base::merge(tidy(marginaleffects(mod, type = "lp")), stata) at test-pkg-survival.R:14:4
      2. ├─generics::tidy(marginaleffects(mod, type = "lp"))
      3. └─marginaleffects::marginaleffects(mod, type = "lp")
      4.   └─marginaleffects:::get_dydx(...)
      5.     └─marginaleffects dydx_fun(...)
      6.       └─marginaleffects:::get_gradient(func = inner, x = newdata[[variable]])
      7.         └─marginaleffects func(x + eps)
      8.           ├─marginaleffects::get_predict(...)
      9.           └─marginaleffects:::get_predict.coxph(...)
     10.             ├─stats::predict(model, newdata = newdata, type = type, ...)
     11.             ├─survival:::predict.coxph(...)
     12.             │ └─base::eval(tcall, parent.frame())
     13.             │   └─base::eval(tcall, parent.frame())
     14.             ├─stats::model.frame(...)
     15.             └─stats::model.frame.default(...)
    
    [ FAIL 1 | WARN 2 | SKIP 26 | PASS 505 ]
    Error: Test failures
    Execution halted
```

**Comment by vincentarelbundock** [comment]
Thanks for the notice.

Yes, I am happy to submit a new version when needed.

**Comment by strengejacke** [comment]
Can you track down that error? Is it due to the fix in `get_data()`? (https://github.com/easystats/insight/issues/487)

**Comment by vincentarelbundock** [comment]
The problem is that the `stata(sex)` component is treated as a numeric variable. Internally, I use `find_predictors` to identify cluster variables, but in this case everything shows up as “conditional”:

``` r
library(insight)
library(survival)
library(marginaleffects)

dat <- list(time = c(4, 3, 1, 1, 2, 2, 3),
            status = c(1, 1, 1, 0, 1, 1, 0),
            x = c(0, 2, 1, 1, 1, 0, 0),
            sex = c(0, 0, 0, 0, 1, 1, 1))
mod <- coxph(Surv(time, status) ~ x + strata(sex), data = dat, ties = "breslow")

find_predictors(mod)
```

    ## $conditional
    ## [1] "x"   "sex"

``` r
marginaleffects(mod, type = "lp") |> summary()
```

    ## Error in model.frame.default(data = newdata, formula = ~x + strata(sex), : factor strata(sex) has new levels 0, 1

``` r
dat$sex <- as.factor(dat$sex)
mod <- coxph(Surv(time, status) ~ x + strata(sex), data = dat, ties = "breslow")

marginaleffects(mod, type = "lp") |> summary()
```

    ## Average marginal effects 
    ##   Term Contrast Effect Std. Error z value Pr(>|z|)   2.5 % 97.5 %
    ## 1  sex    1 - 0 0.4905     0.5363  0.9146  0.36041 -0.5607  1.542
    ## 2    x          0.7357     0.8045  0.9146  0.36041 -0.8410  2.312
    ## 
    ## Model type:  coxph 
    ## Prediction type:  lp

Life is kind of crazy right now, so I’m not sure when I’ll have time to look into this more on the `insight` side, but I’ll open an issue to have a record.

**Comment by strengejacke** [comment]
Yes, please open an issue.

**Comment by vincentarelbundock** [comment]
Just to clear up the confusion. The problem is that before the new `insight` update, `sex` was automatically transformed to a string like `"sex=1"`, so `marginaleffects` "knew" to treat it like a categorical variable. Now that `insight` behaves *correctly* and returns a numeric (the original type of the `sex` variable), `marginaleffects` gets confused.

So this is not a problem with `insight` per se.

**Comment by vincentarelbundock** [comment]
https://github.com/easystats/insight/issues/507
