### ISSUE TITLE
Support: mnlogit multinomial models

### ISSUE THREAD

**Issue by tomwenseleers** [vincentarelbundock/marginaleffects#217]
Would it be possible to also support multinomial models fitted using the mnlogit package, https://www.rdocumentation.org/packages/mnlogit/versions/1.2.6/topics/mnlogit?

**Comment by vincentarelbundock** [comment]
Thanks for the suggestion!

Is this package available on CRAN? `install.packages` doesn't seem to work and I can't find it in the CRAN listing.

**Comment by vincentarelbundock** [comment]
This packages seems to have been archived and is no longer available on CRAN. I inserted a note here. Feel free to open a new issue of the package becomes available again.

Thanks for the suggestion!

**Comment by tomwenseleers** [comment]
I notice it is still available at https://cran.microsoft.com/snapshot/2017-04-21/web/packages/mnlogit/index.html, but indeed not on the regular CRAN for some reason - I'll check with the package authors...
