### ISSUE TITLE
nnet::multinom - Error in match.names

### ISSUE THREAD

**Issue by jay-sf** [vincentarelbundock/marginaleffects#218]
Hi Vincent,

first of all thanks for maintaining `marginaleffects`, looks awesome!

I have an issue though when using a predictor in `nnet::multinom` which is a factor, not sure if that has anything to do with it. It would be great if you could take a look. 

I noticed, `marginaleffects::bind_rows` fails in line 72, but I couldn't figure out why.

Please see example below.

Cheers!

**MWE*:*

````
set.seed(42)
dat <- data.frame(y=factor(sample(c(rep(4, 29), rep(3, 15), rep(2, 4), rep(1, 2)))),
                  x=factor(sample(c(rep(1, 17), rep(2, 12), rep(2, 12), rep(1, 9)))),
                  z1=sample(1:2, 50, replace=TRUE), z2=runif(50, 16, 18))

model <- nnet::multinom(y ~ x + z1 + z2 , data=dat)

me <- marginaleffects::marginaleffects(model, type="probs")
# Error in match.names(clabs, names(xi)) : 
#   names do not match previous names
````

**Comment by vincentarelbundock** [comment]
Hi, thanks a lot for the report! I just want to confirm that I was able to replicate the problem and that I have identified its origin.

Life is a bit crazy right now, but I'll do my best to push a fix as soon as possible. Hopefully next week.

**Comment by vincentarelbundock** [comment]
Thanks again for the report @jay-sf.

I believe that the development version of the package fixes this issue:

``` r
remotes::install_github("vincentarelbundock/marginaleffects")
```

Restart R completely to make sure the changes take effect. Then:

``` r
set.seed(42)
dat <- data.frame(y = factor(sample(c(rep(4, 29), rep(3, 15), rep(2, 4), rep(1, 2)))),
                  x = factor(sample(c(rep(1, 17), rep(2, 12), rep(2, 12), rep(1, 9)))),
                  z1 = sample(1:2, 50, replace = TRUE), z2 = runif(50, 16, 18))

model <- nnet::multinom(y ~ x + z1 + z2 , data = dat)
me <- marginaleffects::marginaleffects(model, type = "probs")
summary(me)
```

    ## Average marginal effects 
    ##    Group Term Contrast    Effect Std. Error    z value Pr(>|z|)     2.5 %   97.5 %
    ## 1      1    x    2 - 1  0.002144  7.859e-03  2.728e-01 0.785035 -0.013259  0.01755
    ## 2      2    x    2 - 1  0.087712  6.265e-06  1.400e+04  < 2e-16  0.087700  0.08772
    ## 3      2   z1          -0.772104  2.702e-05 -2.858e+04  < 2e-16 -0.772157 -0.77205
    ## 4      2   z2           0.089171  8.041e-07  1.109e+05  < 2e-16  0.089170  0.08917
    ## 5      3    x    2 - 1  0.068915  2.806e-40  2.456e+38  < 2e-16  0.068915  0.06891
    ## 6      3   z1           0.176424  7.627e-41  2.313e+39  < 2e-16  0.176424  0.17642
    ## 7      3   z2           0.035160  1.020e-39  3.447e+37  < 2e-16  0.035160  0.03516
    ## 8      4    x    2 - 1 -0.158770  7.856e-03 -2.021e+01  < 2e-16 -0.174168 -0.14337
    ## 9      4   z1           0.357257  1.793e-01  1.993e+00 0.046256  0.005931  0.70858
    ## 10     4   z2          -0.114018  6.877e-03 -1.658e+01  < 2e-16 -0.127497 -0.10054
    ## 
    ## Model type:  multinom 
    ## Prediction type:  probs

**Comment by jay-sf** [comment]
You were faster than I could answer @vincentarelbundock , thanks for fixing the issue! It also works with original data. Cheers!
