### ISSUE TITLE
Three-way interaction using factor variables: Results differ from margins

### ISSUE THREAD

**Issue by jolyphil** [vincentarelbundock/marginaleffects#226]
Thanks for this excellent and very useful package (again)!

It seems like margins and marginaleffects produce different results when calculating marginal effects based on a model that includes a three-way interaction with factor variables. 

Note that, in the example below, the divergence appears _only_ in a **three-way interaction** when both `vs` and `am` are defined as **factor variables**. 

The solution offered by margins is closer to the results from Stata. 

Any idea what is happening here? 

Thanks a lot!

``` r
# Set up ------------------------------------------------------------------

library(margins)
library(marginaleffects)
library(dplyr)

df <- mtcars

df$vs <- as.factor(df$vs)
df$am <- as.factor(df$am)

hp_values <- c(100, 200, 300)


# Two-interaction: Same results -------------------------------------------

m1 <- lm(mpg ~ am * hp + vs, data = df)

margins(
  m1,
  variables = "am",
  at = list(hp = hp_values)) |>
  summary() |>
  select(AME)
#>    AME
#>  5.858
#>  4.688
#>  3.518

marginaleffects(
  m1,
  variables = "am",
  newdata = datagrid(hp = hp_values)) |>
  select(dydx)
#>       dydx
#> 1 5.857547
#> 2 4.687794
#> 3 3.518041


# Three-way interaction: different results --------------------------------

m2 <- lm(mpg ~ am * hp * vs, data = df)

margins(
  m2,
  variables = "am",
  at = list(hp = hp_values)) |>
  summary() |>
  select(AME)
#>    AME
#>  4.386
#>  4.171
#>  3.955

marginaleffects(
  m2,
  variables = "am",
  newdata = datagrid(hp = hp_values)) |>
  select(dydx)
#>       dydx
#> 1 3.709359
#> 2 4.239618
#> 3 4.769877
```

**Comment by vincentarelbundock** [comment]
On my phone now so I can't run code to check, but I am 96% sure that the difference is the same thing that I described here:

https://github.com/strengejacke/ggeffects/issues/249#issuecomment-1068334112

In that example, I talk about the `prediction` package, which was written by the `margins` author and behaves similarly.

**Comment by jolyphil** [comment]
Thanks a lot for the clarification! That's really useful. 

I now get the same estimates with the argument `grid.type = "counterfactual"` but the standard errors are still different. 

``` r
library(margins)
library(marginaleffects)
library(dplyr)

df <- mtcars

df$vs <- as.factor(df$vs)
df$am <- as.factor(df$am)

hp_values <- c(100, 200, 300)

m2 <- lm(mpg ~ am * hp * vs, data = df)

margins(
  m2,
  variables = "am",
  at = list(hp = hp_values)) |>
  summary() |>
  select(AME, SE)
#>    AME    SE
#>  4.386 1.789
#>  4.171 3.482
#>  3.955 6.713

marginaleffects(
  m2,
  variables = "am",
  newdata = datagrid(hp = hp_values,
                     grid.type = "counterfactual")) |> 
  group_by(hp) |> 
  summarize(across(c(dydx, std.error), mean))
#> # A tibble: 3 × 3
#>      hp  dydx std.error
#>   <dbl> <dbl>     <dbl>
#> 1   100  4.39      2.38
#> 2   200  4.17      4.18
#> 3   300  3.96      8.31
```

**Comment by jolyphil** [comment]
This might be related to #216.

**Comment by vincentarelbundock** [comment]
Right, you can’t just take the mean of the unit-level standard deviation. Internally, `margins` computes the “average Jacobian” and then uses that to compute the standard error. The Jacobian is stored in an attribute of the `marginaleffects` object, so we can do this:

``` r
library(margins)
library(marginaleffects)

df <- mtcars
df$vs <- as.factor(df$vs)
df$am <- as.factor(df$am)

hp_values <- c(100, 200, 300)

m2 <- lm(mpg ~ am * hp * vs, data = df)

margins(
  m2,
  variables = "am",
  at = list(hp = hp_values)) |>
  summary() |>
  select(AME, SE)

    ##    AME    SE
    ##  4.386 1.789
    ##  4.171 3.482
    ##  3.955 6.713

nd <- datagrid(model = m2,
               hp = hp_values,
               grid.type = "counterfactual")

mfx <- marginaleffects(
  m2,
  variables = "am",
  newdata = nd)

J <- attr(mfx, "J")
J_mean <- aggregate(J, by = list(mfx$hp), FUN = mean)
J_mean <- as.matrix(J_mean[, 2:ncol(J_mean)])
sqrt(diag(J_mean %*% vcov(m2) %*% t(J_mean)))

    ## [1] 1.789302 3.482390 6.712915
```

Honestly, I think that this approach is quite weird: duplicate the whole dataset and set counterfactual values. In my own work, I either look at the observed data or look at “hypothetical” individuals, but this is kind of a hybrid.

**Comment by jolyphil** [comment]
Everything is clear now. Thanks a lot for that! I really appreciate it.

**Comment by vincentarelbundock** [comment]
Pleasure. Eventually it would be cool to have a case study vignette explaining the differences and similarities to `margins` and `Stata`

**Comment by vincentarelbundock** [comment]
Oh wow, I had not seen that! Very useful indeed.

At first glance, it looks like nearly all of those examples will replicate exactly and straightforwardly. So we might need such a long vignette: just show one example of Stata's `margins` with or without the `dydx` option, comparing to `marginaleffects()` and `predictions()`, perhaps with the `type` argument. 

Then we could explain the `at` issue discussed here.

This could go in a "Case study" vignette like the `brms` one we already have.

Any help you can offer on this would be *suuuper* appreciated, but no pressure, obviously.
