### ISSUE TITLE
How to use predictions() with gam or bam models with random effects?

### ISSUE THREAD

**Issue by isabellaghement** [vincentarelbundock/marginaleffects#227]
Hi Vincent, 

Does the predictions() function work with gam (or bam) models with random effects when we wish to set those random effects to zero? 

Here's such a model: 

```

library(itsadug)
library(mgcv)
data(simdat)


simdat$Subject <- as.factor(simdat$Subject)
# run model with random intercept:
model <- bam(Y ~ Group + s(Time, by=Group)
          + s(Subject, bs="re"), data=simdat)

summary(model)
```

Now I would like to use `predictions()` on this model on the response scale.  If I use `newdata = NULL`, I can get predictions for each Subject represented in the data: 

```
library(marginaleffects)

pred_NULL <- predictions(
  model,
  newdata = NULL,
  conf.level = 0.95,
  type = "response")

pred_NULL

```

But how do I get the `predictions()` function to work for the "typical" Subject for whom the random effect is set to zero? 

Thanks a lot for any insights. 

Isabella

**Comment by vincentarelbundock** [comment]
You can compute predictions for a *specific* type of individual, specifying the exact values of all the regressors and group variables:

``` r
library(itsadug)
library(mgcv)
library(marginaleffects)
data(simdat)

simdat$Subject <- as.factor(simdat$Subject)
model <- bam(Y ~ Group + s(Time, by = Group) + s(Subject, bs = "re"), data = simdat)

predictions(
  model,
  newdata = datagrid(Subject = "a01", Group = "Adults"),
  conf.level = 0.95,
  type = "response")
#>   rowid     type predicted std.error conf.low conf.high Time Subject  Group
#> 1    73 response  9.252819 0.1449744 8.968674  9.536963 1000     a01 Adults
```

However, I don’t think it’s possible to do the equivalent of a “global mean” which ignores the random effects. If you look at [the mixed-effects vignette](https://vincentarelbundock.github.io/marginaleffects/articles/lme4.html#population-level-predictions) I show how to compute “population-level” estimates. The trick is to create a `newdata` data frame where the `Subject` variable is set to `NA`.

Unfortunately, it looks like the `mgcv` package does not support that. If you find a way to compute the correct “raw” predictions with the baseline `predict()` function, let me know and I can implement it on the `marginaleffects` side. In particular, how would you modify this call to do what you want?

``` r
predict(model) |> head()
#>          1          2          3          4          5          6 
#> -1.8738546 -1.3462927 -0.8191262 -0.2929805  0.2312910  0.7526640
```

See here for the relevant documentation:

``` r
?mgcv::predict.bam
```

**Comment by isabellaghement** [comment]
Hi Vincent, 

Thank you so much for your prompt, detailed and helpful answer.  The more I use your **marginaleffects** package, the more I love it - it really is a great package.   You did such nice work in developing this package! 

Here is what I know about how the `predict()` function works for bam or gam models fitted with the **mgcv** package.

**Case 1:  random-intercept model**

The predict() function in the mgcv package can ignore random effects via the `exclude = ` option.   For example, for the random-intercept model:

```
model_ri <- bam(Y ~ Group + s(Time, by=Group) + 
                                   s(Subject, bs="re"),   # random intercept for Subject
                                   data=simdat)
```
we can use the `smooths()` function from the **gratia** package to see the smooths fitted by the model:

```
library(gratia)

smooths(model_ri)
```
The smooths are listed as: 

```
> smooths(model_ri)
[1] "s(Time):GroupChildren" "s(Time):GroupAdults"   "s(Subject)"  
```

Then we can call predict by excluding the smooth `s(Subject)` so that we get the "global" effect of Time separately for each Group: 

```
predict(model, exclude = "s(Subject)") 
```

**Case 2:  random-intercept and random slope model**

For a model with a random intercept and a random slope of Time: 

```
model_rirs <- bam(Y ~ Group + s(Time, by = Group) + 
                                     s(Subject, bs = "re") +          # random intercept for Subject
                                     s(Subject, Time, bs = "re"),   # random slope for Subject 
                                data=simdat)
```

the smooths would be given by: 

```
> smooths(model_rirs)
[1] "s(Time):GroupChildren" "s(Time):GroupAdults"   "s(Subject)"           
[4] "s(Subject,Time)"  
```

so the "global effects" of Time by Group could be estimated with this `predict()` call: 

```
predict(model, exclude = c("s(Subject)", "s(Subject,Time)")) 
```

**Case 3:  random factor smooth model**

For a model with a random factor smooth of Time:

```
model_rfs <- bam(Y ~ Group + s(Time, by = Group) + 
                                     s(Time, Subject, bs = "fs"),   # random smooth of Time for Subject
                                     data = simdat)
```
 
the smooths would be given by:  

```
> smooths(model_rfs)
[1] "s(Time):GroupChildren" "s(Time):GroupAdults"   "s(Time,Subject)" 
```

so the "global effects" of Time by Group could be estimated with this `predict()` call: 

```
predict(model, exclude = "s(Time,Subject)") 
```

Not sure whether this syntax for `predict()` allows for easy integration with **marginaleffects** functionality, but hopefully there is something that you can figure out.

I figured the above out by looking at this reference: 

https://m-clark.github.io/gammit/

Specifically by looking at the predict_gamm() function in the gammit package.  I think (?) that function may work with re_form = NA, which would be more helpful to you. 

Thanks again! 

Isabella

**Comment by vincentarelbundock** [comment]
Thanks, this is very useful info! 

I just made a minor update to the package that will allow you to use the `exclude` argument. First, install the latest version from Github:

``` r
remotes::install_github("vincentarelbundock/marginaleffects")
```

RESTART R COMPLETELY FOR THE CHANGE TO TAKE EFFECT.

Now, we can use the `exclude` argument directly in `predictions()`.

``` r
library(itsadug)
library(mgcv)
library(marginaleffects)
data(simdat)

simdat$Subject <- as.factor(simdat$Subject)
model <- bam(Y ~ Group + s(Time, by = Group) + s(Subject, bs = "re"), data = simdat)

nd <- datagrid(model = model,
               Subject = "a01",
               Group = "Adults")
```

Default `predictions()` output is identical to the default `predict()` function:

``` r
predict(model, newdata = nd)
#>        1 
#> 9.252819

predictions(model, newdata = nd)
#>   rowid     type predicted std.error conf.low conf.high Time Subject  Group
#> 1    73 response  9.252819 0.1449744 8.968674  9.536963 1000     a01 Adults
```

Exclude the smooth and we also get identical results:

``` r
predictions(model, newdata = nd, exclude = "s(Subject)")
#>   rowid     type predicted std.error conf.low conf.high Time Subject  Group
#> 1    73 response  11.74971 0.6946584 10.38821  13.11122 1000     a01 Adults

predict(model, newdata = nd, exclude = "s(Subject)")
#>        1 
#> 11.74971
```

**Comment by isabellaghement** [comment]
Wow! This is so cool!  Thank you, Vincent!  

One last question for now.  Let's say we fit a model with an ordered version of Group so that we get a reference smooth of Time for Group = "Children" and the difference between the smooth of Time for Group = "Adults" and the reference smooth:

```
model.ord <- bam(Y ~ Group.ord + s(Time) + 
                   s(Time, by = Group.ord) + 
                   s(Subject, bs = "re"), 
                   data = simdat)
```

The model now includes an extra term, `s(Time)1, as per https://fromthebottomoftheheap.net/2017/12/14/difference-splines-ii/. 

Here is the model output: 

```
Parametric coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)   3.6207     0.4881   7.417 1.21e-13 ***
Group.ord.L   2.2108     0.6903   3.202  0.00136 ** 
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Approximate significance of smooth terms:
                           edf Ref.df      F p-value    
s(Time)                  8.366  8.826 3661.2  <2e-16 ***
s(Time):Group.ordAdults  7.630  8.472  737.4  <2e-16 ***
s(Subject)              33.940 34.000  569.1  <2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

R-sq.(adj) =  0.609   Deviance explained =   61%
fREML = 2.3795e+05  Scale est. = 31.6      n = 75600
```

In this output, the difference smooth is labelled as `s(Time):Group.ordAdults` and the reference smooth is labelled as `s(Time)`.   

Is it possible to use the `predictions()` function to compute (and then visualize) the difference smooth  `s(Time):Group.ordAdults`?  

When I try things like: 

```

nd.ord.Adults <- datagrid(model = model.ord,
                   Time = seq(0, 2000, by = 100), 
                   Subject = "a01",
                   Group.ord = "Adults")

nd.ord.Children <- datagrid(model = model.ord,
                          Time = seq(0, 2000, by = 100), 
                          Subject = "a01",
                          Group.ord = "Children")


pred.nd.ord.Adults <-  
  predictions(model.ord, 
              newdata = nd.ord.Adults, 
              exclude = "s(Subject)")


pred.nd.ord.Children <-  
  predictions(model.ord, 
              newdata = nd.ord.Children, 
              exclude = "s(Subject)")



plot_ord_Adults <- 
pred.nd.ord.Adults %>% 
  ggplot(aes(x = Time, y = predicted)) +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), 
              alpha = 0.2, fill = "dodgerblue") + 
  geom_line(size = 1) 

plot_ord_Children <- 
  pred.nd.ord.Children %>% 
  ggplot(aes(x = Time, y = predicted)) +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), 
              alpha = 0.2, fill = "dodgerblue") + 
  geom_line(size = 1) 

library(patchwork)

(plot_ord_Adults + ggtitle("Adults Smooth"))/(plot_ord_Children +  ggtitle("Children Smooth"))

```
I get to see the global smooths for Children and Adults: 

![image](https://user-images.githubusercontent.com/57458528/158709721-1f511048-5101-46be-91e1-922a5763482c.png)

But what I wanted was to see the difference smooth between Adults and Children (with Children being the reference).  Not sure how to get that out of the `predictions()` functions.  

Thank you again!

Isabella

**Comment by vincentarelbundock** [comment]
You can of course compute then one after the other, merge, subtract, and plot.

There is currently no built in way to compute uncertainty estimates for this, however.

**Comment by isabellaghement** [comment]
Argh!  It's the uncertainty estimates that I need for the difference smooth.  If I try this instead:

```
plot_cap_ord <- plot_cap(model.ord, condition = "Time")
plot_cap_ord 
```
does that actually plot the difference smooth?  This is what comes out: 
![image](https://user-images.githubusercontent.com/57458528/158714334-3e365153-b9aa-48c0-8f41-9b07d64a507c.png)

It looks more like the Adults global smooth, though strictly speaking, it should be the difference smooth.

All three plots together: 

```
plot_ord_Adults <- plot_ord_Adults + coord_cartesian(y = c(-16,16)) +
                               scale_y_continuous(breaks = seq(-16,16, by = 2))
plot_ord_Adults

plot_ord_Children <- plot_ord_Children + coord_cartesian(y = c(-16,16)) +
                                  scale_y_continuous(breaks = seq(-16,16, by = 2))
plot_ord_Children

plot_cap_ord <- plot_cap_ord + coord_cartesian(y = c(-16,16)) +
                                  scale_y_continuous(breaks = seq(-16,16, by = 2))
plot_cap_ord

(plot_ord_Adults + ggtitle("Adults Smooth") ) +
(plot_ord_Children +  ggtitle("Children Smooth")) +
(plot_cap_ord +  ggtitle("What Smooth is This?"))

```
![image](https://user-images.githubusercontent.com/57458528/158715867-9eb74c9e-c1e6-41de-879e-2b977304ee47.png)

If plot_cap() does compute the difference smooth, than it already knows how to get the uncertainty band for the difference smooth.  How to pass that information to predictions() I would not know.

Thanks so much, Vincent! 

Isabella

**Comment by vincentarelbundock** [comment]
`plot_cap()` does this:

* Find range of `condition` variable in the original data
* Create a prediction grid with values on the range defined above.
* Feeds to the prediction grid to `predictions()`'s `newdata` argument.
* Plots the results

This is the specific process that is followed. Beyond that, I can't really help you with the substantive interpretation because I have no expertise in `mgcv::bam` models.

**Comment by vincentarelbundock** [comment]
Closing this issue now because the original problem has been solved by allowing the `exclude` argument.

These reports are helpful to me, so don't hesitate to make other feature requests if you have any.

**Comment by vincentarelbundock** [comment]
@isabellaghement FYI, I added a short case-study on the website with some of the things we have talked about. Hopefully this will help other users.

https://vincentarelbundock.github.io/marginaleffects/articles/gam.html

Thanks again for your help!
