### ISSUE TITLE
Vignette on alternatives: stata and marginaleffects pvalues don't match

### ISSUE THREAD

**Issue by etiennebacher** [vincentarelbundock/marginaleffects#235]
Hello, the results in [this vignette](https://vincentarelbundock.github.io/marginaleffects/articles/alternative_software.html) show that the pvalues between Stata and `marginaleffects` are slightly different. Note that standard errors and t-values are identical, only pvalues are different.

I don't know whether this is an unknown issue or if it is related to #66, so I preferred reporting this. If this is a known issue, maybe you could add a note explaining why there is a small difference?

**Comment by vincentarelbundock** [comment]
@etiennebacher, `Stata` reports `p<|t|` while `marginaleffects` reports `p<|z|`. You can see that the results are the same by calculating it manually. Copying the first coefficient and standard error in the `Stata` table here: https://vincentarelbundock.github.io/marginaleffects/articles/alternative_software.html

Then, calculating the p value:

``` r
2 * pnorm(-.9416168 / .5509164)
#> [1] 0.08741711
```

I added a note to the vignette.

**Comment by etiennebacher** [comment]
Ok, thank you

**Comment by vincentarelbundock** [comment]
Thanks for reading the vignettes so carefully! Sometimes I feel like I'm writing this only for Google's bots, so it's nice to get a second eye on them ;)
