### ISSUE TITLE
Error in get_predict.fixest

### ISSUE THREAD

**Issue by WildEcology** [vincentarelbundock/marginaleffects#239]
```r
Error in get_predict.fixest(model = model, newdata = newdata_tmp, type = type,  : 
  Unable to extract predictions from a model of type `fixest`. Please report this problem, along with replicable code, on the `marginaleffects` issue tracker: https://github.com/vincentarelbundock/marginaleffects/issues
```

model used:

```r
nonlin_mod <- feNmlm(value ~ ppt*tmax+I(tmax^2) | plot,
       data = dat)
```

conditional plot that caused the error:

```r
plot_cme(nonlin_mod, effect = "tmax", condition="tmax")+
  geom_hline(yintercept = 0, linetype="dashed")
```

**Comment by vincentarelbundock** [comment]
Thanks a lot for the report @WildEcology . I believe this is a bug in `fixest`, and I have reported it here: https://github.com/lrberge/fixest/issues/292

**Comment by WildEcology** [comment]
Thank you for the quick response and thank you for posting to the fixest page!

**Comment by vincentarelbundock** [comment]
@WildEcology, FYI if you install the development versions of both `fixest` and `marginaleffects` and restart `R`, this should work:

``` r
remotes::install_github("lrberge/fixest")
remotes::install_github("vincentarelbundock/modelsummary")
```

Restart R completely, then:

``` r
library("fixest")
library("marginaleffects")
data(trade)
dat <- trade
dat$Product <- factor(dat$Product)
mod <- feNmlm(Euros ~ log(dist_km) | Product,
              data = dat)
mfx <- marginaleffects(mod)
summary(mfx)
#> Average marginal effects 
#>      Term  Effect Std. Error z value   Pr(>|z|)   2.5 % 97.5 %
#> 1 dist_km -106627      24301  -4.388 1.1456e-05 -154257 -58997
#> 
#> Model type:  fixest 
#> Prediction type:  response

plot_cap(mod, condition = "dist_km")
```

![](https://i.imgur.com/9O7JH77.png)

**Comment by WildEcology** [comment]
Thank you! The fixest development version is giving this error:

code:
remotes::install_github("lrberge/fixest")

error: 
Downloading GitHub repo lrberge/fixest@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/lrberge/fixest/tarball/HEAD' failed
  
 marginaleffects downloaded no problem; I am using the latest version of R.

**Comment by vincentarelbundock** [comment]
Looks like a network error. Maybe try just the first line one more time:

```r
remotes::install_github("lrberge/fixest")
```
