### ISSUE TITLE
`get_varcov` sanity checks conditional on `insight` version

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/marginaleffects#277]
Changes:

+ [x] skip tests for `vcov = "HC3"`
+ [x] conditional sanity check on `vcov` with informative message

**Comment by strengejacke** [comment]
I submitted one week ago, _insight_ is now under manual inspection (due to revdep). I hopefully get an answer about submission status soon.

**Comment by vincentarelbundock** [comment]
Thanks! BDR gave me until the 15th to save my package, so I might have to submit before this is resolved. I'll just have a conditional check on version number and an informative error.
