### ISSUE TITLE
Custom contrasts / interaction contrasts?

### ISSUE THREAD

**Issue by mattansb** [vincentarelbundock/marginaleffects#319]
Is there a way to obtain custom contrasts?

This is how I would do this in `emmeans`:

``` r
library(emmeans)
#> Warning: package 'emmeans' was built under R version 4.1.3

m <- lm(mpg ~ factor(carb) + factor(cyl), mtcars)

# Define some weights
w_carb <- data.frame(custom_contrast = c(-2, 1, 1, 0, -1, 1))
w_cyl <- data.frame(cc2 = c(-1, 2, -1))

emmeans(m, "carb") |> 
  contrast(method = w_carb)
#>  contrast        estimate   SE df t.ratio p.value
#>  custom_contrast   -0.211 6.93 24  -0.030  0.9760
#> 
#> Results are averaged over the levels of: cyl

# Yes this is a silly example
emmeans(m, c("carb", "cyl")) |> 
  contrast(interaction = list(cyl = w_cyl, carb = w_carb))
#>  cyl_custom carb_custom     estimate SE df t.ratio p.value
#>  cc2        custom_contrast        0  0 24     NaN     NaN
```

<sup>Created on 2022-05-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by vincentarelbundock** [comment]
Huh, my guess is: probably not?

Hitting my `emmeans` limits. What does this do? Is this:

1. Compute marginal means for each level of the factors.
2. Testing if a linear combination of those marginal means is different from zero

Something else?

**Comment by mattansb** [comment]
Exactly right.

The first example has contrast weights for one predictor, the second has interactions with custom weights defined for the "margin" of each predictor. But they can also be defined for the combinations of both predictors.

**Comment by vincentarelbundock** [comment]
Closed in favor of two feature-specific issues:

* https://github.com/vincentarelbundock/marginaleffects/issues/355
* https://github.com/vincentarelbundock/marginaleffects/issues/356

#355 works already, so you may want to have a look at that one.
