### ISSUE TITLE
Add adjusted marginal odds ratio to transform_pre in comparisons()

### ISSUE THREAD

**Issue by ngreifer** [vincentarelbundock/marginaleffects#322]
Incredible work on the package Vincent! I plan to use `marginaleffects` in the `MatchIt` documentation for estimating effects. Currently there is a lot of code for implementing bootstrapping for certain estimands, in particular for nonlinear contrasts with binary outcomes, because there has been no other way to produce effects and their confidence intervals. I would much rather direct users to a simple function to compute the effect of interest. With the `transform_pre` argument in `comparisons()`, I think I am almost ready to make the full transition.

I am requesting adding a built-in function for `transform_pre`, namely the (log) marginal odds ratio. That is, defining a function
```r
fun <- \(hi, lo) {P_hi <- mean(hi); P_lo <- mean(lo); log((P_hi / (1 - P_hi)) / (P_lo / (1 - P_lo)))}
```
Obviously users could write this function themselves, but some users of `MatchIt` are often not sophisticated enough programmers to do this confidently, and I don't want to alienate them by only providing even this fairly simple code if an alternative could be provided. Since the marginal odds ratio is a fairly common estimand in medical research, I'm hoping you would consider adding this as a built-in. Thank you!

**Comment by vincentarelbundock** [comment]
Sounds great! Do you want to just make a pull request? The built-in shortcuts are hosted here:

https://github.com/vincentarelbundock/marginaleffects/blob/main/R/sanitize_transform_pre.R 

and documented here:

https://github.com/vincentarelbundock/marginaleffects/blob/main/R/comparisons.R#L55

We also need a "smart" label in which we insert the `lo` and `hi` values, and that we feed to `sprintf()` (same link as above). Doesn't need to be the actual function if it's too complicated.

Also, we can't use `\(x)` because of compatibility with older versions.

**Comment by vincentarelbundock** [comment]
This is super cool, thanks\!

Added your name to the `NEWS`.

I have to say that I thought this new `transform_pre` feature was kind of cute: simple and general. But I had no idea it would bear fruits so fast. This is fantastic.

CRAN doesn’t like me releasing packages too often, so this will probably get to CRAN in about 1 month. In the meantime, it’ll obviously be available on Github.

``` r
library(marginaleffects)
mod <- glm(vs ~ factor(gear), data = mtcars, family = binomial)
comparisons(
    mod,
    transform_pre = "lnoravg") |>
summary(transform_post = exp)
#> Average contrasts 
#>   Term              Contrast Effect  Pr(>|z|)   2.5 % 97.5 %
#> 1 gear ln(odds(4) / odds(3))     20 0.0029676 2.77182 144.31
#> 2 gear ln(odds(5) / odds(3))      1 1.0000000 0.07963  12.56
#> 
#> Model type:  glm 
#> Prediction type:  response
```

One thing that – I admit – I had not thought through carefully, is that we can apply the `transform_pre` either in `comparisons()` itself, or at the very end in `summary()`. If we do it in `comparisons()`, then the raw unit-level results make sense, but then the `summary()` output isn’t super intuitive. I’ll have to build some guard rails in the next version…

Example:

``` r
comparisons(
    mod,
    transform_pre = "lnoravg",
    transform_post = exp) |>
summary()
#> Average contrasts 
#>   Term              Contrast Effect Std. Error z value Pr(>|z|) 2.5 % 97.5 %
#> 1 gear ln(odds(4) / odds(3))     20      1.008 19.8354  < 2e-16 18.02  21.98
#> 2 gear ln(odds(5) / odds(3))      1      1.291  0.7746  0.43858 -1.53   3.53
#> 
#> Model type:  glm 
#> Prediction type:  response 
#> Post-transformation:  exp
```

**Comment by ngreifer** [comment]
`transform_pre` is essential! For so long we've been limited to calculating differences in average marginal means when there are so many other effect measures, especially for binary outcomes. I haven't come across another package that can do this, so to me it's a big deal.

Yeah, the deal with `transform_post` is a bit confusing. I found that actually the results make more sense when `transform_post` is used in `summary()`. That is, you compute the log of the marginal odds ratio and its standard error, and since it's a normally distributed, unbounded variable, this makes sense and you could use it as your final estimate, but then kind of as a convenience for readers you exponentiate it and its confidence interval at last. I'm not exactly sure what happens when using`transform_post` in `comparisons()`, but I'm not sure it's what most people are expecting. You do mention in the vignette that what Stata does is closer to using it in `summary()`, so it might make more sense to prioritize that usage in the vignette.

Also might be nice to allow `transform_post` to accept a string instead of a function (I mean, `"exp"` is the most obvious use case) and to print it in the `summary()` output when called in `summary()` like you do when it is called in `comparisons()`.

**Comment by vincentarelbundock** [comment]
Agree on all counts!

From a user interface perspective, my hunch is that it would be better to have both `transform_pre` and `transform_post` in the same function. `transform_post` is useful when you want to get unit-level estimates (the default output) on a different scale. Same thing if a user wants to transform "contrast at the mean". In both cases, we need to keep the argument in `comparisons()` itself. 

However, in an ideal world, the argument should only be called once, so I'm thinking we should just remove it from `summary()` altogether. We could then assume that users want to apply the same transformation to unit-level contrasts and average contrasts. People with weird needs can just call the function twice.

A minor challenge is that when data are transformed in `comparisons()`, we need to save the original data as an attribute if we want to be able to compute the average contrasts on the original scale, and then transform them in `summary()` as well.

It's a little bit of a headache but shouldn't be toooo bad.

I opened a separate issue to track progress on this: https://github.com/vincentarelbundock/marginaleffects/issues/324

Thanks again!

**Comment by vincentarelbundock** [comment]
> Yeah, the deal with `transform_post` is a bit confusing. I found that actually the results make more sense when `transform_post` is used in `summary()`. That is, you compute the log of the marginal odds ratio and its standard error, and since it’s a normally distributed, unbounded variable, this makes sense and you could use it as your final estimate, but then kind of as a convenience for readers you exponentiate it and its confidence interval at last. I’m not exactly sure what happens when using`transform_post` in `comparisons()`,

FYI, I renamed the argument in `tidy()` and `summary()` to `transform_avg` in order to disambiguate. Backward compatibility is preserved.

What happens is:

  - `transform_post` in `comparisons()`: exponentiate the unit-level estimates
  - `transform_avg` in `tidy()`: exponentiate the estimates only *after* we have taken their average

The two can of course produce very different results, because the transform of an average is not the same as the average of a transform:

``` r
x <- rnorm(100)
mean(exp(x))
#> [1] 1.603844
exp(mean(x))
#> [1] 1.033633
```

I tried to improve the vignette to explain this better, but it remains quite confusing. And I did not see a statistical argument in the Stata arr docs about this (I may have missed it).
