### ISSUE TITLE
weights

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/marginaleffects#327]
+ [x] compare to Stata
+ [x] in `tidy` use `weighted.mean`

**Comment by vincentarelbundock** [comment]
@mattansb

The `marginaleffects()` and `comparisons()` function now have "weights" arguments. I checked a simple logit model with weights against Stata and I match the estimates perfectly, but I can't figure out exactly what kind of standard errors they are estimating. We match at 0.002 tolerance for standard errors.

Let me know if you try it and run into issues.

**Comment by ray-p144** [comment]
To keep the discussions organized, I am just restarting the weights discussion from #332 here instead:

> > I just saw that you added the `weights` argument to the `marginaleffects()` and `comparisons()` functions as I was typing this up. Haha.
> 
> Ha, yeah!
> 
> If you have a chance, could you compare a couple models in Stata. I don't have access to a local copy, and couldn't figure out exactly what kind of "robust" vce they are using by default in weighted models.
> 

From what I understand after reading [Ch 20.23.3 of the Stata manual](https://www.stata.com/manuals13/u20.pdf#u20.23.3Samplingweights) (in the last 3 paragraphs of the Sampling weights section), the standard errors they are using for the weighted logit are the same as the ones used for the `svy: logit` command (i.e., first order Taylor series linear approximation [[citation](https://www.stata.com/manuals13/svysurvey.pdf#svysurvey)]).

We can reproduce the same results as you have in the test:
https://github.com/vincentarelbundock/marginaleffects/blob/af7578bb54072c801a4cf1a4fa501acb64796878/inst/tinytest/test-weights.R#L77-L83

by using `svyglm()` in the `survey` package:
``` r
library(marginaleffects)
library(survey)
#> Loading required package: grid
#> Loading required package: Matrix
#> Loading required package: survival
#> 
#> Attaching package: 'survey'
#> The following object is masked from 'package:graphics':
#> 
#>     dotchart
library(broom)
#> Warning: package 'broom' was built under R version 4.1.3
options(pillar.sigfig = 7)

dat <- mtcars
dat$weights <- 1:32

svymod <- svyglm(
    am ~ mpg,
    design = svydesign(ids = ~1, weights = ~weights, data = dat),
    family = binomial
)
#> Warning in eval(family$initialize): non-integer #successes in a binomial glm!

tidy(svymod, conf.int = TRUE)
#> # A tibble: 2 x 7
#>   term          estimate  std.error statistic     p.value    conf.low  conf.high
#>   <chr>            <dbl>      <dbl>     <dbl>       <dbl>       <dbl>      <dbl>
#> 1 (Intercept) -5.484059  2.066302   -2.654045 0.01259926  -9.704010   -1.264108 
#> 2 mpg          0.2789194 0.09430199  2.957726 0.005992926  0.08632909  0.4715098

```
The covariance matrix of Stata's weighted also matches the unscaled covariance matrix returned by `svyglm()` (as `..$cov.unscaled`), which is what the `vcov.svyglm()` method retrieves:

``` stata
. estat vce

Covariance matrix of coefficients of logit model

             | am                     
        e(V) |        mpg       _cons 
-------------+------------------------
am           |                        
         mpg |  .00889288             
       _cons | -.18901298   4.2696082 

```
``` r
vcov(svymod) ## svymod$cov.unscaled
#>             (Intercept)          mpg
#> (Intercept)   4.2696027 -0.189012684
#> mpg          -0.1890127  0.008892865
```

However, for some reason the `marginaleffects()` standard errors are still different:
https://github.com/vincentarelbundock/marginaleffects/blob/af7578bb54072c801a4cf1a4fa501acb64796878/inst/tinytest/test-weights.R#L93-L98
``` r
marginaleffects(svymod, weights = svymod$prior.weights) |>
    tidy()
#>       type term   estimate   std.error statistic      p.value   conf.low
#> 1 response  mpg 0.04410671 0.006096819  7.234381 4.676259e-13 0.03215717
#>    conf.high
#> 1 0.05605626
```

After reading some more about the `margins` command, it seems that they recommend using the `vce(unconditional)` option when the data is weighted [[citation](https://www.stata.com/manuals/rmargins.pdf) page 29-30]. However, this still doesn't match the result from `marginaleffects()`: 

``` stata
. margins, dydx(mpg) vce(unconditional)

Average marginal effects                                    Number of obs = 32

Expression: Pr(am), predict()
dy/dx wrt:  mpg

------------------------------------------------------------------------------
             |            Unconditional
             |      dy/dx   std. err.      z    P>|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
         mpg |   .0441066   .0066914     6.59   0.000     .0309917    .0572216
------------------------------------------------------------------------------
```

What seems strange to me (although I haven't dug into why) is that I was able to verify that the confidence intervals from the `adjrr` command matches those produced by the `comparisons()` function when weighted survey data is used without using the `weights` argument (at least to a higher tolerance than the difference shown above). From the documentation of the `adjrr` command, it automatically calls `margins` with the `vce(unconditional)` when it detects a model fit using a `svy:` command (which I verified from the source code). This seems to match the `comparisons()` function use of the unscaled covariance matrix returned by `vcov.svyglm()`, so I am not sure where the difference is coming from.

``` stata
. svyset [pw=weights]

Sampling weights: weights
             VCE: linearized
     Single unit: missing
        Strata 1: <one>
 Sampling unit 1: <observations>
           FPC 1: <zero>

. 
. svy: logit am i.vs
(running logit on estimation sample)

Survey: Logistic regression

Number of strata =  1                                 Number of obs   =     32
Number of PSUs   = 32                                 Population size =    528
                                                      Design df       =     31
                                                      F(1, 31)        =   2.13
                                                      Prob > F        = 0.1546

------------------------------------------------------------------------------
             |             Linearized
          am | Coefficient  std. err.      t    P>|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
        1.vs |   1.224699   .8394477     1.46   0.155    -.4873664    2.936763
       _cons |  -.4751984   .5875017    -0.81   0.425    -1.673416    .7230192
------------------------------------------------------------------------------

. 
. adjrr vs, x0(0) x1(1)

R1  = 0.6791 (0.1307)    95% CI  (0.4230, 0.9352)
R0  = 0.3834 (0.1389)    95% CI  (0.1112, 0.6556)
ARR = 1.7712 (0.7266)    95% CI  (0.7927, 3.9577)
ARD = 0.2957 (0.1907)    95% CI  (-0.0781, 0.6694)
p-value (R0 = R1):  0.1312
p-value (ln(R1/R0) = 0):  0.1634

. 

```

``` r
dat$vs <- factor(dat$vs)
svymod <- svyglm(
    am ~ vs,
    design = svydesign(ids = ~1, weights = ~weights, data = dat),
    family = binomial
)
#> Warning in eval(family$initialize): non-integer #successes in a binomial glm!
tidy(svymod, conf.int = TRUE)
#> # A tibble: 2 x 7
#>   term          estimate std.error  statistic   p.value   conf.low conf.high
#>   <chr>            <dbl>     <dbl>      <dbl>     <dbl>      <dbl>     <dbl>
#> 1 (Intercept) -0.4751984 0.5875017 -0.8088461 0.4249722 -1.675037  0.7246401
#> 2 vs1          1.224699  0.8394477  1.458934  0.1549752 -0.4896824 2.939080
comparisons(svymod, transform_pre = "lnratioavg") |>
    tidy(transform_post = exp)
#>       type term              contrast estimate   p.value  conf.low conf.high
#> 1 response   vs ln(mean(1) / mean(0))  1.77124 0.1634077 0.7927287  3.957586
```
<sup>Created on 2022-05-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by vincentarelbundock** [comment]
Thanks, this is super useful!

So what is your sense of the current status? I added your `survey` model to the tests and we now match standard errors at 0.0002 tolerance. Without seeing the Stata source code, I'm not sure how we're going to resolve the issue better...

What else should be on the TODO list with respect to weights in the comparisons() or marginaleffects() functions? (predictions() is another issue that I have think about)

**Comment by ray-p144** [comment]
No problem!

I think the current status is great! (I must have been tired and exaggerated the difference between `0.0061046` and `0.006096819` in my head).

At this point, I am just trying to wrap my head around how the adjusted risk ratio calculation using the weighted survey model was able to get the same results as the `adjrr` command in Stata without needing to specify any weights in the `comparisons()` function.

Nothing comes to mind immediately as far as additional things to add to the TODO list, but I will put some thought into it.

Just to give you a heads up: my "vacation" ends today, so I may not have as much time that I can spend on this over the next few months. (I would still love to help test things and discuss potential features, but my responses might just be a little more delayed.)

**Comment by vincentarelbundock** [comment]
Sounds great. I really appreciate the help and the sounding board!

**Comment by ray-p144** [comment]
I thought of something that could potentially be added to the TODO list for weights. (Of course I only think of it after you closed this. Haha.)

It would be very helpful to be able to pass a vector of weights to the `datagrid()` function in order for it to include it in its output and be used in the `comparisons()`, `predictions()`, and `marginaleffects()` functions.

Right now for `svyglm` models, we are required to manually add the weights to the output of `datagrid()` before passing it to `predictions()` to use weights and a counterfactual dataset in `predictions()` (i.e., reproduce the Stata `margins a` command for a weighted model).

Ideally, the `datagrid()` function would be able to recognize weighted models and pull the values when needed, but I don't know how feasible that would be given all the different ways weights can be handled by models.

``` r
library(marginaleffects)
library(survey)
#> Loading required package: grid
#> Loading required package: Matrix
#> Loading required package: survival
#> 
#> Attaching package: 'survey'
#> The following object is masked from 'package:graphics':
#> 
#>     dotchart

dat <- mtcars
dat$we <- 1:32
suppressWarnings({
    svymod <- svyglm(
        am ~ vs + mpg,
        design = svydesign(ids = ~1, weights = ~we, data = dat),
        family = binomial
    )
})

predictions(svymod, weights = "we", newdata = datagrid(vs = 0:1, grid_type = "counterfactual")) |>
    tidy(by = "cyl")
#> Error: The `weights` argument must be a numeric vector of length 64, or a string which matches a column name in `newdata`. If you did not supply a `newdata` explicitly, `marginaleffects` extracted it automatically from the model object, and the `weights` variable may not have been available. The easiest strategy is often to supply a data frame such as the original data to `newdata` explicitly, and to make sure that it includes an appropriate column of weights.

pdat <- datagrid(model = svymod, vs = 0:1, grid_type = "counterfactual")
pdat$we <- rep.int(svymod$prior.weights, 2)

predictions(svymod, weights = pdat$we, newdata = pdat) |>
    tidy(by = "vs")
#>    vs  estimate  std.error statistic      p.value  conf.low conf.high
#> 1:  0 0.5901829 0.09837727  5.999180 1.983166e-09 0.3973670 0.7829988
#> 2:  1 0.3632836 0.09082650  3.999753 6.340856e-05 0.1852669 0.5413003
```

(This example was run using the `tidy.predictions()` function I used in https://github.com/vincentarelbundock/marginaleffects/issues/332#issuecomment-1136668407)

<sup>Created on 2022-05-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by vincentarelbundock** [comment]
You can preserve all the columns of the data frame by passing it to the `newdata` argument *inside* `datagrid()`. That includes the weights column and the group column.

I know this is not super intuitive, but perhaps it could be better documented. Maybe we need a couple vignettes, one on weights, and the other just on `datagrid()`.

Examples:

``` r
library(marginaleffects)

dat <- mtcars
dat$we <- 1:32
suppressWarnings({
    svymod <- svyglm(
        am ~ vs + mpg,
        design = svydesign(ids = ~1, weights = ~we, data = dat),
        family = binomial
    )
})

predictions(svymod,
    weights = "we",
    newdata = datagrid(newdata = dat, vs = 0:1, grid_type = "counterfactual")) |>
    tidy(by = "cyl")
#>    cyl  estimate  std.error statistic      p.value   conf.low conf.high
#> 1:   6 0.4398729 0.11009525  3.995385 6.458923e-05 0.22409018 0.6556556
#> 2:   4 0.8573142 0.05633079 15.219283 2.634022e-52 0.74690785 0.9677205
#> 3:   8 0.1686562 0.08009035  2.105824 3.521967e-02 0.01168195 0.3256303

predictions(svymod,
    newdata = datagrid(newdata = dat, vs = 0:1, grid_type = "counterfactual")) |>
    tidy(by = "cyl")
#>    cyl  estimate  std.error statistic      p.value   conf.low conf.high
#> 1:   6 0.4763363 0.10913466  4.364665 1.273174e-05 0.26243628 0.6902363
#> 2:   4 0.8467155 0.06298525 13.443075 3.380897e-41 0.72326667 0.9701643
#> 3:   8 0.1738362 0.07982079  2.177831 2.941860e-02 0.01739034 0.3302821
```
