### ISSUE TITLE
Simplify parametric g-formula vignette

### ISSUE THREAD

**Issue by ngreifer** [vincentarelbundock/marginaleffects#336]
Hi Vincent,

Thank you for putting together the parametric g-formula vignette! I wanted to say that there is a way to considerably simplify the vignette using `comparisons()`. I think you are underselling the convenience of using `comparisons()`; the whole point is that you don't need to create the counterfactual dataset (`onesample`) and fit a separate model (`std`) to compute the estimate; the parametric g-formula estimate can be computed using the following very simple code:
```
cmp <- comparisons(
  fit,
  variables = list(qsmk = 0:1))
summary(cmp)
```
That is, using the original model fit and simply using the built-in contrast syntax, you can get the exact same estimate and standard error as using the counterfactual method. I recommend you include this in the vignette because it reduces many lines of code into a single one that you can call right after fitting the parametric model. The parametric g-formula is already equivalent to the average marginal effect; you've already done all the work internally, which is what makes it such an amazing tool!

**Comment by vincentarelbundock** [comment]
Haha! Yes, of course.

e047e43c048

The website should update soon.
