### ISSUE TITLE
Multiple imputation

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/marginaleffects#345]
Here’s an example for @TysonStanley. Might be interesting to have a vignette about this. (If we can somehow confirm that it works.)

``` r
library(mice)
library(marginaleffects)

dat <- mtcars
dat$am[c(2, 5)] <- NA
dat$mpg[c(3, 1)] <- NA

fit <- function(dat) {
    mod <- glm(am ~ mpg, family = binomial, data = dat)
    out <- marginaleffects(mod, newdata = dat)
    return(out)
}
dat_mice <- mice(dat, m = 20, printFlag = FALSE, .Random.seed = 1024)
dat_mice <- complete(dat_mice, "all")
mod <- lapply(dat_mice, fit)
mod <- pool(mod)

summary(mod)
#>   term   estimate   std.error statistic       df      p.value
#> 1  mpg 0.04296124 0.007746078  5.546193 28.41068 5.954828e-06
```

**Comment by TysonStanley** [comment]
This is beautiful. I'll have some time this weekend to work on this if you want me to get a vignette at least started. I have some ideas of how to confirm that this is working the way we would like it to work without doing a full simulation study.

**Comment by vincentarelbundock** [comment]
Yeah, that sounds fantastic! No pressure, obviously.
