### ISSUE TITLE
Linear combinations of marginal means

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/marginaleffects#355]
This is for @mattansb

The code below requires the devel version of `marginaleffects`.

The `marginalmeans()` function computes [estimated marginal means.](https://vincentarelbundock.github.io/marginaleffects/articles/mfx04_marginalmeans.html) The `lincom` argument of that function offers a powerful mechanism to estimate custom contrasts between marginal means, by way of linear combination.

Consider a simple example:

``` r
library(marginaleffects)
library(emmeans)
library(nnet)

dat <- mtcars
dat$carb <- factor(dat$carb)
dat$cyl <- factor(dat$cyl)
dat$am <- as.logical(dat$am)

mod <- lm(mpg ~ carb + cyl, dat)
mm <- marginalmeans(mod, variables = "carb")
mm
#>   term value marginalmean std.error conf.low conf.high      p.value statistic
#> 1 carb     1     21.66232  1.438417 18.84307  24.48156 2.975538e-51 15.059829
#> 2 carb     2     21.34058  1.234609 18.92079  23.76037 6.071610e-67 17.285289
#> 3 carb     3     21.41667  2.191616 17.12118  25.71215 1.483584e-22  9.772091
#> 4 carb     4     18.88406  1.210941 16.51066  21.25746 7.929506e-55 15.594538
#> 5 carb     6     19.76014  3.551143 12.80003  26.72026 2.629853e-08  5.564447
#> 6 carb     8     20.11667  3.510156 13.23689  26.99645 9.984697e-09  5.730989
```

The contrast between marginal means for `carb==1` and `carb==2` is:

``` r
21.34058 - 21.66232 
#> [1] -0.32174
```

or

``` r
21.66232 + -(21.34058)
#> [1] 0.32174
```

or

``` r
sum(c(21.66232, 21.34058) * c(1, -1))
#> [1] 0.32174
```

or

``` r
c(21.66232, 21.34058) %*% c(1, -1)
#>         [,1]
#> [1,] 0.32174
```

The last two commands express the contrast of interest as [a linear combination](https://en.wikipedia.org/wiki/Linear_combination) of marginal means.

# Simple contrast between marginal means

In the `marginalmeans()` function, we can supply a `lincom` argument to compute linear combinations of marginal means. This argument must be a numeric vector of the same length as the number of rows in the output of `marginalmeans()`. For example, in the previous there were six rows, and the two marginal means we want to compare are at in the first two positions:

``` r
lc <- c(1, -1, 0, 0, 0, 0)
marginalmeans(mod, variables = "carb", lincom = lc)
#>     term marginalmean std.error  conf.low conf.high   p.value statistic
#> 1 lincom    0.3217391  1.773733 -3.154713  3.798191 0.8560607  0.181391
```

# Complex contrast between marginal means

Of course, we can also estimate more complex contrasts:

``` r
lc <- c(-2, 1, 1, 0, -1, 1)
marginalmeans(mod, variables = "carb", lincom = lc)
#>     term marginalmean std.error  conf.low conf.high   p.value   statistic
#> 1 lincom   -0.2108696  6.928859 -13.79118  13.36945 0.9757213 -0.03043352
```

`emmeans` produces similar results:

``` r
library(emmeans)
em <- emmeans(mod, "carb")
lc <- data.frame(custom_contrast = c(-2, 1, 1, 0, -1, 1))
contrast(em, method = lc)
#>  contrast        estimate   SE df t.ratio p.value
#>  custom_contrast   -0.211 6.93 24  -0.030  0.9760
#> 
#> Results are averaged over the levels of: cyl
```

# Linear combinations across response levels

In models with multinomial outcomes, one may be interested in comparing outcomes or contrasts across response levels. For example, in this model there are 18 estimates marginal means, across 6 outcome levels (the `group` column):

``` r
library(nnet)
mod <- multinom(carb ~ mpg + cyl, data = dat, trace = FALSE)
mm <- marginalmeans(mod, type = "probs")
mm
#>    group term value marginalmean     std.error
#> 1      1  cyl     4 3.678521e-01 1.698597e-112
#> 2      2  cyl     4 6.310922e-01 2.073520e-113
#> 3      3  cyl     4 6.852625e-04 7.238685e-146
#> 4      4  cyl     4 2.118825e-04  2.937334e-06
#> 5      6  cyl     4 8.815299e-06  2.937430e-06
#> 6      8  cyl     4 1.496776e-04 2.004341e-122
#> 7      1  cyl     6 2.828726e-01 3.686508e-112
#> 8      2  cyl     6 1.848644e-06 1.611668e-109
#> 9      3  cyl     6 1.121687e-05 5.743154e-141
#> 10     4  cyl     6 5.562672e-01  8.814399e-04
#> 11     6  cyl     6 1.608378e-01  8.814399e-04
#> 12     8  cyl     6 9.291803e-06 1.031768e-117
#> 13     1  cyl     8 4.625030e-04 2.108275e-111
#> 14     2  cyl     8 6.654572e-01 1.009084e-112
#> 15     3  cyl     8 3.103763e-01 1.251636e-142
#> 16     4  cyl     8 9.582000e-03  1.934535e-05
#> 17     6  cyl     8 4.345753e-09  1.934533e-05
#> 18     8  cyl     8 1.412195e-02 1.868127e-116
```

Let’s contrast the marginal means in the first outcome level when `cyl` equals 4 and 6. These marginal means are located in rows 1 and 7 respectively:

``` r
lc <- rep(0, nrow(mm))
lc[1] <- -1
lc[7] <- 1
marginalmeans(
    mod,
    type = "probs",
    lincom = lc)
#>     term marginalmean     std.error
#> 1 lincom  -0.08497951 1.987911e-112
```

This is indeed equal to the results we would have obtained manually:

``` r
2.828726e-01 - 3.678521e-01
#> [1] -0.0849795
```

How let’s say we want to calculate a “contrast in contrast”, that is, the outcome of a 3-step process:

1.  Contrast between `cyl=6` and `cyl=4` in the 1st outcome level
2.  Contrast between `cyl=6` and `cyl=4` in the 2nd outcome level
3.  Contrast between the contrasts defined in steps 1 and 2.

Create the linear combination weights and display them alongside marginal means to see how they are structured:

``` r
lc <- rep(0, nrow(mm))
lc[c(1, 8)] <- -1
lc[c(7, 2)] <- 1
transform(mm[, 1:3], lc = lc)
#>    group term value lc
#> 1      1  cyl     4 -1
#> 2      2  cyl     4  1
#> 3      3  cyl     4  0
#> 4      4  cyl     4  0
#> 5      6  cyl     4  0
#> 6      8  cyl     4  0
#> 7      1  cyl     6  1
#> 8      2  cyl     6 -1
#> 9      3  cyl     6  0
#> 10     4  cyl     6  0
#> 11     6  cyl     6  0
#> 12     8  cyl     6  0
#> 13     1  cyl     8  0
#> 14     2  cyl     8  0
#> 15     3  cyl     8  0
#> 16     4  cyl     8  0
#> 17     6  cyl     8  0
#> 18     8  cyl     8  0
```

Compute the results:

``` r
marginalmeans(mod, type = "probs", lincom = lc)
#>     term marginalmean     std.error
#> 1 lincom    0.5461109 1.609472e-109
```

**Comment by mattansb** [comment]
That's awesome!

Can `lincom` be a matrix?
Another thing would be to be able to set a `by` argument to get conditional contrasts.

Amazing work, I really don't know how to produce such polished stuff so fast...

**Comment by vincentarelbundock** [comment]
> That's awesome!

cool

> Can `lincom` be a matrix? 

Just to be sure, this would compute 2 distinct --- but independently calculated --- linear combinations simultaneously, right?

> Another thing would be to be able to set a `by` argument to get conditional contrasts.

That should be relatively easy. I'm just a bit annoyed at the inconsistency because we have `by` in all the other `summary`/`tidy` functions, but here it would probably have to go in `marginalmeans()` itself, rather than the `summary()` function. Not the most consistent interface, but probably not the worst either.

> Amazing work, I really don't know how to produce such polished stuff so fast...

Please don't tell the UdeM promotion committee I'm "wasting" all my time on this stuff 😅

**Comment by vincentarelbundock** [comment]
Note to self: Adding `by` to `c()` on this line of code should do everything magically: https://github.com/vincentarelbundock/marginaleffects/blob/main/R/marginalmeans.R#L265

**Comment by mattansb** [comment]
> Just to be sure, this would compute 2 distinct --- and independently calculated --- linear combinations simultaneously, right?

Exactly

> Please don't tell the UdeM promotion committee I'm "wasting" all my time on this stuff 😅

🤣🤣😂

**Comment by mattansb** [comment]
Love it!
Thanks!

**Comment by mattansb** [comment]
🤯🤯🤯
