### ISSUE TITLE
`lincom` everywhere

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/marginaleffects#366]
* [x] check on raw input
* [x] check on number of rows inside get_lincom
* [x] < > not allowed
* [x] x1 x2 collision with term names
* [x] check duplicate term names, means we have contrasts or unit-level estimates and we can't use those duplicate names in the lincom
* [x] Rename argument to `hypothesis`, since this is no longer just linear

**Comment by vincentarelbundock** [comment]
@bwiernik there is now preliminary support for linear combinations in the 4 core functions of this package, including `predictions()`. This works via the `lincom` argument. I would be very interested in feedback on:

1.  Missing features
2.  How to make the interface more user-friendly
3.  What labels would user expect for each row of the final dataset
4. Anything else, really.

First, we fit a model, create a dataset, and compute adjusted predictions for that dataset:

``` r
library(marginaleffects)
mod <- lm(mpg ~ hp + wt, mtcars)

nd <- data.frame(hp = c(110, 120, 140), wt = 3)
nd
#>    hp wt
#> 1 110  3
#> 2 120  3
#> 3 140  3

p <- predictions(mod, newdata = nd)
p
#>   rowid     type predicted std.error statistic p.value conf.low conf.high  hp wt mpg
#> 1     1 response  22.09875 0.5280390  41.85061       0 21.06382  23.13369 110  3   0
#> 2     2 response  21.78102 0.4934625  44.13917       0 20.81386  22.74819 120  3   0
#> 3     3 response  21.14557 0.4709423  44.90054       0 20.22254  22.06860 140  3   0
```

Linear combinations specified using string shortcuts (“pairwise” or “reference”):

``` r
predictions(mod, newdata = nd, lincom = "pairwise")
#>   rowid     type   term lincom  predicted std.error statistic      p.value   conf.low  conf.high  hp wt mpg
#> 1     1 response lincom  2 - 1 -0.3177295 0.0902971 -3.518712 0.0004336473 -0.4947085 -0.1407504 110  3   0
#> 2     2 response lincom  3 - 1 -0.9531884 0.2708913 -3.518712 0.0004336473 -1.4841256 -0.4222512 120  3   0
#> 3     3 response lincom  3 - 2 -0.6354589 0.1805942 -3.518712 0.0004336473 -0.9894171 -0.2815008 140  3   0

p$predicted[2] - p$predicted[1]
#> [1] -0.3177295
p$predicted[3] - p$predicted[1]
#> [1] -0.9531884
p$predicted[3] - p$predicted[2]
#> [1] -0.6354589
```

Linear combinations specified using vectors or matrices:

``` r
lc1 <- c(-1, 0, 1)

lc2 <- matrix(c(
    -1, 1, 0,
    -1, 0, 1,
    0, -1, 1),
    ncol = 3)

predictions(mod, newdata = nd, lincom = lc1)
#>       type   term lincom  predicted std.error statistic      p.value  conf.low  conf.high
#> 1 response lincom custom -0.9531884 0.2708913 -3.518712 0.0004336473 -1.484126 -0.4222512

predictions(mod, newdata = nd, lincom = lc2)
#>   rowid     type   term lincom  predicted std.error statistic      p.value   conf.low  conf.high  hp wt mpg
#> 1     1 response lincom custom -0.3177295 0.0902971 -3.518712 0.0004336473 -0.4947085 -0.1407504 110  3   0
#> 2     2 response lincom custom -0.9531884 0.2708913 -3.518712 0.0004336473 -1.4841256 -0.4222512 120  3   0
#> 3     3 response lincom custom -0.6354589 0.1805942 -3.518712 0.0004336473 -0.9894171 -0.2815008 140  3   0
```

**Comment by vincentarelbundock** [comment]
@grantmcdermott the nice thing about what I showed in the post above is that we can also take linear combinations of other types of estimates. Here’s a diff-in-diff style analysis, where we first use the `comparisons()` function to compute contrasts (already differences in y-hat), and then we take a linear combination of those contrasts.

I’d be particularly interested in your feedback on user interface and features. Do users expect some kind of formula interface to specify the linear combinations?

``` r
library(marginaleffects)
mod <- lm(mpg ~ factor(cyl), mtcars)

cmp <- comparisons(mod, newdata = "mean")
cmp
#>   rowid     type term contrast comparison std.error statistic      p.value   conf.low conf.high eps_tmp cyl
#> 1     1 response  cyl    6 - 4  -6.920779  1.558348 -4.441099 8.950043e-06  -9.975086 -3.866473      NA   8
#> 2     1 response  cyl    8 - 4 -11.563636  1.298623 -8.904534 5.361101e-19 -14.108892 -9.018381      NA   8

diff(cmp$comparison)
#> [1] -4.642857

comparisons(mod, newdata = "mean", lincom = "reference")
#>       type   term lincom comparison std.error statistic    p.value  conf.low conf.high
#> 1 response lincom  2 - 1  -4.642857  1.492005 -3.111825 0.00185935 -7.567133 -1.718581
```

**Comment by grantmcdermott** [comment]
@vincentarelbundock thanks for tagging me. I'm rushing where I should respond only after I've looked in more depth... But to help me understand the interface a little better, could you give me a quick example of how you'd replicate the following `car::lht` example:

```r
> fit = lm(mpg ~ disp + hp, mtcars)
> ## Test a (silly) HO: disp + hisp = 1
> car::lht(fit, 'disp + hp', rhs = 1, verbose = TRUE)

Hypothesis matrix:
          (Intercept) disp hp
disp + hp           0    1  1

Right-hand-side vector:
*rhs* 
    1 

Estimated linear function (hypothesis.matrix %*% coef - rhs)
disp + hp 
-1.055186 


Estimated variance of linear function
[1] 7.720948e-05

Linear hypothesis test

Hypothesis:
disp  + hp = 1

Model 1: restricted model
Model 2: mpg ~ disp + hp

  Res.Df    RSS Df Sum of Sq     F    Pr(>F)    
1     30 141255                                 
2     29    283  1    140972 14421 < 2.2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
```

PS. As an aside, I prefer the return object from `car:deltaMethod` (which also supports non-linear combinations is desired). It's annoying that these return objects are so different, but at least the test-as-a-character-string interface is the same. I mention this only since you ask about how users might specify the combinations.

```r
> car::deltaMethod(fit, 'disp + hp', rhs = 1)
            Estimate         SE      2.5 %     97.5 % Hypothesis z value  Pr(>|z|)    
disp + hp -0.0551864  0.0087869 -0.0724084 -0.0379644  1.0000000 -120.09 < 2.2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
```

**Comment by bwiernik** [comment]
Awesome! Where do the covariances for the predictions come from?

**Comment by vincentarelbundock** [comment]
> Awesome! Where do the covariances for the predictions come from?

When you just call plain `predictions()`, they come from `insight::get_predicted`. When you add the `lincom` argument, we have to apply the Delta Method directly to the final combination, and that is done in-house. So there is no back-transform, but you could for example, do predictions on the link scale with `type="link"` and then use `transform_post`.

**Comment by vincentarelbundock** [comment]
Also, you can use sandwich varcov with the `vcov` argument, and they will be applied here automatically.

**Comment by vincentarelbundock** [comment]
@grantmcdermott, there is currently no way to specify a RHS numeric value, but it would be trivial to implement.

To specify combinations, you can submit a vector or matrix similar to what we see in the “Hypothesis matrix” section of the printout of `car::lht` when `verbose=TRUE`.

Note that I set `newdata="mean"` to compute combinations of “marginal effects at the mean”. This doesn’t matter for the linear model but would in GLM and elsewhere.

The nice thing is we get linearHypothesis for 60+ models automatically now :)

Examples:

``` r
library(marginaleffects)
library(parameters)
fit = lm(mpg ~ disp + hp + drat, mtcars)

# car::lht(fit, 'disp - hp = 0', verbose = TRUE)
marginaleffects(
    fit,
    newdata = "mean",
    lincom = c(1, -1, 0))
#>       type   term       dydx  std.error statistic  p.value    conf.low
#> 1 response lincom 0.01199709 0.02129995 0.5632451 0.573268 -0.02975004
#>    conf.high lincom
#> 1 0.05374423 custom

# car::lht(fit, '2 * disp - hp + 4 * drat = 0', verbose = TRUE)
marginaleffects(
    fit,
    newdata = "mean",
    lincom = c(2, -1, 4))
#>       type   term     dydx std.error statistic    p.value   conf.low
#> 1 response lincom 10.85267  5.965193  1.819332 0.06886082 -0.8388978
#>   conf.high lincom
#> 1  22.54423 custom
```

**Comment by vincentarelbundock** [comment]
I renamed the argument `hypothesis` because it supports non-linear hypothesis tests as well. There is now a vignette which touches on everything we’ve talked about so far:

<https://vincentarelbundock.github.io/marginaleffects/articles/hypothesis.html>

The vignette shows silly stuff like this comparison between marginal effects at the mean:

``` r
library(marginaleffects)
mod <- lm(mpg ~ am + vs, data = mtcars)

marginaleffects(
    mod,
    newdata = "mean",
    hypothesis = "exp(am) - 2 * vs = -400")
#>       type       term        hypothesis     dydx std.error statistic   p.value
#> 1 response hypothesis exp(am)-2*vs=-400 817.3821  550.2221  1.485549 0.1373984
#>    conf.low conf.high
#> 1 -261.0335  1895.798
```

Thanks @grantmcdermott and @bwiernik for nudging me in this direction. I think this is a super cool feature.

I’ll close this issue, but don’t hesitate to keep the conversation going if you have suggestions about the user interface or additional feature request.

**Comment by grantmcdermott** [comment]
Awesome! 

Not sure I contributed much. But I think the new hypothesis interface is really intuitive. Dig it, mate. `marginaleffects` just keeps getting better and better...

**Comment by vincentarelbundock** [comment]
> @vincentarelbundock I'm curious how the delta method computation of covariances works. Could you point me to the relevant spot in the code?

I describe the procedure here: https://vincentarelbundock.github.io/marginaleffects/articles/sandwich.html#delta-method

* Jacobian construction: https://github.com/vincentarelbundock/marginaleffects/blob/main/R/get_jacobian.R
* Main delta method function: https://github.com/vincentarelbundock/marginaleffects/blob/main/R/get_se_delta.R
* `inner` function: https://github.com/vincentarelbundock/marginaleffects/blob/main/R/get_se_delta.R#L79

The key part happens in the `inner` function, where we modify the coefficients held in the model object by a tiny epsilon, and use that that new model compute a new vector of quantities (predictions, contrasts, lin-com, whatever). That allows us to build the Jacobian we need (derivatives of the vector-valued quantity of interest with respect to each of the parameters of the model).
