### ISSUE TITLE
Documentation: Definition of "Adjusted Prediction"

### ISSUE THREAD

**Issue by isabellaghement** [vincentarelbundock/marginaleffects#370]
Hi Vincent, 

In your tweet https://twitter.com/VincentAB/status/1535104451786248197, you shared the current definition of _"Adjusted Prediction"_ used in the **marginaleffects** package:

![image](https://user-images.githubusercontent.com/57458528/173112738-c0a1a174-868c-4924-9912-9022e7ced597.png)

I promised to provide you with some suggestions for how to make the definition clearer.  Please see below and let me know what you think after adding your own touches:

In the context of the **marginaleffects** package, an "Adjusted Prediction" is a predicted value derived from the fitted regression model on a specified scale for a given combination of values of the predictor variables (or regressors) included in the model.   Here, the word "Adjusted" simply means "model-derived" or "model-based".  We can compute "Adjusted Prediction" values from regression models which include either a single predictor variable or multiple predictor variables. 

The specified scale refers to either the scale used to estimate the model (i.e., link scale) or to a more interpretable scale (e.g., response scale).  For example, when fitting a linear regression model using the lm() function, the link scale and the response scale are identical (since this model uses a gaussian family and an identity link function) and an "Adjusted Prediction" computed on either scale will be expressed as the mean value of the response variable at the given values of the predictor variables.  On the other hand, when fitting a binary logistic regression model using the glm() function (which uses a binomial family and a logit link ), the link scale and the response scale will be different:  an "Adjusted Prediction" computed on the link scale will be expressed as a log odds of a "successful" response at the given values of the predictor variables, whereas an "Adjusted Prediction" computed on the response scale will be expressed as a probability of a "successful" response at the given values of the predictor variables.  ("Successful" response corresponds to the binary response variable taking the value 1 rather than 0.) 

In calculating an "Adjusted Prediction",  we can set the value of a predictor variable in accordance to the type of that predictor variable.  If the predictor is continuous/discrete, we can set its value to (i) its mean/median value observed in the data, (ii) one of its observed values, (iii) a reference value of substantive interest, which falls within the range of observed values.  If the predictor is nominal/ordinal, we can set its value to any of the levels of that predictor or to its most frequent level, etc.  If the predictor is binary (i.e., it only takes the values 0 or 1), we can set its value to quantities such as: 0; 1; the proportion of 1's observed in the data. 

When we specify the values of the predictor variables for which we wish to compute an "Adjusted Prediction", we create a so-called "reference grid".  As an example, if our model is a linear model fitted with the lm() function which relates the response variable Happiness with the predictor variables Age, Gender and Income, the reference grid will consist of values for Age, Gender and Income for which we wish to derive the "Adjusted Prediction" of Happiness:  Age = 40, Gender = Male, Income = 60000.  The "reference grid" may or may not correspond to actual observations in the dataset used to fit the model (e.g., Age = 40 mat be the mean age observed in the data, though no particular subject included in the dataset happened to have an age of 40).   Note that it is possible for a "reference grid" to contain more than one particular combination of values for the predictor variables in the model:  Age = 40, Gender = Male, Income = 60000;  Age = 40, Gender = Female, Income = 60000;  Age = 40, Gender = Other, Income = 60000.  Such grid allows us to simultaneously compute "Adjusted Prediction" values for various relevant combinations of predictor values of interest. 

Thanks very much for considering this refinement to the documentation of your fabulous package.   

Isabella Ghement  (Twitter Handle: @IsabellaGhement)

**Comment by nxskok** [comment]
in here: 
> when fitting a binary logistic regression model using the glm() function (which uses a binomial family and an identity link ), 

this should read "logit link".

I think it's also worth stressing that the default link for any of these other models is "response", so that by default the user gets predicted probabilities, Poisson means etc.

A tangent: I was playing a few days ago with predictions from MASS::polr and nnet::multinom models, and they don't have "response" as one of the options to "type" (the option has to be "probs").

A second tangent: in regression, the intervals that come from marginaleffects are confidence intervals for the mean response. predict.lm also gives prediction intervals (interval = "p") for the response for a single observation, but I couldn't persuade marginaleffects to give me the latter.

My tangents are random observations from "kicking the wheels" on marginaleffects for use in teaching my courses next year. I'd have to think about them some more to clarify them into issues that can be worked on (if that is desired).

Ken Butler (@kenbutler12)

**Comment by isabellaghement** [comment]
Thanks for your comments, Ken (aka @kenbutler12)!  Good catch on the logit link - it was a copy and paste error.  I'll digest your other comments later (possibly tomorrow) and see if I can weave them into the narrative I provided.

**Comment by vincentarelbundock** [comment]
@isabellaghement thanks so much for putting this together! Ping me when you are "done" with the text and I will add it to the vignette.

@nxskok thanks for helping out with the text. 

You're right, there is no "response" type available for `MASS::polr` models. I have decided to remain faithful to the names used by the `type` arguments provided by each package's `predict()` method. The upside is that users who are used to calling `predict()` do not have anything new to learn. The downside is that type names are inconsistent across packages. (Also, harmonizing the different quantities' names would be a nightmare, and I absolutely want to avoid endless debates about how to call different quantities in hurdle models, etc.)

You're right, there is currently no support for prediction intervals. It would be relatively easy to add support in the `predictions()` function for basic GLM models, but extending to `marginaleffects()` and other models would likely be a *lot* of work. If there is a lot of demand for that, I might invest some. Would also consider pull request if someone comes by with motivation.

**Comment by vincentarelbundock** [comment]
Thanks all (and especially @isabellaghement). I have update the website: https://vincentarelbundock.github.io/marginaleffects/articles/mfx01_predictions.html
