### ISSUE TITLE
plot_coo()

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/marginaleffects#371]

**Comment by arthur-albuquerque** [comment]
Thank you for opening this, Vincent. Here is the [Twitter thread ](https://twitter.com/vincentab/status/1535398734095437825?s=21) that led to the discussion about plotting conditional contrasts (for future reference).

These plots are very common in medical research (my area). As far I can remember, the most common conditional contrasts are:

- Risk Difference
- Odds Ratio
- Risk Ratio
- Incidence Rate Ratio
- Hazard Ratio
- ...?

**Comment by vincentarelbundock** [comment]
The `plot_cco()` function is now merged in the main development branch. See here for an example plotting ratios and differences:

https://vincentarelbundock.github.io/marginaleffects/articles/transformation.html#custom-contrasts-with-transform_pre-ratios

**Comment by arthur-albuquerque** [comment]
Truly amazing, thank you, Vincent!

One question: what happens to other covariates in the model? Are they fixed at a mean/mode value as in `plot_cme()`? Is there any way to set a specific value? I tried setting the `newdata` within `plot_cco()` without success.

**Comment by vincentarelbundock** [comment]
Yes, control variables are held at their mean or mode.

There currently is no way to specify that. But frankly, it's so easy to call `comparisons()` and feed the results into `ggplot2`, that I'm not sure it's worth investing a ton in customization. 

But I'd be willing to be convinced otherwise if there are compelling features.

**Comment by arthur-albuquerque** [comment]
Thanks! Well, that's really up to you. I have asked too much already haha

One quick suggestion would be to explicitly state that "control variables are held at their mean or mode" in `plot_cme`, `plot_cco`, and `plot_cap` documentation pages.

**Comment by vincentarelbundock** [comment]
Agreed! I improved the documentation here: 4f5b985

**Comment by arthur-albuquerque** [comment]
Thanks! P.S: Sentences seem duplicated in `plot_cap`.

**Comment by vincentarelbundock** [comment]
Thanks for the close read @arthur-albuquerque ! I fixed the duplication in docs.
