### ISSUE TITLE
Expose a generic `delta_method` function

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/marginaleffects#375]
https://stackoverflow.com/questions/72632827/delta-method-for-fixed-effects-regression-using-feols-function#72632827

**Comment by vincentarelbundock** [comment]
@grantmcdermott, [the development version of `marginaleffects`](https://vincentarelbundock.github.io/marginaleffects/#getting-started) now includes a flexible function called `deltamethod()` which can be used to compute estimate and standard errors of functions of model parameters. `deltamethod()` emulates the behavior of the excellent and well-established `car::deltaMethod` and `car::linearHypothesis` functions, but it supports more models, requires fewer dependencies (`car` has > 80!), and offers some convenience features like shortcuts for robust standard errors.

Let me know if you get a chance to try it and run into issues or have ideas for more features.

``` r
library(car)
library(marginaleffects)
mod <- lm(mpg ~ hp + wt + factor(cyl), data = mtcars)
```

When `FUN` and `hypothesis` are `NULL`, `deltamethod()` returns a data.frame of raw estimates:

``` r
deltamethod(mod)
#>           term       value
#> 1  (Intercept) 35.84599532
#> 2           hp -0.02311981
#> 3           wt -3.18140405
#> 4 factor(cyl)6 -3.35902490
#> 5 factor(cyl)8 -3.18588444
```

Test of equality between coefficients:

``` r
deltamethod(mod, "hp = wt")
#>   hypothesis estimate std.error statistic      p.value conf.low conf.high
#> 1    hp = wt 3.158284 0.7199081  4.387066 1.148899e-05  1.74729  4.569278
```

Non-linear function of coefficients

``` r
deltamethod(mod, "exp(hp + wt) = 0.1")
#>           hypothesis    estimate  std.error statistic    p.value
#> 1 exp(hp + wt) = 0.1 -0.05942178 0.02919718 -2.035189 0.04183184
#>     conf.low    conf.high
#> 1 -0.1166472 -0.002196363
```

The `vcov` argument behaves in the same was as in the `marginaleffects()` function. It allows us to easily compute robust standard errors:

``` r
deltamethod(mod, "hp = wt", vcov = "HC3")
#>   hypothesis estimate std.error statistic      p.value conf.low conf.high
#> 1    hp = wt 3.158284 0.8051929  3.922394 8.767334e-05 1.580135  4.736433
```

We can use shortcuts like `r1`, `r2`, `...` to identify the position of each parameter in the output of `FUN`. For example, `r2=r3` is equivalent to `hp=wt` because those term names appear in the 2nd and 3rd row when we call `deltamethod(mod)`.

``` r
deltamethod(mod, "r2 = r3")
#>   hypothesis estimate std.error statistic      p.value conf.low conf.high
#> 1    r2 = r3 3.158284 0.7199081  4.387066 1.148899e-05  1.74729  4.569278
```

Term names with special characters must be enclosed in backticks:

``` r
deltamethod(mod, "`factor(cyl)6` = `factor(cyl)8`")
#>                        hypothesis   estimate std.error  statistic
#> 1 `factor(cyl)6` = `factor(cyl)8` -0.1731405  1.653923 -0.1046847
#>    p.value conf.low conf.high
#> 1 0.916626 -3.41477   3.06849
```

The `FUN` argument can be used to compute standard errors for arbitrary functions of model parameters. This user-supplied function must accept single model object and return a numeric vector or a data.frame with two columns named `term` and `value`.

``` r
mod <- glm(am ~ hp + mpg, data = mtcars, family = binomial)

f <- function(x) predict(x, type = "link", newdata = mtcars)
p <- deltamethod(mod, FUN = f)
head(p)
#>   rowid   estimate std.error  statistic    p.value  conf.low  conf.high
#> 1     1 -1.0983601 0.7160423 -1.5339319 0.12504640 -2.501777  0.3050570
#> 2     2 -1.0983601 0.7160423 -1.5339319 0.12504640 -2.501777  0.3050570
#> 3     3  0.2331884 0.7808207  0.2986452 0.76521076 -1.297192  1.7635688
#> 4     4 -0.5945143 0.6471012 -0.9187346 0.35823441 -1.862809  0.6737808
#> 5     5 -0.4175761 0.6474633 -0.6449417 0.51896494 -1.686581  0.8514287
#> 6     6 -5.0264654 2.1949096 -2.2900558 0.02201808 -9.328409 -0.7245217
```

Test of equality between two predictions (row 2 vs row 1):

``` r
f <- function(x) predict(x, newdata = mtcars)
deltamethod(mod, FUN = f, hypothesis = "r2 = r3")
#>   hypothesis  estimate std.error statistic    p.value  conf.low
#> 1    r2 = r3 -1.331548 0.6155513  -2.16318 0.03052731 -2.538007
#>    conf.high
#> 1 -0.1250901
```

Note that we specified the `newdata` argument in the `f` function. This is because the `predict()` method associated with `lm` objects will automatically the original fitted values when `newdata` is `NULL`, instead of returning the slightly altered fitted values which we need to compute numerical derivatives in the delta method.

**Comment by grantmcdermott** [comment]
@vincentarelbundock this is fantastic! 

I've been kicking the tyres in a few different directions and everything seems to be working great. Here are two things you might want to think about, though:

1. I like the `r1`, `r2`, etc. idea. But for mnemonic value I'd be tempted to use `_b[1], _b[2]`,... This is what both Stata and some other R packages like `nlwaldtest` use, so it might be the natural reach for a lot of people. (Examples [here](https://stata2r.github.io/extras/#multcomp-nlwaldtest).) To be clear, I much prefer writing the actual coefficient names and don't think I'd use these shortcuts much personally. But the potential benefit of familiarity is worth thinking about.

2. I just tried replicating the example I walked through over [here](https://github.com/lrberge/fixest/issues/279#issuecomment-1066044637)&mdash;i.e. aggregating post treatment periods in a DiD model&mdash;and it works perfectly. However, I could imagine wanting to export it in a regression table and couldn't see a way to do that.

``` r
# Note: I'm using the latest dev version of all these packages
library(fixest)
library(marginaleffects)
library(modelsummary)

est = feols(y ~ x1 + i(period, treat, 5) | id + period, base_did)
(poststring = dsb(".['`period::|:treat`'a, ' + 'c!.[6:10]] = 0"))
#> `period::6:treat` + `period::7:treat` + `period::8:treat` + `period::9:treat` + `period::10:treat` = 0

## Aggregating post treatment effects works just fine
est_post = deltamethod(est, poststring) |> within({term = "Post treatment"})
est_post
#>             term estimate std.error statistic     p.value conf.low conf.high
#> 1 Post treatment 19.53277  4.299288  4.543257 5.53916e-06 11.10632  27.95922

## How to put in a regression table?
modelsummary(est_post)
#> Objects of class 'NULL' are currently not supported.
#> Error: $ operator is invalid for atomic vectors
```

<sup>Created on 2022-06-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

As an side, the equivalent `marginaleffects(..., hypothesis = ...)` version doesn't appear to be working here.

```r
marginaleffects(
  est,
  newdata = "mean",
  hypothesis = poststring
  )
#> Warning: Some cluster or group identifiers are numeric. Unless otherwise
#> instructed, `datagrid()` sets all numeric variables to their mean. This is
#> probably inappropriate in the case of cluster or group identifiers. A safer
#> strategy is to convert them to factors before fitting the model.
#> Error: 
#> Unable to compute adjusted predictions for this model. Either the
#> `newdata` does not meet the requirements of the model's `predict()`
#> method, or this model is not supported. If you believe this model
#> should be supported, you can file a report on the Github Issue Tracker:
#> https://github.com/vincentarelbundock/marginaleffects/issues
#>  
#> 
#> In addition: Error: Unable to extract predictions from a model of type `fixest`. Please report this problem, along with replicable code, on the `marginaleffects` issue tracker: https://github.com/vincentarelbundock/marginaleffects/issues
```

<sup>Created on 2022-06-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by grantmcdermott** [comment]
PS. I know that you've got a few "hidden" vignettes. But I'd advocated for the new [Hypothesis testing](https://vincentarelbundock.github.io/marginaleffects/articles/hypothesis.html) article to get a top link  on the main page once you've finalised these functions.

**Comment by grantmcdermott** [comment]
Sorry, I just encountered another error. Continuing with `est` example in point 2 above, the `vcov` argument doesn't appear to be working for me. 

``` r
## No vcov: works
deltamethod(est, poststring)
#>                                                                                                     term
#> 1 `period::6:treat` + `period::7:treat` + `period::8:treat` + `period::9:treat` + `period::10:treat` = 0
#>   estimate std.error statistic     p.value conf.low conf.high
#> 1 19.53277  4.299288  4.543257 5.53916e-06 11.10632  27.95922

## vcov = lowercase complains (can we make these case insensitive like modelsummary?)
deltamethod(est, poststring, vcov = "hc1")
#> Error: Assertion failed. One of the following must apply:
#>  * checkmate::check_null(vcov): Must be NULL
#>  * checkmate::check_function(vcov): Must be a function, not 'character'
#>  * checkmate::check_matrix(vcov): Must be of type 'matrix', not
#>  * 'character'
#>  * checkmate::check_formula(vcov): Must be a formula, not character
#>  * checkmate::check_choice(vcov): Must be element of set
#>  * {'stata','robust','HC','HC0','HC1','HC2','HC3','HC4','HC4m','HC5','HAC','NeweyWest','kernHAC','OPG','satterthwaite','kenward-roger'},
#>  * but is 'hc1'

# vcov = UPPERCASE. still trigger an error.
deltamethod(est, poststring, vcov = "HC1")
#> Warning: Model matrix is rank deficient. Some variance-covariance parameters are
#>   missing.
#> Error in if (ncol(J) == ncol(V)) {: argument is of length zero
```

**Comment by vincentarelbundock** [comment]
Here’s a fun concise way to compute the same linear combination you did (using the very very latest dev):

``` r
library(fixest)
library(marginaleffects)

est <- feols(y ~ x1 + i(period, treat, 5) | id + period, base_did)

hyp <- as.numeric(1:10 %in% 6:10)
deltamethod(est, hypothesis = hyp)
#>     term estimate std.error statistic     p.value conf.low
#> 1 custom 19.53277  4.299288  4.543257 5.53916e-06 11.10632
#>   conf.high
#> 1  27.95922

hyp = dsb(".['`period::|:treat`'a, ' + 'c!.[6:10]] = 0")
deltamethod(est, hypothesis = hyp)
#>                                                                                                     term
#> 1 `period::6:treat` + `period::7:treat` + `period::8:treat` + `period::9:treat` + `period::10:treat` = 0
#>   estimate std.error statistic     p.value conf.low conf.high
#> 1 19.53277  4.299288  4.543257 5.53916e-06 11.10632  27.95922
```

The error in your last post is because `sandwich` breaks. It would be good if `deltamethod` failed more gracefully in those cases.

``` r
sandwich::vcovHC(est)
#> Error in 1 - diaghat: non-numeric argument to binary operator
```

I opened separate issues for each feature or bug.

<https://github.com/vincentarelbundock/marginaleffects/issues/381>

<https://github.com/vincentarelbundock/marginaleffects/issues/380>

<https://github.com/vincentarelbundock/marginaleffects/issues/379>

<https://github.com/vincentarelbundock/marginaleffects/issues/382>

**Comment by grantmcdermott** [comment]
Oh very nice.

I've been asked about this functionality (i.e. aggregating post-treatment periods) a fair bit. So will submit a PR to fixest suggesting this as a recommended solution in the intro vignette once you've pushed the next CRAN release.

I wrote up a little function that does it automatically, including picking out the right reference period. But I'm not sure where the right place for it is. Maybe a case study in the hypothesis vignette ;-)

```r
did_postagg = function(object, rhs = 0, ...) {
  fixest_obj = inherits(object, c('fixest', 'fixest_multi'))
  if (!fixest_obj) stop("Please provide a valid fixest object.")
  mm = object$model_matrix_info[[1]]
  if (is.null(mm)) stop ("This function only works with fixest objects that were ",
                         "created with the i() operator. See `?fixest::i()`.")
  coefs = mm$coef_names_full
  ref_id = mm$ref_id
  coefs_post = coefs[(ref_id+1):length(coefs)]
  post_string = paste(paste(paste0("`", coefs_post, "`"), collapse = " + "), 
                      "=", rhs)
  ret = marginaleffects::deltamethod(object, post_string, ...)
  ret$term = "Post treatment (aggregate)"
  attr(ret, "coefs_post") = coefs_post
  attr(ret, "post_string") = post_string
  return(ret)
}

did_postagg(est)
#>                         term estimate std.error statistic     p.value conf.low conf.high
#> 1 Post treatment (aggregate) 19.53277  4.299288  4.543257 5.53916e-06 11.10632  27.95922
```
