### ISSUE TITLE
Bias adjustment

### ISSUE THREAD

**Issue by strengejacke** [vincentarelbundock/marginaleffects#388]
See https://github.com/easystats/modelbased/issues/57
Would be cool to have such a feature (if it's no yet implemented?)

**Comment by vincentarelbundock** [comment]
That's interesting. In marginal effects, the 4 core functions and quantities are: `marginaleffects`, `comparisons`, `predictions`, and `marginalmeans`.

In general, we can't really do back-transformations on contrasts or marginal effects: https://github.com/vincentarelbundock/marginaleffects/issues/390

In `predictions()` the back transformations are delegated to `insight::get_predicted`, so we would have to implement it there.

I guess that means that the bias correction could only potentially be implemented in the `marginalmeans()` function. In that context, I think it would be very easy to pass a function to the `transform_post` argument: https://vincentarelbundock.github.io/marginaleffects/reference/marginalmeans.html

Any function supplied to this argument will be applied to the estimates and confidence intervals at the very end of the computation process, which I guess is what we need here. We could also possibly include a string shortcut like `transform_post="whatever"` to make things easier for the user.

Frankly, I'm not sure I'm expert enough in this bias correction to implement it correctly. But I'm definitely open to the idea.

**Comment by strengejacke** [comment]
> Frankly, I'm not sure I'm expert enough in this bias correction to implement it correctly

Damn, that was the main reason I opened an issue here... 😉

**Comment by vincentarelbundock** [comment]
Will be happy to continue the conversation if someone has an idea for how to implement this in `marginaleffects`, but since I don't have the knowledge, I'm unlikely to do this myself. So going to close the issue to keep things tidy in the repo, but feel free to re-open or keep the conversation going if you have thoughts.
