### ISSUE TITLE
Backtransforming hurdle lognormal with log predictor

### ISSUE THREAD

**Issue by tklebel** [vincentarelbundock/marginaleffects#389]
Hi Vincent!

Thank you for the very helpful vignette on [Transformations](https://vincentarelbundock.github.io/marginaleffects/articles/transformation.html#back-transform-lognormal-hurdle). I have been working on a model using the `hurdle_lognormal()` family with a logged and centred predictor, and have been struggling to find a good way to communicate results. I'd really like to use some version of marginal effects, but I'm not sure how to adapt the code at the bottom of the mentioned vignette. Explaining how to deal with logged predictors could be a useful extentions there (or maybe I'm just missing something completely).

Assume the following alteration of the example, i.e., a logged and scaled predictor: 
```r
gapminder2 <- gapminder %>%
  mutate(lifeExp = scale(log(lifeExp), scale = FALSE))

mod2 <- brm(
  bf(gdpPercap0 ~ lifeExp,
     hu ~ lifeExp),
  data = gapminder2,
  family = hurdle_lognormal(),
  chains = 4, cores = 4, seed = 1234)
```

I can visualise the effect of `log(lifeExp)` simply using the code you provided: 
<details>
  <summary>Click to expand!</summary>
  
```r
predictions_data <- predictions(
  mod,
  newdata = datagrid(lifeExp = seq(-1, .5, .1)),
  dpar = "mu",
  transform_post = exp
)

slopes_data <- comparisons(
  mod,
  dpar = "mu",
  variables = list(lifeExp = eps),
  newdata = datagrid(lifeExp = seq(-1, .5, .1)),
  transform_pre = function(hi, lo) ((exp(hi) - exp(lo)) / exp(eps)) / eps
) %>% 
  left_join(predictions_data, by = "lifeExp") %>%
  # Point-slope formula: (y - y1) = m(x - x1)
  mutate(intercept = comparison * (-lifeExp) + predicted)

ggplot(predictions_data, aes(x = lifeExp, y = predicted)) +
  geom_line(size = 1) + 
  geom_abline(data = slopes_data, aes(slope = comparison, intercept = intercept), 
              size = 0.5, color = "red") +
  geom_point(data = slopes_data) +
  geom_label(data = slopes_data, aes(label = paste0("Slope: ", round(comparison, 1))),
             nudge_x = -1, hjust = 1) +
  theme_minimal()
```
</details>

While back-transforming the exposure for the predictions is trivial (by adding the centering offset and exponentiating after `predictions()` is run), I do not know how one would do the same for the comparisons. I have tried changing the function for `transform_pre`, but without success.

I know of the %/% interpretation of the log-log model, I just imagine it might be easier for some readers to grasp the impact if I could back-transform it to the original scales, and do this at different levels of the predictor.

p.s.: If you don't have the bandwidth to answer here and/or don't think this would be a useful addition to the vignette, please let me know.

**Comment by tklebel** [comment]
Thanks for the linked issue, that clarifies some of the issues. I'm happy with the answer that it simply might be impossible, and will likely work with predictions instead.

After some thought and further tinkering, I'd also say that in any case, the %/% interpretation (for 1% change in x, y changes beta %) is probably the more meaningful for these scenarios - this is the reason why I'm modeling it with log/log in the first place. 

In particular, for the case of a simple log/log model as above, the slope (in terms of percentages) does not change, and therefore the output for the following is the same regardless of `lifeExp`. It is also very close to the fixed effect from the model (disregarding the different scales).

```r
comparisons(
  mod2,
  dpar = "mu",
  variables = list(lifeExp = .01),
  newdata = datagrid(lifeExp = seq(-1, .5, .5)),
  type = "link"
)
#>   rowid type    term       contrast comparison   conf.low  conf.high lifeExp
#> 1     1 link lifeExp (x + 0.01) - x 0.04245472 0.04079028 0.04410129    -1.0
#> 2     2 link lifeExp (x + 0.01) - x 0.04245472 0.04079028 0.04410129    -0.5
#> 3     3 link lifeExp (x + 0.01) - x 0.04245472 0.04079028 0.04410129     0.0
#> 4     4 link lifeExp (x + 0.01) - x 0.04245472 0.04079028 0.04410129     0.5

fixef(mod2)
#>               Estimate  Est.Error      Q2.5     Q97.5
#> Intercept     8.126512 0.01991099  8.091438  8.162326
#> hu_Intercept -2.618836 0.11407821 -2.845189 -2.428241
#> lifeExp       4.242482 0.08621951  4.079028  4.410129 <<--
#> hu_lifeExp   -4.798262 0.41223271 -5.634484 -4.080870
```

If the model had further non-linear terms or interactions, then `comparison` might be helpful, since it would (as far as I understand it), compute the slope (in terms of %/%) at the specified locations.

**Comment by vincentarelbundock** [comment]
thanks for coming back with the details. This was interesting. Feel free to keep commenting or to open an new issue if you think something else should change in `marginaleffects`
