### ISSUE TITLE
brglm2::bracl plot support

### ISSUE THREAD

**Issue by Jyasmeen** [vincentarelbundock/marginaleffects#391]
Thank you for the very good package. I have tried to work with marginal effects and adjusted predictions and it works perfectly. But need a little more for good graphs.

Since the outcome variable in bracl() models are multi-group, it needs a graph to show marginal effects, adjusted predictions etc. for each group in a separate facet in the graph. 

The options "facet" and "connect.lines" from ggplot are not supported for bracl() models. Please add this support in plot_cap() , plot_cme() and plot_cco(). 

Thank you

**Comment by vincentarelbundock** [comment]
Hi,

I don't know what you mean by "connect.lines". Can you give me a *minimal* and *working* example with publicly available data of `connect.lines` working in a simple `lm()` model?

Facets for grouped outcomes are already supported. See the `multinom` example in this section of the vignette: https://vincentarelbundock.github.io/marginaleffects/articles/predictions.html#conditional-adjusted-predictions-plot

**Comment by Jyasmeen** [comment]
Hello,

Thank you for your quick response.  Yes, I got it but the
"plot(connect.lines = TRUE)" does not connect the dots as attached in the
graph produced.

I would like to produce a Stata like graph which is a visually more
attractive presentation.

Here is a reproducible example:

> data("stemcell", package = "brglm2")
> # Adjacent category logit (non-proportional odds)
> fit_bracl <- bracl(research ~ religion + gender, weights = frequency,
data = stemcell, type = "ML")
> plot_cap(fit_bracl, condition = c("religion", "gender"), type = "probs")
%>% plot(connect.lines = TRUE) + facet_wrap(~group)


When I run the code of plot_cap() for bracl() as below, I get an error
message:

> plot_cap(fit_bracl, condition = c("religion", "gender"), type = "probs",
connect.lines = TRUE) + facet_wrap(~group)
Warning message:
These arguments are not supported for models of class `bracl`:
connect.lines. Please file a request on Github if you believe that
additional arguments should be supported:
https://github.com/vincentarelbundock/marginaleffects/issues

I hope it has clarified what I requested.

Again thank you for the prompt response.

Best regards,
Yasmeen Jamali
Doctorante en Démographie à l'IDUP

**Comment by vincentarelbundock** [comment]
`connect.lines` is not a formal argument of the function, and it is not mentioned anywhere in the package documentation or on the website. So of course it doesn't work.

However, `plot_cap()` produced a standard ˋggplot2` object, so you should be able to customize it infinitely. For example, you will probably get something like what you are looking for by adding `+geom_line()` at the end of your call.

**Comment by vincentarelbundock** [comment]
J'espère que ça fonctionnera. Faites-moi signe si geom_line() ne donne pas le résultat attendu.
