### ISSUE TITLE
Failure to calculate marginal effects for clogit() model from survival package

### ISSUE THREAD

**Issue by csthiago** [vincentarelbundock/marginaleffects#395]
Hey Vincent,

Thanks for the package! I am currently running a conditional logistic model. I am trying to get marginal effects and comparisons, However, it doesn't work in the clogit.

Here is an example
```
pacman::p_load(marginaleffects,survival)
N  <- 100000
ng <- 50000

exd <-data.frame(
  g=rep(1:ng, each = N/ng),
  out=rep(0L:1L,N/2),
  x=sample(0L:1L, N/2, prob = c(.8, .2),
           replace = TRUE))


  mod <- clogit(out ~ x + strata(g),
                method="exact",
                data = exd)

  marginaleffects::marginaleffects(mod) 
  marginaleffects::comparisons(mod) 
```

>   marginaleffects::marginaleffects(mod)  
Error: 
Unable to compute adjusted predictions for this model. Either the
`newdata` does not meet the requirements of the model's `predict()`
method, or this model is not supported. If you believe this model
should be supported, you can file a report on the Github Issue Tracker:
https://github.com/vincentarelbundock/marginaleffects/issues
In addition: Error in match.arg(type): 'arg' should be one of “lp”, “risk”, “expected”, “terms”, “survival”

In other dataset, the message error is different:
>Error in data.table::rbindlist(rep(list(newdata), nrow(levs_idx))) : 
  Column 1 of item 1 is length 1181302 inconsistent with column 3 which is length 2362604. Only length-1 columns are recycled.
In addition: Warning messages:
1: In data.table::setDT(newdata) :
  Some columns are a multi-column type (such as a matrix column): [3]. setDT will retain these columns as-is but subsequent operations like grouping and joining may fail. Please consider as.data.table() instead which will create a new column for each embedded column.
2: In setDT(ans, key = key) :
  Some columns are a multi-column type (such as a matrix column): [3]. setDT will retain these columns as-is but subsequent operations like grouping and joining may fail. Please consider as.data.table() instead which will create a new column for each embedded column.
  
 
 Thanks again!

**Comment by vincentarelbundock** [comment]
Thanks for the feature request. Could you install the package from Github, restart R and try again?

**Comment by csthiago** [comment]
Hi.
I was able to run. (Thanks!). However, I get one estimate for each stratum (I don't know if it is the expected behaviour)

**Comment by vincentarelbundock** [comment]
By default, `marginaleffects` returns one marginal effect estimate for every row of the original dataset, because marginal effects are unit-level quantity. Is this what you mean? If so, you can use `tidy()` or `summary()` to compute "average marginal effects", as described in the vignette: https://vincentarelbundock.github.io/marginaleffects/articles/marginaleffects.html

**Comment by csthiago** [comment]
Yes. Everything is alright then. Thanks
