### ISSUE TITLE
fixest::fenegbin

### ISSUE THREAD

**Issue by bberger94** [vincentarelbundock/marginaleffects#398]
Would it be possible to support negative binomial regression in fixest?

```
library(fixest)
library(marginaleffects)

fit <- fenegbin(Solar.R ~ Wind + Temp,
                airquality)

marginaleffects(fit)
```

**Comment by jamesthesnake** [comment]
Good job!

**Comment by bberger94** [comment]
Works for me. Thanks!

**Comment by StarryCatte** [comment]
I‘m using hypotheses() function in marginaleffects package to test whether there is significant difference between two coefficients. The regression was estimated using fenegbin() function, but I recieved two warnings:
1. In names(model[["coefficients"]]) == names(coefs) : longer object length is not a multiple of shorter object length
2. Package `fixest` is installed, but package version `0.11.2` is required.
What's wrong with it?

**Comment by vincentarelbundock** [comment]
@StarryCatte Could you supply a minimal reproducible example?

**Comment by StarryCatte** [comment]
> @StarryCatte Could you supply a minimal reproducible example?

Here is a data demo:
[test.csv](https://github.com/vincentarelbundock/marginaleffects/files/13561130/test.csv)
And my code and warnings:
`data <- fread(path)
 data$Design <- as.factor(data$Design)
 data$Design <- relevel(data$Design, ref = "BT_PET")`
`model <- fenegbin(diff_live_enter_cnt~Design+diff_show_cnt+diff_click_cnt+t,data=data,vcov=~Design)`
`hypotheses(model, 'DesignBT_BEAUTY=DesignKOL_BEAUTY')`
<img width="457" alt="1701785227(1)" src="https://github.com/vincentarelbundock/marginaleffects/assets/97103878/472382e7-b2fa-45ed-a190-458f684a2a2e">

**Comment by StarryCatte** [comment]
Is that why the warning occurred？
<img width="304" alt="1701833045(1)" src="https://github.com/vincentarelbundock/marginaleffects/assets/97103878/4c71f9cf-97dd-4504-baf0-997d2dcfa890">

**Comment by vincentarelbundock** [comment]
Thanks @StarryCatte I believe that this warning was superfluous and that the numerical results should not be affected. The new version of `marginaleffects` on Github and the next version on CRAN (out soon) should no longer generate this warning.
