### ISSUE TITLE
Error when using `by` argument in `summary()` after `comparisons()`

### ISSUE THREAD

**Issue by ngreifer** [vincentarelbundock/marginaleffects#415]
Hi Vincent,

I found a bug, sorry. If I use `transform_pre` in `comparisons()` and supply `"lnoravg"` or any other options with `"avg"` in the suffix, I get an uninformative error when using `summary()` with `by`. This is because the `comparisons()` output only has one row containing the contrast instead of a row for each unit like it does with other `transform_pre` arguments.

``` r
data("lalonde", package = "MatchIt")

fit <- glm(married ~ race * treat, data = lalonde,
           family = binomial)

library(marginaleffects)
comp <- comparisons(fit, variable = list(treat = 0:1))
summary(comp, by = "race")
#> Average contrasts 
#>     race treat  Effect Std. Error z value   Pr(>|z|)   2.5 %   97.5 %
#> 1  black 1 - 0 -0.1015    0.05766  -1.760   0.078449 -0.2145  0.01154
#> 2 hispan 1 - 0 -0.2027    0.14873  -1.363   0.172962 -0.4942  0.08882
#> 3  white 1 - 0 -0.4241    0.09261  -4.579 4.6692e-06 -0.6056 -0.24257
#> 
#> Model type:  glm 
#> Prediction type:  response

comp <- comparisons(fit, variable = list(treat = 0:1),
                    transform_pre = "lnoravg")
summary(comp, by = "race")
#> Error: 
#> The `by` argument must be a character vector and every element of the vector
#> must correspond to a column name in the `x` marginal effects object.
```

<sup>Created on 2022-07-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I think a potential solution would be for `comparisons()` to return the same output every time regardless of `transform_pre`, a data frame with a row for each unit, except that for transformations with `"avg"` each unit gets the same value, which is the average value. I seem to recall that's how it used to be in a prior version.

**Comment by vincentarelbundock** [comment]
Just to clarify, in this case you would expect `summary()` to print 3 rows with identical estimates, CI, etc.?

I kind of like returning a single row because it allows us to compute average marginal effects in a single step, by specifying `transform_pre="differenceavg"`, instead of calling `summary()`. But maybe consistency is more important.

**Comment by ngreifer** [comment]
Ah I guess I wasn't thinking about it right. I mean ideally I'd like to have marginal (log) ORs for each level of the `by` variable, but I realize the current architecture might not allow for that since the ORs are computed before the `by`-subsetting. Not sure if it's possible at all without `comparisons()` knowing what the `by` variable is.

One idea (which I'm not saying you have to do but just a thought) is that you allow a `by` argument to be passed to `comparisons()`, which, when average effect measures are computed, does so in each stratum of the `by` variable. The `by` variable could be saved as an attribute of the output object so that when `summary()` is called on it it is automatically supplied. Some examples of what I'm thinking:

* `comparisons(fit, transform_pre  = "lnoravg", by = "byvar") |> summary()` produces marginal log ORs for each stratum of `byvar`, which is otherwise impossible.
* `comparisons(fit, by = "byvar") |> summary()` does the same as `comparisons(fit) |> summary(by = "byvar")`

For collapsible effect measures, the `by` attribute doesn't change anything about computation. For noncollapsible effect measures, it allows computation of the stratum-specific contrast. At the very least, using `summary(by = "byvar")` after `comparisons(fit, transform_pre  = "lnoravg")` should produce an informative error for the user.

**Comment by vincentarelbundock** [comment]
Right.

Will people who use `comparisons(mod, by="cyl")` expect to get `transform_pre="differenceavg"` by default? It would be weird to use a `by` argument in `comparisons()` without it doing anything visible, beyond setting an attribute for further processing.

**Comment by vincentarelbundock** [comment]
Also, would it make sense to have an analogous transformation like this?

```
   "lnor" = function(hi, lo) {
        log((hi / (1 - hi)) / (lo / (1 - lo)))
    },
```

**Comment by ngreifer** [comment]
I'm not exactly sure what people will want. To me the workflow of `comparisons() |> summary()` is satisfying and makes a lot of sense, mirroring the original `margins` and `lm`, etc. So giving users the opportunity to skip a step by computing `"differenceavg"` I don't think would have a ton of benefit when `summary()` is meant to be used to average across units anyway. Frankly I was a bit confused that you even had that as an option since the `summary()` output is the same as with `"difference"` because mean differences are collapsible. I'm open to the idea that using `by` in `comparisons()` automatically triggers the `avg` version of the contrast as a way to skip `summary()`, but I don't think it has to, i.e., that for collapsible effect measures `by` is primarily used just to be passed to `summary()`, which does the averaging within subgroups. I guess maybe one nice thing about creating average contrasts in `comparisons()` directly that you can use `hypothesis` with them, if that is true.

Such a transformation would be interesting because it would allow for unit-specific odds ratios, which might be of some use, but it would be important to ensure users don't think the averaged (log) odds ratio is a marginal odds ratio because it's not collapsible. Like maybe `summary()` would throw an error or warning saying that averaging across a noncollapsible effect measure is inadvisable and users should use `"lnoravg"` instead.

**Comment by ngreifer** [comment]
Those sounds like good solutions. So, do you expect that when an `"avg"` transform is supplied, `comparisons()` only returns one row (or one row per `by` level) with an average contrast, and then `summary()` is redundant (kind of like how it was recently)? So `summary()` becomes useful only to average across unit-level comparisons after computing them with a non-`"avg"` transform or for applying a `transform_avg`? 

Are there implications for a user-supplied `transform_pre`? Will you test to see if the output is the same for each row within each level of `by` and then supply the single-row output or the unit-specific output?

**Comment by ngreifer** [comment]
That all sounds really good!

**Comment by vincentarelbundock** [comment]
I *think* this works with current master, but I’m sure we’ll find some breakage.

``` r
library(marginaleffects)

mod <- lm(mpg ~ hp * vs, data = mtcars, family = binomial)
#> Warning: In lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) :
#>  extra argument 'family' will be disregarded

marginaleffects(mod, variables = "hp", by = "vs") |> summary()
#>   Term    Contrast vs   Effect Std. Error z value   Pr(>|z|)    2.5 %
#> 1   hp mean(dY/dX)  0 -0.04153    0.01379  -3.011  0.0026042 -0.06857
#> 2   hp mean(dY/dX)  1 -0.15810    0.03893  -4.061 4.8872e-05 -0.23440
#>     97.5 %
#> 1 -0.01450
#> 2 -0.08179
#> 
#> Model type:  lm 
#> Prediction type:  response

comparisons(mod, variables = "hp", by = "vs") |> summary()
#>   vs                    hp   Effect Std. Error z value   Pr(>|z|)
#> 1  0 mean(x + 1) - mean(x) -0.04153    0.01379  -3.011  0.0026042
#> 2  1 mean(x + 1) - mean(x) -0.15810    0.03893  -4.061 4.8872e-05
#>      2.5 %   97.5 %
#> 1 -0.06857 -0.01450
#> 2 -0.23440 -0.08179
#> 
#> Model type:  lm 
#> Prediction type:  response

comparisons(mod, variables = list("hp" = "sd"), by = "vs", transform_pre = "lnoravg") |>
    summary()
#>   vs                                      hp   Effect Std. Error z value
#> 1  0 ln(odds((x + sd/2)) / odds((x - sd/2))) 0.008947   0.002538   3.525
#> 2  1 ln(odds((x + sd/2)) / odds((x - sd/2))) 0.052952   0.034499   1.535
#>     Pr(>|z|)     2.5 %  97.5 %
#> 1 0.00042325  0.003973 0.01392
#> 2 0.12481285 -0.014665 0.12057
#> 
#> Model type:  lm 
#> Prediction type:  response

predictions(mod, by = "vs") |> summary()
#>   vs Predicted Std. Error z value   Pr(>|z|) CI low CI high
#> 1  0     16.62     0.8081   20.56 < 2.22e-16  15.03   18.20
#> 2  1     24.56     0.9163   26.80 < 2.22e-16  22.76   26.35
#> 
#> Model type:  lm 
#> Prediction type:  response
```

**Comment by ngreifer** [comment]
This looks amazing, can't wait to try it out! Thank you so much for spending time making these edits for me! I hope others find them useful! My plan is to rewrite the `MatchIt` vignette using `marginaleffects` so hopefully it'll bring you more downloads.

**Comment by vincentarelbundock** [comment]
Yeah, I think these are all very good improvements. It's nice to have a power user put the package through its paces.
