### ISSUE TITLE
Treat binary variables like logicals in `comparisons()`

### ISSUE THREAD

**Issue by ngreifer** [vincentarelbundock/marginaleffects#416]
I'd like to request/see what you think about treating binary variables as logicals in `comparisons()`, and perhaps elsewhere. I think running `comparisons(fit, variables = "bin_var")` should be interpreted the same as `comparisons(fit, variables = list(bin_var = 0:1))`, just as it is for logicals. The `(x+1)-x` contrast doesn't really make sense since it doesn't make sense to ask what would happen if units with `bin_var == 1` instead had `bin_var == 2`. This threw me off a bit, and I don't know if most users will understand or notice the difference between the unique levels contrast and the `(x+1)-x` contrast for binary variables. In nonlinear models, these can be quite different quantities. At least it should be clarified that binary variables should be converted to logical or factor before use in `comparisons()` to receive the "automatic" unique levels treatment. Thanks!

**Comment by vincentarelbundock** [comment]
Commit 930c0abe9a58 should makes the recommended change. Note that binary variables are still treated as continuous in `marginaleffects()`, since it feels like users who call that function seems are more explicitly asking for a derivative.

``` r
library(marginaleffects)
mod <- glm(gear ~ am + hp + vs, data = mtcars, family = poisson)
comparisons(mod) |> summary()
#>   Term    Contrast  Effect Std. Error z value Pr(>|z|)    2.5 %  97.5 %
#> 1   am       1 - 0 1.19579   0.731518  1.6347  0.10212 -0.23796 2.62954
#> 2   hp (x + 1) - x 0.00246   0.007042  0.3493  0.72686 -0.01134 0.01626
#> 3   vs       1 - 0 0.35006   0.985908  0.3551  0.72255 -1.58229 2.28240
#> 
#> Model type:  glm 
#> Prediction type:  response
```
