### ISSUE TITLE
The modelsummary package is a dependency

### ISSUE THREAD

**Issue by ercbk** [vincentarelbundock/marginaleffects#43]
I was running your "Getting Started" example and got this error
![Screenshot (489)](https://user-images.githubusercontent.com/25374582/132905941-3b9a324a-20e6-4c45-868b-a4a8beb3bfd4.png)
Installed modelsummary, reran, and everything worked fine.

**Comment by vincentarelbundock** [comment]
Thanks a lot for trying the package and reporting this bug, I really appreciate it!

Should be fixed by commit https://github.com/vincentarelbundock/marginaleffects/commit/19b80bf9d14927661348b3c0d93b5c6a6f8e2434
