### ISSUE TITLE
comparisons() with a Bayesian random-effects logistic regression: understanding estimands

### ISSUE THREAD

**Issue by arthur-albuquerque** [vincentarelbundock/marginaleffects#431]
Hi Vincent, 

I fitted a Bayesian random-effects meta-analysis with the Binomial likelihood. I am trying to use {marginaleffects} to generate the estimands of my interest but am struggling to understand `comparisons()`'s outputs.

In brief, I want to confirm I am estimating the marginal absolute risk reduction and marginal odds ratio correctly.

Below you can find a step-by-step case study with code. You can find my specific questions throughout.

Thank you for developing such a fantastic package. I want to use it daily in my analysis workflow, so confirming I am using it correctly is essential for my work. Hopefully, others will also find this post helpful.

----------------------------------------------------------------------------------------------------------------------------------

``` r
# Ensures the package "pacman" is installed
if (!require("pacman")) install.packages("pacman")
#> Loading required package: pacman

pacman::p_load(brms, dplyr, ggdist)

# Install/load marginaleffects version 0.6.0.9000 
pacman::p_load_gh("vincentarelbundock/marginaleffects")
```

Load data of randomized controlled trials comparing two treatments (“tx”).

``` r
studies = c("CORIMUNO-TOCI-1", "COV-AID", "COVACTA", 
                           "COVIDOSE2-SS-A", "EMPACTA", "PreToVid", "RECOVERY",
                           "REMDACTA", "TOCIBRAS", "CORIMUNO-TOCI-1", "COV-AID",
                           "COVACTA", "COVIDOSE2-SS-A", "EMPACTA", "PreToVid",
                           "RECOVERY", "REMDACTA", "TOCIBRAS")
d = 
  structure(list(study_fixed = studies, 
                 study_random = studies, 
                 events = c(1, 1, 1, 0, 11, 12, 125, 1, 1, 3, 0, 1, 1, 4, 19,
                            173, 0, 0),
                 total = c(10, 25, 11, 6, 128, 116, 766, 14, 20, 12, 21, 12, 1,
                           72, 118, 765,2, 14),
                 tx = c("toci", "toci", "toci", "toci", "toci", "toci", "toci",
                        "toci", "toci", "control", "control", "control",
                        "control", "control", "control", "control", "control",
                        "control")),
            row.names = c(NA,-18L),
            class = "data.frame") |> 
  # dummy approach
  mutate(tx = ifelse(tx == "toci", 1, 0))
```

Fit Bayesian Meta-Analysis with the Binomial likelihood with fixed effects for the baseline risks in each study and random treatment effect per study.

``` r
# Further detatils about the model in
# "Section 3.2, Model 2: the Simmonds and Higgins model"
# https://doi.org/10.1002/sim.7588

# Model formula

mf = 
  brms::bf(
    events | trials(total) ~ 0 + study_fixed + tx + (0 + tx|study_random)
  )

# Weakly-informative priors

priors = 
  prior(normal(0, 1.5), class = "b") +
  prior(normal(0, 0.5), class = "sd") 

ma_toci = 
  brms::brm(
    
    data = d,
    family = binomial,
    formula = mf,
    prior = priors,
    
    control = list(adapt_delta = .99),
    # backend = "cmdstanr", # enable it in case you've it installed 
    cores = parallel::detectCores(),
    chains = 4,
    warmup = 2000, 
    iter = 4000, 
    seed = 123
  )
#> Compiling Stan program...
#> Start sampling
```

# Questions

### Marginal Absolute Risk Reduction (global grand mean)

-   I would like to confirm that `marginaleffects::comparisons()` applies the
    G-formula and calculates the mean and 95% quantiles intervals to calculate the
    marginal absolute risk reduction (global grand mean).

``` r
# As per https://vincentarelbundock.github.io/marginaleffects/articles/brms.html

# Note that, in this subsection, I set dpar = "mu" to generate 
# absolute risk (proportion) reduction instead of absolute number of events
# Further details in https://github.com/stan-dev/rstanarm/issues/509

comparisons(ma_toci,
            variables = "tx",
            dpar = "mu",
            re_formula = NA) |> 
  summary() 
#>   Term Contrast   Effect   2.5 %    97.5 %
#> 1   tx    1 - 0 -0.05156 -0.1028 -0.006426
#> 
#> Model type:  brmsfit 
#> Prediction type:  response
```

I am able to reproduce results with `brms::posterior_epred()`:

``` r
diff = 
  # Predicted value if all were in the treatment group
  posterior_epred(ma_toci, newdata = transform(d, tx = 1),
                  dpar = "mu",
                  re_formula = NA) - 
  
  # Predicted value if all were in the control group
  posterior_epred(ma_toci, newdata = transform(d, tx = 0),
                  dpar = "mu",
                  re_formula = NA)

diff |> 
  apply(1, mean) |> 
  ggdist::mean_qi() |> 
  mutate(across(1:3, ~round(., 3)))
#>        y   ymin   ymax .width .point .interval
#> 1 -0.052 -0.103 -0.006   0.95   mean        qi
```

### Marginal Absolute Risk Reduction in a Hypothetical Study

Regarding the marginal absolute risk reduction in a hypothetical study
(“Conditional effect for a single typical hypothetical group”, term used
by @andrewheiss in [his blog post](https://www.andrewheiss.com/blog/2021/11/10/ame-bayes-re-guide/))):

``` r
# Get total number of patients in the RECOVERY study
t_n = sum(subset(d, study_fixed == "RECOVERY")$total)

nd = data.frame(study_random = "new",
                tx = 0:1,
                study_fixed = "RECOVERY", 
                total = t_n)

comparisons(ma_toci,
            variables = "tx",
            newdata = nd,
            dpar = "mu",
            re_formula = NULL,
            allow_new_levels = TRUE,
            sample_new_levels = "uncertainty") |> 
  summary()
#>   Term Contrast   Effect   2.5 %  97.5 %
#> 1   tx    1 - 0 -0.06937 -0.1571 0.02881
#> 
#> Model type:  brmsfit 
#> Prediction type:  response
```

``` r
diff = 
  # Predicted value if all were in the treatment group
  posterior_epred(ma_toci, newdata = transform(nd, tx = 1),
                  dpar = "mu",
                  re_formula = NULL,
                  allow_new_levels = TRUE,
                  sample_new_levels = "uncertainty") - 
  
  # Predicted value if all were in the control group
  posterior_epred(ma_toci, newdata = transform(nd, tx = 0),
                  dpar = "mu",
                  re_formula = NULL,
                  allow_new_levels = TRUE,
                  sample_new_levels = "uncertainty")

diff |> 
  apply(1, mean) |> 
  ggdist::mean_qi() 
#>             y       ymin       ymax .width .point .interval
#> 1 -0.06914741 -0.1566676 0.03005115   0.95   mean        qi
```

-   Although very close, `marginaleffects::comparisons()` vs. `brms::posterior_epred()` results were not equal. Why?

## Odds ratio

-   How can one estimate the adjusted marginal odds ratio in this Bayesian model?

- Here I have questions about the appropriate `marginaleffects::comparisons()` syntax and how one should set `re_formula` to estimate the *marginal* OR.

I first attempted to use the `marginaleffects::comparisons()`’s syntax for a frequentist model,
explained by @ngreifer [here](https://gist.github.com/arthur-albuquerque/1a126043fef15b55792392e91f969f83?permalink_comment_id=4241990#gistcomment-4241990)..

However, I get the following error:

``` r
comparisons(ma_toci, variables = "rx",
             transform_pre = "lnoravg",
            re_formula = NA) |> 
     summary(transform_avg = exp)
#> Error: 
#> For bayesian models, the `by` argument is not supported and the `transform_pre`
#> shortcut strings cannot include "avg".
```

I then used the following syntax, which seems to work just as the one above for
frequentist models ([example](https://twitter.com/arthur_alb1/status/1552813295660371968?s=21)).

In regards to the `re_formula` argument, I set it as “NA” based on [marginaleffects-brms’ vignette](https://vincentarelbundock.github.io/marginaleffects/articles/brms.html#global-grand-mean).

- I interpreted the *marginal* odds ratio as what you refer to as the “Global grand mean,” but would like to double-check if this is correct.

``` r
comparisons(ma_toci, variables = "tx",
            type = "link",
            re_formula = NA) |> 
  summary(transform_avg = exp)
#>   Term Contrast Effect  2.5 % 97.5 %
#> 1   tx    1 - 0 0.6192 0.3735  0.943
#> 
#> Model type:  brmsfit 
#> Prediction type:  link 
#> Average-transformation:
```

I can reproduce results with `brms::posterior_epred()`:

``` r

# Note that, in this subsection, I also set dpar = "mu" to generate 
# absolute risk (proportion) reduction instead of absolute number of events
# Further details in https://github.com/stan-dev/rstanarm/issues/509

#Predicted outcome under treatment
avep1 <- posterior_epred(ma_toci,
                         newdata = transform(d, tx = 1),
                         dpar = "mu",
                         re_formula = NA)
        
#Predicted outcome under control
avep0 <- posterior_epred(ma_toci,
                         newdata = transform(d, tx = 0),
                         dpar = "mu",
                         re_formula = NA)
              

#Compute marginal odds from the average probabilities
odds1 <- avep1 / (1 - avep1)
odds0 <- avep0 / (1 - avep0)

#Odds ratio
(odds1 / odds0) |> 
  apply(1, mean) |> 
  ggdist::mean_qi() 
#>           y     ymin      ymax .width .point .interval
#> 1 0.6347437 0.373495 0.9429859   0.95   mean        qi
```

### Conditional vs. Marginal Odds Ratios

I was very surprised that I reproduced the results above by simply exponentiating “tx” model coefficient:

``` r
fixef(ma_toci,
      summary = F) |> 
  data.frame() |> 
  exp() |> 
  ggdist::mean_qi(tx)
#> # A tibble: 1 × 6
#>      tx .lower .upper .width .point .interval
#>   <dbl>  <dbl>  <dbl>  <dbl> <chr>  <chr>    
#> 1 0.635  0.373  0.943   0.95 mean   qi
```

- I thought exp(tx) would yield a different estimate as it should be a distinct estimand (conditional OR). What do you think?

<sup>Created on 2022-07-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by vincentarelbundock** [comment]
Arthur,

Thanks for your interest in the package. Love the enthusiasm!

This is the development website for `marginaleffects`. I am more than happy to answer very specific questions about how `marginaleffects` does certain operations, and why it can't do others. For example, you could file different issue with a feature request for support of ˋlnoravg` in Bayesian models. This should be implementable, but I haven't invested the time to do it yet.

However, I am not a statistical consultant, and I do not have the bandwidth to read detailed case studies and to comment on the statistical properties of all the various estimands and research designs that people may cook up. I'm sure you understand that this has the potential to be an infinite time sink for me.

There are many discussion forums online (ex: stats exchange) where you can ask questions like: is it a good idea to take the average of conditional odds ratios? (Probably not.)

Again, I really appreciate your enthusiasm! It's great to have power users push the package to its limits. And please feel free to open new issues about the package itself, its bugs and (lack of) features.

**Comment by vincentarelbundock** [comment]
FYI, i opened a more generic issue for supporting bayes model with `transform_pre` values like "lnoravg": https://github.com/vincentarelbundock/marginaleffects/issues/432
