### ISSUE TITLE
slope option not supported?

### ISSUE THREAD

**Issue by bangecon** [vincentarelbundock/marginaleffects#433]
Thank you for your excellent package. Someone suggested your package for calculating average elasticities (as opposed to elasticities at the mean). 

When I attempted to replicate the elasticity example in the vignette using R version 4.2.1 and marginaleffects version 0.6.0 (https://vincentarelbundock.github.io/marginaleffects/articles/elasticity.html), I received the following message (along with the standard "dydx" margins): 

> mod <- lm(mpg ~ hp + wt, data = mtcars)
> 
> marginaleffects(mod) |> summary()
Average marginal effects 
  Term   Effect Std. Error z value   Pr(>|z|)    2.5 %   97.5 %
1   hp -0.03177    0.00903  -3.519 0.00043365 -0.04947 -0.01408
2   wt -3.87783    0.63273  -6.129 8.8603e-10 -5.11797 -2.63770
Model type:  lm 
Prediction type:  response 

> marginaleffects(mod, slope = "eyex") |> summary()
Average marginal effects 
  Term   Effect Std. Error z value   Pr(>|z|)    2.5 %   97.5 %
1   hp -0.03177    0.00903  -3.519 0.00043365 -0.04947 -0.01408
2   wt -3.87783    0.63273  -6.129 8.8603e-10 -5.11797 -2.63770
Model type:  lm 
Prediction type:  response 
Warning message:
These arguments are not supported for models of class `lm`: slope. Please file a request on Github if you believe that additional arguments should be supported: https://github.com/vincentarelbundock/marginaleffects/issues

**Comment by vincentarelbundock** [comment]
Sorry, I'm in the process of prepping a new release and the docs reflect the development version. You can install from Github (make sure you restart R completely after), and it should work.

**Comment by bangecon** [comment]
Thanks! I can't keep up between testing the suggestion and the exchanges on Twitter. Sorry to waste your time!
