### ISSUE TITLE
Hypothesis argument for comparisons asks for new data when contrast variable is a factor

### ISSUE THREAD

**Issue by norcalbiostat** [vincentarelbundock/marginaleffects#439]
The following code worked with the variable `treat` was numeric 0,1

```
comparisons(mod, variables =list(treat = 0:1),
            vcov = ~subclass, wts = "weights", 
            by = "group", hypothesis = "pairwise") |>
  summary()
```

but when it's modeled as a factor variable, 

```
comparisons(mod, variables = "treat",
            vcov = ~subclass, wts = "weights", 
            by = "group", hypothesis = "pairwise") |>
  summary()
```
I get the following error: 

> Error in `[<-`(`*tmp*`, j, , value = 1) : subscript out of bounds
> In addition: Warning message:
> 
> The `hypothesis` argument of the `comparisons()` function must be used in
> conjunction with the `newdata` argument. `newdata` was switched from NULL to
> "mean" automatically.

**Comment by norcalbiostat** [comment]
Edit: Sorry .. i should have double checked the original code. 
Okay, so why does it need the `newdata` argument? It works when I specify the original model data as `newdata`

**Comment by vincentarelbundock** [comment]
Thanks for the report!

The function should fail more gracefully, so I will take a look as soon as I find some time.

The idea is that `comparisons()` typically generates unit-level estimates of the change in predictions. If the dataset is large and users ask request `hypothesis="pairwise"`, the number of rows will explode.

If that's really what users want, then they will at least have to indicate as much by supplying their whole dataset explicitly to `newdata`.

Of course, this is never going to be a problem when using the new ˋby` argument, as you do here. So my check should be smarter, and the warning message more informative.

**Comment by vincentarelbundock** [comment]
I believe this should now be fixed on Github. Closing now, but feel free to keep the discussion going if the dev version doesn't work for you. (make sure you restart R after install)

Thanks again for the report.
