### ISSUE TITLE
data.table and fixest error

### ISSUE THREAD

**Issue by hauselin** [vincentarelbundock/marginaleffects#443]
When the dataset for model fitting is a `data.table` and the model is a `fixest` model, calling `marginaleffects` with `newdata` argument produces this error:

```r
Error in `[.data.table`(dat, , variables_automatic, drop = FALSE) : 
  j (the 2nd argument inside [...]) is a single symbol but column name 'variables_automatic' is not found. Perhaps you intended DT[, ..variables_automatic]. This difference to data.frame is deliberate and explained in FAQ 1.1.
```

The function breaks here: https://github.com/vincentarelbundock/marginaleffects/blob/2d835598e727525c82099e0355f7fb6ed5ae0de5/R/marginaleffects.R#L218

Code to reproduce error

```r
library(fixest)
library(data.table)
library(marginaleffects)

d <- data.table(mtcars)
m <- feols(mpg ~ cyl * disp, d)
marginaleffects(m)  # works fine
marginaleffects(m, newdata = datagrid(disp = 0))  # data.table error

m <- feols(mpg ~ cyl * disp, data.frame(d))  # data.frame input instead of data.table
marginaleffects(m, newdata = datagrid(disp = 0))  # works 
```

**Comment by vincentarelbundock** [comment]
Thanks a lot for the report and MWE @hauselin!

I believe this should not be fixed. Could you please install the package from Github, restart `R` completely, and try again?

**Comment by hauselin** [comment]
Yes, it's fixed. Thanks, @vincentarelbundock!
