### ISSUE TITLE
`wts` argument should be respected by `transform_pre` that average, e.g., "differenceavg"`

### ISSUE THREAD

**Issue by ngreifer** [vincentarelbundock/marginaleffects#449]
When I try to compute weighted average differences in potential outcomes, I can do so by specifying the `wts` argument to `comparisons()`, which is passed to `summary()` to compute the weighted average of the individual-level contrasts. However, when using `transform_pre` to compute an average contrast, `wts` is not respected. This is mentioned in the documentation, but I think this functionality is a remnant of an older view of `comparisons()` which only computed individual-level effects and then `summary()` did the averaging. Because the averaging needs to occur before `summary()` when the estimand is noncollapsibile (e.g., `"lnoravg"`) or when `by` is used, `wts` should still be able to be incorporated into those weighted averages.

See the example below, which demonstrates the correct incorporation of `wts` when averaging unit-level comparisons using `summary()`, vs the failure to incorporate `wts` when computing comparisons between average predictions using `transform_pre`.

``` r
library(marginaleffects)
data("lalonde", package = "MatchIt")

#Generate weights
set.seed(100)
lalonde$w <- rchisq(614, 2)

fit <- lm(re78 ~ treat * (age + educ + race + married + re74),
          data = lalonde, weights = w)

#Marginal effect of treat, with weights
marg <- comparisons(fit, variables = "treat", wts = "w")
summary(marg)
#>   treat Effect Std. Error z value  Pr(>|z|) 2.5 % 97.5 %
#> 1 1 - 0   3029       1048   2.892 0.0038287 976.3   5082
#> 
#> Model type:  lm 
#> Prediction type:  response

#AME of treat corresponds to weighted mean
weighted.mean(marg$comparison, lalonde$w)
#> [1] 3029.36

#Using "differenceavg" does not respect weights; get the same
#result whether weights are included or not
comparisons(fit, variables = "treat", wts = "w", transform_pre = "differenceavg") |>
  summary()
#>               treat Effect Std. Error z value  Pr(>|z|) 2.5 % 97.5 %
#> 1 mean(1) - mean(0)   2906       1001   2.904 0.0036836 944.6   4867
#> 
#> Model type:  lm 
#> Prediction type:  response
comparisons(fit, variables = "treat", transform_pre = "differenceavg") |>
  summary()
#>               treat Effect Std. Error z value  Pr(>|z|) 2.5 % 97.5 %
#> 1 mean(1) - mean(0)   2906       1001   2.904 0.0036836 944.6   4867
#> 
#> Model type:  lm 
#> Prediction type:  response
```

<sup>Created on 2022-08-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by vincentarelbundock** [comment]
Good catch, thanks!

Haven't looked at this in detail, but one potential implementation would be to:

1. Add analogues to all the `avg` functions in the dictionary here: https://github.com/vincentarelbundock/marginaleffects/blob/main/R/sanitize_transform_pre.R
2. Pass the `wts` argument to the `sanitize_variables()` function here: https://github.com/vincentarelbundock/marginaleffects/blob/main/R/sanitize_variables.R
3. When appropriate based on the `wts` argument, automatically switch to an appropriate weighted function as we do for `avg` here: https://github.com/vincentarelbundock/marginaleffects/blob/main/R/sanitize_variables.R#L141
4. Pass the weights to the `transform_pre` function inside `get_contrasts()` here: https://github.com/vincentarelbundock/marginaleffects/blob/main/R/get_contrasts.R#L236
5. Add a test.

I don't know for sure that this will work, but I'm optimistic.

**Comment by vincentarelbundock** [comment]
Thanks again for the report. I believe that the package should now work as expected.

``` r
library(marginaleffects)
data("lalonde", package = "MatchIt")
set.seed(100)
lalonde$w <- rchisq(614, 2)
fit <- lm(re78 ~ treat * (age + educ + race + married + re74),
          data = lalonde, weights = w)

# no weights
comparisons(fit, variables = "treat") |> tidy()
#>       type  term contrast estimate std.error
#> 1 response treat    1 - 0 2905.597  1000.531
#>   statistic     p.value conf.low conf.high
#> 1  2.904056 0.003683618 944.5933  4866.601

# weights: 4 ways
cmp <- comparisons(fit, variables = "treat", wts = "w")

tidy(cmp)
#>       type  term contrast estimate std.error
#> 1 response treat    1 - 0  3029.36  1047.517
#>   statistic    p.value conf.low conf.high
#> 1  2.891943 0.00382868 976.2636  5082.456

comparisons(fit,variables = "treat", wts = "w", transform_pre = "differenceavg")
#>       type  term          contrast comparison
#> 1 response treat mean(1) - mean(0)    3029.36
#>   std.error statistic     p.value conf.low conf.high
#> 1  1047.517  2.891943 0.003828679 976.2637  5082.456

comparisons(fit,variables = "treat", wts = "w", transform_pre = "differenceavgwts")
#>       type  term          contrast comparison
#> 1 response treat mean(1) - mean(0)    3029.36
#>   std.error statistic     p.value conf.low conf.high
#> 1  1047.517  2.891943 0.003828679 976.2637  5082.456

weighted.mean(cmp$comparison, lalonde$w)
#> [1] 3029.36
```

**Comment by vincentarelbundock** [comment]
closing now to clean the repo, but feel free to keep the conversation going and/or open a new issue if you run into problems.
