### ISSUE TITLE
Documentation output bug

### ISSUE THREAD

**Issue by arthur-albuquerque** [vincentarelbundock/marginaleffects#457]
Hi Vincent, 

There is a bug in this page: https://vincentarelbundock.github.io/marginaleffects/reference/comparisons.html#transformations-1

The same happens on my phone

<img width="881" alt="image" src="https://user-images.githubusercontent.com/77208087/184689274-8b66b610-6ece-4eff-b38b-8bd548de832f.png">

**Comment by vincentarelbundock** [comment]
Thanks!

fixed
