### ISSUE TITLE
`data.table` and `fixest` objects do not play nicely with `marginaleffects`

### ISSUE THREAD

**Issue by aaronw22** [vincentarelbundock/marginaleffects#458]
Hi Vincent,

Love your work! I have discovered that `marginaleffects` isn't working when a `data.table` is fed into regressions estimated using `fixest` functions. See the reprex and error message below.

```
library(data.table)
library(fixest)
library(marginaleffects)

data <- data.table(y = rnorm(10), x = rnorm(10))
model <- feols(y ~ x, data)
marginaleffects(model)

```

Console error message:

```
Error in `[.data.table`(modeldata, , cl) : 
  j (the 2nd argument inside [...]) is a single symbol but column name 'cl' is not found. Perhaps you intended DT[, ..cl]. This difference to data.frame is deliberate and explained in FAQ 1.1.
```

It isn't a major issue, because it can be worked-around by supplying a `data.frame` instead.

**Comment by vincentarelbundock** [comment]
Thanks for the report @aaronw22 

I cannot replicate this on my computer, and I think it's because I fixed this problem very recently while working on another feature. Would you mind installing from Github, restarting `R` completely, and trying again?

**Comment by aaronw22** [comment]
Can confirm that the problem no longer occurs when using the Github version, seems like you did fix it somewhere.

Cheers!
