### ISSUE TITLE
Estimating marginal means using weighting equivalent to emmeans `weights = "prop"`

### ISSUE THREAD

**Issue by sambrilleman** [vincentarelbundock/marginaleffects#459]
Thanks for the great package.

I'm just wondering whether `marginalmeans()` provides an equivalent to the "proportional" / "prop" weighting that **emmeans** provides? Described here: https://cran.r-project.org/web/packages/emmeans/vignettes/messy-data.html#weights

Basically, for any covariates that you are averaging over, using the sample frequencies of the combinations of those covariates.

I've looked through the vignettes and documentation for **marginaleffects** but couldn't find anything mentioned (perhaps I just missed it).

**Comment by vincentarelbundock** [comment]
Thanks a lot for opening this issue @sambrilleman\! I believe that @mattansb mentioned a similar feature a while ago.

I have now implemented a `wts` argument which accepts values: “equal”, “proportional”, “cells”. It will be part of the next release on CRAN, but you can install it from Github right now (make sure you restart `R` after install).

``` r
library(emmeans)
library(marginaleffects)

mod <- glm(vs ~ factor(am) + factor(gear) + mpg, data = mtcars, family = binomial)

emmeans(mod, ~am, weights = "cells", type = "response")
#>  am    prob      SE  df asymp.LCL asymp.UCL
#>   0 0.99677 2.99318 Inf   0.0e+00     1.000
#>   1 0.00159 0.00633 Inf   6.4e-07     0.798
#> 
#> Results are averaged over the levels of: gear 
#> Confidence level used: 0.95 
#> Intervals are back-transformed from the logit scale
marginalmeans(mod, variables = "am", wts = "cells")
#>   term value marginalmean     conf.low conf.high   p.value
#> 1   am     0   0.99677347 2.220446e-16 1.0000000 0.9950850
#> 2   am     1   0.00158873 6.396890e-07 0.7983192 0.1062905

emmeans(mod, ~am, weights = "proportional")
#>  am emmean   SE  df asymp.LCL asymp.UCL
#>   0   10.5 2349 Inf     -4593      4613
#>   1  -13.4 2072 Inf     -4075      4048
#> 
#> Results are averaged over the levels of: gear 
#> Results are given on the logit (not the response) scale. 
#> Confidence level used: 0.95
marginalmeans(mod, variables = "am", wts = "proportional", type = "link")
#>   term value marginalmean std.error  conf.low conf.high   p.value
#> 1   am     0     10.47487  2348.515 -4592.530  4613.480 0.9964413
#> 2   am     1    -13.37349  2072.221 -4074.852  4048.105 0.9948507
#>      statistic
#> 1  0.004460212
#> 2 -0.006453700
```

BTW, instead of `marginalmeans`, you may want to consider using `predictions()` with the `by` argument. The benefit there, is that instead of holding numeric/continuous variables at the mean, they will be held at their actual observed values. So the averaging is proportional to both the categories and the observed numerics.

``` r
predictions(mod, by = "am") |> summary()
#>   am Predicted Std. Error z value   Pr(>|z|) CI low CI high
#> 1  1    0.5385    0.07002   7.690 1.4706e-14 0.4012  0.6757
#> 2  0    0.3684    0.04416   8.343 < 2.22e-16 0.2819  0.4550
#> 
#> Model type:  glm 
#> Prediction type:  response
```

**Comment by vincentarelbundock** [comment]
Closing now to clean up the repo, but feel free to re-open or keep the conversation going if needed.

**Comment by sambrilleman** [comment]
Wow, thanks for implementing this so quickly! That's really cool. 😀

Also thanks for mentioning the predictions + by approach. That is actually what I had hoped to do, but didn't realise it was possible (I thought I was limited to predicting at the mean of the numeric covariates), so perhaps I will opt for that approach. 🙂

**Comment by sambrilleman** [comment]
Hi @vincentarelbundock - just wondering whether the example below demonstrates a bug with respect to `wts = "proportional"` for `marginalmeans()`?

Basically, if estimating marginal means using all variables in the model, the returned object is some form of unit-level predictions or something. I would have expected all three `marginalmeans` results below to return the same thing, since there is nothing else in the model to apply the `wts` over. But maybe I am misunderstanding...

Fwiw, it works if there is an additional variable in the model that isn't included in the `variables` argument for `marginalmeans`, presumably because there then is something to apply the weights to. Also, I've included an interaction in my example model below, but I don't think that is a requirement to demonstrate the potential bug.

```
> library(marginaleffects)
> dat <- mtcars
> dat$am <- factor(dat$am)
> dat$cyl <- factor(dat$cyl)
> mod <- lm(mpg ~ cyl * am, dat)
> marginalmeans(mod, variables = c("cyl", "am"), wts = "equal")
  cyl am marginalmean std.error conf.low conf.high       p.value statistic
1   6  1     20.56667 1.7506745 17.13541  23.99793  7.243576e-32 11.747853
2   6  0     19.12500 1.5161286 16.15344  22.09656  1.759690e-36 12.614366
3   4  1     28.07500 1.0720648 25.97379  30.17621 3.661326e-151 26.187783
4   4  0     22.90000 1.7506745 19.46874  26.33126  4.246646e-39 13.080673
5   8  1     15.40000 2.1441296 11.19758  19.60242  6.849730e-13  7.182402
6   8  0     15.05000 0.8753372 13.33437  16.76563  2.976955e-66 17.193373
> marginalmeans(mod, variables = c("cyl", "am"), wts = "cells")
  cyl am marginalmean std.error conf.low conf.high       p.value statistic
1   4  0     22.90000 1.7506745 19.46874  26.33126  4.246646e-39 13.080673
2   4  1     28.07500 1.0720648 25.97379  30.17621 3.661326e-151 26.187783
3   6  0     19.12500 1.5161286 16.15344  22.09656  1.759690e-36 12.614366
4   6  1     20.56667 1.7506745 17.13541  23.99793  7.243576e-32 11.747853
5   8  0     15.05000 0.8753372 13.33437  16.76563  2.976955e-66 17.193373
6   8  1     15.40000 2.1441296 11.19758  19.60242  6.849730e-13  7.182402
> marginalmeans(mod, variables = c("cyl", "am"), wts = "proportional")
       mpg cyl am wts
1 20.09062   6  1   1
2 20.09062   6  0   1
3 20.09062   4  1   1
4 20.09062   4  0   1
5 20.09062   8  1   1
6 20.09062   8  0   1
```

HTH!
