### ISSUE TITLE
Marginal means averaged across categorical variable levels

### ISSUE THREAD

**Issue by ArthurAndrews** [vincentarelbundock/marginaleffects#468]
Apologize if my question is poorly-worded or is addressed in the documentation.

Is there a way to produce marginal means for the **average** across variable levels?

I believe that averaging across levels is typically how marginal means are handled in JMP or `emmeans` - by setting fractional values of the dummy variable columns in the X matrix.

Correct me if I'm wrong, but functions like `plot_cap` and `predictions` by default will choose one level of the categorical variables with `typical`.

Thanks for the great package!

**Comment by vincentarelbundock** [comment]
Thanks for trying the package!

Are you looking for the `marginalmeans()` function?

Docs: https://vincentarelbundock.github.io/marginaleffects/reference/marginalmeans.html
Vignette: https://vincentarelbundock.github.io/marginaleffects/articles/marginalmeans.html

**Comment by ArthurAndrews** [comment]
You're welcome!

I should have included some code at the beginning!  I've been using `marginalmeans` for the categorical predictor variables, but for continuous ones, I've been using `predictions` and `plot_cat` using `datagrid` to specify a range of values for the continuous predictor.  Both these functions seem to choose one level of the categorical variables.  

In this example, `predictions` chooses cyl = 8 for example.  It would be great to be able to specify `cyl = NA` or `cyl = "mean"` to `datagrid` somehow and have that be interpreted as a marginal mean across cyl levels.  Or accomplish this some other way?

``` r
library(marginaleffects)
  
mod <- lm(mpg ~ hp + factor(cyl), data = mtcars)

predictions(mod, newdata = datagrid(hp = seq(100, 120, length.out = 10)))
#>    rowid     type predicted std.error statistic      p.value conf.low conf.high
#> 1      1 response  17.72538  1.881157  9.422599 4.400597e-21 13.87201  21.57876
#> 2      2 response  17.67196  1.850591  9.549361 1.304982e-21 13.88120  21.46273
#> 3      3 response  17.61854  1.820157  9.679686 3.678438e-22 13.89012  21.34697
#> 4      4 response  17.56513  1.789860  9.813689 9.830732e-23 13.89876  21.23149
#> 5      5 response  17.51171  1.759707  9.951489 2.484375e-23 13.90711  21.11630
#> 6      6 response  17.45829  1.729707 10.093206 5.920379e-24 13.91514  21.00143
#> 7      7 response  17.40487  1.699867 10.238960 1.326546e-24 13.92285  20.88689
#> 8      8 response  17.35145  1.670195 10.388873 2.786265e-25 13.93021  20.77269
#> 9      9 response  17.29803  1.640702 10.543065 5.468721e-26 13.93720  20.65885
#> 10    10 response  17.24461  1.611396 10.701654 9.997701e-27 13.94381  20.54540
#>    cyl       hp
#> 1    8 100.0000
#> 2    8 102.2222
#> 3    8 104.4444
#> 4    8 106.6667
#> 5    8 108.8889
#> 6    8 111.1111
#> 7    8 113.3333
#> 8    8 115.5556
#> 9    8 117.7778
#> 10   8 120.0000
```

<sup>Created on 2022-08-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by vincentarelbundock** [comment]
Aaah, got it.

Under the hood, the `datagrid()` mechanism is completely distinct from the averaging mechanism, so I think it would be very difficult to implement the specific suggestion you made. I’ll have to think about whether there’s a clean & easy way to make this easier.

In the meantime, you can use the `by` argument of the `predictions()` function to do this pretty easily. The intuition is that we build a data grid with all values of the categorical predictor, and then we use `by="x"` to average over those categories – with `x` being the x-axis variable in your plot.

For example:

``` r
library(marginaleffects)
library(ggplot2)

mod <- lm(mpg ~ hp + factor(cyl), data = mtcars)

p <- predictions(mod,
    by = "hp",
    newdata = datagrid(
        model = mod,
        hp = seq(100, 120, length.out = 10),
        cyl = mtcars$cyl))

ggplot(p) +
    geom_ribbon(aes(hp, ymin = conf.low, ymax = conf.high), alpha = .2) +
    geom_line(aes(hp, predicted))
```

![](https://i.imgur.com/nm07rjx.png)

**Comment by vincentarelbundock** [comment]
Oh, forgot to say that the example above *may* require the latest development version from Github. Make sure you restart `R` after you install it.

**Comment by ArthurAndrews** [comment]
Thanks - perhaps this is what I'm looking for!  Is there any documentation for how the averaging is done?  Does it simply average the marginalmean, conf.high, conf.low across levels, or do a statistical calculation with the model matrix?

**Comment by vincentarelbundock** [comment]
The order of operations is:

1. Create a perfectly "balanced" data grid for each combination of `hp` and `cyl`. This user-specified in the `datagrid()` call.
2. Compute fitted values (aka "adjusted predictions") for each cell of the grid.
3. Use the `by` argument to take the average of predicted values for each value of `hp`, across margins of `cyl`.
4. Compute standard errors around the averaged predicted values (i.e., marginal means).
5. Create symmetric confidence intervals in the usual manner.

This should work well in linear cases. In GLM models with different link functions, you may want to use `type="link"` and the `transform_post` argument to backtransform on the response scale.

Makes sense?

**Comment by ArthurAndrews** [comment]
I'm getting there!  For step 4, how are the standard errors for the individual levels averaged to produce the standard error for the marginal mean?

**Comment by vincentarelbundock** [comment]
The standard errors are not averages. We treat the average predictions as a function of the parameters, and compute the standard errors directly on those final quantities using the delta method, as describe here: https://vincentarelbundock.github.io/marginaleffects/articles/sandwich.html#delta-method

**Comment by ArthurAndrews** [comment]
Thank you!

**Comment by vincentarelbundock** [comment]
It would be cool to add a section to the Marginal Means vignette with this example. It's a cool one.

**Comment by vincentarelbundock** [comment]
example added to the vignette: https://github.com/vincentarelbundock/marginaleffects/commit/e5cc9f1246ddc655e9d285b0646091ffdad4af86
