### ISSUE TITLE
Bug in get_predict.multinom

### ISSUE THREAD

**Issue by tomwenseleers** [vincentarelbundock/marginaleffects#476]
Sorry still caught a bug in `get_predict.multinom` :

```
library(nnet)
library(mclogit)
library(emmeans)
library(dplyr)
library(tidyverse)

x = 1:1000
n = length(x)
set.seed(1)
y1 = rbinom(n, 10, prob=plogis(-10+0.02*x))
y2 = 10-y1
dat = data.frame(x,y1,y2)
dat_long = dat |>
  pivot_longer(!x, names_to = "y", values_to = "count") |>
  mutate(y = factor(y, levels=c("y2", "y1")))

fit_multinom = nnet::multinom(y ~ x, weights=count, data=dat_long)

predictions(fit_multinom, 
            newdata = datagrid(x=unique(dat$x)),
            type = "latent")
Error in `$<-.data.frame`(`*tmp*`, "rowid", value = c(1L, 2L, 3L, 4L, : 
replacement has 1000000 rows, data has 1000
```

Was also still wondering if it might not be worth also implementing `type="link" `also for `nnet::multinom` models in `get_predict.multinom`, so that `nnet::multinom` models behave the same in all respects than `mclogit::mblogit` models. If `X` is the model matrix, making predictions with `type="link"` as in `mclogit::mblogit ` is really just doing

```
betahat <- t(rbind(0, coef(fit_multinom ))) # model coefficients, with expicit zero row added for reference category & transposed
preds_link <- X %*% betahat # predictions on the link scale (with explicit zero for reference level included here, in mclogit::predict.mblogit this level/column is dropped)
colnames(preds_link) <- fit_multinom $lev
```

**Comment by vincentarelbundock** [comment]
No apologies needed. I looooove bug reports! (very useful)

I pushed a commit which should fix this. The bug was related to the fact that your model only has a binary outcome and I didn't expect people to use the `multinom` function with binary outcomes...

For the `type="link"` support, how do you recommend we construct the `X` matrix, allowing for data frames of arbitrary sizes (ex: created by `datagrid()`) and models with or without transformations in the formula?

**Comment by tomwenseleers** [comment]
Ha great - thanks! To construct that `X` matrix - maybe you can use the first bits of the `predict.mblogit `function?
[https://github.com/melff/mclogit/blob/master/pkg/R/mblogit.R](https://github.com/melff/mclogit/blob/master/pkg/R/mblogit.R)

```
predict.mblogit <- function(object, newdata=NULL,type=c("link","response"),se.fit=FALSE,...){
  
  type <- match.arg(type)
  mt <- terms(object)
  rhs <- delete.response(mt)
  if(missing(newdata)){
    m <- object$model
    na.act <- object$na.action
  }
  else{
    m <- model.frame(rhs,data=newdata,na.action=na.exclude)
    na.act <- attr(m,"na.action")
  }
  X <- model.matrix(rhs,m,
                    contrasts.arg=object$contrasts,
                    xlev=object$xlevels
  )
...

```

I was fitting multinomial models on binomial data just to check whether or not the conf intervals are identical.

For the example above a binomial fit on the same data
`fit_glm = glm(cbind(y1,y2) ~ x, family=binomial(logit), data=dat)`
gave me with `emmeans `(calculated on the logit link scale & then backtransformed, ie without having to use the Delta method):
```
as.data.frame(emmeans(fit_glm, ~ x, at=list(x=unique(dat$x)), type="link"), 
              type="response")[400,]
#   x  prob      SE  df asymp.LCL asymp.UCL
# 400 0.118 0.00688 Inf     0.105     0.132
```

Using multinomial fit
`fit_mblogit = mclogit::mblogit(y ~ x, weights=count, from.table=FALSE, dispersion=FALSE, data=dat_long)`

I am able to calculate identical confidence intervals on the link scale & then backtransform to the response scale, i.e. without having to use the Delta method :
```
softmax <- function(x) exp(x) / sum(exp(x)) # softmax function = inverse link function for multinomial (with sum(exp(x)) taken over all outcomes per row)

system.time(preds_latent_backtransformed <- predictions(fit_mblogit, 
                                                        newdata = datagrid(x=unique(dat$x)),
                                                        type = "link") |>  # this is a prediction type that normalizes the log(odds) of the references category to be zero & then drops that category
              # transform(conf.low = predicted - 1.96 * std.error,
              #           conf.high = predicted + 1.96 * std.error) |>
              group_by(rowid) |>
              mutate_at(c("predicted", "conf.low", "conf.high"), function (x) softmax(c(0,x))[-1]) |>
              dplyr::filter(x == 400)) # 0.04s
as.data.frame(preds_latent_backtransformed)
#   rowid type group predicted  std.error statistic       p.value  conf.low conf.high count   x  y
# 1   400 link    y1 0.1177451 0.06627675 -30.38712 8.129214e-203 0.1049064 0.1319233     5 400 y1
```
(the value for the reference outcome level y2 here would still have to be added as 1-the sum of the probs for the other levels)

I think this would be the most sensible way in fact to calculate confidence intervals for multinomial models... At least in spirit it would mirror what is being done for binomial GLMs. What do you reckon?

**Comment by vincentarelbundock** [comment]
Thanks! Bug fixed so I'm closing this. I created a new issue to discuss implementation of `type="link"`: https://github.com/vincentarelbundock/marginaleffects/issues/477
