### ISSUE TITLE
`by` data frame with not covered categories

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/marginaleffects#481]
Currently, categories which are not covered get aggregated in `NA`. As @bwiernik notes:

> One place where post-filtering becomes difficult is when hypothesis is given. Then na.omit() or friends won't work. Perhaps an argument to remove by = NA from the predictions before the hypothesis test?

Initially I wanted to keep the `NA` for diagnostic purposes: It might be good for users to see when their `by` does not encompass all categories.

However, it is true that filtering with `hypothesis` becomes very hard, because labels are composites with `NA` strings.

But I really want to avoid the proliferation of arguments. So perhaps just filter those automatically after all? Need to think about this a bit more.

**Comment by bwiernik** [comment]
Do you have a verbose argument already? If so, maybe give a message or warning that some rows were dropped by `by`?

**Comment by vincentarelbundock** [comment]
There's no `verbose` argument yet.

I'm of two minds about these, without a strong view necessarily. If a package only uses one type of warning or message, then they can all be silenced by adding `|>suppressWarnings` after the call, which seems as easy as `verbose=TRUE`. But maybe it's cleaner to have a `verbose`...

**Comment by vincentarelbundock** [comment]
80cc6511f02392db96e92db0af39006ef9b0450e

A warning is now issued and rows are dropped when the `by` data frame does not cover all rows of the output dataset:

``` r
library(marginaleffects)
library(nnet)
mod <- multinom(factor(gear) ~ mpg + am * vs, data = mtcars, trace = FALSE)
by <- data.frame(
    by = c("4", "5"),
    group = 4:5)
comparisons(mod, variables = "mpg", newdata = "mean", by = by)
#> Warning: The `by` data.frame does not cover all combinations of response levels
#>   and/or predictors. Some estimates will not be included in the
#>   aggregation.
#>    type term   comparison  std.error  statistic   p.value    conf.low
#> 1 probs  mpg 0.0219776556 0.36886586 0.05958170 0.9524888 -0.70098614
#> 2 probs  mpg 0.0002841416 0.02199149 0.01292052 0.9896912 -0.04281839
#>    conf.high by
#> 1 0.74494145  4
#> 2 0.04338668  5
```
