### ISSUE TITLE
`by` with different functions: `sum` instead of `mean`

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/marginaleffects#482]
> Hold on, `by` still isn't doing what I am looking for.
> 
> I want to **sum** across the levels of `group`, not **average** across them. Above, for each value of `cyl`, the predictions for `group = 3` and `group = 4` are being averaged. I want them to be summed.

_Originally posted by @bwiernik in https://github.com/vincentarelbundock/marginaleffects/issues/445#issuecomment-1239815774_

**Comment by vincentarelbundock** [comment]
Need to think of a user interface.

**Comment by bwiernik** [comment]
I think the call for sum() vs mean () is probably specific to `group` in categorical models, so an argument about how to handle group summarizing might be sufficient

**Comment by vincentarelbundock** [comment]
I worked on this today but it is quite a bit more tricky than I anticipated. The day job also adds a lot of pressure these days, so I may not have a solution to this before 2-3 weeks.

Notes to self:

* See the `byfun` branch
* `predictions()` is trivial. We can call `get_by()` at the very end and everything is fine.
*  `comparisons()` is quite tricky. 
    - In some known cases, we want `by` to change the `transform_pre` function on the fly. For ex, when the statistic is non-collapsible, we can't compute it and then take the average. Instead, we need to change the function to an `avg` analogue that takes the mean of vectors before computing the statistic.
    - In some other cases, we want to apply `by` at the very end, as in `predictions()`.
* If we introduce a new `byfun` argument, how does that interact with `transform_pre`?
* TODO: Explore if we may be able to avoid introducing a new `byfun` argument altogether, and use `transform_pre` and `by` instead. For example:
     - `transform_pre = \(hi, lo) sum(hi - lo), by = "response"`

**Comment by vincentarelbundock** [comment]
@bwiernik, could you try the new `byfun` argument of the `predictions()` function?

``` r
library(nnet)
library(marginaleffects)

mod <- multinom(factor(cyl) ~ mpg + am, data = mtcars, trace = FALSE)

by <- data.frame(
    by = c("4,6", "4,6", "8"),
    group = as.character(c(4, 6, 8)))

predictions(mod, newdata = "mean")
#>   rowid  type group  predicted  std.error statistic      p.value   conf.low
#> 1     1 probs     4 0.02000367 0.07259636 0.2755465 7.828964e-01 -0.1222826
#> 2     1 probs     6 0.89583968 0.14111052 6.3484967 2.174291e-10  0.6192681
#> 3     1 probs     8 0.08415665 0.12180769 0.6908977 4.896298e-01 -0.1545820
#>   conf.high      mpg      am cyl
#> 1 0.1622899 20.09062 0.40625   6
#> 2 1.1724112 20.09062 0.40625   6
#> 3 0.3228953 20.09062 0.40625   6

predictions(mod, newdata = "mean", byfun = sum, by = by)
#>    type  predicted std.error statistic      p.value   conf.low conf.high  by
#> 1 probs 0.91584335 0.1218077 7.5187647 5.529622e-14  0.6771047 1.1545820 4,6
#> 2 probs 0.08415665 0.1218077 0.6908977 4.896298e-01 -0.1545820 0.3228953   8

predictions(mod, newdata = "mean", byfun = mean, by = by)
#>    type  predicted  std.error statistic      p.value   conf.low conf.high  by
#> 1 probs 0.45792167 0.06090384 7.5187647 5.529622e-14  0.3385523 0.5772910 4,6
#> 2 probs 0.08415665 0.12180769 0.6908977 4.896298e-01 -0.1545820 0.3228953   8
```

I’m not sure the same kind of aggregation makes sense of contrasts, so I will not implement this in the `comparisons()` or `marginaleffects()` functions, until I see a compelling use-case.

**Comment by vincentarelbundock** [comment]
Closing now to clean up the repo, but feel free to open a new one or keep the discussion going if necessary.
