### ISSUE TITLE
Document extension mechanism

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/marginaleffects#490]
Use latent `multinom` as an example:

```r
    if (is_latent && is_mclogit) {
        missing_level <- as.character(unique(insight::get_response(model)))
        missing_level <- setdiff(missing_level, colnames(pred))
        if (length(missing_level == 1)) {
            pred <- cbind(0, pred)
            colnames(pred)[1] <- missing_level
            pred <- pred - rowMeans(pred)
        } else {
            stop("Unable to compute predictions on the latent scale.", call. = FALSE)
        }

    } else if (is_latent && is_nnet) {
        inverse_softMax <- function(mu) {
            log_mu <- log(mu)
            return(sweep(log_mu, 1, STATS = rowMeans(log_mu), FUN = "-"))
        }
        pred <- inverse_softMax(pred)
    }
```

**Comment by vincentarelbundock** [comment]
@tomwenseleers

I'm very sorry this took so long, but "real" life/work has been kind of overwhelming in the past few months.

I finally got around to fixing the extension mechanism and writing a vignette: https://vincentarelbundock.github.io/marginaleffects/articles/extensions.html

I think you'll see that it is *very* easy to support new models from scratch, but also to override some of the methods. In the vignette, I give an example where we override the `get_predict` method by creating a new inherited model class.

In just a few lines of code, we can estimate predictions (or slopes, etc.) for `mblogit` on the centered link scale.

My current idea is to add a new section to the vignette with user-written methods to override certain model types in useful ways. The extensions in your PR would very nicely fit in this project, and it would be a neat place to hold them to make them available to the community. It would be easy to just add to the vignette.

What do you think?

**Comment by tomwenseleers** [comment]
Hi Vincent, Yes, I think that's a good idea! I just looked at the documentation and that mechanism looks fine! Is your idea that in this way also other package authors could put the marginaleffects entirely in their own package, without requiring everything to be put in marginaleffects? For nnet::multinom I also had to write a faster vcov() method (written in Rcpp) as the one that was currently in nnet was really slow (mine was 80x faster for my problem size). But that's also supported, by the looks of it, right? I had my code more or less finished (though for confidence intervals calculated on the additive logratio scale I still had problems with underflows or overflows if probabilities get close to 0 or 1, so was still going to fix that), but got stuck at writing those unit tests (mainly for lack of time) - would you still require those? Guess not right?

**Comment by vincentarelbundock** [comment]
Yes, exactly! All you have to do is name your function `get_vcov.customclass` and extracting the variance-covariance matrix should fly :)

Yeah, I think we can close the PR. But if you can give me "clean" versions of your functions, I could host them on the `marginaleffects` website for other users who might be interested. Let me know if you'd like to do that.

**Comment by tomwenseleers** [comment]
Yes close that PR then for now! I'll send you tidied up versions of my functions then later on! Probably it would be most elegant in fact if I would put those modifications of the nnet package in some separate package nnet2 or fastnnet or something (since the package author doesn't get back to me, so no chance to have it fixed there it seems)... Super busy with teaching for the moment unfortunately, so I hope in a few weeks would still be OK for you? Thanks in any case for organising this extension mechanism!

**Comment by vincentarelbundock** [comment]
Yep, all of this sounds great. Very busy here as well, so no rush.
