### ISSUE TITLE
{marginaleffects} update breaks test in {insight}

### ISSUE THREAD

**Issue by strengejacke** [vincentarelbundock/marginaleffects#495]
This test no longer works since the latest update:
https://github.com/easystats/insight/blob/main/tests/testthat/test-marginaleffects.R

Not recognized yet because it's skipped on CRAN.

What's the best way to fix this? Are _insight_ functions still working as intended?

**Comment by vincentarelbundock** [comment]
Thanks. I opened a PR on `insight`. Will merge when the tests are done running.
