### ISSUE TITLE
`plot_cap()` could have more features

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/marginaleffects#498]
This is a super cool package:

https://cran.r-project.org/web/packages/interactions/vignettes/interactions.html

* `threenum`: -sd, mean, +sd

**Comment by iago-pssjd** [comment]
I am not sure if open a new issue or comment on this one. 

First, on the vignette you link, the argument `modx.values` specifying which values of the `modx` variable you want to print is great.

Actually I would like to ask for a related FR (if it is not possible already). For the argument `condition`
> String or vector of two strings. The first is a variable name to be displayed on the x-axis. The second is a variable whose values will be displayed in different colors. Other numeric variables are held at their means. Other categorical variables are held at their modes. Other numeric variables are held at their means.

It would be great to have the option either to include other categorical variables which would be passed to `facet_wrap` (or `facet_grid`). I have tried `plot_cap()+ facet_wrap()` but id does not work. Or to have an option extending in some way the  `modx.values` in the `interactions` package (or also in `sjPlot`, where one can do `"barthtot [30,50,70]"`, see https://strengejacke.github.io/sjPlot/articles/plot_interactions.html#three-way-interactions) to fix a specific value. Therefore, for the second variable in `condition` we could choose multiple values (like `"barthtot [30,50,70]"` or `modx.values = c(4, 5, 6, 8)`, and for the next variables we could choose a unique variable). For example we could do
```
mod <- lm(mpg ~ hp * wt * am, data = mtcars)
plot_cap(mod, condition = c("hp", "wt [1, 3, 5]", "am = 0"))
```

**Comment by vincentarelbundock** [comment]
@iago-pssjd This should now be possible using the development version from Github. See the new vignette:

https://vincentarelbundock.github.io/marginaleffects/articles/plot.html

**Comment by iago-pssjd** [comment]
@vincentarelbundock 
Great! 
PD: Although not clear in the vignette, wher you claim
> We can include a 3rd conditioning variable, specify what values we want to consider, and use one of several string shortcuts for common reference values (“threenum”, “minmax”, “quartile”, etc.):

but the following examples use only 2 variables:
```r
plot_cap(mod, condition = list(hp = 110:120, "wt" = "threenum")) /

plot_cap(mod, condition = list("hp", "wt" = "minmax")) /

plot_cap(mod, condition = list("hp", "wt" = fivenum))
```
Further, it is unclear in the vignette what is `fivenum`. I see that it is a `stats` function and then I see we can pass to the conditioning variables a string (like `"threenum"` or `"minmax"`), a function (like `fivenum`) or, (after testing) also a vector `(like `"wt" = c(1,2,3,5)`)`. May it be documented on `?plot_cap` more details on it, what other strings, what kind of functions and what other options there are?

Many thanks for your great packages!

**Comment by iago-pssjd** [comment]
Another thing. Let's say we have
```r
mod <- lm(mpg ~ hp * wt * factor(cyl), data = mtcars)
plot_cap(mod, condition = list("hp", "cyl", "wt" = "minmax"))
```
![image](https://user-images.githubusercontent.com/40892925/198559851-572be9f4-fccd-48a5-8bb7-6b8c710b1cb9.png)
Then, we have facets labelled by `Min` and `Max` or whatever...

Would you mind to add a `labeller` option to `plot_cap` so it would be passed to `facet_wrap/grid` argument `labeller` allowing us to customize these labels?

Many thanks!

**Comment by vincentarelbundock** [comment]
Thanks for this feedback!

Try: `?fivenum` It's a useful function in base `R`.

I tried to clarify the vignette and documentation, and added some examples.

Unfortunately, I do not think I will implement the other features. The problem is that data visualization is an intensely personal and context-specific process, and the number of feature requests is infinite: Change colors, bolder lines, arrows, reorganize facets, use dotted lines instead of colors, etc. This is a slippery slope that leads to an unmaintainable `plot_cap()` function with 50 arguments to satisfy the needs of everyone.

Personally, I think that functions like `plot_cap()` are useful to iterate quickly between different plots. However, for publication, I always construct plots "by hand" with `ggplot2`, which allows me full customization.

Thankfully, you can use `plot_cap()` to make even that full-custom process easier by setting the argument `draw=FALSE`. This will return the underlying data, which you can then plot however you want.
