### ISSUE TITLE
plot_cap() x-axis labels, plm models

### ISSUE THREAD

**Issue by ebkreyson** [vincentarelbundock/marginaleffects#505]
Getting a weird issue where the x-axis labels for a plot from plot_cap() are in the incorrect order. The issue is exclusive to plm models and is likely related to using a non-default reference level for whatever factor is being used with the "condition" argument.

Take the following two models as examples
```
#Create dataframe
ID <- rep(c('A','B','C','D','E','F'), each=4)
Time <- rep(c(1:4), 6)
factor1 <- rep(c("c","0","1"), each=8)
factor2 <- rep(c(0, 0, 1, 1), 6)
y <- c(
  rep(c(5, 5, 5, 5), 2),
  rep(c(2, 2, 10, 20), 2),
  rep(c(3, 3, 15, 5), 2)
)
df <- as.data.frame(cbind(ID,Time,factor1,factor2,y))

#Reclass dataframe columns
df$y <- as.numeric(df$y)
df$factor1 <- as.factor(df$factor1)
df$factor1 <- relevel(df$factor1, ref = "c")
df$factor2 <- as.factor(df$factor2)

#Make the models, must have "plm" installed
library(plm)
glm <- glm(y ~ factor1 * factor2, data = df)
plm <- plm(y ~ factor1 * factor2, data = df, model = "random", index = c("ID","Time"))

#Make the plots
plot_glm <- plot_cap(glm, condition = "factor1")
plot_plm <- plot_cap(plm, condition = "factor1")
```

The above example will yield two identical plots, but plot_glm will have x_axis labels in the correct order of: "c", "0", "1", while plot_plm will have labels in the incorrect order of "0", "1", "c".

The issue is likely caused by the relevel() line, where before and after changing the reference level:
```
> levels(df$factor1)
[1] "0" "1" "c"
> df$factor1 <- relevel(df$factor1, ref = "c")
> levels(df$factor1)
[1] "c" "0" "1"
```

Somehow plot_cap() is ignoring the relevel. The issue also extends to plot_cme() based on the actual data I'm using for my own project. In my case it was obvious that something was wrong with the plot labels, but others might not be so lucky.

**Comment by vincentarelbundock** [comment]
Thanks for the report.

This is a bug in the `get_data` function of the upstream package `insight`. To fix it, someone would have to diagnose and improve the function here: <https://github.com/easystats/insight/blob/main/R/get_data.R#L811>

Here is a MWE example which shows that the factor variables are converted to character when we extract the data used to fit the model with the `get_data()` function:

``` r
library(plm)
library(insight)

ID <- rep(c('A','B','C','D','E','F'), each=4)
Time <- rep(c(1:4), 6)
factor1 <- rep(c("c","0","1"), each=8)
factor2 <- rep(c(0, 0, 1, 1), 6)
y <- c(
  rep(c(5, 5, 5, 5), 2),
  rep(c(2, 2, 10, 20), 2),
  rep(c(3, 3, 15, 5), 2)
)
df <- as.data.frame(cbind(ID,Time,factor1,factor2,y))
df$y <- as.numeric(df$y)
df$factor1 <- as.factor(df$factor1)
df$factor1 <- relevel(df$factor1, ref = "c")
df$factor2 <- as.factor(df$factor2)

mod <- plm(y ~ factor1 * factor2, data = df, model = "random", index = c("ID","Time"))

get_data(mod) |> str()
#> 'data.frame':    24 obs. of  5 variables:
#>  $ y      : num  5 5 5 5 5 5 5 5 2 2 ...
#>  $ factor1: chr  "c" "c" "c" "c" ...
#>  $ factor2: chr  "0" "0" "1" "1" ...
#>  $ ID     : chr  "A" "A" "A" "A" ...
#>  $ Time   : chr  "1" "2" "3" "4" ...
#>  - attr(*, "is_subset")= logi FALSE
```

**Comment by ebkreyson** [comment]
I'm fairly certain I see the issue in get_data.plm from "insight": they use cbind() on Line 827, which converts factors into characters. Changing cbind() to data.frame() could be an easy fix, but I don't know if I'm oversimplifying this.

I'll go ahead and post the issue over on the insight page and see if it gets any traction.

**Comment by vincentarelbundock** [comment]
Thanks again for the report. Given your comment, I assume that things are now working as expected in `plot_cap()` too, so will close this.

Thanks for using the package and reporting problems with a replicable example. This is very useful.

**Comment by ebkreyson** [comment]
Posted this in the ['insight' thread](https://github.com/easystats/insight/issues/665), but the most recent change to 'insight' has fixed the issue. Granted, the CRAN version still has the same issue until it gets updated, but the code downloaded directly from GitHub is now producing plots with the correct labels.
