### ISSUE TITLE
Scale at which marginalization happens

### ISSUE THREAD

**Issue by stefgehrig** [vincentarelbundock/marginaleffects#508]
A great package. I just came across behavior of the `marginalmeans()` function and the super useful `by` option that was unexpected for me and wanted to make sure that this not simply an error or misunderstanding of my own.

(Somehwat) minimal example:

```
library(tidyverse)       
library(marginaleffects) 

set.seed(123)
df <- tibble(
  id = rep(1:5, each = 2e2),
  city = ifelse(id <= 3, "Denver", "Paris"),
  y  = rbinom(1e3, 1, prob = plogis(-3 + 1/2 * id)) 
  ) %>% mutate(id = factor(id))

df %>% 
  group_by(city) %>% 
  summarise(mean(y))

# city        `mean(y)`
# Denver      0.123
# Paris       0.332
```
So these are the marginal probabilities of the binary event we created in each city. Predicting `id`-level probabilities via logistic regression, and averaging over them, we get the same results (as expected by the rules of maximum likelihood):

```
m <- glm(y ~ id, data = df, family = binomial)

df <- df %>% mutate(pred = predict(m, type = "response"))
df %>% group_by(
  city
) %>% summarise(mean(pred))

# city   `mean(pred)`
# Denver        0.123
# Paris         0.332
```

It is still relatively easy to get uncertainty estimates for these marginal means "by hand". But since my models were much more complex, I wanted to use `marginaleffects::marginalmeans()` for a short-cut. I was surprised to see the following results: 

```
by <- tibble(
  id = 1:5,
  by = ifelse(id <= 3, "Denver", "Paris"), 
)
marginalmeans(m,
              by = by)

# by marginalmean   conf.low conf.high      p.value
# 1 Denver   0.1154006 0.09134567 0.1447807 5.722380e-53
# 2 Paris    0.3307775 0.28612015 0.3787073 4.447401e-11
```
So these marginal means are different from the ones calculated above. Why is that? Obviously, the function is averaging on the logit scale first and then back-transforming to the probability scale, as can be verified easily:

```
df <- df %>% mutate(pred_logit = predict(m, type = "link"))
df %>% group_by(
  city
) %>% summarise(plogis(mean(pred_logit)))
# city   `plogis(mean(pred_logit))`
# <chr>                       <dbl>
# 1 Denver                      0.115
# 2 Paris                       0.331
```

Now my questions are:

1) Is this desired behavior? Looking at logistic random effects models in analogy, for example, the term "marginalization" usually means to marginalize over the distribution of random effects *on the response scale* (e.g., via simulation of numerical integration), rather than averaging on the logit scale (effectively setting the random effet to zero) with a transformation *afterwards*. Also, the marginalized outcome on the response scale seems to be more natural for interpretation, I believe, than a transformation of a logit-average. Maybe there should at least be a warning about what is happening?

2) Is there a way to obtain what I need via `marginaleffects` or alternatives like `emmeans`? That is, not only the estimates, but also CIs or SEs?

Thanks a lot!

**Comment by vincentarelbundock** [comment]
The order of operations is:

1. Build grid
2. Predict on link scale
3. Average
4. Back transform to response scale

This ensures that, for example, (averaged) predictions in a logit model remain in the [0,1] interval. I'm not 100% sure what you need. Is this it?

1. Build grid
2. Predict on response scale (with `predict(model, type = "response")`
3. Average

This could produce nonsense (out of bounds) results in some cases, no?

**Comment by vincentarelbundock** [comment]
Arrgh, tried to edit and deleted.

Current order is:

1. Build grid
2. `predict(type = "link")`
3. Average predictions
4. Compute standard errors and confidence intervals
5. Backtransform

IIUC, you want to change step 2 to be `predict(type="response")` instead, or you want to put the backtransform between steps 2 and 3.

One problem with this is that bounds of the confidence intervals could be outside the [0,1] interval for logit models (not the average probability, obviously, as per my now deleted comment).

Is that what you want.

**Comment by stefgehrig** [comment]
Thank you for the quick response! I understand, so the problem I see is that the code `marginalmeans(..., by = X , type = "response")` suggests that the function returns the marginal means for the specified levels of X on the response scale. So, in my data example, I would expect to get estimates for 

$\mathbb{P}(Y=1|\text{city} = \text{Denver})$ and $\mathbb{P}(Y=1|\text{city} = \text{Paris})$. These are *marginal* with respect to `id`. That's not what the function returns. Instead, the function returns

$\text{logit}^{-1}(\frac{\text{logit}(\mathbb{P}(Y=1|\text{id} = 1) + \text{logit}(\mathbb{P}(Y=1|\text{id} = 2) + \text{logit}(\mathbb{P}(Y=1|\text{id} = 3))}{3} )$ and $\text{logit}^{-1}(\frac{\text{logit}(\mathbb{P}(Y=1|\text{id} = 4) + \text{logit}(\mathbb{P}(Y=1|\text{id} = 5))}{2} )$.

Obviously, in a linear model, the second approach would also lead to the marginal means on the city-level, but for logistic case here, there is a difference, as can be seen in the calculations.

So, yes, I think that `predict(type = "response")` would be sensible before averaging. I do not really understand yet the problem with the confidence intervals you mention. Whether "sensible" confidence result depends on the method of estimation / approximation used, doesn't it?

What do you think? Or do others have an opinion?

**Comment by vincentarelbundock** [comment]
The issue I was trying to explain is that if you compute standard errors by applying the delta method directly to the averaged probabilities, and then add +/-1.96*se (or whatever other significance threshold) to the marginal means, you will often get confidence intervals that stretch outside [0,1].

If you read the "Timing is everything" section of the `emmeans` vignette that you linked to above, you will see that `emmeans` proceeds uses the same order of operations.

It would not be super difficult to allow users more control over this, and I am totally open to doing that. But I would like to see a statistical argument to prefer the other approach, beyond "it yields different results."

**Comment by stefgehrig** [comment]
Thanks again!! I think that flexibility would be great. Hm, I understand there to be quite good statistical reasons, because in my example, the result the function is giving is *not* the marginal city-level probability. But then again, for most other cases, it might not play a role. So if I am the only person confused by this, then there is probably no need to change something ;)

**Comment by luozhy88** [comment]
+1

**Comment by vincentarelbundock** [comment]
I think that commit <https://github.com/vincentarelbundock/marginaleffects/commit/20f354f9d960145e0cf667dd06117512564f22f3> should fix this issue. The new behavior is:

  - If `type=NULL` and the default type for that model object is `response`, then we do as usual and try to do the backtransform, since this is likely the most common use-case.
  - If the user specifies a value of `type="response"` (or any other) explicitly, then we don’t try to be clever and just make predictions directly on the `type` scale.



``` r
library(marginaleffects)

df <- data.frame(id = rep(1:5, each = 2e2))
df$city = ifelse(df$id <= 3, "Denver", "Paris")
df$y <- rbinom(1e3, 1, prob = plogis(-3 + 1/2 * df$id))
df$id <- factor(df$id)
ma <- aggregate(y ~ city, FUN = mean, data = df)

m <- glm(y ~ id, data = df, family = binomial)
by <- data.frame(
  id = 1:5,
  by = ifelse(1:5 <= 3, "Denver", "Paris"))
mm <- marginalmeans(m, by = by, type = "response")

ma
#>     city         y
#> 1 Denver 0.1383333
#> 2  Paris 0.3800000

mm
#>       by marginalmean  std.error
#> 1 Denver    0.1383333 0.01391140
#> 2  Paris    0.3800000 0.02384875
```

Closing the issue to clean up the repo, but feel free to keep commenting or open a new issue if this does not solve the problem, or if you want to discuss further.
