### ISSUE TITLE
bug: `plm` with unbalanced panel

### ISSUE THREAD

**Issue by chsuong** [vincentarelbundock/marginaleffects#510]
Thanks so much for a great package. I wondered if the commands `plot_cme` and `plot_cme` are supposed to work for plm models with unbalanced panel data. When I try them with unbalanced panel data, I get the response 
`Error in data.frame(..., check.names = FALSE) : arguments imply differing number of rows: 3326, 4979` and was wondering if this is related to my data frame, which is an unbalanced panel with n = 67, T = 1-102, N = 3326.

**Comment by vincentarelbundock** [comment]
could you supply an ultra-simple / minimal example using publicly available data? Maybe one of the built-in models in the `plm` package or something from Rdatasets? 

https://vincentarelbundock.github.io/Rdatasets/articles/data.html

**Comment by chsuong** [comment]
I think I figured out the error. `plot_cme` works fine when I run a plm model with random effects on a *subsetted* data that includes only the variables that go into the model. It produces the error I mentioned when I run with a plm model with random effects on the data frame that includes variables that are *not* used in the model. I will try reproducing the error later. Anyway, thanks for a great package!

**Comment by vincentarelbundock** [comment]
Closing to keep the repo clean, but I'll be happy to re-open if/when someone supplies a minimal replicable example using the latest development versions of marginaleffects and plm
