### ISSUE TITLE
For `betareg` methods, why only include mean coefficients in `set_coef()`?

### ISSUE THREAD

**Issue by ngreifer** [vincentarelbundock/marginaleffects#511]
Hi Vincent,

For `betareg` objects, the `set_coef()` method (and `get_coef()` method) only operate on the coefficients for the mean, which is fine for predictions, but given the `deltamethod()` function is more general than that and users might want to do inference on a quantity computed from the scale coefficients, might it not make sense to include those as well? They are naturally included in the `vcov()` method for `betareg` objects. I'm not sure if you have other methods that do this (i.e., the `set_coefs()` and `get_coefs()` methods ignore certain legitimate coefficients), but you might want to look into them as well.

Noah

**Comment by vincentarelbundock** [comment]
Thanks, I'll look into this when I have a chance. But just to clarify the level of urgency: this is better thought of as a "feature request" rather than a "bug report", right?

**Comment by vincentarelbundock** [comment]
I'd be very happy to merge a PR if you have time (I'm not super familiar with these objects). If you don't, I'll probably be able to look into this eventually, but it might take a little while because the day job is a bit crazy these days.

**Comment by vincentarelbundock** [comment]
https://github.com/vincentarelbundock/marginaleffects/pull/512
