### ISSUE TITLE
interactions using multinom not supported in marginaleffects package

### ISSUE THREAD

**Issue by imjenniferim** [vincentarelbundock/marginaleffects#517]
The package description says multinom is supported by marginaleffects but it doesn't seem to be supported for including interaction terms. When i run marginaleffects(model), it seems to drop the interaction terms in the output. I tried to run marginaleffects for a multinomial interaction model using effect and condition arguments and was given the following error message:

These arguments are not supported for models of class `multinom`: effect, condition. Please file a request on Github if you believe that additional arguments should be supported: https://github.com/vincentarelbundock/marginaleffects/issues

**Comment by vincentarelbundock** [comment]
What do you mean by "drop interaction terms in the output"? The ˋmarginaleffects` computes the slope of the outcome function with respect to the predictors. So of course there will be no interaction term in the output, just the slope estimates. What specific mathematical quantity were you expecting?

Can you supply an ultra-minimalist example using publicly available data like the ˋmtcars` dataset?

**Comment by vincentarelbundock** [comment]
The problem is not `R`, the problem is that I don’t understand *mathematically* what you mean by “the full marginal effects for interaction terms.”

You can do a *ton* of different things, as explained in the vignettes. For example:

``` r

library(nnet)
library(marginaleffects)

test <- multinom(cyl ~ am*vs, data=mtcars)

# What happens to the probability of each outcome level when am increases from 0 to 1, at different values of vs and hp?
comparisons(
    test,
    variables = "am",
    newdata = datagrid(vs = 0:1, hp = 110))
#> Warning: Some of the variable names are missing from the model data: hp
#>   rowid  type group term contrast    comparison  std.error  statistic
#> 1     1 probs     4   am    1 - 0  1.666751e-01 0.15215076  1.0954600
#> 2     2 probs     4   am    1 - 0  5.714409e-01 0.18704193  3.0551488
#> 3     1 probs     6   am    1 - 0  5.000039e-01 0.20412502  2.4494981
#> 4     2 probs     6   am    1 - 0 -5.714191e-01 0.18704312 -3.0550126
#> 5     1 probs     8   am    1 - 0 -6.666789e-01 0.19245201 -3.4641308
#> 6     2 probs     8   am    1 - 0 -2.183405e-05 0.00176618 -0.0123623
#>        p.value     conf.low    conf.high    predicted predicted_hi predicted_lo
#> 1 0.2733151607 -0.131534938  0.464885079 3.455332e-04 1.666775e-01 2.381393e-06
#> 2 0.0022494891  0.204845473  0.938036353 9.983640e-01 9.999999e-01 4.285590e-01
#> 3 0.0143055457  0.099926167  0.900081554 7.670515e-04 5.000082e-01 4.302241e-06
#> 4 0.0022505108 -0.938016853 -0.204821305 1.635922e-03 9.135012e-08 5.714192e-01
#> 5 0.0005319478 -1.043877938 -0.289479924 9.988874e-01 3.333144e-01 9.999933e-01
#> 6 0.9901365616 -0.003483484  0.003439816 7.197414e-08 4.938773e-12 2.183406e-05


# What is the predicted probability of each outcome level at specific values of the regressors?
predictions(
    test,
    newdata = datagrid(vs = 0:1, am = 1, hp = 120))
#>   rowid  type group    predicted    std.error    statistic    p.value
#> 1     1 probs     4 1.666775e-01 1.521501e-01 1.095480e+00 0.27330625
#> 2     2 probs     4 9.999999e-01 1.142438e-04 8.753210e+03 0.00000000
#> 3     1 probs     6 5.000082e-01 2.041241e-01 2.449530e+00 0.01430429
#> 4     2 probs     6 9.135012e-08 1.142424e-04 7.996168e-04 0.99936200
#> 5     1 probs     8 3.333144e-01 1.924506e-01 1.731948e+00 0.08328280
#> 6     2 probs     8 4.938773e-12 1.006626e-09 4.906265e-03 0.99608538
#>        conf.low    conf.high    cyl vs am  hp
#> 1 -1.315313e-01 4.648862e-01 6.1875  0  1 120
#> 2  9.997760e-01 1.000224e+00 6.1875  1  1 120
#> 3  9.993219e-02 9.000841e-01 6.1875  0  1 120
#> 4 -2.238196e-04 2.240023e-04 6.1875  1  1 120
#> 5 -4.388179e-02 7.105106e-01 6.1875  0  1 120
#> 6 -1.968012e-09 1.977889e-09 6.1875  1  1 120

# What happens to the probability of each outcome level when am and vs BOTH increase from 0 to 1 simultaneously, and all other variables are held at their means or modes?
comparisons(
    test,
    variables = c("am", "vs"),
    newdata = "mean")
#>   rowid  type group        term contrast_am contrast_vs    comparison
#> 1     1 probs     4 interaction       1 - 0       1 - 0  9.999975e-01
#> 2     1 probs     6 interaction       1 - 0       1 - 0 -4.210891e-06
#> 3     1 probs     8 interaction       1 - 0       1 - 0 -9.999933e-01
#>      std.error     statistic   p.value     conf.low    conf.high  predicted
#> 1 0.0004598711  2.174517e+03 0.0000000  0.999096196  1.000898858 0.86128699
#> 2 0.0006095947 -6.907689e-03 0.9944885 -0.001198995  0.001190573 0.08152549
#> 3 0.0007462645 -1.339998e+03 0.0000000 -1.001455968 -0.998530665 0.05718752
```

There are hundreds of other queries we could make up. To answer your question, I need to know *exactly* what quantity you are trying to estimate, not just a vague expression like “the full marginal effects for interaction terms.” As noted in the docs, “marginal effects” is a very ambiguous expression.

**Comment by imjenniferim** [comment]
Oh, this is helpful. I wanted to understand what happens to the probability of  each outcome level when one variable changes from 0 to 1 and when two variables both change from 0 to 1 simultaneously. It looks like the comparisons function is what I want to use. I just didn't understand it before. Thanks!

**Comment by vincentarelbundock** [comment]
Great news! Glad we found a solution.

**Comment by imjenniferim** [comment]
Hi Vincent,

I am having a strange issue with replicating results. I was able to complete my analysis using the code for the third example you provided, as I was interested in seeing what would happen to the outcome when the values of two variables change simultaneously. I was able to get results back in October. Recently, we had to drop a variable so I tried to rerun the models and noticed I wasn't able to produce results in the same format. I tried testing my code by running the example code using the mtcars dataset and I also couldn't get the same results as what you have above, which is so strange because I was able to before! Below are the results I get using the same code, which if I am understanding correctly shows the results for changing the values of one variable at a time, and not two simultaneously. Do you know what may be causing the issue? I would appreciate any help! Thank you! 

test <- multinom(cyl ~ am*vs, data=mtcars)

> comparisons(
+     test,
+     variables = c("am", "vs"),
+     newdata = "mean")

     rowid  type group term contrast    comparison  std.error     statistic      p.value
1     1 probs     4   am    1 - 0  0.9526802479 4.89261792   0.194717892 8.456138e-01
2     1 probs     4   vs    1 - 0  0.9980184727 0.83064245   1.201501883 2.295566e-01
3     1 probs     6   am    1 - 0 -0.0708431777 5.79387475  -0.012227254 9.902443e-01
4     1 probs     6   vs    1 - 0  0.0008688707 0.83217010   0.001044102 9.991669e-01
5     1 probs     8   am    1 - 0 -0.8818370702 7.52326667  -0.117214650 9.066900e-01
6     1 probs     8   vs    1 - 0 -0.9988873434 0.07401667 -13.495437695 1.663642e-41
     conf.low  conf.high  predicted predicted_hi predicted_lo    cyl      am     vs   eps
1  -8.6366747 10.5420352 0.86128699 9.984416e-01 0.0457613696 6.1875 0.40625 0.4375 1e-04
2  -0.6300108  2.6260478 0.86128699 9.983640e-01 0.0003455332 6.1875 0.40625 0.4375 1e-04
3 -11.4266290 11.2849427 0.08152549 1.541707e-03 0.0723848846 6.1875 0.40625 0.4375 1e-04
4  -1.6301546  1.6318923 0.08152549 1.635922e-03 0.0007670515 6.1875 0.40625 0.4375 1e-04
5 -15.6271688 13.8634946 0.05718752 1.667557e-05 0.8818537458 6.1875 0.40625 0.4375 1e-04
6  -1.1439573 -0.8538173 0.05718752 7.197414e-08 0.9988874153 6.1875 0.40625 0.4375 1e-04

**Comment by vincentarelbundock** [comment]
Apologies, `marginaleffects` is still a relatively young package, and I had to release a new version with a small breaking change. You now need the `cross=TRUE` argument if you want to estimate the effect of two simultaneous changes (also need `type="probs"` for this model type):

```r
comparisons(
     test,
     variables = c("am", "vs"),
     type = "probs",
     cross = TRUE,
     newdata = "mean")
```

**Comment by imjenniferim** [comment]
Oh, I am so relieved! Thank you so much!
