### ISSUE TITLE
Multiplicity adjustments

### ISSUE THREAD

**Issue by moleps** [vincentarelbundock/marginaleffects#521]
I have a mixed effects negative binomial model where I need to calculate differences between three different groups at 5 different time points. I run the following pseudo code:

marginaleffects::comparisons(mod,variables =  list(group="pairwise"),by="time")

Big question now - are these p-values adjusted for multiplicity or not? I've been reading the documentation but can't find any information on it and presume that it is not adjusted - but would be nice to know for certain before going wild with p.adjust

**Comment by vincentarelbundock** [comment]
They are *not* adjusted for multiplicity.

**Comment by moleps** [comment]
Thx-would that be an option for future updates or do you think it is preferable to use p.adjust from base R? Could be an issue that it is easy to run p.adjust for all results whereas the p-values, from I understand, should only be adjusted for each timepoint.

**Comment by vincentarelbundock** [comment]
This is an interesting suggestion. So far, I've just assumed that `p.adjust` would be sufficient. 

I can see why implementing multiplicity adjustment in the package would be convenient, but it seems like a lot of work to accommodate all the different applications and contexts. Plus, frankly, I'm not expert enough to be highly confident that my implementation would 100% correct and would cover all the corner cases.

If an expert volunteers to work on the implementation, I would be happy to discuss it and guide the code infrastructure (discussion about design would have to happen *before* the actual coding starts). Realistically, though, unless someone volunteers to do a lot of work for this, I am unlikely to implement it myself.

**Comment by bersco** [comment]
From my experience, the `emmeans` package does different types of multiple comparisons adjustments very well. It's relatively simple to implement so I don't think it needs to be implemented here.

**Comment by vincentarelbundock** [comment]
Sure, but `emmeans` does not support all the same models, and does not compute all the same quantities. So there would be a case for implementing this here too. Also, switching back and forth between packages is annoying...

**Comment by vincentarelbundock** [comment]
tukey and sidak may be easy to implement:

https://github.com/strengejacke/ggeffects/pull/285/files

**Comment by vincentarelbundock** [comment]
There are now 7 different multiple comparisons adjustment methods available in the development version of `marginaleffects`. This is installable right now from Github and will be on CRAN in about 1 month.

See the `p_adjust` argument in most functions. Docs on the development website: https://vincentarelbundock.github.io/marginaleffects/dev/
