### ISSUE TITLE
Support for objects from `rms` package

### ISSUE THREAD

**Issue by ngreifer** [vincentarelbundock/marginaleffects#522]
The `rms` package is pretty widely used as I understand it, and it would be nice to have support in `marginaleffects`. I don't think it would be too hard. The primary modeling functions are `ols()` for linear models, `lrm()` for binary and ordinal logistic regression models, `orm()` for ordinal regression models, and `cph()` for Cox models. (Since you don't support `survival::coxph()` you can maybe do without supporting `cph()`.)

These models work pretty similarly to `glm()` objects. There are a few things to be aware of:
* The `predict` methods for these use their own `type` argument, not the usual ones. But they do map on to the usual ones. For example, for the linear predictor (including for `ols()` models), you need `type = "lp"`; for predicted probabilities from `lrm()`, you need `type = "fitted"`.
* They are not compatible with `sandwich()`.
* `lrm()` supports binary *and* ordinal regression, so you need to check on which since you treat ordinal models differently.
* By default, `predict()` and `vcov()` don't consider all groups/breakpoints for ordinal regression models. There are arguments you can supply to ensure all groups/coefficients are returned.

I attempted to make some changes in a fork, but there were some internal files I couldn't parse well enough to know if I was doing it right, so I didn't finish the job.

**Comment by vincentarelbundock** [comment]
Looks like pretty much all the `rms` models work out-of-the-box, so we probably don't need to change much. You can try this branch:

 https://github.com/vincentarelbundock/marginaleffects/pull/526

And look at the new test file in that branch for some example models that seem to work (at first glance; I haven't done any serious checking).

**Comment by ngreifer** [comment]
Looks good; a few changes.

For `orm` and `lrm` models, the `type` argument should accept `"mean"`, which should maybe be the default when the outcome is numeric and not ordinal. That may be trying to be too smart, though. `orm()` and `lrm()` can be used on regular continuous numeric outcomes, and `type = "mean"` in `predict` computes the predicted outcome value on the original scale, which may fall between observed categories.

For `orm()` models, the `get_vcov()` method needs to have `intercepts='all'` in the call to `vcov()`.

**Comment by vincentarelbundock** [comment]
Thanks!

Merged.

I don't have an elegant mechanism to switch the default `type` based on model characteristics like that. But at least now `mean` is available in those two models. It also felt safer to keep the other default since it should work for all models regardless of the outcome variable class (in principle).
