### ISSUE TITLE
Different differencing method for numerics?

### ISSUE THREAD

**Issue by bjedwards** [vincentarelbundock/marginaleffects#527]
First, thank you for this package. It has been massively useful in my research. I am wondering if what I am trying to do is possible in the package right now, could be possible with an update, or is maybe just a bad idea. 

My situation is that I have a `log` transformed variable in a model that I'd like to use `comparisons` on, but the way differencing happens (centered differencing) means I can only calculate effects for a subset of the data. A minimal example, that is not my data but illustrates my point:

```{r}
library(marginaleffects)

# A hack transform, but illustrates the point
mtcars$new_hp <- 49*(mtcars$hp - min(mtcars$hp))/(max(mtcars$hp) - min(mtcars$hp)) + 1

mod <- lm(mpg~log(new_hp), data=mtcars)

comparisons(mod, variables = list(new_hp =10))
```

`comparisons` is smart enough to drop the 5 points where `new_hp <= 5`, but what I'd like to do is make the comparison not between `new_hp-5` (where `predicted_lo` is currently calculated) and `new_hp +5` (`predicted_hi`) but rather `new_hp` and `new_hp + 10`.

Is this possible now? I think I can hack it together with `predictions` but am not at all confident in the `std.error` calculation.

```{r}
# Forward differencing hack job
# Copy
mtcars_plus_hp_10 <- mtcars
# Add 10
mtcars_plus_hp_10$new_hp <- mtcars$new_hp + 10

pred_base <- predictions(mod)
pred_plus_10 <- predictions(mod, newdata = mtcars_plus_hp_10)

hack_comp <- data.frame(predicted_lo = pred_base$predicted,
                        predicted_hi = pred_plus_10$predicted,
                        std.error_lo = pred_base$std.error,
                        std.error_hi = pred_plus_10$std.error)

hack_comp$comparison <- hack_comp$predicted_hi - hack_comp$predicted_lo
hack_comp$std.error <- sqrt((hack_comp$std.error_hi^2 + hack_comp$std.error_lo^2)/2)
```

If it were to change I would think a `difference_type=c("centered", "forward", "backward")` argument passed all the way through to `get_contrasts_data_numeric`, starting about [here](https://github.com/vincentarelbundock/marginaleffects/blob/main/R/get_contrast_data_numeric.R#L60). Don't know how possible or pain in the neck that is.

I also am willing to accept that this is a bad idea. I read the issue #389 and it seems related, but I'd be curious if there is more insights.

**Comment by vincentarelbundock** [comment]
You can use the `variables` argument to setup a +10 comparison and the `transform_pré` to define the type of differencing you need. There are several `transform_pré` shortcuts available, but you can also supply arbitrary functions.

See the `?comparisons` docs and the Transformations vignette on the website.

**Comment by vincentarelbundock** [comment]
Sorry, I'm not in front my my computer and I likely misunderstood, but why can't you do something like this?

```r
comparisons(
  mod,
  variables = list(x=2),
  transform_pre = function(hi, lo) (hi+4)-(lo+1))
```

**Comment by vincentarelbundock** [comment]
Sorry, my last comments makes no sense at all. I shouldn't type when tired/confused.

Will come back later after I've had time to think about this a bit.

**Comment by bjedwards** [comment]
No problem! I appreciate your time, and can definitely wait. 

Let me try to clarify too. When passing a function to `transform_pre` it's my understanding that it can only take two arguments `hi` and `lo` and those are the already computed predictions, from the docs

> function: accept two equal-length numeric vectors of adjusted predictions (hi and lo) and returns a vector of contrasts of the same length, or a unique numeric value.

If it could accept more arguments like some of the prebuilt examples, ie 

```
"eydxavg"  \(hi, lo, eps, y, x) mean(((hi - lo)/eps)/y)
```

I could potentially do 
```{r}
comparisons(
  mod,
  variables = list(x=20),
  transform_pre = function(hi, lo, eps, y, x) (hi-y))
```

The current check only allows functions with two arguments. But this still might filter out the `NaN` that would get computed when calculating `predicted_lo`.

**Comment by vincentarelbundock** [comment]
OK, how about this: the `variables` argument accepts a function which takes a vector of numeric values (the predictor) and returns a data frame with two columns with the values to compare.

For example, using the most recent version from Github (make sure you restart after install), you can do:

``` r
library(marginaleffects)
mtcars$new_hp <- 49 * (mtcars$hp - min(mtcars$hp)) / (max(mtcars$hp) - min(mtcars$hp)) + 1
mod <- lm(mpg ~ log(new_hp), data = mtcars)

forward_diff <- \(x) data.frame(x, x + 10)
backward_diff <- \(x) data.frame(x - 10, x)
center_diff <- \(x) data.frame(x - 5, x + 5)

comparisons(
    mod,
    variables = list(new_hp = forward_diff)) |>
    summary()
#>     Term Contrast Effect Std. Error z value   Pr(>|z|)  2.5 % 97.5 %
#> 1 new_hp   custom -3.799     0.4346  -8.742 < 2.22e-16 -4.651 -2.948
#> 
#> Model type:  lm 
#> Prediction type:  response

comparisons(
    mod,
    variables = list(new_hp = backward_diff)) |>
    summary()
#>     Term Contrast Effect Std. Error z value   Pr(>|z|)  2.5 % 97.5 %
#> 1 new_hp   custom -6.507     0.7443  -8.742 < 2.22e-16 -7.966 -5.048
#> 
#> Model type:  lm 
#> Prediction type:  response

comparisons(
    mod,
    variables = list(new_hp = center_diff)) |>
    summary()
#>     Term Contrast Effect Std. Error z value   Pr(>|z|)  2.5 % 97.5 %
#> 1 new_hp   custom -4.056      0.464  -8.742 < 2.22e-16 -4.966 -3.147
#> 
#> Model type:  lm 
#> Prediction type:  response

comparisons(
    mod,
    variables = list(new_hp = 10)) |>
    summary()
#>     Term Contrast Effect Std. Error z value   Pr(>|z|)  2.5 % 97.5 %
#> 1 new_hp      +10 -4.056      0.464  -8.742 < 2.22e-16 -4.966 -3.147
#> 
#> Model type:  lm 
#> Prediction type:  response
```

**Comment by bjedwards** [comment]
That would definitely work. You're amazing.

**Comment by vincentarelbundock** [comment]
Great! I'll add an example to the contrasts vignette. Thanks for the feature request.
