### ISSUE TITLE
marginalmeans with variables at observed values

### ISSUE THREAD

**Issue by GregoryEady** [vincentarelbundock/marginaleffects#528]
Hi Vincent,

This has come up a few times for me and my students. As I understand it, in Stata, marginal means are calculated holding the other variables at their observed values. Is this possible with the marginalmeans() function? It appears that one can only hold the other variables at their means. If it's not possible, I suppose this is a feature request. And thank you for all your work on this library!

**Comment by vincentarelbundock** [comment]
Gregory,

I think you might be looking for the `predictions()` function. See the vignette: https://vincentarelbundock.github.io/marginaleffects/articles/predictions.html

**Comment by GregoryEady** [comment]
Ahh, yes, I see, because there is a tidy() and summary() function that can be applied to the resulting dataset. Thanks for the quick response!

Is it possible then to use tidy/summary separately for the predictor that is being held fixed?

Example:

library(marginaleffects)
data(mtcars)

mod <- lm(mpg ~ hp + am + vs, data = mtcars)
pred <- predictions(mod, variables = list(hp = c(150, 200)))

# Something like this, where one wants to summarize the prediction for hp = 150 and hp = 200 separately:
# Something that would look like this:
pred %>%
group_by(hp) %>%
tidy() # ???

**Comment by vincentarelbundock** [comment]
Yes. All this (and more!) is very easy and well documented. See in particular the `newdata` and `by` arguments, as well as the `datagrid` and `datagridcf` functions.

**Comment by GregoryEady** [comment]
Yes, I see, thank you very much for this. If I understand correctly, one would do this as follows:

library(marginaleffects)
data(mtcars)

mod <- lm(mpg ~ hp + am + vs, data = mtcars)

**Done individually**:

pred_150 <- predictions(mod, variables = list(hp = c(150)))
summary(pred_150)

pred_200 <- predictions(mod, variables = list(hp = c(200)))
summary(pred_200)

**With the "by" argument**:

predictions(mod, newdata = datagridcf(hp = c(150, 200)), by = "hp")

**Comment by vincentarelbundock** [comment]
Right. alternatively:

```r
predictions(mod, variables = list(hp = c(150, 200)), by = "hp")
```

**Comment by GregoryEady** [comment]
Excellent. Thanks again!

**Comment by vincentarelbundock** [comment]
pleasure
