### ISSUE TITLE
FR: Bayesian directional hypothesis tests

### ISSUE THREAD

**Issue by andymilne** [vincentarelbundock/marginaleffects#529]
I am very new to the `marginaleffects` package, and it's been a pleasure to begin to learn and to use. Is there already (I think not), or could there be, an easy way to perform directional Bayesian hypothesis tests from the outputs of `marginaleffects()`, `comparisons()`, or `predictions()`? For example, in `brms` you can use the `hypothesis()` function and supply it either with a fitted brms model or a matrix of draws where each column is an effect of interest. However, the `marginaleffects::posteriordraws()` function puts the effects or contrasts of interest into rows rather than columns so cannot be directly used in `brms::hypothesis()`. Perhaps there could be an option to produce a matrix of draws compatible with `brms::hypothesis` or maybe `marginaleffects` could calculate the posterior probabilities (and evidence ratios) itself. Just a suggestion. Great work on this package.

**Comment by vincentarelbundock** [comment]
Thanks.

I'm not familiar with the hypothesis function.

What exact shape should the matrix of draws take? What are the rows and what are the columns?

**Comment by andymilne** [comment]
As far as I understand, each column in an array suitable for `brms::hypothesis` should be a posterior effect (or contrast) of interest and each row is a draw of that posterior effect (it's not very well documented in `brms`'s help). For example, in `marginaleffects` if you run `posteriordraws` on the output of, e.g., `comparisons`, you get a column called `term` and a column called `contrast`. The array required by `brms::hypothesis` would have a column for every unique combination of `term` and `contrast` (and be named accordingly), and each row would be a draw from its posterior. 

In `brms`, the user could then write something like 
```
hypothesis(array_from_marginaleffects, 
c("name_of_column_of_interest1 > 0", 
"name_of_column_of_interest1 - name_of_column_of_interest2 < 0"))
```
The output of `hypothesis()` summarizes the two specified effects/contrasts with their mean, SE, and CI, and provides the posterior probability the hypothesis is true (p) (i.e., the number of draws from that effect/contrast > 0 divided by total number of draws) and an "evidence ratio", which are just the odds the hypothesis is true; i.e. p/(1-p).

Or maybe this would be better handled entirely within `marginaleffects`.

Hopefully that explanation makes sense. 

(An advantage of directional hypothesis testing is that in some fields (e.g., cognitive science/psychology/social science), it is implausible that most effects of interest can ever be exactly zero; so, arguably, null hypothesis-testing (e.g., Bayes factors) don't make conceptual sense.)

**Comment by vincentarelbundock** [comment]
Thanks for the details. 

If you install the latest version from Github (make sure you restart R after), you should be able to do much of that within `marginaleffects` itself. 

I've also expanded the `posteriordraws()` with a new argument in case you need to pass the object forward to `brms::hypothesis`.

I've opened a new issue to implement equivalence and non-inferiority tests. I think this should be doable and not super hard to do within `marginaleffects`, but I have not started work in it yet. You can follow progress here: https://github.com/vincentarelbundock/marginaleffects/issues/530 

Finally, I have added a couple examples to the vignette. In that example I use `differenceavg`, but you could of course use another quantity of interest like `dydxavg` if you want to compare average slopes. https://vincentarelbundock.github.io/marginaleffects/articles/brms.html#non-linear-hypothesis-testing

Let me know if this works for you.

**Comment by andymilne** [comment]
It's very possible I am misunderstanding what is actually required or intended here for the `shape = "DxP"` method. But, when applied to a `comparison` object, I would be expecting a matrix with a single column for each unique pair of `term` and `contrast` (hence there will be more than D rows because I am interested in the **average** marginal effects). Then, in `brms::hypothesis` I would be able to do a directional test on any of those average marginal effects (or any nonlinear combination of them).

**Comment by vincentarelbundock** [comment]
I don’t understand what you mean. Example:

``` r
library(brms)
library(marginaleffects)

mod <- brm(hp ~ mpg + drat, data = mtcars)

mfx <- comparisons(
    mod,
    transform_pre = "dydxavg"
)

mfx
#>       type term    contrast comparison  conf.low conf.high predicted
#> 1 response  mpg mean(dY/dX)  -10.01344 -13.63887 -6.112761  143.0181
#> 2 response drat mean(dY/dX)   18.84752 -23.47802 59.059506  143.0181
#>   predicted_hi predicted_lo
#> 1     142.9892     143.0181
#> 2     143.0244     143.0181
```

The code above gives us the average marginal effects of `mpg` and `drat`. There are two parameters – two averages.

Now we call `posteriordraws()`:

``` r
posteriordraws(mfx, shape = "DxP") |> head()
#>               b1       b2
#> draw1 -10.105962 13.56095
#> draw2  -8.618372 14.66053
#> draw3 -11.677522 10.20274
#> draw4  -9.770585 40.60563
#> draw5 -12.606973 46.60394
#> draw6 -10.808466 36.58222

posteriordraws(mfx, shape = "DxP") |> dim()
#> [1] 4000    2
```

Again, there were two parameters, two rows in the original `comparisons()` output, so we get a matrix with two columns, and 4000 draws (4 chains with 1000 iterations each).

Now we want to compare the two quantities to see if the average marginal effects of `mpg` and `drat` are different from one another:

``` r
posteriordraws(mfx, shape = "DxP") |> 
    brms::hypothesis("b1 = b2")
#> Hypothesis Tests for class :
#>      Hypothesis Estimate Est.Error CI.Lower CI.Upper Evid.Ratio Post.Prob Star
#> 1 (b1)-(b2) = 0   -28.68     22.73   -71.72    16.27         NA        NA     
#> ---
#> 'CI': 90%-CI for one-sided and 95%-CI for two-sided hypotheses.
#> '*': For one-sided hypotheses, the posterior probability exceeds 95%;
#> for two-sided hypotheses, the value tested against lies outside the 95%-CI.
#> Posterior probabilities of point hypotheses assume equal prior probabilities.
```

Alternatively,

``` r
comparisons(
    mod,
    hypothesis = "b1 = b2",
    transform_pre = "dydxavg"
)
#>       type  term comparison  conf.low conf.high
#> 1 response b1=b2  -28.96171 -71.71993  16.26673
```

What am I not getting?

**Comment by andymilne** [comment]
This is what I am seeing ... 

```
> cmp <-
+   comparisons(
+     mdl_1_0_WschlrFnl_smooth,
+     contrast_factor = "pairwise",
+     conf_level = 0.90,
+     re_formula = NA
+   )
> summary(cmp)
            Term    Contrast   Effect   5.0 %   95.0 %
1            Age          +1 -0.02373 -0.0933  0.03982
2        BscClss     NG - QR -0.84559 -2.6400  1.04866
3        BscClss     NG - TK -2.54981 -4.4365 -0.63010
4        BscClss     TK - QR  1.70044 -0.1268  3.61329
5           Gndr Woman - Man  0.67751 -1.0847  2.40744
6          Ltrcy       1 - 0 -0.19970 -1.9321  0.62554
7          Ltrcy       2 - 0 -0.49061 -2.5684  1.78290
8          Ltrcy       2 - 1 -0.09698 -1.1066  1.36341
9  OthrLngKnwldg       1 - 0  0.60664 -1.2460  2.47803
10    WschlrFnl0          +1  0.26144  0.1124  0.41520

Model type:  brmsfit 
Prediction type:  response 
> 
> pdr <- posteriordraws(cmp, shape = "DxP") 
> head(pdr)
              b1        b2         b3         b4          b5         b6        b7        b8         b9        b10         b11         b12
draw1  0.1895672 0.2827794 0.61443624  0.2033521 -0.23401841 0.24391581 0.2798081 0.4689962  0.1736593  0.2033521 -0.34054989 -0.16288794
draw2  0.5102506 0.3867414 0.64576028  0.5683241  0.45604713 0.06854605 0.4706422 0.6646194  0.7453359  0.5683241 -0.25191223 -0.26989267
draw3  0.1322322 0.3782357 0.18466374  0.1160998 -0.05836315 0.35310686 0.2960560 0.2410760  0.1075049  0.1160998  0.04178443  0.06028016
draw4 -0.2310126 0.3693731 0.08096265 -0.2777603 -0.46228090 0.49424259 0.3507467 0.2631313 -0.2658221 -0.2777603 -0.27525406 -0.48176400
draw5  0.4096764 0.2175073 0.21005456  0.3274622  0.32753467 0.16744523 0.2192932 0.2067701  0.3806338  0.3274622  0.24858433  0.39506222
draw6  0.3038347 0.4344970 0.38398951  0.3628985  0.11578102 0.29781854 0.4401442 0.3971902  0.3612279  0.3628985  0.10102717  0.17087481
```
section of output removed for space
```
            b969        b970        b971        b972        b973        b974        b975        b976        b977        b978        b979
draw1 -0.73685660 -0.79492878 -1.06932741 -0.87209946 -1.01731575 -1.13432099 -0.77456251 -0.94512704 -1.00888225 -0.56407989 -0.76517859
draw2  2.04909128  1.99892417  2.03182251  2.46458172  1.85135993  2.76558285  1.78726879  2.14674502  1.97374837  2.19965998  2.05192237
draw3 -0.10208465 -0.10266136 -0.09369592 -0.08379884 -0.09550656 -0.09456881 -0.07707288 -0.08639908 -0.08586251 -0.10297719 -0.08560964
draw4 -0.79995234 -0.70479431 -0.95818539 -0.89917917 -1.04031924 -0.84724592 -0.90818057 -0.85036474 -0.90230735 -0.77773934 -0.84186556
draw5 -0.08048327 -0.07094503 -0.06937000 -0.08237014 -0.08185976 -0.08217421 -0.07216302 -0.08148976 -0.07281446 -0.06419121 -0.06624329
draw6 -0.06998373 -0.07783602 -0.07440305 -0.10601755 -0.08123876 -0.08432248 -0.08945400 -0.08038912 -0.07065041 -0.07226987 -0.08250931
             b980
draw1 -0.74186315
draw2  2.11695306
draw3 -0.08574997
draw4 -0.91103518
draw5 -0.06483722
draw6 -0.07572780
```

**Comment by vincentarelbundock** [comment]
You need to call ˋposteriordraws()` AFTER `tidy()`, otherwise the estimates your are comparing are unit-level, rather than averages.

**Comment by vincentarelbundock** [comment]
Or use `transform_pre="differenceavg"` as in the vignette

**Comment by andymilne** [comment]
Aah beautiful -- yes that works! Thank you for spotting my rookie error (I am not really up with the whole tidyverse thing or really understand it). I will now explore a bit further, but this looks great so far. I will look into `transform_pre="differenceavg"` too -- that is not something I have used before.

**Comment by vincentarelbundock** [comment]
Glad it works!
