### ISSUE TITLE
CIs wrong when "by" argument is used on a `fixest::i` model

### ISSUE THREAD

**Issue by grantmcdermott** [vincentarelbundock/marginaleffects#531]
Sorry, another minor bug related to `fixest::i`. First reported here: https://github.com/grantmcdermott/etwfe/issues/8

I'll try to demonstrate with a running MWE consisting of three equivalent models:

``` r
library(fixest)
library(marginaleffects)
library(modelsummary)

m1 =    lm(Ozone ~ Wind + factor(Month), airquality)
m2 = feols(Ozone ~ Wind | Month        , airquality, vcov = "iid")
m3 = feols(Ozone ~ Wind + i(Month)     , airquality, vcov = "iid") # this will be our problem case later

# Just to prove they're all the same
modelsummary(
    list(m1, m2, m3), 
    coef_map = "Wind", gof_map = NA,
    statistic = c("std.error", "conf.int"),
    output = "markdown"
    )
```

|      |      Model 1       |      Model 2       |      Model 3       |
|:-----|:------------------:|:------------------:|:------------------:|
| Wind |       -4.643       |       -4.643       |       -4.643       |
|      |      (0.702)       |      (0.702)       |      (0.702)       |
|      | \[-6.034, -3.252\] | \[-6.034, -3.252\] | \[-6.034, -3.252\] |

The first thing to note is that, AFAICT, this is only limited to cases where the `by` argument is invoked. For example, we get the same result across our models here:

``` r
mfx1 = marginaleffects(m1, variable = "Wind")
mfx2 = marginaleffects(m2, variable = "Wind")
mfx3 = marginaleffects(m3, variable = "Wind")

modelsummary(
    list(mfx1, mfx2, mfx3), 
    coef_map = "Wind", gof_map = NA,
    statistic = c("std.error", "conf.int"),
    output = "markdown"
    )
```

|      |      Model 1       |      Model 2       |      Model 3       |
|:-----|:------------------:|:------------------:|:------------------:|
| Wind |       -4.643       |       -4.643       |       -4.643       |
|      |      (0.702)       |      (0.702)       |      (0.702)       |
|      | \[-6.019, -3.267\] | \[-6.019, -3.267\] | \[-6.019, -3.267\] |

Okay, so far so good. But here's where the bug bites once we invoke "by". Note that the CI entries in the far right column are way off compared to the other two models. At the same time, it's only the CIs that are off; the main MFX estimates and even the SEs are consistent throughout.

``` r

mfx1b = marginaleffects(m1, variable = "Wind", by = "Month")
mfx2b = marginaleffects(m2, variable = "Wind", by = "Month")
mfx3b = marginaleffects(m3, variable = "Wind", by = "Month")

modelsummary(
    list(mfx1b, mfx2b, mfx3b), 
    shape = month + statistic ~ model,
    coef_map = "Wind", gof_map = NA,
    statistic = c("std.error", "conf.int"),
    output = "markdown"
    )
```

|      |       |      Model 1       |      Model 2       |      Model 3       |
|:-----|:------|:------------------:|:------------------:|:------------------:|
| Wind | 5.000 |       -4.643       |       -4.643       |       -4.643       |
|      |       |      (0.702)       |      (0.702)       |      (0.702)       |
|      |       | \[-6.019, -3.267\] | \[-6.019, -3.267\] | \[31.236, 53.675\] |
|      | 6.000 |       -4.643       |       -4.643       |       -4.643       |
|      |       |      (0.702)       |      (0.702)       |      (0.702)       |
|      |       | \[-6.019, -3.267\] | \[-6.019, -3.267\] | \[28.841, 63.272\] |
|      | 7.000 |       -4.643       |       -4.643       |       -4.643       |
|      |       |      (0.702)       |      (0.702)       |      (0.702)       |
|      |       | \[-6.019, -3.267\] | \[-6.019, -3.267\] | \[68.169, 91.135\] |
|      | 8.000 |       -4.643       |       -4.643       |       -4.643       |
|      |       |      (0.702)       |      (0.702)       |      (0.702)       |
|      |       | \[-6.019, -3.267\] | \[-6.019, -3.267\] | \[57.725, 77.663\] |
|      | 9.000 |       -4.643       |       -4.643       |       -4.643       |
|      |       |      (0.702)       |      (0.702)       |      (0.702)       |
|      |       | \[-6.019, -3.267\] | \[-6.019, -3.267\] | \[36.006, 56.383\] |

<sup>Created on 2022-11-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by vincentarelbundock** [comment]
Thanks for the detailed bug report. This should be fixed in https://github.com/vincentarelbundock/marginaleffects/commit/388e52f4a015c459014b0733ab81fc5d52baa84e

We might also get a nice speed boost, because the previous code computed CIs several times for no reason while making predict() calls.

**Comment by grantmcdermott** [comment]
Confirmed, thanks @vincentarelbundock!
