### ISSUE TITLE
Support: ZBZIMM

### ISSUE THREAD

**Issue by theclairecamp** [vincentarelbundock/marginaleffects#541]
I was trying to use the plot_cme() function mentioned in [this thread](https://stackoverflow.com/questions/72468726/how-do-i-create-an-interaction-plot-when-doing-a-negative-binomial-regression) on my modeling function glmm.zinb() within package [ZBZIMM](https://github.com/nyiuab/NBZIMM) but this package is currently not supported. When I received the error it said to submit an issue on this github to include it.

**Comment by vincentarelbundock** [comment]
Thanks for trying `marginaleffects` and for opening this issue!

Unfortunately, `marginaleffects` only supports packages published on CRAN.

That said, in many cases, it is very easy for users to add support for new models. See instructions here: https://vincentarelbundock.github.io/marginaleffects/articles/extensions.html

If NBZIMM offers a `predict()` method to make predictions on new datasets, it may be relatively easy to support it. If you do manage it, let me know and I can share your code in the user-submitted library.
