### ISSUE TITLE
`summary.comparisons()` should accept string for `transform_avg` and print it

### ISSUE THREAD

**Issue by ngreifer** [vincentarelbundock/marginaleffects#542]
To exponentiate a comparison, you need to run `summary(., transform_avg = exp)`. I think one should be able to supply a string, e.g., `"exp"`, that is matched using `match.fun()`. This would make it easier to print the transformation, which is currently bugged. That is, what I see is
```
> summary(comp2, transform_avg = exp)
  Term              Contrast Effect Pr(>|z|) 2.5 % 97.5 %
1    A ln(mean(1) / mean(0))   1.57   <2e-16  1.41   1.75

Model type:  glm 
Prediction type:  response 
Average-transformation:   
```
Note that `Average-transformation:` is blank. What I would expect to see is

```
> summary(comp2, transform_avg = "exp")
  Term              Contrast Effect Pr(>|z|) 2.5 % 97.5 %
1    A ln(mean(1) / mean(0))   1.57   <2e-16  1.41   1.75

Model type:  glm 
Prediction type:  response 
Average-transformation:  exp
```
which I believe is the intended output, or even

```
> summary(comp2, transform_avg = "exp")
  Term                 Contrast Effect Pr(>|z|) 2.5 % 97.5 %
1    A exp(ln(mean(1) / mean(0)))   1.57   <2e-16  1.41   1.75

Model type:  glm 
Prediction type:  response 
Average-transformation:  exp
```
which makes the exponentiation clearer, or even

```
> summary(comp2, transform_avg = "exp")
  Term         Contrast Effect Pr(>|z|) 2.5 % 97.5 %
1    A mean(1) / mean(0)   1.57   <2e-16  1.41   1.75

Model type:  glm 
Prediction type:  response 
Average-transformation:  exp
```
i.e., it knows that `exp` negates the `ln` of the `transform_pre`. I'm not sure which function you expect to see in `transform_avg`, but I would bet `exp` is among the few and could be given some special status (i.e., being recognized as special by the `print` method).

**Comment by vincentarelbundock** [comment]
Yes, that sounds reasonable and useful, especially since the cost of implementation is rather trivial.

Ideally the original behaviour would also too, of course...

**Comment by vincentarelbundock** [comment]
Commit 1d6101e2d96b24bf7618a9db6f31174a0a0b4bb2 fixes the bug in printed
output:

``` r
library(marginaleffects)

mod <- glm(gear ~ hp + mpg, data = mtcars, family = poisson)
cmp <- comparisons(mod)
pre <- predictions(mod)

summary(cmp, transform_avg = exp)

      Term Contrast Effect Pr(>|z|)  2.5 % 97.5 %
    1   hp       +1  1.006  0.41428 0.9910  1.022
    2  mpg       +1  1.120  0.20079 0.9417  1.331

    Model type:  glm 
    Prediction type:  response 
    Average-transformation:  exp 

summary(pre, transform_avg = exp)

      Predicted   Pr(>|z|) CI low CI high
    1     39.94 < 2.22e-16  20.53   77.73

    Model type:  glm 
    Prediction type:  response 
    Average-transformation:  exp 
```

Now that the bug is fixed, I’m looking at your other proposal more
seriously. (I was on my phone earlier and didn’t see the labels
properly.) Those labels are quite nice, but I wonder if they are
necessary.

As long as we get the transformation printed at the bottom, the output
is pretty clear. And users have explicitly supplied the `transform_avg`
argument, so I doubt there’s much risk of confusion.

The canceling out labels is clever, but I worry that it might lead to
some confusion. And it might also create confusion if people see
examples of `exp` and `"exp"` out there. So limiting it to functions has
some value for simplicitly. (`transform_pre` is a different case, where
it makes sense to use shortcuts because complex functions can be
annoying to write by hand.)

To be clear, I don’t have a very strong opinion on this; just trying to
weigh benefits against potential feature creep.

**Comment by ngreifer** [comment]
No strong opinion on it either, I just go with my gut. To me, people will almost always supply `transform_pre` as a string, and for symmetry, I would be inclined to supply `transform_avg` as one as well. Right now there is an asymmetry in that `transform_pre` accepts a function or a string but is typically supplied as a string, and `transform_avg` only accepts a function. If someone supplied an anonymous function (e.g., `function(x) #do a lot of stuff`), how would that appear in the `print()` output? Definitely no need to change anything big. I'm just imagining the average user looking at the output [here](https://kosukeimai.github.io/MatchIt/articles/estimating-effects.html) (section "Binary outcomes") and being a little confused (in fact, I had to include a footnote to address what I saw as a potential confusion). I think your fix will go a long way. What do you think?

**Comment by vincentarelbundock** [comment]
Anonymous functions are handled fine:

``` r
library(marginaleffects)
mod <- lm(mpg ~ hp, mtcars)
predictions(mod) |>
    summary(transform_avg = function(x) log2(x))
```

      Predicted   Pr(>|z|) CI low CI high
    1     4.328 < 2.22e-16  4.229   4.421

    Model type:  lm 
    Prediction type:  response 
    Average-transformation:  function(x) log2(x) 

I think I’m convinced by your symmetry argument. The next few weeks are
going to be tough for me, so I’m not sure I’ll have time to get to this
before a while. Just for the record, here are main things that should be
done:

-   [ ] All changes made to `predictions()` and `comparisons()`
-   [ ] All changes made to `transform_avg` and `transform_post`
-   [ ] Modify `checkmate::assert_function(transform_avg)` to allow some strings using `checkmate::assert()` and `checkmate::check_choice`
-   [ ] Modify labels on the fly if using a shortcut string.
-   [ ] Make sure the printed output is not confusing.

**Comment by vincentarelbundock** [comment]
This now works in the dev version:

``` r
library(marginaleffects)

mod <- glm(vs ~ mpg + drat, data = mtcars, family = binomial)

predictions(mod, newdata = "mean", transform_post = "exp") |>
    summary()

      Predicted Std. Error z value   Pr(>|z|) CI low CI high
    1     1.572     0.1231   12.76 < 2.22e-16   1.33   1.813

    Model type:  glm 
    Prediction type:  response 
    Post-transformation:  exp 

predictions(mod, newdata = "mean") |>
    summary(transform_avg = "exp")

      Predicted   Pr(>|z|) CI low CI high
    1     1.572 0.00024151  1.235   2.001

    Model type:  glm 
    Prediction type:  response 
    Average-transformation:  exp 

comparisons(mod, transform_post = "exp") |>
    summary()

      Term Contrast Effect Std. Error z value   Pr(>|z|)  2.5 % 97.5 %
    1  mpg       +1 1.0640    0.01561  68.168 < 2.22e-16 1.0334  1.095
    2 drat       +1 0.9317    0.16897   5.514  3.508e-08 0.6005  1.263

    Model type:  glm 
    Prediction type:  response 
    Post-transformation:  exp 

comparisons(mod) |>
    summary(transform_avg = "exp")

      Term Contrast Effect   Pr(>|z|)  2.5 % 97.5 %
    1  mpg       +1 1.0631 8.9426e-05 1.0310  1.096
    2 drat       +1 0.9305    0.67006 0.6682  1.296

    Model type:  glm 
    Prediction type:  response 
    Average-transformation:  exp 
```
