### ISSUE TITLE
Blank graph in the documentation

### ISSUE THREAD

**Issue by arthur-albuquerque** [vincentarelbundock/marginaleffects#545]
Hi Vincent, 

There is a blank graph in the [GAM vignette](https://vincentarelbundock.github.io/marginaleffects/articles/gam.html): 

![image](https://user-images.githubusercontent.com/77208087/202852180-c61be7e5-fbf8-428a-80da-50b542b10be5.png)

**Comment by vincentarelbundock** [comment]
thanks a lot. there was a bug in the development version. it should be fixed now.

**Comment by arthur-albuquerque** [comment]
Same problem here: https://vincentarelbundock.github.io/marginaleffects/articles/comparisons.html#ratios

<img width="936" alt="image" src="https://user-images.githubusercontent.com/77208087/221286348-52855e99-fd55-436c-8f17-cf1581596ff7.png">

**Comment by vincentarelbundock** [comment]
Thanks a lot for the report @arthur-albuquerque . These are super useful.

Should be fixed on Github now and on the development version of the website: https://vincentarelbundock.github.io/marginaleffects/dev/articles/comparisons.html
