### ISSUE TITLE
`get_vcov()` etc. do not accept functions

### ISSUE THREAD

**Issue by ngreifer** [vincentarelbundock/marginaleffects#554]
`get_vcov()` and `marginaleffects()`, etc., are not accepting functions. See reprex below:

``` r
data("mtcars")

fit <- lm(mpg ~ cyl, data = mtcars)

marginaleffects::get_vcov(fit, sandwich::vcovHC)
#> Error in as.character(x): cannot coerce type 'closure' to vector of type 'character'
marginaleffects::marginaleffects(fit, vcov = sandwich::vcovHC)
#> Error in vcov == FALSE: comparison (1) is possible only for atomic and list types
```

<sup>Created on 2022-11-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

The documentation and `checkmate` checks claim a function should work, but it doesn't. Oddly the error differs between the two functions above.

**Comment by vincentarelbundock** [comment]
Thanks for the report. Should be fixed on Github.
