### ISSUE TITLE
Risk ratio p values are based on 0

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/marginaleffects#568]
Probably doesn't make much sense.

**Comment by ASKurz** [comment]
Thanks for opening this issue!

**Comment by vincentarelbundock** [comment]
With the new version from Github you can now specify the null hypothesis using the `hypothesis` argument. For example, consider a logistic regression model:

``` r
library(marginaleffects)
mod <- glm(am ~ hp + drat, data = mtcars, family = binomial)
```

We can compute the predicted outcome for a hypothetical unit where all regressors are fixed to their sample means:

``` r
predictions(mod, newdata = "mean")
```

      rowid     type predicted std.error statistic   p.value   conf.low conf.high
    1     1 response 0.2309657  0.142912  1.616139 0.1060643 0.05842351 0.5924504
           am       hp     drat
    1 0.40625 146.6875 3.596563

The Z statistic and p value reported above assume that the null hypothesis equals zero. We can change the null with the `hypothesis` argument:

``` r
predictions(mod, newdata = "mean", hypothesis = .5)
```

      rowid     type predicted std.error statistic    p.value   conf.low conf.high
    1     1 response 0.2309657  0.142912 -1.882517 0.05976592 0.05842351 0.5924504
           am       hp     drat
    1 0.40625 146.6875 3.596563

This can obviously be useful in other contexts. For instance, if we compute risk ratios (at the mean) associated with an increase of 1 unit in `hp`, it makes more sense to test the null hypothesis that the ratio of predictions is 1 rather than 0:

``` r
comparisons(
    mod,
    newdata = "mean",
    variables = "hp",
    transform_pre = "ratio",
    hypothesis = 1)
```

      rowid     type term contrast comparison   std.error statistic   p.value
    1     1 response   hp       +1   1.008334 0.007890531  1.056249 0.2908546
       conf.low conf.high predicted predicted_hi predicted_lo      am       hp
    1 0.9928692    1.0238 0.2309657    0.2319256    0.2300086 0.40625 146.6875
          drat    eps
    1 3.596563 0.0283

Warning: Z statistics and p values are computed *before* applying functions in `transform_post`.
