### ISSUE TITLE
emmeans contrasts on the response scale and OR CIs

### ISSUE THREAD

**Issue by ercbk** [vincentarelbundock/marginaleffects#58]
I noticed the categorical contrasts were odds ratios, and I just wanted to point out that you can have these on the probability scale by including `regrid` between `emmeans` and `contrast` if you want to.  

Also, the oddsratio CI for "Gentoo / Chinstrap" looked off, since it has a p-value < 0.05 but a CI that includes 0. Only browsed the get_contrast code, so I didn't find where that calc was being done. But {emmeans} has method for confint and that CI looks more reasonable.

``` r
library(magrittr)
library(marginaleffects)

dat <- read.csv("https://vincentarelbundock.github.io/Rdatasets/csv/palmerpenguins/penguins.csv")
dat$large_penguin <- ifelse(dat$body_mass_g > median(dat$body_mass_g, na.rm = TRUE), 1, 0)

mod <- glm(large_penguin ~ bill_length_mm + flipper_length_mm + species, 
           data = dat, family = binomial)

# W/Odds Ratios
mfx <- marginaleffects(mod)
summary(mfx)
#> Warning in `[<-.factor`(`*tmp*`, is.na(out$contrast), value = ""): invalid
#> factor level, NA generated
#> Average marginal effects 
#>       type              Term           Contrast    Effect Std. Error  z value
#> 1 response    bill_length_mm               <NA>   0.02757    0.00849  3.24819
#> 2 response flipper_length_mm               <NA>   0.01058    0.00332  3.18766
#> 3 response           species Chinstrap / Adelie   0.00547    0.00574 -4.96164
#> 4 response           species    Gentoo / Adelie   2.19156    2.75319  0.62456
#> 5 response           species Gentoo / Chinstrap 400.60647  522.34202  4.59627
#>     Pr(>|z|)      2.5 %     97.5 %
#> 1  0.0011614    0.01093    0.04421
#> 2  0.0014343    0.00408    0.01709
#> 3 2.0906e-06   -0.00578    0.01673
#> 4  0.8066373   -3.20459    7.58770
#> 5 1.2828e-05 -623.16509 1424.37802
#> 
#> Model type:  glm 
#> Prediction type:  response

emm_or <- emmeans::emmeans(mod, "species", type = "response") %>% 
  emmeans::contrast(., method = "revpairwise")
emm_or
#>  contrast           odds.ratio       SE  df z.ratio p.value
#>  Chinstrap / Adelie     0.0055   0.0057 Inf -4.962  <.0001 
#>  Gentoo / Adelie        2.1916   2.7532 Inf  0.625  0.8066 
#>  Gentoo / Chinstrap   400.6065 522.3420 Inf  4.596  <.0001 
#> 
#> P value adjustment: tukey method for comparing a family of 3 estimates 
#> Tests are performed on the log odds ratio scale
confint(emm_or)
#>  contrast           odds.ratio       SE  df asymp.LCL asymp.UCL
#>  Chinstrap / Adelie     0.0055   0.0057 Inf  4.67e-04     0.064
#>  Gentoo / Adelie        2.1916   2.7532 Inf  1.15e-01    41.635
#>  Gentoo / Chinstrap   400.6065 522.3420 Inf  1.89e+01  8508.999
#> 
#> Confidence level used: 0.95 
#> Conf-level adjustment: tukey method for comparing a family of 3 estimates 
#> Intervals are back-transformed from the log odds ratio scale

# W/probabilities
emm_probs <- emmeans::emmeans(mod, "species", type = "response") %>% 
  emmeans::regrid() %>% 
  emmeans::contrast(., method = "revpairwise")
emm_probs
#>  contrast           estimate     SE  df z.ratio p.value
#>  Chinstrap - Adelie  -0.8057 0.0771 Inf -10.446 <.0001 
#>  Gentoo - Adelie      0.0836 0.1156 Inf   0.723 0.7499 
#>  Gentoo - Chinstrap   0.8893 0.0853 Inf  10.421 <.0001 
#> 
#> P value adjustment: tukey method for comparing a family of 3 estimates

confint(emm_probs)
#>  contrast           estimate     SE  df asymp.LCL asymp.UCL
#>  Chinstrap - Adelie  -0.8057 0.0771 Inf    -0.986    -0.625
#>  Gentoo - Adelie      0.0836 0.1156 Inf    -0.187     0.355
#>  Gentoo - Chinstrap   0.8893 0.0853 Inf     0.689     1.089
#> 
#> Confidence level used: 0.95 
#> Conf-level adjustment: tukey method for comparing a family of 3 estimates
```

<sup>Created on 2021-09-12 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by vincentarelbundock** [comment]
Good catch, Eric! I'm not an `emmeans` expert, so this kind of concrete suggestion is *tremendously* helpful. I really appreciate it.

In commit 91e2730 I put in a call to `emmeans::regrid`, and I added your specific example as a test to ensure that the CI and p reject the same nulls.

Let me know if you spot anything else or if you are looking for some new feature.

Cheers!

**Comment by ercbk** [comment]
I guess one other thing I'll add is that I think using emmeans for this will produce different values than Stata. I've been reading this [text](https://us.sagepub.com/sites/default/files/upm-assets/114728_book_item_114728.pdf) on marginal effects, and the description of using the average marginal effect method for categorical variables doesn't sound like what emmeans is doing to me.  

I think the emmeans contrasts are differences in averages and the way Stata would do it is by calculating the differences and then taking the average. ...if that makes sense. I'd double check me on that though.

**Comment by ercbk** [comment]
pg 35

**Comment by vincentarelbundock** [comment]
Right, that's an important difference: "Contrasts at the mean" vs. "Mean of contrasts". And you are right to point out that there is currently a discrepancy between how marginal effects and contrasts are reported.

I'm tempted to write code to estimate contrasts internally, so I can handle all of this consistently instead of outsourcing to `emmeans`. The infracture is already there to compute both types of quantities very easily. For example:

``` r
library(emmeans)
library(marginaleffects)
library(dplyr)
tmp <- mtcars
tmp$cyl <- as.factor(tmp$cyl)
mod <- glm(am ~ mpg + cyl, data = tmp, family = binomial)
```

#### Mean of contrasts

```r
marginaleffects(mod, newdata = counterfactual(cyl = c(4, 6, 8))) %>%
    arrange(rowid, cyl) %>%
    group_by(rowid) %>%
    mutate(contrast = predicted_response - predicted_response[1]) %>%
    group_by(cyl) %>%
    summarize(contrast = mean(contrast))

#>   cyl   contrast
#> 1 4       0     
#> 2 6       0.0974
#> 3 8       0.0931
```

#### Contrasts at the mean

```r
marginaleffects(mod, newdata = typical(cyl = c(4, 6, 8))) %>%
    mutate(contrast = predicted_response - predicted_response[1]) %>%
    select(cyl, contrast)

#>   cyl  contrast
#> 2   6 0.1685067
#> 3   8 0.1610827
```

#### Contrasts at the mean, using `emmeans`

```r
emmeans(mod, specs = "cyl", type = "response") %>%
    regrid %>%
    contrast(method = "revpairwise")

#>  contrast estimate    SE  df z.ratio p.value
#>  6 - 4     0.16851 0.311 Inf   0.542  0.8505
#>  8 - 4     0.16108 0.442 Inf   0.364  0.9294
```

What's holding me back is I don't have a really good sense of what I would need in terms of infrastructure to get a clean and generalizable way to compute standard errors for those contrasts...

**Comment by ercbk** [comment]
Not familiar with Stata docs. Couldn't find anything technical on how the errors are calculated, but the Stata output in the text I linked indicates it uses the delta method to combine errors. Gonna try it on that text's data in R and see if I can get matching results.

**Comment by vincentarelbundock** [comment]
I think I figured this out today, actually.

Stata does use the Delta method, but in kind of a weird way. Roughly speaking for factor variable `x` they do:

1. Get all predictions with `x` set at baseline
2. Get all predictions with `x` set at the level we care about
3. The gap between 1 and 2 is treated as the marginal effect, even if it isn't really one.
4. Then, take the Jacobian of this "marginal effect" (in quotes) w.r.t. to the coefficients.
5. Take the coefficient-wise average of this Jacobian (by term)
6. Multiply: J V J'   (where V is the variance covariance matrix and J is what we got above)

With this, I can replicate almost exactly the results of Stata (those of `R`'s `margins`, which does the same thing). The only weird part about all this is step 5, which implies that even if we are calculating unit-specific standard errors, we are not actually using those when summarizing the whole model. Instead we use the Delta method to compute "standard errors at the mean gradient", whatever that means.

In any case, I can implement both options natively in Base `R`, so I think I can also get rid of `emmeans`. Perhaps I'll write a very thin wrapper around `emmeans` to facilitate life for those who want to move back and forth. But at least for the main summary functions, I don't think we need it.

I implemented all this already, so if you try the latest Github, in principle you should get Stata-matching results.

**Comment by ercbk** [comment]
It's dang close.
``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(marginaleffects)

dat <- readr::read_csv("~/R/Data/Pampel Logistic Regression Primer Data/NHIS 2017 Logistic Regression Primer.csv")
#> Rows: 52616 Columns: 10
#> -- Column specification --------------------------------------------------------
#> Delimiter: ","
#> dbl (10): year, sampweight, Age, Smoker, Smoke3, Gender, Education, Agecat, ...
#> 
#> i Use `spec()` to retrieve the full column specification for this data.
#> i Specify the column types or set `show_col_types = FALSE` to quiet this message.

datc <- dat %>% 
  janitor::clean_names() %>% 
  mutate(gender = factor(gender, labels = c("Female", "Male")),
         race = factor(race),
         ethnicity = factor(ethnicity))

mod <- glm(smoker ~ education + age + gender + race + ethnicity, family = binomial, data = datc)

mfx <- marginaleffects(mod)
summary(mfx)
#> Average marginal effects 
#>       type       Term   Effect Std. Error   z value   Pr(>|z|)    2.5 %
#> 1 response        age -0.00296    0.00017 -17.47570 < 2.22e-16 -0.00329
#> 2 response  education -0.02258    0.00107 -21.11160 < 2.22e-16 -0.02468
#> 3 response ethnicity1 -0.09889    0.00589 -16.78037 < 2.22e-16 -0.11044
#> 4 response genderMale  0.03152    0.00472   6.67387 2.4915e-11  0.02226
#> 5 response      race2 -0.01025    0.00692  -1.48069 0.13868979 -0.02381
#> 6 response      race3  0.03963    0.02269   1.74683 0.08066635 -0.00484
#> 7 response      race4 -0.07832    0.00827  -9.47376 < 2.22e-16 -0.09452
#> 8 response      race5  0.06262    0.01897   3.30055 0.00096496  0.02543
#>     97.5 %
#> 1 -0.00262
#> 2 -0.02048
#> 3 -0.08734
#> 4  0.04077
#> 5  0.00332
#> 6  0.08410
#> 7 -0.06212
#> 8  0.09981
#> 
#> Model type:  glm 
#> Prediction type:  response
```

<sup>Created on 2021-09-15 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

![Screenshot (490)](https://user-images.githubusercontent.com/25374582/133534521-359e54c0-537c-40fa-ba51-8a45f390a975.png)

**Comment by vincentarelbundock** [comment]
Thanks for posting this. Very cool!

But it looks like I forgot to update the `summary` function. If you look at the `se_at_mean_gradient` attribute (need to find a better name), you'll see that we get even closer!

```r
attr(mfx, "se_at_mean_gradient")

        term    std.error
1  education 0.0008188907
2        age 0.0001439145
3 genderMale 0.0046230151
4      race2 0.0069155791
5      race3 0.0226704263
6      race4 0.0079958957
7      race5 0.0189217644
8 ethnicity1 0.0049594235
```

**Comment by ercbk** [comment]
You're welcome. Great job!
