### ISSUE TITLE
Predictions at marginalmeans with a binomial response

### ISSUE THREAD

**Issue by larmarange** [vincentarelbundock/marginaleffects#580]
Let's consider a logistic regression:

``` r
library(marginaleffects)
df <- Titanic |> 
  dplyr::as_tibble() |> 
  tidyr::uncount(n) |> 
  dplyr::mutate(Survived = factor(Survived, c("No", "Yes")))
mod <- glm(
  Survived ~ Class + Sex,
  data = df, family = binomial
)

res <- predictions(mod, newdata = "marginalmeans")
nrow(res)
#> [1] 16
res
#>    rowid     type predicted  std.error statistic       p.value   conf.low
#> 1      1 response 0.1180158 0.01242879  9.495354  2.194641e-21 0.09574802
#> 2      2 response 0.6010814 0.02978980 20.177419  1.546102e-90 0.54152246
#> 3      3 response 0.4126260 0.03289143 12.545092  4.229233e-36 0.34998469
#> 4      4 response 0.8877746 0.01671254 53.120273  0.000000e+00 0.85061530
#> 5      5 response 0.2132044 0.02552031  8.354301  6.582130e-17 0.16743786
#> 6      6 response 0.7531737 0.03063739 24.583481 1.897498e-133 0.68839001
#> 7      7 response 0.2254938 0.01405803 16.040214  6.692358e-58 0.19913670
#> 8      8 response 0.7662749 0.02820183 27.171109 1.426064e-162 0.70656675
#> 9      9 response 0.1180158 0.01242879  9.495354  2.194641e-21 0.09574802
#> 10    10 response 0.6010814 0.02978980 20.177419  1.546102e-90 0.54152246
#> 11    11 response 0.4126260 0.03289143 12.545092  4.229233e-36 0.34998469
#> 12    12 response 0.8877746 0.01671254 53.120273  0.000000e+00 0.85061530
#> 13    13 response 0.2132044 0.02552031  8.354301  6.582130e-17 0.16743786
#> 14    14 response 0.7531737 0.03063739 24.583481 1.897498e-133 0.68839001
#> 15    15 response 0.2254938 0.01405803 16.040214  6.692358e-58 0.19913670
#> 16    16 response 0.7662749 0.02820183 27.171109 1.426064e-162 0.70656675
#>    conf.high Survived Class    Sex
#> 1  0.1446340       No   3rd   Male
#> 2  0.6577925       No   3rd Female
#> 3  0.4782304       No   1st   Male
#> 4  0.9165969       No   1st Female
#> 5  0.2674618       No   2nd   Male
#> 6  0.8082407       No   2nd Female
#> 7  0.2542321       No  Crew   Male
#> 8  0.8169807       No  Crew Female
#> 9  0.1446340      Yes   3rd   Male
#> 10 0.6577925      Yes   3rd Female
#> 11 0.4782304      Yes   1st   Male
#> 12 0.9165969      Yes   1st Female
#> 13 0.2674618      Yes   2nd   Male
#> 14 0.8082407      Yes   2nd Female
#> 15 0.2542321      Yes  Crew   Male
#> 16 0.8169807      Yes  Crew Female
```

<sup>Created on 2023-01-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

The generated grid contains 16 rows, as the outcome Survived has been considered for generating the grid.

Shouldn't the grid consider only categorical regressors and not the outcome? And therefore generate only 8 rows?

**Comment by vincentarelbundock** [comment]
Thanks a lot for the bug report and the detailed example, I really appreciate it!

You are 100% right. The new version on Github should fix this issue. `gear` has 2 values, `am` and `vs` are binary, so we get 6 rows:

``` r
library(marginaleffects)
dat <- mtcars |> transform(
    vs = factor(vs),
    gear = factor(gear),
    am = factor(am))
mod <- glm(vs ~ gear + am, data = dat, family = binomial)
predictions(mod, newdata = "marginalmeans")
```

      rowid     type    predicted    std.error    statistic      p.value     conf.low conf.high vs gear am
    1     1 response 7.500000e-01 1.530931e-01 4.898979e+00 9.633570e-07 3.771432e-01 0.9369627  0    4  1
    2     2 response 1.000000e+00 2.820020e-05 3.546074e+04 0.000000e+00 2.220446e-16 1.0000000  0    4  0
    3     3 response 6.485152e-09 2.115015e-05 3.066244e-04 9.997553e-01 2.220446e-16 1.0000000  0    3  1
    4     4 response 2.000000e-01 1.032796e-01 1.936492e+00 5.280751e-02 6.589996e-02 0.4697512  0    3  0
    5     5 response 2.000000e-01 1.788854e-01 1.118034e+00 2.635525e-01 2.718309e-02 0.6910456  0    5  1
    6     6 response 9.999999e-01 3.384024e-04 2.955062e+03 0.000000e+00 2.220446e-16 1.0000000  0    5  0

Make sure you restart `R` after installation.

Feel free to comment again or re-open an issue if the fix doesn't work for you.

**Comment by larmarange** [comment]
Thanks a lot for your rapid feedback.

The broom.helpers will soon support marginaleffects cf https://github.com/larmarange/broom.helpers/pull/202

**Comment by larmarange** [comment]
Thanks a lot for your rapid feedback.

The broom.helpers will soon support marginaleffects cf https://github.com/larmarange/broom.helpers/pull/202

As a side effect, it will be possible to generate nicely formatted tables with gtsummary. See examples in the vignette embedded in broom.helpers

**Comment by vincentarelbundock** [comment]
This looks fantastic @larmarange. Nice work!

FYI, the next version of `marginaleffects` will introduce major changes in the recommended workflow and terminology. In principle, there should be *no* break in backward compatibility, but let me know if you run into issues.

In the future, I will be de-emphasizing the expression "marginal effects" when talking about partial derivatives, and instead try to use the word "slopes".

The problem is that there are two competing and *opposite* uses of "marginal":

* Economists, political scientists and sociologists use "marginal effects" to mean "slope/derivative".
* Everyone else uses "marginal" to mean "averaged/marginalized/integrated"

This has led to endless debate and confusion among users. The next version of the docs will note this confusion and mostly use the expression "slopes" instead. The recommended workflow will be:

```r
mod <- lm(mpg ~ hp, data = mtcars)

slopes(mod) |> averages()

comparisons(mod) |> averages()

predictions(mod) |> averages()
```

Note that `tidy()` et al. should work as before.

**Comment by larmarange** [comment]
Thank you very much.

We present the implementation done in `broom.helpers` in this vignette https://larmarange.github.io/broom.helpers/dev/articles/marginal_tidiers.html

This is still the dev version. Do not hesitate to provide feedback about the wording.

Once the next version of `marginaleffects` on CRAN, we could update `broom.helpers` accordingly.
