### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by arthur-albuquerque** [vincentarelbundock/marginaleffects#593]
Hi Vincent,

There is a minor typo in the documentation. I guess it should say "slopes()" instead of "comparisons()" in the 6th row

![image](https://user-images.githubusercontent.com/77208087/212996873-97a965ba-618c-41c4-aa57-6af9ac284aeb.png)

**Comment by vincentarelbundock** [comment]
thanks a lot. Fixed here: https://github.com/vincentarelbundock/marginaleffects/commit/487344f6f16110791e904eff82c03635bbbd47d3

Website will update eventually.
