### ISSUE TITLE
pkgdown development mode

### ISSUE THREAD

**Issue by larmarange** [vincentarelbundock/marginaleffects#613]
Considering all ongoing changes in your package, you could consider the development mode of pkgdown. 

It is very easy to implement and generate two different documentation website : one for the latest released version and one for the development version.

With GitHub action, it's automatic.

**Comment by vincentarelbundock** [comment]
Thanks for this great suggestion! I didn't know it was this easy. Done: 

https://vincentarelbundock.github.io/marginaleffects/dev/

**Comment by larmarange** [comment]
Thanks
