### ISSUE TITLE
Interactions section in vignette is confusing

### ISSUE THREAD

**Issue by andymilne** [vincentarelbundock/marginaleffects#622]
I am confused by the Interactions section of the Comparisons vignette: https://vincentarelbundock.github.io/marginaleffects/articles/contrasts.html#interactions. It may just be me or perhaps it is more generally confusing.

The first example is preceded by "What happens if am increases by 1 unit and cyl changes from a baseline reference to another level?"
```
cmp <- comparisons(mod, variables = c("cyl", "am"))
summary(cmp)
```
But this seems to show the effect of changing either `cyl` **or** `am` (not `cyl` **and** `am`). This can be confirmed by running the following, which gives identical numbers.

```
cmp1 <- comparisons(mod, variables = "cyl")
summary(cmp1)
cmp2 <- comparisons(mod, variables = "am")
summary(cmp2)
```
So it seems there is no interaction as such included in the summary. Surely "interaction" implies conditioning of some kind? And a way to actually get an interaction is to use the `by` argument:

```
cmp3 <- comparisons(mod, variables = "cyl", by = "am")
summary(cmp3)
```
This gives the interactions between `cyl` and `am`. 

Alternatively, set `cross` to `TRUE`:
```
cmp4 <- comparisons(mod, variables = c("cyl", "am"), cross = TRUE)
> summary(cmp4)
```
This gives the contrast of changing "cyl" and "am" at the same time, which corresponds to the earlier quoted text. But I don't think this is showing what I what would think of as the "interaction" between the two terms (as shown when using `by`).

So it's not clear to me whether this section is about interactions (it's title) or about changing two or more predictors at the same time (what's in the text). And the main example provided doesn't seem to correspond to either.

**Comment by vincentarelbundock** [comment]
Thanks for raising this issue.

I'm preparing to release a new major version of the package which will recommend a slightly different workflow. I tried to improve that portion of the vignette on the development website. Let me know if you think this is clearer:

https://vincentarelbundock.github.io/marginaleffects/dev/articles/comparisons.html#interactions-and-cross-contrasts

**Comment by andymilne** [comment]
Yes, the rewrite is now very clear. Thank you, and looking forwards to seeing what the new recommended workflow will be.
