### ISSUE TITLE
`etwfe` problems

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/marginaleffects#624]
+ [ ] `group` is not a predictor, but it is in `newdata`, then `by` will automatically group by this. But this may not be desired. Causes problems in `etwfe` `test_baker.R` for example.
+ [ ] exact zero results in `test_emfx_xvar.R` `event_pre_known`

**Comment by grantmcdermott** [comment]
Thanks for keeping track of these! 

One minor FYI and another question (which can be rolled into a separate issue it makes sense):

1. I've [tweaked](https://github.com/grantmcdermott/etwfe/blob/c5cc4e1c40daabf7764379ab1fc4e979a8ce0af9/R/emfx.R#L156-L157) your proposed workaround for the zero results case to avoid false positives from `vcov=FALSE`.
 
2. Is it possible to provide a `newdata` argument to `plot_slopes()` (or any of the related plotting functions)? My conceptual use-case is allowing users to plot the results from an `etwfe::emfx()` call directly, essentially by switching out the `slopes()` call [here](https://github.com/grantmcdermott/etwfe/blob/c5cc4e1c40daabf7764379ab1fc4e979a8ce0af9/R/emfx.R#L142) for the equivalent `plot_slopes()` call.

**Comment by vincentarelbundock** [comment]
Thanks for the note on 1. Will take a look.

On 2, could you give me a bit more detail? The impetus for these `plot_*()` functions was to give the user a simple way to create the `newdata` automatically. Otherwise, this is just a `slopes()` call with a vanilla `ggplot()`, so there’s not much value add.

BTW, you can actually specify the values of the grid manually in `plot_comparisons()`‘s’ `condition` argument, and you can set `transform_pre="dydx"` if you want the partial:

``` r
library(marginaleffects)
mod <- lm(mpg ~ hp * qsec * am, data = mtcars)

plot_comparisons(
    mod,
    transform_pre = "dydx",
    effect = "hp",
    condition = list("am", "qsec" = c(14, 18, 34)))
```

![](https://i.imgur.com/c1c5mvT.png)

**Comment by vincentarelbundock** [comment]
And I had forgotten, but this apparently also works with `plot_slopes()`

```r
plot_slopes(
    mod,
    effect = "hp",
    condition = list("am", "qsec" = c(14, 18, 34)))
```

So you don't have to mess with `transform_pre`

**Comment by grantmcdermott** [comment]
(Thanks for the quick reply/suggestion. Heading out bit, but will respond when I get back.)

**Comment by vincentarelbundock** [comment]
@grantmcdermott I took a look at your tweak. In those cases, I think it might make more sense for `marginaleffects` to return a column of 0s for `estimate` and a column of `NA`s for `std.error`. The zeros might actually be informative: in the pre-treatment period, the model imposes an exact zero effect. But the zeros obviously don’t make sense for `std.error`, so we return `NA`, which will propagate to CIs, etc.

Makes sense?

If so, I think that would require a little adaption here, otherwise you’ll let `NA` elements in `idx`: <https://github.com/grantmcdermott/etwfe/blob/c5cc4e1c40daabf7764379ab1fc4e979a8ce0af9/R/emfx.R#L156>

4c97b6f399ab7ba09f77343ae753bfa0aef085de implements the suggestion above, and gives an informative warning for the reserved `group` name:

``` r
library(marginaleffects)
dat <- transform(mtcars, group = cyl)
mod <- lm(mpg ~ hp, data = dat)
slopes(mod, by = "cyl")
# 
#  Group Term    Contrast cyl Estimate Std. Error      z  Pr(>|z|)    2.5 %
#      6   hp mean(dY/dX)   6 -0.06823    0.01012 -6.742 1.558e-11 -0.08806
#      4   hp mean(dY/dX)   4 -0.06823    0.01012 -6.742 1.558e-11 -0.08806
#      8   hp mean(dY/dX)   8 -0.06823    0.01012 -6.742 1.558e-11 -0.08806
#    97.5 %
#  -0.04839
#  -0.04839
#  -0.04839
# 
# Prediction type:  response 
# Columns: type, group, term, contrast, cyl, estimate, std.error, statistic, p.value, conf.low, conf.high, predicted, predicted_hi, predicted_lo

slopes(mod, by = "group")
# Error: The "group" variable name is forbidden to avoid conflicts with the
#   column names of the outputs produced by the `marginaleffects` package.
#   Please rename your variable of change the value of the `by` argument.
```

Let's discuss plotting in your other issue: https://github.com/vincentarelbundock/marginaleffects/issues/647

**Comment by grantmcdermott** [comment]
SGTM. I'll circle back to the plotting issue as soon as I get a chance. Trying to get this next release ready for CRAN resubmission in addition to regular work stuff...

Quickly though: The `group` column in the example above is randomly ordered (6 => 4 => 8). This may be an artefact of data.table's unsorted grouping heuristic. But I think users will probably expect sorted results on the marginaleffects side.

**Comment by vincentarelbundock** [comment]
> Quickly though: The `group` column in the example above is randomly ordered (6 => 4 => 8). This may be an artefact of data.table's unsorted grouping heuristic. But I think users will probably expect sorted results on the marginaleffects side.

Good point: https://github.com/vincentarelbundock/marginaleffects/issues/649
