### ISSUE TITLE
Linetypes in plots

### ISSUE THREAD

**Issue by fschaffner** [vincentarelbundock/marginaleffects#630]
Hi @vincentarelbundock, I was wondering if you would consider adding an argument to the `plot_*()` functions that plots the lines in different linetypes? (e.g., `add_linetypes = TRUE` or similar). This would be useful for two reasons: 1) it would make the plots suitable for black-and-white printing, and 2) it would make them colorblind-friendly. 
(Some people would probably advocate for making the print-ready and colorblind-friendly version the default, but it's also reasonable to implement it as an optional argument)

I know it's possible to use `draw = FALSE` and then ggplot to modify linetypes (see below), but this does get quite tedious, especially when having to create lots of plots quickly. I also tried to find a way to update the linetype in one line after `plot_predictions()` without success, but if you know a way, that might be an easy solution.

Thanks for considering this!

``` r
library("marginaleffects")
library(ggplot2)
theme_set(theme_minimal())

mod <- lm(mpg ~ hp * wt * am, data = mtcars)

# Current output
plot_predictions(mod, condition = list("hp", wt = "threenum"))
```

![](https://i.imgur.com/FkjD6Em.png)

``` r

# Could an argument be added?
plot_predictions(mod, condition = list("hp", wt = "threenum"), add_linetypes = TRUE)
```

``` r

# Proposed output
plot_predictions(mod, condition = list("hp", wt = "threenum"), draw = FALSE) |>
  ggplot() +
  aes(
    x = hp,
    y = estimate
  ) +
  geom_line(aes(color = wt, linetype = wt)) +
  geom_ribbon(aes(
    ymin = estimate - 1.96 * std.error,
    ymax = estimate + 1.96 * std.error,
    fill = wt
  ), alpha = 0.1)
```

![](https://i.imgur.com/oZAJS3m.png)

``` r

# First try to update linetype in one line after plot_predictions() - doesn't work
plot_predictions(mod, condition = list("hp", wt = "threenum")) +
  geom_line(aes(linetype = wt))

# Second try to update linetype in one line after plot_predictions() - doesn't work
plot_predictions(mod, condition = list("hp", wt = "threenum")) +
  scale_linetype_manual(values = c("dotted", "dashed", "dotdash", "longdash", "solid"))
```

**Comment by vincentarelbundock** [comment]
Those are two very good arguments. I am convinced.

I'd just like us to think a bit about the user interface. Is there a way to generalize this into a more powerful way to choose which `aes` and `geoms` match which dimension? What other option would people like to get?

**Comment by vincentarelbundock** [comment]
Closing issue to consolidate here: https://github.com/vincentarelbundock/marginaleffects/issues/673
