### ISSUE TITLE
`get_predict()` should always return a named list

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/marginaleffects#633]
A few model classes use their own `get_predict()` methods. They should all be converted to the list-style proposed by @etiennebacher in https://github.com/vincentarelbundock/marginaleffects/pull/632

This would make things more efficient. Searching the `methods_*.R` file, it looks like there are probably a dozen of them.

Also, revisit whether we need `sanity_predict_vector()` and `sanity_predict_numeric()`. Those seem useful, but `get_predict()` is where `marginaleffects` spends most of its time, so it might be worth it to make some assumptions or to make checks outside a method that gets called a ton like this one.

Also, update the Extending vignette to say that we need a list with elements of equal length.

**Comment by vincentarelbundock** [comment]
FWIW, I'm reading the error messages in those `sanity_` functions and I can't remember the last time I ran agaisnt them in practice. Also, we now have very strong checks at the outset on which models are supported and which `type` arguments are accepted. So my guess is we can scrap all those checks inside `get_predict()`. Need to run the test suite, of course.

**Comment by etiennebacher** [comment]
> A few model classes use their own get_predict() methods. They should all be converted to the list-style proposed by @etiennebacher in https://github.com/vincentarelbundock/marginaleffects/pull/632

FYI the change I made in #632 to use `list()` is only useful to replace a call to `data.table()`. Using `setDF(list(...))` as in #632 is not much faster than calling `data.frame()` directly.

``` r
library(data.table)

x <- sample(1:10, 25000000, replace = TRUE)
y <- sample(1:10, 25000000, replace = TRUE)

bench::mark(
  setDF(data.table(x, y))[],
  setDF(list(x = x, y = y))[]
)
#> # A tibble: 2 × 6
#>   expression                       min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>                  <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 setDF(data.table(x, y))[]     49.4ms   63.8ms      15.7     191MB     31.3
#> 2 setDF(list(x = x, y = y))[]   13.3µs   15.2µs   51552.         0B     15.5

bench::mark(
  data.frame(x, y),
  setDF(list(x = x, y = y))[]
)
#> # A tibble: 2 × 6
#>   expression                       min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>                  <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 data.frame(x, y)             100.7µs  107.4µs     7324.        0B     17.9
#> 2 setDF(list(x = x, y = y))[]   13.2µs   14.2µs    55402.        0B     22.2
```

**Comment by vincentarelbundock** [comment]
Good to know, thanks. 

Then it looks like the only relevant case might be `mlogit`. I think that most of the calls to `data.table()` are one-time deals where overheard won't affect total much.

The sanity checks are from `checkmate` which is super fast, so it's probably not worth the trouble of removing them.
