### ISSUE TITLE
Loading `dplyr` in tests significantly slows them down

### ISSUE THREAD

**Issue by etiennebacher** [vincentarelbundock/marginaleffects#634]
I noticed that calling `requiet("dplyr")` in the tests files makes all the subsequent tests run much slower.

For example, the first call to `dplyr` is in `test-equivalence.R`. All the tests files before this one run in ~5sec, but all those after take between 20 and 50 sec, which makes quite a diff given the number of tests. Replacing `dplyr` by `datawizard` (for example) in `test-equivalence.R` solves this problem (until the next call to `dplyr`).

I don't know if it's just my local config but I thought I'd open an issue in case someone has the same problem. Feel free to close.

**Comment by vincentarelbundock** [comment]
Good catch!

My impression is that loading `dplyr` does not slow down the actual `marginaleffects` functions. My best guess is that this had to do with the `conflicted` calls in `inst/tinytest/helpers.R`. I removed those, added some namespaces, and replaced `dplyr` with `poorman`. Things are much faster now:



![Screenshot 2023-02-03 083712](https://user-images.githubusercontent.com/987057/216618642-b39c02b0-f899-481e-8f46-5db3282b670e.png)

**Comment by etiennebacher** [comment]
I confirm, it's much faster now, thank you!
