### ISSUE TITLE
brms multivariate models with additional response information

### ISSUE THREAD

**Issue by hwallen** [vincentarelbundock/marginaleffects#641]
Hi!

Im wondering how {marginaleffects} works with brms multivariate models and would be possible to add additional arguments related to those models, especially related to multivariate models with "additional response information"? For example, brms allows to subset the data used for the model in the formula by an additional TRUE/FALSE variable. Also, brms::posterior_predict -function has an optional argument "resp", in which "resp=Optional names of response variables. If specified, predictions are performed only for the specified response variables.".

It seems that in brms multivariate models argument "resp" works, although it produces a warning that the argument "resp" is not supported. If this argument is used in multivariate model with "resp_subset", then in the case of this response variable with the subset argument error is produced: _"This error was also raised:  arguments imply differing number of rows"_ Im guessing the subset-argument causes the mismatch of rows? A simple, although completely toy, example provided below. I hope it illustrates the issue in an understandable way.

Thank you!

```{r}
library(tidyverse)
library(brms)
library(marginaleffects)

set.seed(03022023)
df_data <- tibble(
    y1 = rnorm(100, 0, 1),
    y2 = rbinom(100, 1, 0.65),
    x1 = rnorm(100, 1, 0.5),
    x2 = as.factor(rbinom(100, 1, 0.5)),
    g1 = as.factor(rbinom(100, 1, .5))) %>%
    mutate(resp = if_else(x1 < .5, 0, 1))

m1 <- bf(y1 | resp_subset(resp) ~ x1 + x2 + (1 | g1)) + gaussian(link = "identity")
m2 <- bf(y2 ~ x1 + x2 + (1 | g1)) + bernoulli(link = "logit")

fit1 <- brm(
    data = df_data,
    formula = m1 + m2 + set_rescor(rescor = FALSE),
    backend = "cmdstanr",
    chains = 2,
    iter = 1000
)

avg_predictions(fit1)

avg_predictions(fit1, resp = "y1")

avg_predictions(fit1, resp = "y2")
```

**Comment by vincentarelbundock** [comment]
Thanks a lot for the report.

I have added `resp` to the white list of supported arguments. If you install the development version from Github and restart `R` entirely, it won’t raise warning anymore:

``` r
library(tidyverse)
library(brms)
library(marginaleffects)

set.seed(03022023)
df_data <- tibble(
    y1 = rnorm(100, 0, 1),
    y2 = rbinom(100, 1, 0.65),
    x1 = rnorm(100, 1, 0.5),
    x2 = as.factor(rbinom(100, 1, 0.5)),
    g1 = as.factor(rbinom(100, 1, .5))) %>%
    mutate(resp = if_else(x1 < .5, 0, 1))

m1 <- bf(y1 | resp_subset(resp) ~ x1 + x2 + (1 | g1)) + gaussian(link = "identity")
m2 <- bf(y2 ~ x1 + x2 + (1 | g1)) + bernoulli(link = "logit")

fit1 <- brm(
    data = df_data,
    formula = m1 + m2 + set_rescor(rescor = FALSE),
    backend = "cmdstanr",
    chains = 2,
    iter = 1000)
```

If you don’t supply a `resp` argument at all, you will see an appropriate and informative error message:

``` r
avg_predictions(fit1)
# Error: Unable to compute predicted values with this model. You can try to
#   supply a different dataset to the `newdata` argument. This error was
#   also raised:
#   
#   Argument 'resp' must be a single variable name for models using addition
#   argument 'draw_ids'.
#   
#   Bug Tracker:
#   https://github.com/vincentarelbundock/marginaleffects/issues
```

Supplying `resp` with `y2` no longer generates a useless warning:

``` r
avg_predictions(fit1, resp = "y2")
#  Estimate  2.5 % 97.5 %
#    0.6177 0.5224 0.7064
# 
# Prediction type:  response 
# Columns: type, estimate, conf.low, conf.high

avg_comparisons(fit1, resp = "y2")
#  Term Contrast  Estimate   2.5 % 97.5 %
#    g1    1 - 0 -0.013476 -0.1817 0.1241
#    x1       +1  0.005019 -0.1719 0.1884
#    x2    1 - 0  0.055388 -0.1474 0.2492
# 
# Prediction type:  response 
# Columns: type, term, contrast, estimate, conf.low, conf.high
```

Unfortunately, I’m not sure how to compute estimates for `y1 | resp_subset()`. To do this, I would need to be able to match columns in `posterior_epred()` (83 columns) to rows in `df_data` (100 rows):

``` r
posterior_epred(fit1, resp = "y1") |> dim()
# [1] 1000   83

dim(df_data)
# [1] 100   6

avg_predictions(fit1, resp = "y1")
# Error: Unable to compute predicted values with this model. You can try to
#   supply a different dataset to the `newdata` argument. This error was
#   also raised:
#   
#   Dimension mismatch: There are 83 parameters in the posterior draws but
#   100 observations in `newdata` (or the original dataset).
#   
#   Bug Tracker:
#   https://github.com/vincentarelbundock/marginaleffects/issues
```

What matches what? I tried to look inside `fit1` but couldn’t find an index. Any hints?

**Comment by vincentarelbundock** [comment]
Closing to clean up the repo, not to put pressure on you. I'd still be interested in your views on this.

Feel free to keep commenting if you find some information about indexing in the model object.
