### ISSUE TITLE
Average Marginal Contrasts with a by variable

### ISSUE THREAD

**Issue by larmarange** [vincentarelbundock/marginaleffects#643]
Hi,

I have a methodological question. If you have a model with an interaction between two categorical variables, and if you want to compute marginal contrasts of the first variable by the value of the second variable. I suppose that in such a situation, the overall dataset should be duplicated for each unique value of the second variable. However, if `newdata = NULL`, the dataset will be duplicated only for the values of the first variable. Not sure if I'm clear, see below an example.

``` r
library(marginaleffects)
library(tidyverse)

df <- Titanic %>%
  dplyr::as_tibble() %>%
  tidyr::uncount(n) %>%
  dplyr::mutate(Survived = factor(Survived, c("No", "Yes")))
mod <- glm(
  Survived ~ Class + Age + Sex,
  data = df, family = binomial
)

avg_comparisons(mod, variables = "Class", by = "Sex")
#> 
#>   Term               Contrast    Sex Estimate Std. Error       z   Pr(>|z|)
#>  Class  mean(2nd) - mean(1st)   Male  -0.2098    0.03928  -5.341 9.2646e-08
#>  Class  mean(2nd) - mean(1st) Female  -0.1414    0.02990  -4.729 2.2515e-06
#>  Class  mean(3rd) - mean(1st)   Male  -0.3072    0.03324  -9.242 < 2.22e-16
#>  Class  mean(3rd) - mean(1st) Female  -0.3046    0.02859 -10.653 < 2.22e-16
#>  Class mean(Crew) - mean(1st)   Male  -0.1825    0.03560  -5.127 2.9483e-07
#>  Class mean(Crew) - mean(1st) Female  -0.1129    0.02293  -4.923 8.5059e-07
#>    2.5 %   97.5 %
#>  -0.2867 -0.13278
#>  -0.2000 -0.08280
#>  -0.3723 -0.24203
#>  -0.3606 -0.24855
#>  -0.2523 -0.11274
#>  -0.1578 -0.06795
#> 
#> Prediction type:  response 
#> Columns: type, term, contrast, Sex, estimate, std.error, statistic, p.value, conf.low, conf.high, predicted, predicted_hi, predicted_lo
avg_comparisons(mod, variables = "Class", by = "Sex", newdata = datagridcf(Sex = unique))
#> 
#>   Term               Contrast    Sex Estimate Std. Error       z   Pr(>|z|)
#>  Class  mean(2nd) - mean(1st)   Male  -0.2103    0.03934  -5.344 9.0750e-08
#>  Class  mean(2nd) - mean(1st) Female  -0.1452    0.03067  -4.733 2.2123e-06
#>  Class  mean(3rd) - mean(1st)   Male  -0.3086    0.03325  -9.280 < 2.22e-16
#>  Class  mean(3rd) - mean(1st) Female  -0.3116    0.02934 -10.622 < 2.22e-16
#>  Class mean(Crew) - mean(1st)   Male  -0.1828    0.03560  -5.135 2.8154e-07
#>  Class mean(Crew) - mean(1st) Female  -0.1160    0.02346  -4.943 7.6840e-07
#>    2.5 %   97.5 %
#>  -0.2874 -0.13315
#>  -0.2053 -0.08506
#>  -0.3737 -0.24339
#>  -0.3691 -0.25413
#>  -0.2526 -0.11306
#>  -0.1620 -0.06999
#> 
#> Prediction type:  response 
#> Columns: type, term, contrast, Sex, estimate, std.error, statistic, p.value, conf.low, conf.high, predicted, predicted_hi, predicted_lo
avg_comparisons(mod, variables = "Class", by = "Sex", newdata = datagridcf(Sex = unique, Class = unique))
#> 
#>   Term               Contrast    Sex Estimate Std. Error       z   Pr(>|z|)
#>  Class  mean(2nd) - mean(1st)   Male  -0.2103    0.03934  -5.344 9.0750e-08
#>  Class  mean(2nd) - mean(1st) Female  -0.1452    0.03067  -4.733 2.2123e-06
#>  Class  mean(3rd) - mean(1st)   Male  -0.3086    0.03325  -9.280 < 2.22e-16
#>  Class  mean(3rd) - mean(1st) Female  -0.3116    0.02934 -10.622 < 2.22e-16
#>  Class mean(Crew) - mean(1st)   Male  -0.1828    0.03560  -5.135 2.8154e-07
#>  Class mean(Crew) - mean(1st) Female  -0.1160    0.02346  -4.943 7.6840e-07
#>    2.5 %   97.5 %
#>  -0.2874 -0.13315
#>  -0.2053 -0.08506
#>  -0.3737 -0.24339
#>  -0.3691 -0.25413
#>  -0.2526 -0.11306
#>  -0.1620 -0.06999
#> 
#> Prediction type:  response 
#> Columns: type, term, contrast, Sex, estimate, std.error, statistic, p.value, conf.low, conf.high, predicted, predicted_hi, predicted_lo
```

<sup>Created on 2023-02-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

In `sanitize_newdata()`, there is a specific treatment of the `by` variable when `newdata = "mean"` or `newdata = "marginalmean"` but not when `newdata = NULL`.

https://github.com/vincentarelbundock/marginaleffects/blob/9a06aa03c017947df978caa4d82fa6e650e2de8f/R/sanitize_newdata.R#L15-L17

https://github.com/vincentarelbundock/marginaleffects/blob/9a06aa03c017947df978caa4d82fa6e650e2de8f/R/sanitize_newdata.R#L28-L29

I may be wrong, but should the computation of the comparison be done on the overall dataset for each value of the by variable?

**Comment by vincentarelbundock** [comment]
I don't remember a published argument in favor of either.

My own intuition is to *not* use `datagridcf()`. If you do, then the distribution of the `by` variable in your overall dataset will be perfectly uniform, which probably does not match the empirical distribution of your sample (or of your population if the sample is representative). In doing so, you are marginalizing over a weird non-representative grid.

In practice, I doubt this will often make a big difference.

I will close this issue because this is the `marginaleffects` development website. My sense is that the current behavior is sufficiently easy to infer from the documentation, and that `newdata=datagridcf()` makes it very easy to get the counterfactual grid if the user wants that.

If you need methodological advice, I suggest you describe the quantities in mathematical notation and [post on Cross Validated](https://stats.stackexchange.com/), perhaps with a `marginaleffects` example at the end of your post, after the math.

**Comment by larmarange** [comment]
Thanks for your feedback
