### ISSUE TITLE
Failing pkgdown action

### ISSUE THREAD

**Issue by etiennebacher** [vincentarelbundock/marginaleffects#644]
I tried to explore a bit why this action fails because this "shutdown signal" is quite strange (and who knows, it could happen to me too). I couldn't find the root of the problem but it probably lies in the `brms` vignette (where it stops). Everything works fine locally for me so I don't know where it comes from. I tried to narrow down the problem by commenting out parts of the vignette: sometimes it failed, sometimes it worked but I couldn't find the reason.

That's it, just putting it here if it helps.

**Comment by vincentarelbundock** [comment]
Yeah, I really don't know what the problem is. The site builds fine on my computer too. Initially I thought code 143 was a graceful exit when CPU limit is exceed on the host, but I just removed the last `brms` call and am downloading the models instead, so there's really not that much computation going on in the vignette at all...

**Comment by vincentarelbundock** [comment]
In any case, I removed the workflow. What matters is that tests get run automatically. I can update the website manually once in a while.

**Comment by vincentarelbundock** [comment]
@etiennebacher FYI, the `pkgdown` workflow is working again. 

In 0.9.0 I changed the `get_modeldata()` function to retrieve all columns in the original data frame by default. In one of the `brms` vignette examples, the dataset has many useless variables. Just copying all those columns back and forth was very memory-expensive (>16GB). So I guess we were hitting the Github machine's limits.

**Comment by etiennebacher** [comment]
I see, thanks for the explanation!
