### ISSUE TITLE
Support: `coxme`

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/marginaleffects#645]
https://cran.r-project.org/web/packages/coxme/index.html

https://twitter.com/jezroff/status/1622184422798929920?s=46&t=ANLh8VwY0MUKovDgz09aJA

**Comment by vincentarelbundock** [comment]
Unfortunately, we cannot support this model because the `predict.coxme()` method supplied by `coxme` does not support the `newdata` argument:

``` r
library(coxme)
# Loading required package: survival
# Loading required package: bdsmatrix
# 
# Attaching package: 'bdsmatrix'
# The following object is masked from 'package:base':
# 
#     backsolve

tmp <- tempfile()
download.file("https://github.com/cran/coxme/raw/master/data/eortc.rda", tmp)
load(tmp)

mod <- coxme::coxme(Surv(y, uncens) ~ trt + (1|center), eortc)
predict(mod, newdata = head(eortc))
# Error in predict.coxme(mod, newdata = head(eortc)): newdata argument not yet supported
```

The author of the `coxme` package would have to add support for `newdata` before we can start working on this.

**Comment by marine-ecologist** [comment]
@vincentarelbundock many thanks for taking a look at this - I'll message [Terry Therneau](https://github.com/therneau) and ask if there's any timeline for this to be implemented.

**Comment by csthiago** [comment]
@vincentarelbundock  Take a look at this package: https://github.com/junkka/ehahelper the predict_coxme from there allows newdata

**Comment by vincentarelbundock** [comment]
Thanks, this is very interesting.

Unfortunately, we only support CRAN packages and we don't have enough development resources to ship and maintain our own predict functions.

**Comment by vincentarelbundock** [comment]
If/when this is merged in coxme, I'll be happy to revisit and see if we can add full support.

**Comment by raffaem** [comment]
Was this reported upstream? I don't understand
