### ISSUE TITLE
Error with subsetted list and hypotheses() 

### ISSUE THREAD

**Issue by kennchua** [vincentarelbundock/marginaleffects#656]
Hi Vincent, 

Thanks for your amazing work on this R package.

I just wanted to report a potential bug I encountered when using the `hypotheses()` command and working with list subsets. In the following example, `hypotheses()` works when fed a named regression output but not when fed a call to a subset of a list.

```
library(tidyverse)
library(marginaleffects)

reg_list <- list()
reg_list[[1]] <- lm(mpg ~ wt + hp, data = mtcars)
reg_list[[2]] <- lm(mpg ~ wt + hp + factor(vs), data = mtcars)


hypotheses(reg_list[[1]]) # error

reg_list_1 <- reg_list[[1]] 
hypotheses(reg_list_1) # ok
```

The error I get is the following: 
> Error in class(out) <- c("hypotheses", class(out)) : 
>   attempt to set an attribute on NULL

A potentially related issue I encountered when working with lists:

```
map(reg_list, hypotheses) # returns error
map(reg_list, ~hypotheses(.)) # works

```

Seems this just has something to do with the input hypotheses() expects. I can work around them currently so not a big deal. Thanks again!

**Comment by vincentarelbundock** [comment]
@kennchua unfortunately, this is a known problem and, for boring infrastructure reasons, I am not sure there will ever be a solution.

See the warning in the documentation: https://vincentarelbundock.github.io/marginaleffects/reference/hypotheses.html

**Comment by vincentarelbundock** [comment]
@kennchua sorry, closed this one too fast. I think I may have an idea for at least a partial fix. Will ping you if/when there's success.

**Comment by kennchua** [comment]
No worries. I'll look out for any updates. Thank you!

**Comment by vincentarelbundock** [comment]
I think this should work now with the current version from Github. Make sure you restart completely after installing, and let me know if you find other variations that break things.

Thanks for filing the issue!

**Comment by kennchua** [comment]
Hi Vincent, I got a chance to check the Github version. So far it works on the above examples, but I'm running into new errors when providing a specific hypothesis to test.

```
library(tidyverse)
library(broom)
library(marginaleffects)

reg_list <- list()
reg_list[[1]] <- lm(mpg ~ wt + hp, data = mtcars)
reg_list[[2]] <- lm(mpg ~ wt + hp + factor(vs), data = mtcars)


hypotheses(reg_list[[1]]) # works in Github version;  error in CRAN version
hypotheses(reg_list[[1]], "wt = 0") # works in Github version;  error in CRAN version

map(reg_list, ~hypotheses(.)) # works in Github and CRAN versions
map(reg_list, hypotheses) # works in Github version; error in CRAN version


map(reg_list, ~hypotheses(., "wt = 0"))  # works in Github and CRAN versions
map(reg_list, hypotheses("wt = 0")) # error for Github version and CRAN version

```

The error is the following:

> Error in `colnames<-`(`*tmp*`, value = `*vtmp*`) : 
>   attempt to set 'colnames' on an object with less than two dimensions
> In addition: Warning messages:
> 1: Unable to extract a variance-covariance matrix from this model. 
> 2: Parameters can't be retrieved for objects of class `simpleError`. 

Also, I didn't encounter this next error in the CRAN version, but in the Github version, piping `hypotheses` output to `broom::tidy()` within `map()` / `lapply()` started giving me errors in which the model in the list is not found. 

```
map(reg_list , ~hypotheses(.) |> broom::tidy()) # error in Github version; works in CRAN version
map(reg_list, function(reg) reg |>  hypotheses("wt = 0") |>  broom::tidy()) # error in Github version; works in CRAN version
```

Thanks for looking into these issues. This package has been really helpful in my work.

**Comment by vincentarelbundock** [comment]
Thanks a lot for all of these examples @kennchua. They are super useful, and I have added them all to the test suite to make sure that future package updates don’t break them.

Version 0.9.0.9033 should now work as expected. The only exception is this example which, I believe, is a misuse of the `purrr::map` syntax:

``` r
purrr::map(reg_list, hypotheses("wt = 0"))
```

`hypotheses` requires the first argument to be a model. But note that your syntax does *not* supply the list element as first argument:

``` r
fun <- function(x, ...) return(x)
purrr::map(c("a", "b"), fun("c"))
# [[1]]
# NULL
# 
# [[2]]
# NULL
``
