### ISSUE TITLE
Improve `plot_*()` functions

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/marginaleffects#673]
TODO items completed.

**Comment by vincentarelbundock** [comment]
FYI, I merged a refactor of the `plot_*()` functions. See the new vignette on the development site: 

https://vincentarelbundock.github.io/marginaleffects/dev/articles/plot.html

@grantmcdermott : For consistency, the `effect` argument is now `variables`. There is a new `by` argument which allows you to plot marginal (average) estimates of all three quantities (predictions, comparisons, slopes). So you can do: `slopes(mod, by = "cyl")` and the analogous `plot_slopes(mod, by = "cyl")`

@fschaffner : There is a new `gray` argument. Also, `rug` and `points` arguments.

@strengejacke : I added an informative error and a new section to the vignette explaining why it's not possible to call `plot(predictions(mod))` and what the easy alternatives are.

Hope this is helpful.

**Comment by grantmcdermott** [comment]
Fantastic! I've under a major deadline at work, but am looking to reading the new vignette once that's done. Appreciate all the thought and consideration that you given to these requests.
