### ISSUE TITLE
Why does `inferences(method = "delta")` take time if it's equivalent to the default?

### ISSUE THREAD

**Issue by etiennebacher** [vincentarelbundock/marginaleffects#682]
In [this vignette](https://vincentarelbundock.github.io/marginaleffects/dev/articles/bootstrap.html#delta-method), you say that adding `inferences(method = "delta")` after `avg_comparisons(mod, by = "Species", variables = "Petal.Width")` doesn't change anything in terms of results because the default is to use the delta method. However, it makes a big difference in terms of timing.

Why does adding `inferences(method = "delta")` take so much time if it's equivalent to the default of `avg_comparisons()`? Maybe there's a way to skip computations in this case?
``` r
library(marginaleffects)

tmp <- list()
for (i in 1:300) {
  tmp[[i]] <- iris
}
dat <- data.table::rbindlist(tmp)

mod <- lm(Sepal.Length ~ Petal.Width * Petal.Length + factor(Species), data = dat) 

bench::mark(
  without_inf = avg_comparisons(mod, by = "Species", variables = "Petal.Width"),
  with_inf = avg_comparisons(mod, by = "Species", variables = "Petal.Width") |>
    inferences(method = "delta")
)
#> Warning: Some expressions had a GC in every iteration; so filtering is
#> disabled.
#> # A tibble: 2 × 6
#>   expression       min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>  <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 without_inf  539.9ms  539.9ms    1.85       292MB    22.2 
#> 2 with_inf       18.7s    18.7s    0.0535     585MB     1.18
```

<sup>Created on 2023-02-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by vincentarelbundock** [comment]
Thanks for noting this. This is a remnant of an older implementation which could capture the call, modify arguments, and re-evaluate. I'm suprised it too so long, but it's not needed anyway in the current implementation. `method="delta"` should just return the original object. https://github.com/vincentarelbundock/marginaleffects/commit/24eac2b4e1d7bd8d030024c99577c80accce94f8
