### ISSUE TITLE
avg_predictions() if data.frame contains variable named "term"

### ISSUE THREAD

**Issue by nowo1978** [vincentarelbundock/marginaleffects#683]
Hi, I'm a big fan of your package! However, there appears to be a strange problem with running avg_predictions() on a glm()-model if the data.frame on which the model was estimated contains a variable called "term", even if this variable is not in the model. It appears that in this case avg_predictions(model) actually replicates predictions(model, by = "term").

Minimal example:
```
library(marginaleffects)

logit <- glm(am ~ mpg + cyl, 
             data = mtcars, 
             family = binomial(link = "logit"))

# Works as expected
avg_predictions(logit)

# Create new random variable "term" in mtcars
mtcars$term <- sample(1:5, nrow(mtcars), TRUE)

# avg_predictions(model) behaves like 
# predictions(model, by = "term")
avg_predictions(logit)
predictions(logit, by = "term")

# Deleting variable "term" solves the issue
mtcars$term <- NULL
avg_predictions(logit)
```
Here's the output:
```
>library(marginaleffects)
> 
> logit <- glm(am ~ mpg + cyl, 
+              data = mtcars, 
+              family = binomial(link = "logit"))

> # Works as expected
> avg_predictions(logit)

 Estimate Std. Error     z   Pr(>|z|)  2.5 % 97.5 %
   0.4062    0.06884 5.902 3.5978e-09 0.2713 0.5412

Prediction type:  response 
Columns: type, estimate, std.error, statistic, p.value, conf.low, conf.high 

> # Create new random variable "term" in mtcars
> mtcars$term <- sample(1:5, nrow(mtcars), TRUE)

> # avg_predictions(model) behaves like 
> # predictions(model, by = "term")
> avg_predictions(logit)

 Term Estimate Std. Error     z   Pr(>|z|)     2.5 % 97.5 %
    2   0.5206    0.09058 5.747 9.0612e-09  0.343078 0.6982
    1   0.3586    0.07179 4.995 5.8709e-07  0.217921 0.4993
    5   0.4239    0.09313 4.552 5.3121e-06  0.241393 0.6064
    3   0.4265    0.06049 7.051 1.7731e-12  0.307955 0.5451
    4   0.1320    0.07105 1.858   0.063207 -0.007263 0.2712

Prediction type:  response 
Columns: type, term, estimate, std.error, statistic, p.value, conf.low, conf.high 

> predictions(logit, by = "term")

 Term Estimate Std. Error     z   Pr(>|z|)     2.5 % 97.5 %
    2   0.5206    0.09058 5.747 9.0612e-09  0.343078 0.6982
    1   0.3586    0.07179 4.995 5.8709e-07  0.217921 0.4993
    5   0.4239    0.09313 4.552 5.3121e-06  0.241393 0.6064
    3   0.4265    0.06049 7.051 1.7731e-12  0.307955 0.5451
    4   0.1320    0.07105 1.858   0.063207 -0.007263 0.2712

Prediction type:  response 
Columns: type, term, estimate, std.error, statistic, p.value, conf.low, conf.high 

> # Deleting variable "term" solves the issue
> mtcars$term <- NULL
> avg_predictions(logit)

 Estimate Std. Error     z   Pr(>|z|)  2.5 % 97.5 %
   0.4062    0.06884 5.902 3.5978e-09 0.2713 0.5412

Prediction type:  response 
Columns: type, estimate, std.error, statistic, p.value, conf.low, conf.high
```
Here's the output of sessionInfo():
```
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=German_Austria.utf8  LC_CTYPE=German_Austria.utf8   
[3] LC_MONETARY=German_Austria.utf8 LC_NUMERIC=C                   
[5] LC_TIME=German_Austria.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] marginaleffects_0.9.0 wooldridge_1.4-2     

loaded via a namespace (and not attached):
[1] compiler_4.2.2    backports_1.4.1   generics_0.1.3   
[4] tools_4.2.2       data.table_1.14.4 checkmate_2.1.0  
[7] insight_0.19.0 
```
Came across this issue by pure chance, maybe a fix will save someone else the time it took me to figure out the problem. Thanks!

**Comment by vincentarelbundock** [comment]
Thanks a lot for this detailed and useful reproducible example. I really appreciate it\! It's kind of a cute bug, isn't it?

The bug should now be fixed in version 0.9.0.9046 on Github. Make sure you restart after installing. I expect this to reach CRAN in 2 or 3 weeks.

``` r
library(marginaleffects)
mtcars$term <- sample(1:5, nrow(mtcars), TRUE)
logit <- glm(am ~ mpg + cyl, 
             data = mtcars, 
             family = binomial(link = "logit"))
avg_predictions(logit)
# 
#  Estimate Pr(>|z|) 2.5 % 97.5 %
#       0.4     0.38  0.21   0.62
# 
# Prediction type:  link 
# Columns: type, estimate, p.value, conf.low, conf.high

**Comment by nowo1978** [comment]
No, thank you for the quick reply and your excellent work! 

Sadly, with the fix there is now a new problem: avg_predictions(model)$estimate does not give the same result as mean(predictions(model)$estimate) or the sample mean, which it should (at least that's the behavior I'd expect after reading the Predictions vignette).

This minimal example highlights the issue:
```
library(marginaleffects)

logit <- glm(am ~ mpg + cyl, 
             data = mtcars, 
             family = binomial(link = "logit"))

mean(mtcars$am)
avg_predictions(logit)
avg_predictions(logit)$estimate
mean(predictions(logit)$estimate)
```
The mean of the individual predictions is equal to the sample mean (0.40625), but the estimate from avg_predictions() is not (0.4004122).

Here's the output of sessionInfo():
```
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=German_Austria.utf8  LC_CTYPE=German_Austria.utf8   
[3] LC_MONETARY=German_Austria.utf8 LC_NUMERIC=C                   
[5] LC_TIME=German_Austria.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] marginaleffects_0.9.0.9046

loaded via a namespace (and not attached):
[1] compiler_4.2.2    backports_1.4.1   generics_0.1.3   
[4] tools_4.2.2       data.table_1.14.4 insight_0.19.0   
[7] checkmate_2.1.0  
```
Thanks again for your effort!

**Comment by vincentarelbundock** [comment]
For some models like `glm()`, we backtransform the predictions using the inverse link function. This ensures better properties, such as predictions that stay in \[0,1\] for logit models:

``` r
library(marginaleffects)

logit <- glm(
    am ~ mpg + cyl,
    data = mtcars,
    family = binomial(link = "logit"))

avg_predictions(logit)$estimate
# [1] 0.4004122

avg_predictions(logit, type = "link")$estimate |>
    mean() |>
    logit$family$linkinv()
# [1] 0.4004122
```

**Comment by nowo1978** [comment]
Of course, but mathematically, the mean of the inverse logit applied to the predicted values of the link function is in general not equal to the inverse logit applied to the mean of the predicted values of the link function (this is Jensen's inequality if I'm not mistaken). And since it is a mathematical property of the logit model that the mean of the predicted probabilities must be equal to the sample mean of the binary dependent variable (if the model contains a constant), a command that calculates the average prediction should report the former, not the latter.

In principle, this just requires switching:
```
predictions(logit, type = "link")$estimate |>
  mean() |>
  logit$family$linkinv()
# [1] 0.4004122
```
to
```
predictions(logit, type = "link")$estimate |>
  logit$family$linkinv() |>
  mean()
# [1] 0.40625
```
The vignette to "predictions" says that `avg_predictions(mod)` is equivalent to 
```
pred <- predictions(mod)
mean(pred$estimate)
```
With version 0.9.0.9046 this is no longer true, but it should be.
Thank you!

**Comment by vincentarelbundock** [comment]
Yes, I am aware of the inequality.

> since it is a mathematical property of the logit model that the mean of the predicted probabilities must be equal to the sample mean of the binary dependent variable (if the model contains a constant), a command that calculates the average prediction should report the former, not the latter.

I don’t think your conclusion necessarily follows from the mathematical property itself. I agree that it would be *desirable* for the average prediction of a logit model to return the sample mean. But other goals may contradict our first desideratum. For example, that the CI around an average prediction never cross \[0,1\].

Also, note that the `emmeans` and `lsmeans` packages have been doing exactly this for 10+ years, and I’d consider those packages a “reference” software implementation for many key analyses. See their discussion here: <https://cran.r-project.org/web/packages/emmeans/vignettes/transformations.html>

All that being said, I agree with you that many users would expect and want what you want. Therefore, I have clarified the vignette and the documentation. I have also modified the package so that:

1.  If the user does not specify `type` explicitly, the current automatic behavior prevails.
2.  If the user specifies `type="response"` explicitly, we average the predictions on the response scale directly.



``` r
library(marginaleffects)

logit <- glm(am ~ mpg + cyl, 
             data = mtcars, 
             family = binomial(link = "logit"))

# automatic back transform
avg_predictions(logit) |> print(digits = 6)
# 
#  Estimate Pr(>|z|)    2.5 %   97.5 %
#  0.400412 0.383318 0.212245 0.623388
# 
# Prediction type:  link 
# Columns: type, estimate, p.value, conf.low, conf.high

# explicit type name does not back transform
avg_predictions(logit, type = "response") |> print(digits = 6)
# 
#  Estimate Std. Error       z Pr(>|z|)    2.5 %   97.5 %
#   0.40625  0.0688355 5.90175  < 0.001 0.271335 0.541165
# 
# Prediction type:  response 
# Columns: type, estimate, std.error, statistic, p.value, conf.low, conf.high

mean(predictions(logit)$estimate)
# [1] 0.40625
```
