### ISSUE TITLE
Standard errors wrong?

### ISSUE THREAD

**Issue by langbe** [vincentarelbundock/marginaleffects#684]
`marginaleffects` and `margins` differ with respect to standard errors. Consider for example
```
library(marginaleffects)
library(margins)
dat <- read.csv("https://vincentarelbundock.github.io/Rdatasets/csv/palmerpenguins/penguins.csv")
dat$large_penguin <- ifelse(dat$body_mass_g > median(dat$body_mass_g, na.rm = TRUE), 1, 0)
mod <- glm(large_penguin ~ bill_length_mm * flipper_length_mm + species,
           data = dat, family = binomial)
avg_slopes(mod)
#> 
#>               Term           Contrast Estimate Std. Error       z Pr(>|z|)
#>     bill_length_mm              dY/dX  0.02786    0.02062  1.3514 0.176582
#>  flipper_length_mm              dY/dX  0.01049    0.01177  0.8913 0.372777
#>            species Chinstrap - Adelie -0.41279    0.24276 -1.7004 0.089054
#>            species    Gentoo - Adelie  0.06093    0.10770  0.5657 0.571609
#>     2.5 %  97.5 %
#>  -0.01255 0.06827
#>  -0.01258 0.03357
#>  -0.88858 0.06301
#>  -0.15017 0.27202
#> 
#> Prediction type:  response 
#> Columns: type, term, contrast, estimate, std.error, statistic, p.value, conf.low, conf.high
summary(margins(mod))
#>             factor     AME     SE       z      p   lower   upper
#>     bill_length_mm  0.0279 0.0059  4.6844 0.0000  0.0162  0.0395
#>  flipper_length_mm  0.0105 0.0024  4.4255 0.0000  0.0058  0.0151
#>   speciesChinstrap -0.4128 0.0561 -7.3639 0.0000 -0.5227 -0.3029
#>      speciesGentoo  0.0609 0.1073  0.5676 0.5703 -0.1495  0.2713
```
It could well be that `margins` does not calculate SEs correctly, but I guess it is worth checking. Thanks.

**Comment by vincentarelbundock** [comment]
Well, I’ll admit that I was quite stressed when I ran your example. But it turns out that the difference is (almost?) entirely due to the (arbitrary) step size constant that we use for the finite difference derivative. That constant comes into play at two stages:

1.  When differentiating with respect to the variables in the model (for slopes).
      - `margins` uses the `eps` argument, which is `1e-7` by default.
      - `marginaleffects` uses the `eps` argument. By default, this is set “adaptively” based on the range of the variable.
2.  When differentiating with respect to coefficients in the model (for standard errors).
      - `margins` uses the same `eps` argument.
      - `marginaleffects` uses a fixed constant of `1e-4`.

Coefficients often have very different scales than variables, so I’m not sure it makes more sense to use the `margins` approach (which uses the same step size for both). I prefer the adaptive approach of `marginaleffects` for slopes, but perhaps I should review that code and think of something clever for standard errors too.

In short, I don’t think there’s a particularly good reason to prefer one or the other. This is driven primarily by numerical issues, which are made worse by the non-linear link function and the interaction.

Notice that when I set the `eps` argument in `margins` I get a much closer match:

``` r
options(width = 1000)
library(margins)
library(marginaleffects)
dat <- read.csv("https://vincentarelbundock.github.io/Rdatasets/csv/palmerpenguins/penguins.csv")
dat$large_penguin <- ifelse(dat$body_mass_g > median(dat$body_mass_g, na.rm = TRUE), 1, 0)
mod <- glm(large_penguin ~ bill_length_mm * flipper_length_mm + species, data = dat, family = binomial)

avg_slopes(mod, eps = 1e-4) |> print(digits = 7)
# 
#               Term           Contrast    Estimate Std. Error          z   Pr(>|z|)       2.5 %     97.5 %
#  bill_length_mm    dY/dX               0.02785900 0.02057564  1.3539799 0.17574280 -0.01246851 0.06818650
#  flipper_length_mm dY/dX               0.01049274 0.01176030  0.8922169 0.37227670 -0.01255703 0.03354251
#  species           Chinstrap - Adelie -0.41278521 0.24275620 -1.7004106 0.08905373 -0.88857863 0.06300820
#  species           Gentoo - Adelie     0.06092648 0.10770429  0.5656830 0.57160932 -0.15017005 0.27202301
# 
# Prediction type:  response 
# Columns: type, term, contrast, estimate, std.error, statistic, p.value, conf.low, conf.high

margins(mod, eps = 1e-4) |> summary() |> data.frame()
#              factor         AME         SE          z          p       lower      upper
# 1    bill_length_mm  0.02785881 0.02080964  1.3387455 0.18065355 -0.01292733 0.06864495
# 2 flipper_length_mm  0.01049183 0.01190297  0.8814465 0.37807619 -0.01283756 0.03382122
# 3  speciesChinstrap -0.41278521 0.24275620 -1.7004106 0.08905373 -0.88857863 0.06300820
# 4     speciesGentoo  0.06092648 0.10770429  0.5656830 0.57160932 -0.15017005 0.27202301
```

**Comment by vincentarelbundock** [comment]
I dove a bit deeper into this, cleaned up some code, and made `marginaleffects` more flexible. We can now specify the two step sizes independently, and also use the `numDeriv` package for delta method standard errors (allows derivatives with Richardson's method, which is supposed to be more accurate).

I also wrote a pretty detailed vignette on exactly what computations `marginaleffects` is doing, with manual / from scratch computations of standard errors.

The new version on Github now generates standard errors which are closer to `margins`, though they are still not identical. Frankly, I can't figure out exactly what `margins` is doing, but at least we now have a lot of transparency about what `marginaleffects` is doing (plus lots of tests against Stata and such).

At the bottom of the relevant section of the vignette, you'll note that I include several calls to `margins()` to show that that function is also extremely sensitive to the step size in this particular model:

https://vincentarelbundock.github.io/marginaleffects/dev/articles/uncertainty.html#numerical-derivatives-sensitivity-to-step-size

Let me know if you think any of this is unclear.

**Comment by langbe** [comment]
Wow, thank you so much for taking this up so quickly. I hope it did not stres you out too much. Reading your initial response and the vignette helped a lot, although I feel I am still not into all the technicals. Nevertheless, all what you wrote appears reasonable. Just to get this right: The changed code results in 0.0059 as SE for `bill_length_mm` in the example above, but this change does not come from using `numDeriv` (Richardson), right? Why not always use `numDeriv`? I guess run-time could be an issue (as noted in the `numDeriv` package).

Another check could be running the example against Stata, but I do not have access to it. It seems you have access to Stata?

**Comment by vincentarelbundock** [comment]
Correct. The main difference is that I changed how `marginaleffects` sets the step size for delta method computation. It used to be completely fixed at `eps=1e-4`, and now we choose it based on the size of the smallest coefficient in the model.

I'm not exactly sure what `margins` does, but this is the kind of thing where no single default will work everywhere. So I'd encourage you to try different values when the estimates are mission critical.

Unfortunately, I don't have access to Stata right now. 

@nadjim10, could you please run this in Stata?  We just need a printout of the table generated by the equivalent of:

```{r}
library(marginaleffects)
dat <- read.csv("https://vincentarelbundock.github.io/Rdatasets/csv/palmerpenguins/penguins.csv")
dat$large_penguin <- ifelse(dat$body_mass_g > median(dat$body_mass_g, na.rm = TRUE), 1, 0)
mod <- glm(large_penguin ~ bill_length_mm * flipper_length_mm + species,
           data = dat, family = binomial)
avg_slopes(mod)
```

Saving the data in `Stata` format will make your life easier:

```{r}
library(haven)
write_dta(dat, "penguins.dta")
```

And the Stata code will probably look a bit like this:

```stata
encode species, gen(speciesid)
logit large_penguin c.bill_length_mm##c.flipper_length_mm i.speciesid
margins, dydx
```

**Comment by Nadjim10** [comment]
@vincentarelbundock I don't have access to Stata as well!

**Comment by vincentarelbundock** [comment]
@Nadjim10 

on campus we can use one of the virtual machines. It just opens a window with a different computer which you control remotely, can download from
the web and open Stata. It's super easy to use.

https://bib.umontreal.ca/travailler/logiciels/connexion-distance-logiciels/

I would do it on my own, but my VPN is broken and am working off campus.

**Comment by grantmcdermott** [comment]
If it helps, I just ran this quickly on the Stata version that I have through work (Stata 17 MP 16).

```sh
. encode species, gen(speciesid)
. qui logit large_penguin c.bill_length_mm##c.flipper_length_mm i.speciesid
. margins, dydx(*)

Average marginal effects                                   Number of obs = 342
Model VCE: OIM

Expression: Pr(large_penguin), predict()
dy/dx wrt:  bill_length_mm flipper_length_mm 2.speciesid 3.speciesid

-----------------------------------------------------------------------------------
                  |            Delta-method
                  |      dy/dx   std. err.      z    P>|z|     [95% conf. interval]
------------------+----------------------------------------------------------------
   bill_length_mm |   .0278588   .0059463     4.69   0.000     .0162043    .0395134
flipper_length_mm |   .0104927   .0023708     4.43   0.000      .005846    .0151394
                  |
        speciesid |
       Chinstrap  |  -.4127852   .0560029    -7.37   0.000    -.5225488   -.3030216
          Gentoo  |   .0609265   .1073649     0.57   0.570    -.1495048    .2713578
-----------------------------------------------------------------------------------
Note: dy/dx for factor levels is the discrete change from the base level.
```

**Comment by vincentarelbundock** [comment]
Thanks a ton @grantmcdermott , I really appreciate this.

Looks like we're now super close to Stata:

```r
              Term           Contrast   Estimate Std. Error         z Pr(>|z|)       2.5 %     97.5 %
 bill_length_mm    dY/dX               0.0278630 0.00594832  4.684169  < 0.001  0.01620445  0.0395215
 flipper_length_mm dY/dX               0.0104940 0.00237149  4.425068  < 0.001  0.00584597  0.0151420
 species           Chinstrap - Adelie -0.4127852 0.05607356 -7.361494  < 0.001 -0.52268738 -0.3028831
 species           Gentoo - Adelie     0.0609265 0.10733847  0.567611 0.570299 -0.14945306  0.2713060
```

The settings I had in place for the delta method were clearly suboptimal for that kind of model, so I'm very grateful that you raised this issue @langbe. This feels like a high priority change, so I'll try to push out a new release to CRAN this week.

**Comment by vincentarelbundock** [comment]
@Nadjim10 Just in case you don't follow the thread: no need to look at this anymore. Thanks.
