### ISSUE TITLE
Plotting functions not consistent with their underlying counterparts?

### ISSUE THREAD

**Issue by langbe** [vincentarelbundock/marginaleffects#685]
The description of `plot_slopes()` states "Plot average slopes". This suggests that there is a one-to-one relationship to `slopes()` / `avg_slopes()`. If I understand it correctly, this is however not completely the case because `plot_slopes()` sets unspecified variables to their means or modes, whereas `slopes()` / `avg_slope()` is not doing that. Similarly for `predictions()` and `plot_predictions()`. I'd like to suggest the following. For most of the functions in the package, there is the argument `newdata` (with all the different input possibilities). Why not for the `plot_*()` functions? Introducing this (with the same defaults as for `slopes()` etc.) would solve the inconsistency described above.

**Comment by vincentarelbundock** [comment]
@langbe Thaks for the feedback. I agree, and I just did a major refactor of the plotting functions. There is no `newdata` argument, because the whole point of those plotting functions is that they build the grid automatically (otherwise people should just call the main function and feed it to `ggplot2`), but I think you'll find the documentation and consistency has improved. See the dev version of the website, in particular:

https://vincentarelbundock.github.io/marginaleffects/dev/articles/plot.html
https://vincentarelbundock.github.io/marginaleffects/dev/reference/plot_predictions.html

**Comment by langbe** [comment]
Fair enough. It’s just that if an automated plot is available, to me it would be more natural to have the counterpart to average marginal effects, i.e. predictive margins (instead of the fixed rule with mean or mode for unspecified variables).

Needless to say, I do like you your package very much and the way it has evolved over time is great! Also, the new documentation reads well.
(PS: in the slopes article, for the quadratic example at the bottom the conclusion should be the other way around. That is, if the derivative is 1+4x, then for negative x (actually x < 1/4) an increase in x is associated with a decrease in y and for x>1/4 it results in an increase in y)

**Comment by vincentarelbundock** [comment]
Good catch on that typo. Will fix.

Right. The goal of the re-write was to allow parallel “margins” calls like these, where the plot represents the same quantities that were printed just above:

``` r
library(marginaleffects)
mod <- lm(mpg ~ hp * factor(cyl), mtcars)

predictions(mod, by = "cyl")
# 
#  cyl Estimate Std. Error  z Pr(>|z|) 2.5 % 97.5 %
#    4       27       0.91 29   <0.001    25     28
#    6       20       1.14 17   <0.001    17     22
#    8       15       0.81 19   <0.001    14     17
# 
# Prediction type:  response 
# Columns: type, cyl, estimate, std.error, statistic, p.value, conf.low, conf.high

plot_predictions(mod, by = "cyl")
```

![](https://i.imgur.com/cKU0SOb.png)
