### ISSUE TITLE
`datagrid()` `by` argument for group-wise summaries

### ISSUE THREAD

**Issue by langbe** [vincentarelbundock/marginaleffects#688]
When calculating and plotting predictions, the default is to set unspecified variables to their mean/mode. By doing so, the mean is calculated across all rows (per variable), in particular across variables that we will be `condition`ing on. It may however be that the mean values calculated for each of the levels of a condition-variable are very different from each other. Therefore, the overall mean is not representative at all for any kind of level of the `condition` variable. Wouldn't it make more sense to use the mean per level of the condition variable instead? Do you see value of adding this as a feature to `plot_prediction`?

**Comment by vincentarelbundock** [comment]
Oh that's a cool idea. As a first step, it might be nice to implement a `by` argument in `datagrid()`. Then, we could have a `newdata="meanby"` shortcut similar to the current `newdata="mean"`. Finally, we could explore possibilities for `plot_predictions()`. For that last step, I worry a bit about there being too much "magic" and about the result being surprising, but this is something that could be looked at later, and if steps 1 and 2 are implemented, it is trivial to feed the object in `ggplot2` anyway.

**Comment by langbe** [comment]
Thanks. I had similar thoughts, just wasn't sure if that's too much. About the surprising results: It might be problematic for small sample sizes; nevertheless, I recently had 2 examples where this was the case and for the first time it took me quite a while to realize that the problem was the overall mean that was plugged in. So for me this is definitely a nice feature.
