### ISSUE TITLE
Question about default values for continuous condition variable

### ISSUE THREAD

**Issue by langbe** [vincentarelbundock/marginaleffects#689]
Consider the example from the man page of `plot_predictions`:
```
mod <- lm(mpg ~ hp * wt * am, data = mtcars)
plot_predictions(mod, condition = c("hp", "wt"))
```
The output provides 5 prediction-curves, one for each value of `wt`. The 5 values that have been chosen for `wt` are the default ones and it is not stated what kind of values those are. The values shown are 1.513, 2.5425, 3.325, 3.65, 5.424. The first, the third and the last are min, median and maximum. For the others I would have guessed it's the 0.25 and 0.75 quantile, but those are
``` r
quantile(mtcars$wt, probs = c(0.25, 0.75))
#>     25%     75% 
#> 2.58125 3.61000
```

<sup>Created on 2023-02-19 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
Could you please clarify.

**Comment by vincentarelbundock** [comment]
Tukey's 5 numbers: `?stats::fivenum`

I added a note to the docs.
