### ISSUE TITLE
Potential improvement for Bayesian models

### ISSUE THREAD

**Issue by etiennebacher** [vincentarelbundock/marginaleffects#694]
I noticed this line that should be quite easy to optimize:

https://github.com/vincentarelbundock/marginaleffects/blob/cc97c7feda6c5723d176e7114ba2769a761732fa/R/get_contrasts.R#L321

I never do Bayesian things (and `brms` just takes so much time to run) so I don't have an example to test it myself. I'm just putting the potential replacement here if you want to test:
``` r
set.seed(123)
# 500,000 rows
test <- data.frame(
  x = sample(letters, 5*1e5, TRUE),
  y = sample(letters, 5*1e5, TRUE)
)

bench::mark(
  apply = apply(test, 1, paste, collapse = "|"),
  do.call = do.call(paste, c(test, sep = "|")),
  iterations = 10
)
#> Warning: Some expressions had a GC in every iteration; so filtering is
#> disabled.
#> # A tibble: 2 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 apply         2.15s    2.36s     0.418   26.77MB     8.39
#> 2 do.call     86.39ms  96.01ms     9.58     3.81MB     0
```

<sup>Created on 2023-02-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by vincentarelbundock** [comment]
good catch, thanks!
