### ISSUE TITLE
Interpreting p-values and 95% CI in avg_comparisons with "ratio" transform_pre

### ISSUE THREAD

**Issue by alicehyunmin** [vincentarelbundock/marginaleffects#699]
Hi Vincent,
I'm just starting out looking at marginaleffects package and been exploring computing adjusted risk ratio.
After using "transform_pre = "ratio"" on a logistic model (example below using mtcars dataset), I get p-value of 0.0114 and 95% CI of (0.33, 2.59) on an adjusted predicted risk ratio estimate of 1.46.
So the p-value seems to test whether the risk ratio is 0 or not (z = 2.53) although we would usually test whether the ratio was 1 or not.
If we were to report an estimate of OR from a binomial model, we would report exp(0.693) = 2 with CI of (0.48, 8.76) and p-value 0.344.
Example using mtcars:
mod <- glm(vs ~ am, data = mtcars, family = binomial)

> avg_comparisons(mod, transform_pre = "ratio")

 Term Contrast Estimate Std. Error    z Pr(>|z|) 2.5 % 97.5 %
   am    1 / 0     1.46      0.578 2.53   0.0114  0.33   2.59

Prediction type:  response 
Columns: type, term, contrast, estimate, std.error, statistic, p.value, conf.low, conf.high 

> avg_comparisons(mod, transform_pre = function(hi, lo) log(hi / lo), transform_post = exp)

 Term Contrast Estimate Pr(>|z|) 2.5 % 97.5 %
   am   custom     1.46    0.337 0.674   3.17

Prediction type:  response 
Columns: type, term, contrast, estimate, p.value, conf.low, conf.high 

For my own dataset (which I can't share for ethical reasons), the p-value is <0.001 and the 95% CI shows (0.82, 1.04). So seems quite incompatible. 

> meffects = avg_comparisons(cfit, variables = "rf_suto",  transform_pre = "ratio", vcov = ~ anzicsid)
> meffects

    Term Contrast Estimate Std. Error    z Pr(>|z|) 2.5 % 97.5 %
 rf_suto    1 / 0    0.931     0.0552 16.9   <0.001 0.823   1.04

#####################################################################
# model output
> mod <- glm(vs ~ am, data = mtcars, family = binomial)
> summary(mod)

Call:
glm(formula = vs ~ am, family = binomial, data = mtcars)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-1.2435  -0.9587  -0.9587   1.1127   1.4132  

Coefficients:
            Estimate Std. Error z value Pr(>|z|)
(Intercept)  -0.5390     0.4756  -1.133    0.257
am            0.6931     0.7319   0.947    0.344

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 43.860  on 31  degrees of freedom
Residual deviance: 42.953  on 30  degrees of freedom
AIC: 46.953

Number of Fisher Scoring iterations: 4

> exp(coef(mod))
(Intercept)          am 
  0.5833333   2.0000000

**Comment by vincentarelbundock** [comment]
Hi,

You can set the null using the `hypothesis=1` argument. The default is 0. See documentation.

**Comment by alicehyunmin** [comment]
Wonderful! Thank you for your prompt response.

**Comment by vincentarelbundock** [comment]
Cool. BTW, a lot of people seem to like computing the log ratio, and then backtransforming by exponentiation. See the bottom of this section for examples:

https://vincentarelbundock.github.io/marginaleffects/articles/comparisons.html#ratios

**Comment by vincentarelbundock** [comment]
But in that case, the `hypothesis` argument doesn't need to be specified, because it refers to the hypothesis *before* applying the `transform_post` function.

**Comment by alicehyunmin** [comment]
Hi Vincent, thanks for the additional information and documentation on the package. The functions in the package are really comprehensive and the vignettes are well detailed and have good examples. I look forward to using this package more often.
