### ISSUE TITLE
Sequential contrasts for a numerical predictor

### ISSUE THREAD

**Issue by arthur-albuquerque** [vincentarelbundock/marginaleffects#710]
Hi Vincent,

I am trying to generate some estimands with marginaleffects but can't figure out how.

I have a logistic regression with an interaction between numerical ("Age") and categorical ("PClass") predictors. For each PClass (there are three options), I want to calculate risk ratios (RR) between a range of "Age" values using Age=28 as the reference. 

Here is an ~ugly~ drawing of a figure I plan to present. X-axis is Age, Y-axis is Risk Ratio. Red line represents the mean RR whereas green lines represent the 95% CI. Imagine this is the panel for PClass = "1st".

<img width="415" alt="image" src="https://user-images.githubusercontent.com/77208087/223293168-55aa78fb-9b96-4fca-b5a3-7f70e09eb90c.png">

I understand that to generate Risk Ratios from a logistic regression I must use 

`comparisons(...,
                         transform_pre = "lnratioavg",
                         transform_post = exp)
  `

However, I can't find a way to set Age=28 as the reference (ie, RR = 1). I also can't figure out how to generate multiple contrasts vs. 28, eg 10 vs. 28; 12 vs. 28; 30 vs. 28, etc...

I know this a little bit confusing. Let me know if you need further details. Here is the toy dataset/model I used:

```
library(marginaleffects)

dat <- "https://vincentarelbundock.github.io/Rdatasets/csv/Stat2Data/Titanic.csv"
dat <- read.csv(dat)
dat$PClass[dat$PClass == "*"] <- NA

mod <- glm(Survived ~ PClass * Age, data = dat, family = binomial)
```

P.S: I know how to generate all of these estimands if "Age" was a categorical predictor. However, I'd like to maintain it as a numerical one.

**Comment by vincentarelbundock** [comment]
You can feed a numeric vector of length 2 to the `variables` argument, but you'll need to use a loop and call `comparisons` many times to get all the comparisons you need:

```r
avg_comparisons(mod, variables = list(Age = c(28, 32), transform_pre = "ratio")
```
