### ISSUE TITLE
Incomplete get_predict.clm() method

### ISSUE THREAD

**Issue by MrJerryTAO** [vincentarelbundock/marginaleffects#717]
Hi @vincentarelbundock, glad to see so much expansion of the package since half a year ago. I tried the package with ordinal::clm() models and found that certain prediction arguments in marginaleffects:::get_predict.clm() do not work correctly. I implemented a simple fixed and now it worked well for me. You may refer to the following script when making the next update. 

I noticed that ordinal:::prob.predict.clm() that generate predicted probability masses may have incorrect components, as its confidence interval is built from only a logistic distribution around a linear predictor while clm() allows a few other distributions. But if {marginaleffects} does not use the interval estimates, then results of marginaleffects routines should be okay. 

```
get_predict.clm_Tao <- function (
    model, newdata = insight::get_data(model), type = "response", ...) 
{

1.   if (type == "response") {
2.     type <- "prob"
3.   }
4.   if (type == "linear_predictor") { # changed, type = "response", "prob",
5.     type <- "linear.predictor"      # "com.prob", "linear_predictor" allowed
6.   } # c("prob", "class", "cum.prob", "linear.predictor") in predict.clm
7.   resp <- insight::find_response(model)
8.   data.table::setDF(newdata)
9.   newdata <- newdata[, setdiff(colnames(newdata), resp), drop = FALSE]
10.   # pred <- stat::predict(model, newdata = newdata, type = type)$fit changed
11.   pred <- if(as.character(model$call[[1]]) == "clm_Tao") {
12.     predict.clm_Tao(model, newdata = newdata, type = type)[[1]]
13.   } else stats::predict(model, newdata = newdata, type = type)[[1]]
14.   # [[1]] extracts $fit if type = "prob" for Pr{y == k};
15.   # $cprob1 if type = "cum.prob" for Pr{y <= k};
16.   # $eta1 if type = "linear.predictor" for qlogis(Pr{y <= k}).
17.   # Otherwise $cprob2 gets Pr{y <= k - 1} and $eta2 qlogis(Pr{y <= k - 1})
18.   out <- data.frame(
19.     group = rep(colnames(pred), each = nrow(pred)), estimate = c(pred))
20.   if ("rowid" %in% colnames(newdata)) {
21.     out$rowid <- rep(newdata$rowid, times = ncol(pred))
22.   }
23.   else {
24.     out$rowid <- rep(1:nrow(pred), times = ncol(pred))
25.   }
26.   return(out)
27. }
28. environment(get_predict.clm_Tao) <- asNamespace("marginaleffects")
29. assignInNamespace( # replace original function
30.   "get_predict.clm", get_predict.clm_Tao, ns = "marginaleffects")

```

**Comment by vincentarelbundock** [comment]
Thanks, but I don't quite understand. Can you tell me exactly which argument values lead to incorrect results and specifically what is incorrect about the results?

Also, could you supply an ultra minimalist replicable example using a public dataset like `mtcars`? I would need to see the incorrect results using the current version of `marginaleffects` (not your modified version).

**Comment by vincentarelbundock** [comment]
Also, is it "incomplete" or "incorrect"? There's obviously a big difference...

**Comment by MrJerryTAO** [comment]
It is incomplete, as predictions() will only give results if type = "response" or type = "prob."
However, two other estimands are important: cumulative probabilities and linear predictor for the cumulative probabilities. 
Currently, type = "cum.prob", type = "linear.predictor", type = "linear_predictor" will all lead to errors. 

So, the problem-causing argument is type = ..., and the extracting index in "pred <- stat::predict(model, newdata = newdata, type = type)$fit" needs a repair.

**Comment by vincentarelbundock** [comment]
Thanks a lot for the explanation. I think I understand now. This should be fixed in the development version of `marginaleffects`. Can you install from Github, restart your `R` session, and try again?

If it works on your machine, we can close this issue.

**Comment by MrJerryTAO** [comment]
> Thanks a lot for the explanation. I think I understand now. This should be fixed in the development version of `marginaleffects`. Can you install from Github, restart your `R` session, and try again?
> 
> If it works on your machine, we can close this issue.

Hi @vincentarelbundock, I installed the development version, but the new package did not work better. I believe that you only need to change two spots: Line 4 & 5 (to fix the type argument), and Line 13 (to extract the correct component across multiple possible type arguments) in my pasted script above.

**Comment by MrJerryTAO** [comment]
It turned out that my package update was not successful. Now with the new version, I can confirm that it works. However, I am curious how eta1/eta2 (also cprob1/cprob2) list data frames were used. Your new script implies that both eta1 and eta2 data frames are extracted, but the returned predictions() data frame only includes results associated with eta1 (also cprob1).

**Comment by vincentarelbundock** [comment]
Cool.

`mariginaleffects` checks each of these in turn and returns the first one it finds: `c("fit", "eta1", "eta2", "cprob1", "cprob2")`

In basically all cases, we get `eta1` or `cprob1`. Are there situations where we absolutely need `eta2` or `cprob2`?

**Comment by MrJerryTAO** [comment]
No, I don’t. List items 1/2 contain equivalent information in both cumulative probability and linear predictor for it. The distinction was not straightforward in the ordinal package documentation, and I had to use an example to understand the difference. It would be nice if your package prints a message about which of these two versions were used and what it means, as there might be ambiguity.

**Comment by vincentarelbundock** [comment]
Thanks for the clarification and for opening this issue.

I think we can close this now.

**Comment by MrJerryTAO** [comment]
> `mariginaleffects` checks each of these in turn and returns the first one it finds: `c("fit", "eta1", "eta2", "cprob1", "cprob2")`

I see. Then using c("fit", "eta1", "cprob1") in the for loop should be sufficient. I hope the list names remain unchanged in future {ordinal} release, otherwise I would use [[1]] to extract the first list component from predict(). It is amazing to see that your packages estimate the approximate SEs without using $se.fit from predict() results.

**Comment by vincentarelbundock** [comment]
Yes, we never extract standard errors and always compute our own. Always using the same delta method infrastructure.
