### ISSUE TITLE
Documentation: what does p.values represent in the results returned by `predictions()`

### ISSUE THREAD

**Issue by larmarange** [vincentarelbundock/marginaleffects#722]
`predictions()` returns a p.value column. This p.value column is not listed in the **Value** subsection of `predictions()` help page. 

It would be relevant to add to the documentation the meaning of this p.value. What is tested?

Best regards

**Comment by vincentarelbundock** [comment]
Thnanks for the suggestion. I clarified the docs here: 

https://github.com/vincentarelbundock/marginaleffects/commit/79b6bfeeca50bc9104eda13a34c755843596052b

The development website should be updated in the next hour:

https://vincentarelbundock.github.io/marginaleffects/dev/reference/predictions.html

**Comment by larmarange** [comment]
Thanks
