### ISSUE TITLE
marginaleffects::slopes() does not work with lme() model?

### ISSUE THREAD

**Issue by tongsuo-um** [vincentarelbundock/marginaleffects#726]
Hi, just ran into this error:
![marginaleffects_error](https://user-images.githubusercontent.com/70928006/225996131-4f4d3d9a-c4c5-46b9-bbf7-4a15b1db6be2.png)

Any chance can incorporate lme model into the function as well? Thanks so much!

**Comment by vincentarelbundock** [comment]
Could you try to install from Github, restart R completely, and try again?

**Comment by tongsuo-um** [comment]
Yep! Once I directly downloaded it from Github adn restarted R. It works without problems.
Thanks so much!
