### ISSUE TITLE
Predictions yielding unexpected CIs with `type = "link", transform_post = "exp"`

### ISSUE THREAD

**Issue by ngreifer** [vincentarelbundock/marginaleffects#727]
Hi Vincent.

I have been trying to reconcile some results between `ggeffects` and `marginaleffects` for a client. I noticed the confidence intervals differ between the two. I am able to replicate the `ggeffects` confidence intervals, which are the same as the ones I compute manually, by setting `type = "link", transform_post = "exp"`, but the vignette on uncertainty seems to suggest this is what `predictions()` is doing internally anyway, so I'm not sure why there is a discrepancy. In the example below, the discrepancy is minor, but in my application, it is a bit large.

``` r
library(marginaleffects)
data("lalonde", package = "cobalt")
fit <- MASS::glm.nb(age ~ educ, data = lalonde)

p <- predict(fit, newdata = data.frame(educ = 12), se.fit = TRUE)
exp(p$fit + p$se.fit * qnorm(c(.025, .975)))
#> [1] 25.76559 27.49520

predictions(fit, newdata = data.frame(educ = 12)) |>
  subset(select = c(estimate, conf.low, conf.high)) |>
  print(digits = 5)
#> 
#>  Estimate CI low CI high
#>    26.616 25.752  27.481
#> 
#> Prediction type:  
#> Columns: estimate, conf.low, conf.high

predictions(fit, newdata = data.frame(educ = 12),
            type = "link", transform_post = "exp") |>
  subset(select = c(estimate, conf.low, conf.high)) |>
  print(digits = 5)
#> 
#>  Estimate CI low CI high
#>    26.616 25.766  27.495
#> 
#> Prediction type:  
#> Columns: estimate, conf.low, conf.high
```

<sup>Created on 2023-03-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Can you explain what `predictions()` is actually doing? Thanks.

**Comment by vincentarelbundock** [comment]
This kind of backtransformation is only done automatically for models of class `glm` and `Gam`. It would be very easy to add `negbin` to the class of supported models, but for now, we just compute symmetric intervals directly on the response scale:

``` r
library(marginaleffects)
data("lalonde", package = "cobalt")
fit <- MASS::glm.nb(age ~ educ, data = lalonde)

nd <- data.frame(educ = 12)
p1 <- predict(fit, newdata = nd, se.fit = TRUE, type = "response")
p2 <- predictions(fit, newdata = nd)

sprintf("%.3f [%.3f, %.3f]", p1$fit, p1$fit - 1.96 * p1$se.fit, p1$fit + 1.96 * p1$se.fit)
# [1] "26.616 [25.752, 27.481]"
print(p2, digits = 5)
# 
#  Estimate Std. Error      z Pr(>|z|)  2.5 % 97.5 % educ
#    26.616    0.44117 60.332  < 0.001 25.752 27.481   12
# 
# Columns: rowid, estimate, std.error, statistic, p.value, conf.low, conf.high, educ, age
```

**Comment by ngreifer** [comment]
I see. `negbin` objects are `glm` objects which is why I was surprised. This seems like something that should be applied to all models where it is possible, e.g., `feglm` or `logistf` as well. Could be a bit of work but I was definitely thrown off by the inconsistency here.

**Comment by vincentarelbundock** [comment]
I agree. I used to use `insight::get_predicted()` to do this, but decided to drop it and handle all predictions internally because prediction is such a core part of all `marginaleffects` functionality.

Just added `negbin` and `fixest::feglm`. `logistf` is not supported.

Let me know if you find other cases where model objects include a `family$linkinv()` function and where it would make sense to backtransform predictions.

**Comment by grasshoppermouse** [comment]
I think I had this problem with `glmmTMB(family = nbinom2)`, but plotting with `plot_predictions` on the response scale, where the CI dips below 0.
