### ISSUE TITLE
How to create a data grid of set values and automatic values?

### ISSUE THREAD

**Issue by ngreifer** [vincentarelbundock/marginaleffects#728]
Hi Vincent,

Let's say I fit a model like so:
```r
fit <- lm(y ~ x1 + x2 + x3 + x4 + x5, data = df)
```
I want predictions for two hypothetical units (conditional predictions, one with `x1 = 0, x2 = 10` and one with `x1 = 5, x2 = 20`, both with mean values of `x3`, `x4`, and `x5`.

Manually, I would create this data.frame as such:
```r
p <- data.frame(x1 = c(0, 5), x2 = c(10, 20), x3 = mean(df$3), x4 = mean(df$x4), x5 = mean(df$x5)
```

I feel like this is something `datagrid()` could be able to do since it has the nice automatic facility for summarizing unspecified variables (e.g., using `FUN_numeric`), but I can't figure out how to do it.

**Comment by vincentarelbundock** [comment]
`datagrid(x1 = c(0, 5), x2 = c(10, 20))` would give you what you need but generate two extraneous rows. Is that a big problem?
