### ISSUE TITLE
Support: `phylolm`

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/marginaleffects#736]
@MarcRieraDominguez

I think I was able to add support for `phylolm`. Could you install `marginaleffects` from Github, restart `R` completely, and try it?

Thanks!

**Comment by strengejacke** [comment]
FWIW, support for `phylolm` is now also in _insight_, _paramerers_ and _performance_ (the latter two to be submitted soon).

**Comment by vincentarelbundock** [comment]
Nice!

**Comment by MarcRieraDominguez** [comment]
@vincentarelbundock awesome! so far I've been able to run `marginal_means()` and `avg_comparisons()`. Thank you!
A follow-up question: I will run mutliple `phylolm` models and perform model averaging (with `MuMIn::dredge()` + `MuMIn::model.avg()`). It seems that `marginaleffects` does not support objects of class `averaging`. Are there any plans to include them in the near future?

@strengejacke great news! So far I am interested in collinearity, and I see that `performance` calculates variance inflation factors for `phylolm` models, so will start using that immediately :) I wasn't aware of the other two packages, I'll check them out as well, thank you!

**Comment by strengejacke** [comment]
_insight_ is rather a workhorse for the higher-level packages. I guess for daily use outside programming, there's not much benefit in using it beyond _modelsummary_, _marginaleffects_, _parameters_, _performance_ etc.

**Comment by vincentarelbundock** [comment]
>  Are there any plans to include them in the near future?

No plans, sorry.

**Comment by MarcRieraDominguez** [comment]
@vincentarelbundock I see, can I ask, is this due to technical difficulty? Or is it because of some issue against model averaging as such, from a conceptual/methodological standpoint?

@strengejacke thanks!

**Comment by MarcRieraDominguez** [comment]
@vincentarelbundock thank you for your reply! I am not that familiar with `MuMIn::model.avg()` to provide a useful insight. Compatibility between `marginaleffects` and model averaging would be an interesting feature, given the popularity of model averaging and the `MuMIn` package.
Thank you for your work!
