### ISSUE TITLE
Issue with Fixest Weights and Supplying newdata to MICE models

### ISSUE THREAD

**Issue by Tristan-Siegfried** [vincentarelbundock/marginaleffects#739]
## Broad Description
I have multiply imputed data which I am trying to use with marginaleffects. However, I am having an issue with using the `wts` argument with `fixest` models in the `avg_slopes` command. Furthermore, what would normally be the natural fix to this (passing a `newdata` argument which includes the desired weights as a column) appears to not be implemented in such a way as to allow passing multiply imputed datasets even when those datasets were used in the initial model fitting process.

## Details

Here is my desired workflow:
1. Multiply impute a dataset. After some further processing, these different multiple datasets will give different weights to the same observations (e.g. the 1st dataset might give a particular observation weight .1, while the 2nd dataset might give that same observation weight .2)
2. Fit a feglm model to each multiply imputed dataset with the weights specified from the corresponding dataset
3. Find the average slopes of those models in `marginaleffects` with the wts argument using the same weights as were used in the fitting process.

### Things work properly for `glm`

Implementing the above using `glm` (instead of `feglm`) works properly:
```{r}
library(marginaleffects)
library(mice)

dat <- mtcars
# make some missing values, including in weights (gear) so each imputed dataset uses different weights
dat$hp[sample(seq_len(nrow(mtcars)), 10)] <- NA
dat$mpg[sample(seq_len(nrow(mtcars)), 10)] <- NA
dat$gear[sample(seq_len(nrow(mtcars)), 10)] <- NA
# make a multiply imputed list of datasets
dat_mice <- mice(dat, m = 5, method="sample")
dat_completed <- complete(dat_mice, action="all")

mods_glm <- lapply(dat_completed, function(x) glm(am ~ mpg*cyl+hp,
                                                  weight=gear,
                                                  family=binomial,
                                                  data=x))
mods_glm_mira <- as.mira(mods_glm)

# Without weighted avgs works.
avg_slopes(mods_glm_mira)

# With weighted avgs also works and gives appropriately different results
avg_slopes(mods_glm_mira, wts="gear")
```
Here we are directly able to call the `gear` column in the `wts` argument as the data returned from `insights::get_data` from a glm object includes the weighting column, so when `avg_slopes` is run on each of the multiple imputed datasets with its corresponding model it can always find the appropriate column.

### How things break with `feglm`

However, it does not work with `feglm` (using same `dat` as above):
```
library(fixest)

mods_feglm <- lapply(dat_completed, function(x) feglm(am ~ mpg*cyl+hp,
                                                      weight=~gear,
                                                      family=binomial,
                                                      data=x))
mods_feglm_mira <- as.mira(mods_feglm)

# Without weighted avgs still works.
avg_slopes(mods_feglm_mira)

# With weighted avgs if FAILS with "Error in mfx_list[[1]] : subscript out of bounds"
avg_slopes(mods_feglm_mira, wts="gear")
```

Note that this same issue would happen even without the multiple imputation aspect of my workflow (I include the multiple imputation as it stops me from addressing this issue using the `newdata` argument as I will discuss below):
```
# This also fails with "Error: The `wts` argument must be a numeric vector of length 32..."
avg_slopes(feglm(am ~ mpg*cyl+hp,
                 weight=~gear,
                 family=binomial,
                 data=mtcars),
           wts="gear")
```

What I believe is happening is that the data returned from `insights::get_data` for a `fixest` object does not contain the column(s) for the weights, and instead fixest stores the weights as a vector in the `weights` slot in the resulting `fixest` object. This means, though, that `marginaleffects` would have to look in that `weights` slot to find the vector of weights I want to use, which I do not think is implemented.

### `newdata` does not help when doing multiple imputation

A natural way to handle this issue from the user side would be to pass the original dataset (which includes the desired weights column) to the `newdata` argument, as then `avg_slopes` will again see the weighting column and be able to take the weighted average.
This works nicely in the case without multiple imputation, but it fails for multiple imputation:
```
# This works
avg_slopes(feglm(am ~ mpg*cyl+hp,
                 weight=~gear,
                 family=binomial,
                 data=mtcars),
           newdata = mtcars,
           wts="gear")

# This does not work, get "Error in mfx_list[[1]] : subscript out of bounds"
avg_slopes(mods_feglm_mira,
           newdata = dat_completed,
           wts="gear")
```

I believe this fails in the multiple imputation case because `marginaleffects` does not allow a multiply imputed list of datasets to be passed to the `newdata` argument. If I only pass a single dataset to the `newdata` argument, even for models fit after multiple imputation, it computes the average slopes for that dataset, but it appears impossible to pass a list of imputed datasets (even if its the right length as it is in the above example) and have each used to find averages slopes with the corresponding model over which we then aggregate using multiple imputation rules.

## Possible Fixes

1. Allow a way to pass a list of datasets to the `newdata` argument when working with a list of models resulting from multiple imputation. It is natural that when using a multiple imputation workflow you do the analysis for each model on a different dataset, but that appears not yet possible in `marginaleffects`. **This fix seems to me sufficiently important that I am wondering if I am just missing something, but I have tried a few things and looked around a little and can't find anything.**
2. Allow a way for `fixest` objects to use the weights used during model fitting when using the `wts` argument in `marginaleffects`. This would mean that when this option is selected, then inside `marginaleffects` it sets the `wts` argument to the vector `fixest_object$weights`. I think this is potentially warranted given how common it would be to want to use the same weights during fitting and analysis, though also recognize it might not be worth the added complexity for just a single model type since the newdata argument (if fix 1 is implemented above) should be sufficient to handle such edge cases across all model types
3. (I only include this fix for completeness, though I think it would be unnecessary if fix 1 above is implemented) Allow passing a list of vectors to the `wts` argument when using models fit using multiple imputation, where each vector is used as the weights for the corresponding model.

**Comment by vincentarelbundock** [comment]
I was trying to make the language general, but I agree with your nitpick. I would be happy to merge a PR if you want to add some other language to make the warning more general.

Good catch on the `modelsummary` problem. I just pushed a change to `marginaleffects` to attach the full list of underlying model to the `attr(mfx, "model")` attribute. This means that you can have easy access to the full list of models, and that `modelsummary` will no longer just report goodness-of-fit statistics of the first model instead of the pooled version.

**Comment by vincentarelbundock** [comment]
Moving now so can't check, but there's a good chance it's related to the glance method at the bottom here. Maybe you can try to modify it:

https://github.com/vincentarelbundock/marginaleffects/blob/main/R/imputation.R
