### ISSUE TITLE
Providing dynamic input to datagrid within 

### ISSUE THREAD

**Issue by istallworthy** [vincentarelbundock/marginaleffects#743]
Hello! Thanks so much for this package. I'm wondering if you could help me with the following: 

I would like to make the variables (names and values) provided to datagrid() and 'by' dynamic, pulling new names and values from a dataframe and updating with each iteration of a for loop. Any ideas for how to implement this would be much appreciated!
   
```
 marginaleffects::avg_predictions(mice::as.mira(fits),
                            newdata=datagrid(HOMEETA1_Infancy=c(-0.87125,0.48375),
                                             HOMEETA1_Toddlerhood=c(-0.403875,1.123375),
                                             HOMEETA1_Childhood=c(-0.02475,1.60475)),                                            
                            by=c("HOMEETA1_Infancy","HOMEETA1_Toddlerhood","HOMEETA1_Childhood"))

```

**Comment by vincentarelbundock** [comment]
Sorry, but I don’t understand what you mean. Could you perhaps try to explain differently and give more detail?

**Comment by istallworthy** [comment]
Sorry for the confusion! I'm wondering if you have suggestions for referencing the variable names and values provided to datagrid instead of hard coding them?

**Comment by vincentarelbundock** [comment]
Oh I see. The standard way in R would be to create a list of arguments and use do.call(). Make sure your list includes the model argument too, because it won’t be filled in automatically if you use datagrid() inside do.call() instead of directly.

**Comment by istallworthy** [comment]
thanks so much!
