### ISSUE TITLE
Confusing results with `hypotheses()` after `avg_predictions()` for logistic regression

### ISSUE THREAD

**Issue by ngreifer** [vincentarelbundock/marginaleffects#745]
Hello my friend. I've been working on a guide for estimating effects after prooensity score weighting using `marginaleffects`. I cam across a result I don't understand and I'm hoping you can explain. I have a feeling this has to do with transforming predictions but the results are still opaque to me.

I'm fitting a logistic regression model and getting the expected average potential outcomes using `avg_predictions()`. When I try to compare them using `hypotheses()` (also happens with the `hypothesis` argument) I get output that doens't make sense to me. The contrast is so far from the true value and it is odd that changing the order of the terms makes the value 1 minus the first value.

``` r
data("lalonde", package = "cobalt")
fit <- glm(re78 > 0 ~ treat, data = lalonde,
           family = binomial)

library("marginaleffects")
(p <- avg_predictions(fit, variables = "treat"))
#> 
#>  treat Estimate Pr(>|z|) 2.5 % 97.5 %
#>      0    0.772   <0.001 0.729  0.809
#>      1    0.757   <0.001 0.690  0.813
#> 
#> Columns: treat, estimate, p.value, conf.low, conf.high
hypotheses(p, "b1 - b2 = 0")
#> 
#>     Term Estimate Pr(>|z|) 2.5 % 97.5 %
#>  b1-b2=0    0.521    0.691  0.42  0.619
#> 
#> Columns: term, estimate, p.value, conf.low, conf.high
hypotheses(p, "b2 - b1 = 0")
#> 
#>     Term Estimate Pr(>|z|) 2.5 % 97.5 %
#>  b2-b1=0    0.479    0.691 0.381   0.58
#> 
#> Columns: term, estimate, p.value, conf.low, conf.high
```

<sup>Created on 2023-04-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Note that I get the right answer when I use `avg_comparisons()`, but in my actual case that won't work. Thanks for looking into this when you can.

**Comment by vincentarelbundock** [comment]
What happens if you specify `type="response"` explicitly? That should prevent the automatic backtransform trick.

**Comment by vincentarelbundock** [comment]
I think you’ve hit on an important issue, and I don’t think we use the backtransform trick automatically when the analyst uses the `hypothesis` argument. With version 0.11.0.9006 (now on Github), we get:

``` r
library("marginaleffects")
data("lalonde", package = "cobalt")
fit <- glm(re78 > 0 ~ treat, data = lalonde, family = binomial)

p <- avg_predictions(fit, variables = "treat")
hypotheses(p, "b1 - b2 = 0")
# 
#     Term Estimate Std. Error     z Pr(>|z|)   2.5 % 97.5 %
#  b1-b2=0   0.0148     0.0375 0.395    0.693 -0.0587 0.0883
# 
# Columns: term, estimate, std.error, statistic, p.value, conf.low, conf.high
hypotheses(p, "b2 - b1 = 0")
# 
#     Term Estimate Std. Error      z Pr(>|z|)   2.5 % 97.5 %
#  b2-b1=0  -0.0148     0.0375 -0.395    0.693 -0.0883 0.0587
# 
# Columns: term, estimate, std.error, statistic, p.value, conf.low, conf.high

avg_predictions(fit, variables = "treat", hypothesis = "b1 - b2 = 0")
# 
#     Term Estimate Std. Error     z Pr(>|z|)   2.5 % 97.5 %
#  b1-b2=0   0.0148     0.0375 0.395    0.693 -0.0587 0.0883
# 
# Columns: term, estimate, std.error, statistic, p.value, conf.low, conf.high
avg_predictions(fit, variables = "treat", hypothesis = "b2 - b1 = 0")
# 
#     Term Estimate Std. Error      z Pr(>|z|)   2.5 % 97.5 %
#  b2-b1=0  -0.0148     0.0375 -0.395    0.693 -0.0883 0.0587
# 
# Columns: term, estimate, std.error, statistic, p.value, conf.low, conf.high

avg_comparisons(fit, variables = "treat")
# 
#   Term Contrast Estimate Std. Error      z Pr(>|z|)   2.5 % 97.5 %
#  treat    1 - 0  -0.0148     0.0375 -0.395    0.693 -0.0883 0.0587
# 
# Columns: term, contrast, estimate, std.error, statistic, p.value, conf.low, conf.high
```

**Comment by ngreifer** [comment]
Looks great, thank you! Hope you stayed safe during the storm!

**Comment by vincentarelbundock** [comment]
Oh yeah, storm itself wasn't too bad, but many trees fell and millions of people were out of power. We were able to eat/shower at my sister's place, and now my house just power back. So all good.
