### ISSUE TITLE
Using datagridcf with mira object

### ISSUE THREAD

**Issue by istallworthy** [vincentarelbundock/marginaleffects#746]
Hello! 

I'm wondering if` datagridcf `supports mira objects from mice? I am able to successfully use `datagrid` with a `mira` object but using `datagridcf` produces an empty dataframe. `Datagridcf` seems to work with a single lm model. 

Thanks!

**Comment by istallworthy** [comment]
` ###
 library(mice)
      library(marginaleffects)
      library(MatchThem)
      library(survey)
      library(mitools)
      set.seed(1024)
      dat <- iris
      dat$Sepal.Length[sample(seq_len(nrow(iris)), 40)] <- NA
      dat$Sepal.Width[sample(seq_len(nrow(iris)), 40)] <- NA
      dat$Species[sample(seq_len(nrow(iris)), 40)] <- NA
      dat$weights=seq(0,3, by=3/ 149)
      dat_mice <- mice(dat, m = 2, printFlag = FALSE, .Random.seed = 1024)
      Wd2 <- MatchThem::complete(dat_mice , "all")
      s=svydesign(~1,data=mitools::imputationList(Wd2),weights=~weights)
      mod_mice <- with(s, svyglm(Petal.Width ~ Sepal.Length * Sepal.Width + Species, weights=weights))
      datagrid(model = mice::as.mira(mod_mice), Sepal.Length = c(100, 110))
      datagridcf(model = mice::as.mira(mod_mice), Sepal.Length = c(100, 110))
      mod <- lm(Petal.Width ~ Sepal.Length * Sepal.Width + Species, weights=weights, dat)
      datagrid(model = mod, Sepal.Length = c(100, 110))
      datagridcf(model = mod, Sepal.Length = c(100, 110))
      ####`

**Comment by vincentarelbundock** [comment]
No, sorry, it's not supported. But you can feed any data frame to the `newdata` argument *inside* `datagrid(newdata = df, x = 1:2, y = 1:3)`

**Comment by istallworthy** [comment]
thanks!
