### ISSUE TITLE
Documentation improvement: Logistic regression with interaction

### ISSUE THREAD

**Issue by marcora** [vincentarelbundock/marginaleffects#747]
In a logistic regression model with two interacting categorical predictors, for example:

DISEASE ~ DRUG * SEX

How can I test that the hypothesis that sex does not influence the effect of the drug (expressed as odds-ratio with placebo as reference)?

It would be a great addition to the article re: logistic regression.

**Comment by vincentarelbundock** [comment]
Personally, I would work with probabilities rather than odds ratios. I would define the covariances of interest using datagrid() and then use the hypothesis argument to compare rows of interest.

Pull Requests are most welcomed if you want to improve the documentation.

**Comment by vincentarelbundock** [comment]
Also see related tutorial here: https://vincentarelbundock.github.io/marginaleffects/articles/experiments.html

**Comment by marcora** [comment]
I wish I was proficient enough in `marginaleffects` to contribute to the documentation ;)

Hopefully soon.
