### ISSUE TITLE
Assertion on 'df' failed: Must have length 1

### ISSUE THREAD

**Issue by MrJerryTAO** [vincentarelbundock/marginaleffects#754]
predictions(df = ...) only allows df as one constant across all coefficients. However, gls and mixed effect models often have df corrections resulting in different df across coefficients. 

It gives "Assertion on 'df' failed: Must have length 1." if df is supplied as a vector of more than one element.

**Comment by vincentarelbundock** [comment]
Thanks for the feature request. This should now be possible using version 0.11.1.9009 from Github.
