### ISSUE TITLE
What is the scope of the by argument?

### ISSUE THREAD

**Issue by andymilne** [vincentarelbundock/marginaleffects#755]
This is quite weird.

In the help file for the `by` argument in `comparisons()` is "Character vector of column names in newdata or in the data frame produced by calling the function without the by argument."

I have a data frame with a column called Age (participants' ages in years) and another column called Age_sc, which is the standardized version of these ages. In my brms model, I use only Age_sc.

When using `comparisons()` (without the `newdata` argument), I inadvertently typed into the `by` argument Age instead of Age_sc. The weird thing is that this worked and the output data shows the estimates and CIs by Age (i.e., in the original years) even though that data is not in the model formula! Replacing Age by Age_sc, the estimates and CIs are exactly the same, but now the by values are (correctly) in their standardised form.

I do not understand how `comparisons()` is accessing the data for Age (and calculating the average comparisons correctly) because – to repeat – Age is not in the model formula and running `comparisons()` with no `by` argument shows no column named Age (and I wouldn't expect it too).

The only place I can see in the brms model where the values of Age are available is in the fit>stanmodel>mk_cppmodule>environment field which stores the original data frame specified in the `brm()` `data` argument. Surely the data shouldn't be coming from there though? 

I can share the model and data privately if required.

Some additional info. Outputs from comparisons with Age and with Age_sc from the same model which was not fitted to Age:

```
cmp_mdl_CERAD_age <- 
  comparisons(
    mdl_CERAD,
    variables = list(
      TstTm = c(0, 1)),
    by = c("Cndtn", "Age_sc"),
    cross = TRUE,
    conf_level = 0.95,
    re_formula = ~ (1 | Ptcpnt)
  )
cmp_mdl_CERAD_age

          C: TstTm Cndtn Age_sc Estimate 2.5 % 97.5 %
 mean(1) - mean(0)    PC -0.654     1.06 -2.02   4.09
 mean(1) - mean(0)    QR -0.496     9.01  4.40  14.92
 mean(1) - mean(0)    TK  1.001     9.15  2.77  16.44
 mean(1) - mean(0)    QR  1.395     3.76 -3.05  11.01
 mean(1) - mean(0)    TK  0.134     8.21  4.88  12.51
--- 97 rows omitted. See ?print.marginaleffects --- 
 mean(1) - mean(0)    TK -0.969     2.78 -3.51   9.31
 mean(1) - mean(0)    QR -0.654    15.89  6.69  26.18
 mean(1) - mean(0)    TK -0.102     6.83  2.83  13.04
 mean(1) - mean(0)    TK -0.812     7.49  2.62  14.61
 mean(1) - mean(0)    PC -1.206    -1.55 -6.86   2.36
Columns: term, contrast_TstTm, Cndtn, Age_sc, estimate, conf.low, conf.high, predicted, predicted_hi, predicted_lo, tmp_idx  

cmp_mdl_CERAD_age <- 
  comparisons(
    mdl_CERAD,
    variables = list(
      TstTm = c(0, 1)),
    by = c("Cndtn", "Age"),
    cross = TRUE,
    conf_level = 0.95,
    re_formula = ~ (1 | Ptcpnt)
  )
cmp_mdl_CERAD_age

          C: TstTm Cndtn Age Estimate 2.5 % 97.5 %
 mean(1) - mean(0)    PC  44     1.06 -2.02   4.09
 mean(1) - mean(0)    QR  46     9.01  4.40  14.92
 mean(1) - mean(0)    TK  65     9.15  2.77  16.44
 mean(1) - mean(0)    QR  70     3.76 -3.05  11.01
 mean(1) - mean(0)    TK  54     8.21  4.88  12.51
--- 97 rows omitted. See ?print.marginaleffects --- 
 mean(1) - mean(0)    TK  40     2.78 -3.51   9.31
 mean(1) - mean(0)    QR  44    15.89  6.69  26.18
 mean(1) - mean(0)    TK  51     6.83  2.83  13.04
 mean(1) - mean(0)    TK  42     7.49  2.62  14.61
 mean(1) - mean(0)    PC  37    -1.55 -6.86   2.36
Columns: term, contrast_TstTm, Cndtn, Age, estimate, conf.low, conf.high, predicted, predicted_hi, predicted_lo, tmp_idx 
```

**Comment by vincentarelbundock** [comment]
marginaleffects used the get_data() function from the insight package to retrieve the data used to fit the model. Often, this means looking at the name of the data in the call, and retrieving that from the environment.

When we are luckily, this means that we can use the by arguments with variables that are not in the model. But this doesn't always work, so it is an undocumented "bonus" feature.

**Comment by andymilne** [comment]
It is definitely a feature and not a bug! But only if it is working correctly – my concern is that there are additional data frames stored in fit>stanmodel>mk_cppmodule>environment, some of which also contain an Age variable. Can I be sure that the variable Age is extracted only from a data frame with the same name as that specified in the `data` argument of `brm()`? If so, perhaps it would be worth updating the help file text for `by` to explain that it can access data from the data frame passed to the model but which is not included in the model's formula?

**Comment by vincentarelbundock** [comment]
get_data() works slightly differently for different models, because packages themselves are wildly inconsistent. There is no clean alternative.

You can always look at the open source code to be sure.

The safest approach is to feed your own data (even the original) to the newdata argument. That way, you know exactly what you get.

**Comment by vincentarelbundock** [comment]
I have improved the `newdata` argument to indicate that when `newdata=NULL` the data are extracted using `insight::get_data()`.
