### ISSUE TITLE
Possible? (easier?) to calculate differences-in-differences

### ISSUE THREAD

**Issue by andymilne** [vincentarelbundock/marginaleffects#756]
I have data from a teaching intervention with the following variables: Score, which is the score achieved in a test; TstTm (0, 1) representing whether the test was a pre or post-test; Cndtn (PC, QR, TK, NG, which indicates the control or the type of teaching intervention) and a bunch of participant-level covariates such as Age.

The model has a formula like: `Score ~ 1 + Time + Time:Cndtn * Age + (1 | Ptcpnt)`. (See this page discussing models like this: https://solomonkurz.netlify.app/blog/2022-06-13-just-use-multilevel-models-for-your-pre-post-rct-data/.) I am using brms, so this is Bayesian. 

I want to estimate the causal effect of QR, TK, NG (i.e., relative to the control PC) using the g-estimation counterfactual thing. It is straightforward for me to do the following:

```
> test1 <- 
+     avg_comparisons(
+         newdata = datagridcf(Cndtn = unique),
+         mdl_CERAD,
+         variables = "TstTm",
+         by = "Cndtn",
+         conf_level = 0.95,
+         re_formula = ~ (1 | Ptcpnt)
+     )
> test1

  Term          Contrast Cndtn Estimate  2.5 % 97.5 %
 TstTm mean(1) - mean(0)    PC     1.77 -0.194   3.80
 TstTm mean(1) - mean(0)    QR     6.78  4.261   9.82
 TstTm mean(1) - mean(0)    TK     7.49  5.028  10.50
 TstTm mean(1) - mean(0)    NG     6.80  4.068   9.92
```
This all seems good, but I now want to get comparisons between the teaching conditions. And this is where I am hitting a wall. I thought I could get those with the following but, as you can see, the outputs don't make sense (they are identical for the first item in each contrast of Cndtn):

```
test2 <- 
  avg_comparisons(
    newdata = datagridcf(Cndtn = unique),
    mdl_CERAD,
    variables = list(TstTm = c(0, 1), Cndtn = "pairwise"),
    cross = TRUE,
    conf_level = 0.95,
    re_formula = ~ (1 | Ptcpnt)
  )
test2

 C: TstTm C: Cndtn Estimate 2.5 % 97.5 %
    1 - 0  NG - PC     6.80  4.07   9.92
    1 - 0  NG - QR     6.80  4.07   9.92
    1 - 0  NG - TK     6.80  4.07   9.92
    1 - 0  QR - PC     6.78  4.26   9.82
    1 - 0  TK - PC     7.49  5.03  10.50
    1 - 0  TK - QR     7.49  5.03  10.50
```
I am probably misunderstanding what the syntax in test2 is doing. Is there any straightforward way to get the contrasts (estimates of causal effects) I am seeking? Or is this not currently possible with marginaleffects?

**Comment by vincentarelbundock** [comment]
Don't use cross. Make the exact same call as the first one, and add a hypothesis argument.

**Comment by andymilne** [comment]
Using hypothesis works (I have not previously used that argument – very nice). Thank you! 

May I ask exactly what my second (incorrect) call is actually doing? I would like to know how I am misunderstanding the syntax because it seems to me it should work in the same way as hypothesis.

**Comment by vincentarelbundock** [comment]
cross gives you the effect of a **simultaneous** change in two predictors. See the Comparisons Article for a discussion.

**Comment by andymilne** [comment]
Ah yes, of course. It all makes sense now. Thank you for the explanation and the amazing package!

**Comment by vincentarelbundock** [comment]
Glad you like it!
