### ISSUE TITLE
predictions() is much slower than newdata with brms::posterior_epred

### ISSUE THREAD

**Issue by andymilne** [vincentarelbundock/marginaleffects#760]
The following takes about 90 seconds to complete, which seems extraordinary given it's just one row of data:
```
> options(marginaleffects_posterior_center = mean)
> cmp_cndtn_diff_mdl_CERAD <- 
+   predictions(
+     newdata = datagrid(Cndtn = "QR"),
+     mdl_CERAD,
+     conf_level = 0.95,
+     re_formula = ~ (1 | Ptcpnt)
+   )
> cmp_cndtn_diff_mdl_CERAD
```
Calculating directly with `brms::posterior_epred()` completes in less than 1 second:
```
newdata = datagrid(model = mdl_CERAD, Cndtn = "QR")
posterior_epred(mdl_CERAD, newdata = newdata, re_formula = ~ (1 | Ptcpnt))
```

The posterior mean of the latter is identical to the value reported by the former:
```
mean(posterior_epred(mdl_CERAD, newdata = newdata, re_formula = ~ (1 | Ptcpnt))) - cmp_cndtn_diff_mdl_CERAD[1, 2]
[1] 0
```

**Comment by vincentarelbundock** [comment]
Are you using the development version of marginaleffects from GitHub (make sure you restart R after install)?

Can you share the data and model object? Maybe by email? Just using saveRDS.

**Comment by andymilne** [comment]
I'm using marginaleffects 0.11.1.9009, which is a recent dev version. I have restarted R and no difference to the time taken. I'll try the latest dev version tomorrow and, if I see the same issue, I'll send you stuff by email tomorrow.

**Comment by vincentarelbundock** [comment]
Note to self: The problem is due to a character variable in `datagrid()`. Transforming it to factor before fitting the model fixes the issue.

My guess is that we can do something in `get_modeldata`, but I'm not sure. See example datasets in my personal box under issue 760.

**Comment by vincentarelbundock** [comment]
Version 0.11.1.9015 from Github should now be much faster.

The solution was kind of a hack, but it should work in most cases.

Thanks for the report!
