### ISSUE TITLE
 inferences() fails with large data sets

### ISSUE THREAD

**Issue by amcmahon17** [vincentarelbundock/marginaleffects#761]
Hello,

I haven't gotten inferences() to complete on large datasets (100k or above), even with n=10; sometimes I get the following error: invalid type (closure) for variable '(weights)'.

Here's some example code.

```r
library(marginaleffects)
library(tidyverse)
data(mtcars)
big_mtcars<-mtcars %>% sample_n(100000,replace=TRUE)

#unclear how long this takes

system.time(
  avg_predictions(lm(mpg~.,data=big_mtcars)) %>% inferences(method="rsample")
)


#for comparison, completes in several minutes

boots <- bootstraps(big_mtcars, times = 1000)
            
fit_lm_on_bootstrap <- function(split) {
  lm(mpg ~., data= analysis(split))
}

boot_models <-
boots %>% 
mutate(model = map(splits, fit_lm_on_bootstrap),
         coef_info = map(model, tidy))

int_pctl(boot_models, coef_info)
```

**Comment by vincentarelbundock** [comment]
Thanks a lot for the report and the clear reproducible example. I see the same problem on my computer. I am traveling and overcommitted with "real work", so i can't look into this seriously now, but I'll ping you if/when I find a solution.

**Comment by amcmahon17** [comment]
No problem.

I do want to compliment you on the package. I get quite a bit out of it and
I'm impressed by how easy it is to use.
