### ISSUE TITLE
`wts` argument to `avg_predictions()` is ignored

### ISSUE THREAD

**Issue by EoinTraversUnmind** [vincentarelbundock/marginaleffects#762]
I may be misunderstanding how the `wts` argument to `avg_predictions()` is supposed to work,
but I've found that predictions with and without this argument are unexpectedly (to me at least) the same.

Here's a reprex:

``` r
library(tidyverse)
library(marginaleffects)

set.seed(1)
data = data.frame(
  x1 = c(0, 0, 1, 1),
  x2 = c(0, 1, 0, 1),
  mu = c(.2, .8, .9, .1),
  n = c(600, 400, 20, 80)
) %>%
  uncount(n) %>%
  mutate(
    y = rnorm(n(), mu, .1),
    across(c(x1, x2), factor))

cell_means = data %>%
  group_by(x1, x2) %>%
  summarise(mean = mean(y),
            n = n(), .groups = 'drop') %>%
  mutate(weight = n / sum(n))
cell_means
#> # A tibble: 4 × 5
#>   x1    x2     mean     n weight
#>   <fct> <fct> <dbl> <int>  <dbl>
#> 1 0     0     0.201   600 0.545 
#> 2 0     1     0.795   400 0.364 
#> 3 1     0     0.870    20 0.0182
#> 4 1     1     0.106    80 0.0727
```

```r
model = lm(y ~ x1 * x2, data = data)

means_by_x1 = cell_means %>%
  ungroup() %>%
  group_by(x1) %>%
  summarise(
    unweighted_mean = mean(mean),
    weighted_mean = sum(mean * weight / sum(weight)))
# (weighted_mean) is same as `data %>% group_by(x1) %>% summarise(mean(y))`

# With wts argument
weighted_prediction = avg_predictions(model, cell_means, variables = 'x1', wts = 'weight') %>%
  data.frame() %>% select(x1, weighted_mm = estimate)

# Without
unweighted_prediction = avg_predictions(model, cell_means, variables = 'x1') %>%
  data.frame() %>% select(x1, unweighted_mm = estimate)

unweighted_prediction %>%
  left_join(weighted_prediction, by = 'x1') %>%
  left_join(means_by_x1, by = 'x1') %>%
  mutate_if(is.numeric, round, digits = 3)
#>   x1 unweighted_mm weighted_mm unweighted_mean weighted_mean
#> 1  0         0.498       0.498           0.498         0.439
#> 2  1         0.488       0.488           0.488         0.259
```

I had expected that the estimates in `weighted_prediction` would be the weighted average of the prediction when `x2 == 0` and `x2 == 1`, weighted by the `weights` column. Since this is an OLS model, these would be the same as the `weighted_mean` value from `means_by_x1`. 

For reference, the `wts` section in the docs for `avg_predictions()` say 

> string or numeric: weights to use when computing average contrasts or slopes. These weights only affect the averaging in ⁠avg_*()⁠ or with the by argument, and not the unit-level estimates themselves.
>    - string: column name of the weights variable in newdata. When supplying a column name to wts, it is recommended to supply the original data (including the weights variable) explicitly to newdata.
>    - numeric: vector of length equal to the number of rows in the original data or in newdata (if supplied).
```

**Comment by vincentarelbundock** [comment]
Thanks for trying marginaleffects. I don’t have time to figure out this `tidyverse` code right now, but I can show you a straightforward equivalence with base R. I’ll use the `mtcars` dataset as an example. Hopefully this is transparent enough to help you understand what is happening under the hood.

``` r
library(marginaleffects)

mod = lm(mpg ~ cyl * disp, data = mtcars)

# auto
avg_predictions(mod, by = "cyl", wts = mtcars$qsec)
# 
#  cyl Estimate Std. Error    z Pr(>|z|) 2.5 % 97.5 %
#    4     26.7      0.781 34.2   <0.001  25.2   28.3
#    6     19.2      0.855 22.5   <0.001  17.6   20.9
#    8     15.2      0.699 21.7   <0.001  13.8   16.5
# 
# Columns: cyl, estimate, std.error, statistic, p.value, conf.low, conf.high

# manual
p = predictions(mod, newdata = mtcars, wts = mtcars$qsec)
by(p, mtcars$cyl, \(x) weighted.mean(x$estimate, x$qsec))
# mtcars$cyl: 4
# [1] 26.72566
# ------------------------------------------------------------ 
# mtcars$cyl: 6
# [1] 19.23177
# ------------------------------------------------------------ 
# mtcars$cyl: 8
# [1] 15.17778
```

**Comment by EoinTraversUnmind** [comment]
Ah! My issue was that I was using the `variables` parameter, when I should have been using the `by` parameter. I get the expected results with

```r
weighted_prediction = avg_predictions(model, cell_means, by = 'x1', wts = 'weight') %>%
  data.frame() %>% 
  select(x1, weighted_mm = estimate)
```

Looking back at https://vincentarelbundock.github.io/marginaleffects/articles/predictions.html, I probably should have been able to figure this out, so I don't know whether or not this warrants any change in the docs. Thanks for your help, and for a great package!
