### ISSUE TITLE
Feature request: Support for simultaneous tests

### ISSUE THREAD

**Issue by snhansen** [vincentarelbundock/marginaleffects#763]
I'm often interested in performing a test on multiple parameters, e.g. testing several interactions terms equal to zero simultaneously, so it would be nice to have support for such tests with the `hypotheses` function.

The starting point is thus a hypothesis of the form `Rb = r`, where `R` is a `qxp` matrix, `b` is a `px1` vector of parameters and `r` is a `qx1` vector of hypothesis values. Looking at other packages such as `car::linearHypothesis` and `multcomp::glht` there are two options: A Chi-squared-test and an F-test. The Chi-squared-test is a Wald test, see e.g. this vignette [Simultaneous Inference in General Parametric Models](https://cran.r-project.org/web/packages/multcomp/vignettes/generalsiminf.pdf). To calculate the Wald test you just need a vector of estimates and a covariance matrix. The recipe is also described [here](https://en.wikipedia.org/wiki/Wald_test#Test(s)_on_multiple_parameters).

The Wald test is an asymptotic test. For linear normal models, you can do an F-test instead which is exact. The F-test is also used for GLMs but is asymptotic here. The F-test is obtained by scaling the Chi-squared-test from above by `q` (see the vignette above). It would be nice to add support for this as well.

The function `car::linearHypothesis.default` shows an example for the actual calculation. It seems fairly simple to do the calculations. The hard part, I guess, is to translate the specification of the hypothesis into matrices `R` and `r`.

This is the wanted behavior:

	library(multcomp)
	library(car)

	lmfit <- lm(mpg~as.factor(cyl)*hp, data=mtcars)
	car::linearHypothesis(lmfit, c("as.factor(cyl)6:hp", "as.factor(cyl)8:hp"), test = "F")
	car::linearHypothesis(lmfit, c("as.factor(cyl)6:hp", "as.factor(cyl)8:hp"), test = "Chisq")
	summary(multcomp::glht(lmfit, c("`as.factor(cyl)6:hp` = 0", "`as.factor(cyl)8:hp` = 0")), test = Ftest())
	summary(multcomp::glht(lmfit, c("`as.factor(cyl)6:hp` = 0", "`as.factor(cyl)8:hp` = 0")), test = Chisqtest())

**Comment by vincentarelbundock** [comment]
Just for fun, here is what Chat-GPT came up with:

``` r
library(car)
# Loading required package: carData
library(marginaleffects)

wald_test <- function(theta_hat, V_hat, R, r, n) {
  # theta_hat: P x 1 vector of estimated parameters
  # V_hat: estimated covariance matrix
  # R: Q x P matrix for testing Q hypotheses on P parameters
  # r: Q x 1 vector for null hypothesis
  # n: sample size
  
  # Calculate the difference between R*theta_hat and r
  diff <- R %*% theta_hat - r
  
  # Calculate the inverse of R*(V_hat/n)*R'
  inv <- solve(R %*% V_hat %*% t(R))
  
  # Calculate the Wald test statistic
  wald_statistic <- t(diff) %*% inv %*% diff / dim(R)[1]  # Q is the number of rows in R
  
  # Degrees of freedom
  df1 <- dim(R)[1]  # Q
  df2 <- n - length(theta_hat)  # n - P
  
  # Calculate the p-value
  p_value <- 1 - pf(wald_statistic, df1, df2)
  
  # Return the Wald test statistic and p-value
  return(list(wald_statistic = wald_statistic, p_value = p_value))
}

lmfit <- lm(mpg~as.factor(cyl)*hp, data=mtcars)
n <- nrow(mtcars)
theta_hat <- coef(lmfit)
V_hat <- vcov(lmfit)
P <- length(theta_hat)
r <- matrix(0, nrow = 2, ncol = 1)
R <- matrix(0, nrow = 2, ncol = P)
R[1, which(names(coef(lmfit)) == "as.factor(cyl)6:hp")] <- 1
R[2, which(names(coef(lmfit)) == "as.factor(cyl)8:hp")] <- 1

# Run the Wald test
wald_test(theta_hat, V_hat, R, r, n)
# $wald_statistic
#          [,1]
# [1,] 2.109913
# 
# $p_value
#           [,1]
# [1,] 0.1415331

car::linearHypothesis(lmfit, c("as.factor(cyl)6:hp", "as.factor(cyl)8:hp"), test = "F")
# Linear hypothesis test
# 
# Hypothesis:
# as.factor(cyl)6:hp = 0
# as.factor(cyl)8:hp = 0
# 
# Model 1: restricted model
# Model 2: mpg ~ as.factor(cyl) * hp
# 
#   Res.Df    RSS Df Sum of Sq      F Pr(>F)
# 1     28 277.17                           
# 2     26 238.47  2    38.703 2.1099 0.1415
```
