### ISSUE TITLE
Getting simple average prediction ratios with comparisons()

### ISSUE THREAD

**Issue by joaotedde** [vincentarelbundock/marginaleffects#767]
I am currently running an analysis aiming to investigate if having a 'previous_outcome' affects the effect of a categorical variable 'interval' on a 'current_outcome'. I used Generalized linear model, with some other predictors, as follows:

```
#loading required packages

pacman::p_load(tidyverse,mgcv,marginaleffects,gamRR, sandwich,here)

#generating dataset
N = 50000
dat <- data.frame(mother_id = rep(sample(c(1:500), replace = T, size = N)),
                  
                  interval = sample(factor(c("<6","[6-11[","[11-18[","[18-23[","[23-59[", #"[18-23[" is my reference level
                                             "[59-120[", ">=120"),
                                           levels = c("[18-23[","<6","[6-11[","[11-18[","[23-59[",
                                                      "[59-120[", ">=120"),ordered = T),
                                    replace = T, size = N),
                  
                  previous_outcome = sample(factor(c("3","2","1","0"),
                                                   levels = c("0","1","2","3")),
                                            replace = T, size = N),
                  
                  current_outcome = sample(factor(c("1","0"),
                                                  levels = c("0","1")),
                                           replace = T, size = N),
                  
                  mother_age = sample(factor(c("<18","[18-24]","[25-35]",">=35"),
                                             levels = c("[18-24]","<18","[25-35]",
                                                        ">=35"),ordered = T),
                                      replace = T, size = N),
                  
                  number_antenatal_visits = sample(factor(c("1","2","3","4"),
                                                          levels = c("1","2","3","4")),
                                                   replace = T, size = N),
                  
                  mother_education = sample(factor(c("1","2","3","4","5"),
                                                   levels = c("1","2","3","4","5")),
                                            replace = T, size = N),
                  
                  number_of_children_alive = sample(factor(c("1","2","3","4","5"),
                                                           levels = c("1","2","3","4","5")),
                                                    replace = T, size = N),
                  
                  year_of_birth = sample(factor(c("[2000-2005]","[2006-2010]",
                                                  "[2011-2015]"),
                                                levels = c("[2000-2005]","[2006-2010]",
                                                           "[2011-2015]")),
                                         replace = T, size = N)) 

var <-  vcov(mod)

#Modeling current outcome with GLM

mod <- glm(data = dat, formula = current_outcome ~ interval +
             
             previous_outcome + mother_age + number_antenatal_visits +
             
             mother_education + number_of_children_alive + year_of_birth + interval:previous_outcome,
           family = binomial)

#Extracting original dataset variable names included in the model

names <- c("current_outcome" , "interval" , "previous_outcome" , "mother_age" , "number_antenatal_visits" ,        
"mother_education" , "number_of_children_alive" , "year_of_birth")

#Counting unique combinations of variables in the original dataset

new_dat <- count_(dat, names)  #in this case, the column 'n' is the weight for each unique combination of variable
new_dat <- new_dat[c(1091,1414,3483,4133,5752,5791,25848,26140,10461,10648,12920,12730,32960
                     ,15734),] #selecting only a subset of lines (two for each interval category)
new_dat <- new_dat %>% mutate(n = c(1,440,2,1,4,3,2,1,1,2,3,4,3,5)) #changing weights 

```

Suppose I want simply to get weighted average of predicted absolute risks:

```
 predictions(mod,type = "response",
            by = "interval",
            vcov = var,
            newdata = new_dat,
            wts = "n")

# interval Estimate Std. Error    z Pr(>|z|) 2.5 % 97.5 %
 [18-23[     0.490     0.0099 49.5   <0.001 0.471  0.510
 <6          0.497     0.0102 48.6   <0.001 0.477  0.517
 [6-11[      0.502     0.0140 35.9   <0.001 0.475  0.530
 [11-18[     0.494     0.0109 45.2   <0.001 0.473  0.516
 [23-59[     0.490     0.0136 35.9   <0.001 0.463  0.517
 [59-120[    0.507     0.0134 38.0   <0.001 0.481  0.533
 >=120       0.499     0.0137 36.4   <0.001 0.472  0.526

```
I wonder if there is a way of simply getting ratios of the above predicted risks using comparisons(). I have tried many things in order to get this, without success. To exemplify, supose I waould like to know what is the ratio of average predicted risks for intervals of <6 months compared to those within 18-23 months. I could simply take  0.497/0.490 = 1.014286. Is there a way of doing that inside comparisons() in order to generate confidence intervals, etc... ? All approaches I came accross involved counterfactuals, changing the original value of the predictor,.. whereas I just want the rate of predictions with 95%CI.

Thanks !

**Comment by vincentarelbundock** [comment]
What have you tried, specifically? Have you read
the documentation for the "comparison" and "hypothesis" arguments? Have you read the Comparisons, the Logit , and the Hypothesis vignettes? There are sections about risk ratios there. What was not clear, exactly? How can I clarify the existing documentation to avoid having to tutor users on an individual basis?

**Comment by vincentarelbundock** [comment]
Relevant links:

https://vincentarelbundock.github.io/marginaleffects/reference/comparisons.html#arguments

https://vincentarelbundock.github.io/marginaleffects/articles/comparisons.html

https://vincentarelbundock.github.io/marginaleffects/articles/hypothesis.html

https://vincentarelbundock.github.io/marginaleffects/articles/logit.html

**Comment by joaotedde** [comment]
Yes, I read them all. I need specifically to derive RRs from the average predicted probabilities (i.e., just AR1/AR2). However, comparisons() seems to keep applying counterfactuals on the variable I specify at "variable" argument (i.e., it takes its original value on the newdata and replaces for each possible category for that variable). This obviously leads to different predictions, and to different RRs than would ne expected from simply dividing predicted ARs for the original value (i.e., the value from newdata).

**Comment by vincentarelbundock** [comment]
Sorry if I'm misunderstanding (I'm travelling so can't concentrate very well), but aren't you just looking for an argument like  `hypothesis="b1/b2=0"`

**Comment by joaotedde** [comment]
I will try,but my question is much simpler. I am interested in calculating Risk Ratios of current outcome for each interval length compared to the reference one (18-23 months). 
First, I used predictions(), with arguments exactly as I reported above, to compute predictions for each interval length. I used a newdata composed of unique observations and their weights (their frequencies at the original dataset) to optimize computation time. With this approach, each unique row will produce a prediction (estimate). Then “by= interval” + “wts= ‘n’ ” will take weighted average of predictions for each interval category (output pinted above).
The next step would be to compute RRs using those weighted average estimates. I am
Interested particularly, as I said, in RRs and 95% CI between each interval length (<6,6-11, 11-18, 23-59, 59-120, >=120) and the reference length (18-23 months). That is:
1. RR(<6 vs 18-23): risk for Interval <6 mo divided by risk for Interval 18-23 mo (i.e, 0.497/0.490). 
2. RR (6-11 vs 18-23): Risk for interval 6-11 mo divided by risk for interval 18-23 mo (i.e.,0.502/0.490)
3. …. The same for the remaining interval lengths

How would you do that with comparisons() or predictions() ?

**Comment by joaotedde** [comment]
Nice example! But in this case, as we are talking about risk ratios, it would be more appropriate to set "hypothesis = b1/b2=1" right? For my purposes, maybe I need to compute one comparison at a time, right?

**Comment by vincentarelbundock** [comment]
> Nice example! But in this case, as we are talking about risk ratios, it would be more appropriate to set "hypothesis = b1/b2=1" right? For my purposes, maybe I need to compute one comparison at a time, right?

Yes, if you want want a p value for the null of 1, you need to specify that hypothesis. But note that you'll also get a "centered" estimate then.

> About a possible but difficult new feature: How about truncating in these cases? If I wanted, for example, to compare predictions with a reference category, I could use a "$" symbol for example. "hypothesis = b$/b1(ref)". Maybe setting b$ within the bounds of parameter possible numbers.

That's a very interesting idea. I can't make any promises right now, but I opened a separate issue and will think about it when I find time.

Cheers!
