### ISSUE TITLE
Wildcards: `hypothesis = "b* / b1 = 1"`

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/marginaleffects#768]
+ [ ] Wildcards `hypothesis = "b* / b1 = 1"`
+ [ ] Better label engine for hypotheses with `b1`, etc.

Feature requested by @joaotedde here: https://github.com/vincentarelbundock/marginaleffects/issues/767#issuecomment-1536800794

I think this is an interesting feature, but I'm not sure how much work it would be to implement (or if I will have time in the short run).

**Comment by vincentarelbundock** [comment]
@joaotedde Thanks for the suggestion. This is now possible with version 0.12.0.9021 from Github:

``` r
library(marginaleffects)
mod <- lm(mpg ~ wt * factor(cyl), data = mtcars)
avg_comparisons(mod, variables = "wt", by = "cyl", hypothesis = "b* / b1 = 0")
# 
#     Term Estimate Std. Error     z Pr(>|z|)   S  2.5 % 97.5 %
#  b1/b1=0    1.000         NA    NA       NA  NA     NA     NA
#  b2/b1=0    2.031      2.107 0.964    0.335 1.6 -2.099   6.16
#  b3/b1=0    0.789      0.858 0.919    0.358 1.5 -0.894   2.47
# 
# Columns: term, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high
```

**Comment by joaotedde** [comment]
Nice job! Thanks for this feature
