### ISSUE TITLE
Marginal Means at levels of continuous variable

### ISSUE THREAD

**Issue by pmeiners** [vincentarelbundock/marginaleffects#780]
Thank you for the great package and support.

I was wondering if there is a way to create marginal_means of several factor variables separately for levels of a covariate. 
I've played around with datagrid. However, I only managed to create a grid that crosses all factor variables which is not what I am aiming for.

**Comment by vincentarelbundock** [comment]
I don't understand what you need, exactly. I bet some version of `predictions(model, newdata = datagrid(....), by=...)` will work, but your question is not specific enough for me to answer.

**Comment by vincentarelbundock** [comment]
Hmm, I can't think of a way to do this in one step right now. Sorry.
