### ISSUE TITLE
FR: by-level "sd" calculations

### ISSUE THREAD

**Issue by andymilne** [vincentarelbundock/marginaleffects#784]
Generally, would it be more principled if the `"sd"` and `"2sd"` options for `variables` in `comparisons()`, calculated the SD within each 'by' group individually, rather than across the whole data?

For example, with a model formula like `Y ~ X*Z` where `X` is continuous and `Z` is a factor, in something like:
```
cmp <- 
  comparisons(
    mdl,
    variables = list(X = "sd"),
    by = "Z"
  )
```
`marginaleffects` will add and subtract 0.5 standard deviations for the predictions in the contrast. Those standard deviations are calculated across all of the observations. But it would be good to have an option (arguably, the default option?) for those standard deviations to be calculated separately for each level of `Z`. This is particularly relevant when `X` and `Z` are highly correlated and one is attempting to estimate the additional predictive power `X` provides over `Z`. Of course this can be done by hand, with multiple calls to `comparisons()`, but it gets a bit messy.

**Comment by vincentarelbundock** [comment]
Hmm, interesting. But off the top of my head, I can't really think of a good user interface.

**Comment by andymilne** [comment]
Perhaps something like `variables = list(X = "group sd")` so it's just another option and there's no need to worry about default behaviour?

**Comment by andymilne** [comment]
And the output table could say something like `mean(x + group-SD/2) - mean(x - group-SD/2)`.

**Comment by vincentarelbundock** [comment]
Thanks, that's an interesting idea. I won't have the time to implement this in the near future, but just in case someone is interested in preparing a Pull Request, here is what I think would need to happen:

1. Add a new `group_sd` code block to the `get_contrast_data_numeric()` function. This code would compute the group-wise SD and add/subtract it from `x`: https://github.com/vincentarelbundock/marginaleffects/blob/main/R/get_contrast_data_numeric.R#L89
2. The code block above requires information about groups. So we need to pass the `by` argument to both `get_contrast_data()` and `get_contrast_data_numeric()`.
3. Add `group_sd` to `sanitize_variables()`.
4. Add an extra sanity check to make sure that `group_sd` is only used in conjunction with the `by` argument.
5. Add `group_sd` to the `comparisons()` documentation.
6. Add a test in `inst/tinytest/test-variables.R` which compares the `comparisons()` call to manual computation.

I may be missing something, but this should cover most of it.

**Comment by vincentarelbundock** [comment]
This could eventually be a good/fun project for @Nadjim10.

**Comment by vincentarelbundock** [comment]
Thanks again for the feature request.

In 0.12.0.9017 I have opted to implement a more general interface. It is slightly less convenient than what you recommended, but it will make it much easier for me to maintain, and it is much more powerful and flexible.

The `variables` argument now accepts a numeric vector of “treatment sizes”, so users can construct whatever they want manually and feed it to the `variables` argument. In your initial request, you wanted the treatment effect to be 1 group-wise standard error. This is how you would do that now:

``` r
library(dplyr)
# 
# Attaching package: 'dplyr'
# The following objects are masked from 'package:stats':
# 
#     filter, lag
# The following objects are masked from 'package:base':
# 
#     intersect, setdiff, setequal, union
library(marginaleffects)
mod <- lm(mpg ~ hp + factor(cyl), mtcars)
tmp <- mtcars %>% 
    group_by(cyl) %>%
    mutate(hp_sd = sd(hp))
avg_comparisons(mod, variables = list(hp = tmp$hp_sd), by = "cyl")
# 
#  Term Contrast cyl Estimate Std. Error     z Pr(>|z|)   S 2.5 % 97.5 %
#    hp   custom   6   -0.583      0.374 -1.56    0.119 3.1 -1.32  0.149
#    hp   custom   4   -0.503      0.323 -1.56    0.119 3.1 -1.14  0.129
#    hp   custom   8   -1.225      0.785 -1.56    0.119 3.1 -2.76  0.314
# 
# Columns: term, contrast, cyl, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high
```

**Comment by andymilne** [comment]
Thank you -- this works well and, as you say, is nicely flexible.
