### ISSUE TITLE
Predictions for multinom modified from version 11.0

### ISSUE THREAD

**Issue by celia-bouchet** [vincentarelbundock/marginaleffects#788]
Thanks so much for this great package. Actually I am not 100% sure this is a bug, but I couldn't find any explanation for it in the Changelog. While, until version 10.0, predictions for multinonial logistic regressions (multinom models) obtained with marginaleffects were congruent with whose of the [prediction](https://cran.r-project.org/web/packages/prediction/index.html) package, it is not the case in version 11.0. So I don't know which one to trust?

Example, with version 10.0

> library(nnet)
> library(carData)
> library(prediction)
> library(marginaleffects)

> reg <-multinom(poverty ~ religion + degree + gender,
               family=multinomial(refLevel=1),
               data=WVS)
> pred <- predictions(reg , variables = list(religion=c("no"), gender=c("male")))
> summary(pred)

Group Estimate Std. Error    z Pr(>|z|) 2.5 % 97.5 %
  About Right    0.362     0.0181 20.0   <0.001 0.327  0.398
Too Little     0.480     0.0187 25.7   <0.001 0.444  0.517
Too Much       0.157     0.0137 11.5   <0.001 0.131  0.184
Prediction type:  probs 
Columns: type, group, estimate, std.error, statistic, p.value, conf.low, conf.high 

> pred <- prediction(reg , at = list(religion=c("no"), gender=c("male")))

> mean(pred$`Pr(Too Little)`)

0.4803656

> mean(pred$`Pr(Too Much)`)

0.157453

> mean(pred$`Pr(About Right)`)

0.3621814`

> sessionInfo()

R version 4.2.3 (2023-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so

locale:
  [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C               LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.UTF-8     LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=fr_FR.UTF-8   
[7] LC_PAPER=fr_FR.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
  [1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
  [1] carData_3.0-5          marginaleffects_0.10.0 prediction_0.3.14      nnet_7.3-18           

loaded via a namespace (and not attached):
  [1] httr_1.4.6        compiler_4.2.3    backports_1.4.1   R6_2.5.1          generics_0.1.3    cli_3.6.1         tools_4.2.3       rstudioapi_0.14   data.table_1.14.8
[10] insight_0.19.1    checkmate_2.2.0   texreg_1.38.6     sessioninfo_1.2.2

Now, with version 11.0

> library(nnet)
> library(carData)
> library(prediction)
> library(marginaleffects)

> pred <- predictions(reg , variables = list(religion=c("no"), gender=c("male")))
> summary(pred)
 
Group Estimate Std. Error    z Pr(>|z|) 2.5 % 97.5 %
 About Right    0.376     0.0190 19.8   <0.001 0.338  0.413
 Too Little     0.473     0.0193 24.5   <0.001 0.435  0.511
 Too Much       0.151     0.0138 11.0   <0.001 0.124  0.178
Columns: group, estimate, std.error, statistic, p.value, conf.low, conf.high

> sessioninfo::session_info()

─ Session info ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.2.3 (2023-03-15)
 os       Ubuntu 22.04.2 LTS
 system   x86_64, linux-gnu
 ui       RStudio
 language (EN)
 collate  fr_FR.UTF-8
 ctype    fr_FR.UTF-8
 tz       Europe/Paris
 date     2023-05-23
 rstudio  2023.03.0+386 Cherry Blossom (desktop)
 pandoc   NA

─ Packages ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package         * version date (UTC) lib source
 backports         1.4.1   2021-12-13 [1] CRAN (R 4.2.3)
 carData         * 3.0-5   2022-01-06 [1] CRAN (R 4.2.3)
 checkmate         2.2.0   2023-04-27 [1] CRAN (R 4.2.3)
 cli               3.6.1   2023-03-23 [1] CRAN (R 4.2.3)
 data.table        1.14.8  2023-02-17 [1] CRAN (R 4.2.3)
 generics          0.1.3   2022-07-05 [1] CRAN (R 4.2.3)
 httr              1.4.6   2023-05-08 [1] CRAN (R 4.2.3)
 insight           0.19.1  2023-03-18 [1] CRAN (R 4.2.3)
 marginaleffects * 0.11.0  2023-03-10 [1] CRAN (R 4.2.3)
 nnet            * 7.3-18  2022-09-28 [4] CRAN (R 4.2.1)
 prediction      * 0.3.14  2019-06-17 [1] CRAN (R 4.2.3)
 R6                2.5.1   2021-08-19 [1] CRAN (R 4.2.3)
 Rcpp              1.0.10  2023-01-22 [1] CRAN (R 4.2.3)
 rstudioapi        0.14    2022-08-22 [1] CRAN (R 4.2.3)
 sessioninfo       1.2.2   2021-12-06 [1] CRAN (R 4.2.3)
 texreg            1.38.6  2022-04-06 [1] CRAN (R 4.2.3)

 [1] /home/celia-bouchet/R/x86_64-pc-linux-gnu-library/4.2
 [2] /usr/local/lib/R/site-library
 [3] /usr/lib/R/site-library
 [4] /usr/lib/R/library

(Apologies for any English mistakes and inelegant styling. Neither English nor Markdown is my first language...)

**Comment by vincentarelbundock** [comment]
@celia-bouchet

Can you please install version 0.12.0 from CRAN, restart R, and try again? I cannot replicate your problem with the latest version:

``` r
packageVersion("marginaleffects")
# [1] '0.12.0'


library(nnet)
library(carData)
library(prediction)
library(marginaleffects)

reg <- multinom(poverty ~ religion + degree + gender,
    family = multinomial(refLevel = 1),
    data = WVS, trace = FALSE)
pred <- predictions(reg, variables = list(religion = c("no"), gender = c("male")))
summary(pred) |> print(digits = 7)
# 
#        Group  Estimate Std. Error        z Pr(>|z|)     2.5 %    97.5 %
#  Too Little  0.4803656 0.01866692 25.73353  < 0.001 0.4437791 0.5169521
#  About Right 0.3621814 0.01809300 20.01777  < 0.001 0.3267198 0.3976430
#  Too Much    0.1574530 0.01370697 11.48708  < 0.001 0.1305878 0.1843181
# 
# Columns: group, estimate, std.error, statistic, p.value, conf.low, conf.high

pred <- prediction(reg , at = list(religion=c("no"), gender=c("male")))
colMeans(pred[, grep("^Pr", colnames(pred))])
#  Pr(Too Little) Pr(About Right)    Pr(Too Much) 
#       0.4803656       0.3621814       0.1574530
```

**Comment by celia-bouchet** [comment]
You are totally right - I don't know how exactly but version 12 solves the problem. All my apologies I did not see the release of Version 12 before posting. Thanks for checking !

**Comment by vincentarelbundock** [comment]
Glad it works for you! Don't hesitate to raise other issues if you find a bug or have a feature request.
