### ISSUE TITLE
Average slope conditioned on itself

### ISSUE THREAD

**Issue by andymilne** [vincentarelbundock/marginaleffects#800]
Let's say we have a model formula with a quadratic term: `Y ~ X + I(X^2) + Z`. Is there any way to get the average slopes of X at different values of X; put differently, the average effect of X conditioned by X -- e.g., at 50 values of X over its range? I know this is possible with conditional slopes, but I don't think it is with average slopes (I realise this is a combination of _conditional_ (on X) and _average_ for everything else (e.g., Z)).

This may be relevant to interacting variables too. In `Y ~ X * U + Z`, one might want to condition X on U but average those across Z. 

It's quite possible I am missing an obvious reason why this is not possible or not a good idea, but I prefer average effects to conditional and I am looking for a way to look at the average effects (average slopes) of a quadratic predictor.

**Comment by vincentarelbundock** [comment]
Yes, use the `datagridcf()` function instead of `datagrid()`.

**Comment by andymilne** [comment]
Thanks, I will see if I can work out the `datagridcf() `solution tomorrow.

**Comment by andymilne** [comment]
Confirmed! That works beautifully:
```
avg_slopes(
  model,
  newdata = datagridcf(X = seq(-2, 2, by = 0.1)),
  variables = "X",
  by = "X")
```
