### ISSUE TITLE
a few broken/misdirected links on gh pages

### ISSUE THREAD

**Issue by bbolker** [vincentarelbundock/marginaleffects#805]
From https://vincentarelbundock.github.io/marginaleffects/

- "Some operations" links to https://vincentarelbundock.github.io/marginaleffects/performance.html (404 error)  [should be `.../marginaleffects/articles/performance.html` ?]
- "other packages like modelsummary" links to https://vincentarelbundock.github.io/marginaleffects/ (i.e., back to the same page) [should be `.../marginaleffects/articles/alternative_software.html` ?]
- "80 classes" and "numerical results are checked" link to https://vincentarelbundock.github.io/marginaleffects/supported_models.html (404 error) [first should be `.../marginaleffects/articles/supported_models.html`, not sure about the second ?]

**Comment by vincentarelbundock** [comment]
Thanks a lot for the report! (and sorry it took a bit to respond). Should be fixed now.
