### ISSUE TITLE
Website: small mistake in chunk parameters

### ISSUE THREAD

**Issue by etiennebacher** [vincentarelbundock/marginaleffects#808]
In the causal inference section, the chunk parameters are not applied because they are prefixed with `##|` instead of `#|`:

![image](https://github.com/vincentarelbundock/marginaleffects/assets/52219252/f9706e46-92b9-4b58-9cb4-ffe2a5f893b7)

**Comment by vincentarelbundock** [comment]
Thanks! should be fixed
