### ISSUE TITLE
Multiple Imputation Bug

### ISSUE THREAD

**Issue by giac01** [vincentarelbundock/marginaleffects#817]
Hi Again, 

I'm not sure if this is a bug or the desired behaviour of the newgrid function:

```
Code:
rm(list=ls())
library(mice)
library(brms)
set.seed(10)
N = 1000

x = rbinom(N, size = 1, prob = .5 )

df = data.frame(
  x = x,
  z = rnorm(N),
  y = rnorm(N) + .5*x)

df$x[sample(N,20)] = NA
df$y[sample(N,20)] = NA

df_imputed = mice::mice(data = df, m = 4, method = "pmm")

model = brm_multiple(
  formula = brms::brmsformula("y ~ x + z"),
  family  = gaussian(),
  data    = df_imputed,
  cores   = 8,
  chains  = 2,
  iter    = 3000
)

# Mean of x across ALL imputed datasets

var_means =
  df_imputed %>%
  complete(., "long") %>%
  summarise(mean_x = mean(x),
            mean_z = mean(z),
            mean_y = mean(y)
            )

var_means$mean_x
[1] 0.50225

# Mean of x in the FIRST imputed dataset

var_means_firstimputation =
  df_imputed %>%
  complete(., "long") %>%
  filter(.imp ==1) %>%                     # Include only FIRST imputed dataset
  summarise(mean_x = mean(x),
            mean_z = mean(z),
            mean_y = mean(y)
  )

var_means_firstimputation$mean_x
[1] 0.501

# Mean of x calculcated by datagrid matches the first imputed dataset

datagrid_input = datagrid(z=0,
                          model = model
) 

datagrid_input$x

[1] 0.501

```

When using the newgrid function on a brmsfit_multiple object, it only pulls the means from the first multiply-imputed dataset. I'm not sure if this is the desired default behaviour here. 

Thanks!

**Comment by vincentarelbundock** [comment]
This is not a bug per se. The documentation says:

![Screenshot 2023-06-16 101316](https://github.com/vincentarelbundock/marginaleffects/assets/987057/419a0733-5140-44a5-96a1-3e0dbcc452a6)

My guess is that `insight::get_data()` returns only the first imputed dataset. There are two options:

1. Feed the dataset you want explicitly to the `newdata` argument inside the `datagrid()` call. (Note that *both* `avg_predictions` and `datagrid` have `newdata` arguments.)
2. Open an issue upstream to the `insight` repository asking for support to extract multiply imputed datasets, perhaps with a new column with an "imputation index."
