### ISSUE TITLE
Include warning about non-linear tests in the documentation?

### ISSUE THREAD

**Issue by huftis** [vincentarelbundock/marginaleffects#821]
[Section 7.3.1 of the documentation](https://vincentarelbundock.github.io/marginaleffects/articles/hypothesis.html#marginal-effects) has an example of a non-linear test::

>The hypotheses() string can include any valid R expression, so we can run some silly non-linear tests:
>
>```r
> slopes(
>    mod,
>    newdata = "mean",
>    hypothesis = "exp(am) - 2 * vs = -400")
>#> 
>#>               Term Estimate Std. Error    z Pr(>|z|)   S 2.5 % 97.5 %
>#>  exp(am)-2*vs=-400      817        550 1.49    0.137 2.9  -261   1896
>#> 
>#> Columns: term, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high
>```

I’m wondering if there perhaps should be a warning that the results of such tests can’t necessarily be trusted. If I have understood things correctly, the tests are Wald tests (where the SE is calculated using the delta method), i.e., they are based on an assumption of normality of the test statistic.

Here's an example, based on the same data and model. There are two tests, of the hypotheses `exp(am) = 36` and `am = log(36)`. They are of course equivalent. But the first test gives a P-value of 0.47, and the second, a P-value of 0.05. I guess the problem is that the `exp(am)` estimator is not approximately normally distributed, so a simple Wald test is not valid. (The second test should be valid.)

```r
library(marginaleffects)
mod <- lm(mpg ~ am + vs, data = mtcars)
slopes(
  mod,
  newdata = "mean",
  hypothesis = "exp(am) = 36")
#> 
#>        Term Estimate Std. Error     z Pr(>|z|)   S 2.5 % 97.5 %
#>  exp(am)=36      395        550 0.719    0.472 1.1  -683   1473
#> 
#> Columns: term, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high
slopes(
  mod,
  newdata = "mean",
  hypothesis = "am = log(36)")
#> 
#>        Term Estimate Std. Error    z Pr(>|z|)   S   2.5 % 97.5 %
#>  am=log(36)     2.48       1.27 1.95   0.0514 4.3 -0.0155   4.98
#> 
#> Columns: term, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high
```

**Comment by vincentarelbundock** [comment]
> They are of course equivalent.

Except that they are not. Look at the "Estimate" column.

**Comment by huftis** [comment]
Hm, I’m not sure I understand. The estimates are different, but the hypotheses are equivalent. `exp(am) - 36 = 0` is the same hypothesis as `am - log(36) = 0`. 

The estimate of `am` is 6.066667, and the estimates seems correct:

```r
am <- 6.066667
exp(am) - 36
#> [1] 395.241
am - log(36)
#> [1] 2.483148
```

**Comment by huftis** [comment]
Just to clarify, I’m not saying that there’s anything *wrong* in the *calculations*. But the P-values for Wald tests for non-linear transformations of the parameters can’t necessarily be trusted. As people may not be aware of this, perhaps it should be mentioned as a caveat in documentation/tutorial?

**Comment by vincentarelbundock** [comment]
What I meant is that the difference between 395.24 and 0 is much larger than the difference between 2.48 and 0. Since they are two very different quantities, the p values characterize very different tests, and they should be very different:

``` r
library(marginaleffects)
mod <- lm(mpg ~ am + vs, data = mtcars)
s <- slopes(mod, variables = "am", newdata = "mean")

am <- s$estimate

exp(am) - 36
# [1] 395.2408
am - log(36)
# [1] 2.483148
```

It’s very early in the morning for me and my brain is in a fog, but I don’t understand why you are saying that the hypotheses are equivalent. The null hypothesis tested by the `p.value` column is simply that the number in the `estimate` column is different from 0. No more, no less. In the two different commands that you ran, the numbers in the `estimate` columns are very different. Hence the hypotheses are different and the p values too.

**Comment by huftis** [comment]
Sorry if I was unclear. I’m coming to this more from a mathematical angle, and I’ll try to explain my reasoning. Please correct me if I’m wrong.

We’re considering hypotheses about a parameter `am` in certain model. A simple example of such a hypothesis is:

    am = log(36)

By doing the same operation on both sides of the equation, we get mathematically equvialent expressions. E.g., we can subtract log(36) from both sides:

    am - log(36) = log(36) - log(36)
    ↓
    am - log(36) = 0

Or multiply both sides by 2:

    2*am = 2*log(36)

Since both of these are mathematically equivalent hypotheses, we would expect identical P-values.

We can also exponentiate both sides of the equation:

    exp(am) = exp(log(36))
    exp(am) = 36

and then subtract 36 from both sides:

    exp(am) - 36 = 0

In all of these examples, the null hypothesis is the same (namely that `am` is `log(36)`). (For example, the expression `exp(am) - 36` is different from 0 in exactly the same cases as when `am - log(36)` is different from 0.)

So we might also expect the P-values from the `marginaleffects` package to be the same in all the examples.

But they’re not, since the hypotheses are being tested using Wald tests, which assume that the test statistic is normally distributed. And the Wald test is unfortunately not invariant under non-linear transformations. So, while the standard errors *are* (approx.) correct for arbitrary functions/transformations of the parameters, the P-values (and confidence intervals) are not. Therefore one should be careful when testing hypotheses using non-linear transformations, especially using such extreme transformations as exp().

**Comment by huftis** [comment]
BTW, I now see that the use of the `slopes()` function in the example might be confusing. The hypotheses are not really about slopes, and you get the same results with a simple:

```r
hypotheses(
  mod,
  hypothesis = "exp(am) = 36") # P-value 0.47
hypotheses(
  mod,
  hypothesis = "am = log(36)") # P-value 0.05
```

**Comment by vincentarelbundock** [comment]
Sorry it took a while for me to get back. Life and the day job have been crazy.

Yeah, I see what you mean now. Thanks for taking the time to explain. I agree that a note would be relevant in one (or all) of these places:

1. In the vignette next to this weird example.
2. In the documentation section which discusses the delta method: https://github.com/vincentarelbundock/marginaleffects/blob/main/man-roxygen/deltamethod.R
3. In the vignette on standard errors: https://github.com/vincentarelbundock/marginaleffects/blob/main/book/articles/uncertainty.qmd

Feel free to recommend language (or even better: a PR) if you have time.

Thanks!

**Comment by huftis** [comment]
I’ll try to come with some text for the documentation. But it’ll probably take a few weeks (I’m not at my usual computer).

**Comment by vincentarelbundock** [comment]
This is excellent stuff! Thanks!
