### ISSUE TITLE
Relative percentage change in avg_comparisons 

### ISSUE THREAD

**Issue by parasurama** [vincentarelbundock/marginaleffects#824]
First of all, thank you for this wonderful package. 

I'm wondering if there's a built-in way to compute relative % change in average comparisons. 
I looked at the elasticity documentation here, but couldn't find it:  https://vincentarelbundock.github.io/marginaleffects/articles/elasticity.html

Say I have the following glm:

```
set.seed(123)
n <- 1000
X <- sample(0:1, n, replace = TRUE)
error <- rnorm(n)
Y <- rbinom(n, 1, plogis(5*X + error))
dataset <- data.frame(X = X, Y = Y)
head(dataset)

mod = glm(Y ~ X, data = dataset, family = "binomial")
avg_comparisons(mod, variables = "X")
```

<img width="702" alt="image" src="https://github.com/vincentarelbundock/marginaleffects/assets/13189566/536cfdcc-c9f9-4934-a31b-4b95be661e85">

The contrast shows that 1 unit increase in X corresponds to 0.51 increase in Y.
Is there a way to normalize by the baseline Y i.e. E[Y|X=0]. 
In this case, it would be 1 unit increase in X corresponds to 108% increase in Y (0.515/0.474)

<img width="156" alt="image" src="https://github.com/vincentarelbundock/marginaleffects/assets/13189566/f589fb16-9f6d-46d0-b80a-b9e8d1fd61a7">

Thank you!

**Comment by parasurama** [comment]
Just saw that it can accept custom functions :)

`avg_comparisons(mod, variables = "X", comparison = function(hi, lo) (hi-lo)/lo*100)`

**Comment by vincentarelbundock** [comment]
Glad you like it!

Sure. Just change the value of the `variables` argument, either specific numeric values or even a function (see the section on forward/backward/centered in the Comparisons vignette for inspiration.)

**Comment by vincentarelbundock** [comment]
Ah yeah, that too :)
