### ISSUE TITLE
What's the difference between by and condition in plot_comparisons

### ISSUE THREAD

**Issue by parasurama** [vincentarelbundock/marginaleffects#825]
I'm trying to figure out the difference by arguments `by` and `condition` in `plot_comparisons`.

For example, the following two yield vastly different results.
```
# case 1
plot_comparisons(fixestmodel, variables = "x", by = "cell", type = "response")

# case 2
plot_comparisons(fixestmodel, variables = "x", condition = "cell", type = "response")

```
From what I understand from the documentation,  case 1, it's calculating the marginal effect for each observation in the dataset and averaging over "cell".

I'm not sure what's case 2. Is there any documentation on it?

Thank you!

**Comment by vincentarelbundock** [comment]
Case 2 is plotting over a grid built from equallY spaced values on the x-axis, and means of everything else.
