### ISSUE TITLE
ebook typo

### ISSUE THREAD

**Issue by ASKurz** [vincentarelbundock/marginaleffects#835]
Hey Vincent, thank you for linking to my blog series in your ebook [here](https://vincentarelbundock.github.io/marginaleffects/articles/links.html). However, it looks like you listed my blog series twice, which I appreciate, but probably isn't what you meant to do. :)

**Comment by vincentarelbundock** [comment]
Thanks!

Fixed on the dev version of the website: https://vincentarelbundock.github.io/marginaleffects/dev/articles/links.html
