### ISSUE TITLE
Generic for `hypotheses` testing with `coeftable` and `vcov`

### ISSUE THREAD

**Issue by kylebutts** [vincentarelbundock/marginaleffects#838]
Say you have a `coeftable` that is a data.frame with `term` and `estimate` and a `vcov` matrix with `colnames(vcov) == rownames(vcov) == coeftable$terms`. The following allows you to perform hypothesis tests. Like you said in https://github.com/lrberge/fixest/issues/424, might be too niche? But might be useful for any time you have a set of estimates and standard errors and you want to perform a hypothesis test? 

If you think it's useful, I can PR `methods-data.frame` and find a spot to add that info in documentation?

```r
marginaleffects::hypotheses(
  coeftable, vcov = vcov_sur,
  hypothesis = hypothesis,
  FUN = function(x) { x }
)

get_coef.data.frame = function(model) {
  x = model$estimate
  names(x) = model$term
  return(x)
}

set_coef.data.frame = function(model, coefs) {
  model$estimate = coefs
  return(model)
}
```

**Comment by vincentarelbundock** [comment]
Oh yes, that’s a very cool idea!

The methods should probably include some assertions to make sure the data frame conforms to expectation: column names, matches length of coef, etc.

i use the checkmate package for that and you’ll find a ton of similar assertions throughout the codebase. Very easy and useful.
