### ISSUE TITLE
bootstrapped avg_comparisons from feols model

### ISSUE THREAD

**Issue by cmjoyce** [vincentarelbundock/marginaleffects#839]
Hi there --

Thanks for the excellent package. I'm using avg_comparisons to compare contrasts from a feols model, but when I add on inferences(method = boot) I get the error that 
"The argument 'weights' is a formula whose variables must be in the data set given in argument 'data'. Problem: the variable
'weight' is not in the data."

Here's what it looks like:
```{r}
mod <- feols(Y ~ X1*X2 | X3 + X4,
                             cluster = ~cluster, 
                             weights = ~weight, data = dat)

avg_comparisons(mod, 
                variables = list(X2= "reference")
) %>% inferences(method = "boot", R = 1000)
```

The code works well if I exclude the inferences function, which makes me think the issue is in bootstrapping the feols object. 
My fixed effect X3 is quite large, so it's much more efficient to run in the fixest package. 

Is there a workaround so inferences could bootstrap a feols model? 

Thanks so much,
Caroline

**Comment by vincentarelbundock** [comment]
Thanks a lot for the report. I just pushed a new commit to Github. It should be fixed in version 0.13.0.9004.
