### ISSUE TITLE
`poly` and `ns` do not work fine with interactions in `plot_slopes`

### ISSUE THREAD

**Issue by XiangLiu-github** [vincentarelbundock/marginaleffects#846]
Hi, thanks for this package.

It seems that when using `plot_slopes`, the `poly` and `ns` can not work with interaction.

Example:

```r
library(tidyverse)
library(marginaleffects)
library(datasets)
library(fixest)
  
model = feols(Fertility ~ poly(Agriculture, df = 3) * Education, data = swiss)
  
plot_slopes(model, 'Agriculture', list('Agriculture', 'Education' = 'quartile'))
```
The quartile Education does not work.

**Comment by vincentarelbundock** [comment]
Thanks for the report.

The graph works: the plotting function correctly displays the slopes in the three groups, based on the output of the `fixest` `predict()` function. The lines are just exactly on top of one another, so you just see one. See this example, where the slopes are the same in the two groups (Education 1 and 12):

``` r
library(datasets)
library(fixest)
  
model = feols(Fertility ~ poly(Agriculture, df = 3) * Education, data = swiss)
nd = data.frame(Agriculture = c(24, 25, 24, 25), Education = c(1, 1, 12, 12))
p = predict(model, newdata = nd)
p[2] - p[1]
# [1] 0.2932421
p[4] - p[3]
# [1] 0.2932421
```

If the slopes *should* be different in this model, then this should be fixed upstream in `fixest`.

**Comment by XiangLiu-github** [comment]
Thanks for your reply!

```r
library(marginaleffects)
library(datasets)
library(fixest)

model = feols(Fertility ~ Education * ns(Agriculture, df = 3), data = swiss)

plot_slopes(model, 'Agriculture', list('Agriculture', 'Education' = 'quartile'))
```

I reorder the Education and `ns` or `poly`, and the result is what I want.

**Comment by vincentarelbundock** [comment]
Cool. Still weird that the output of `predict()` from `fixest` depends on the order. Might be worth reporting there with a minimal example if you think there's an actual problem.

**Comment by XiangLiu-github** [comment]
Not sure why. `lm` works for both formulas, this issue is probably related to `fixest` package.
