### ISSUE TITLE
Comparisons with feols doesn't work

### ISSUE THREAD

**Issue by simon-lowe** [vincentarelbundock/marginaleffects#855]
Thanks a lot for the great package!

I'm looking at a comparison done across two groups. It does what I expect it to do with lm, but not with feols.

```
library(marginaleffects)
library(fixest)

dat <- mtcars
dat$am <- as.logical(dat$am)

reg2 <- lm(data = dat, mpg ~ am*vs + disp)
summary(reg2)

cmp <- comparisons(reg2,
                   variables = list(am = c("FALSE", "TRUE")),
                   newdata = datagrid(vs = c(FALSE, TRUE)))
cmp

reg3 <- feols(data = dat, mpg ~ am*vs + disp)
summary(reg3)

cmp <- comparisons(reg3,
                   variables = list(am = c("FALSE", "TRUE")),
                   newdata = datagrid(vs = c(FALSE, TRUE)))
cmp
```
The reason I'm interested in it working with fixest is because ultimately I'd like to do this on regression with a lot of fixed effect on huge administrative data.

Thanks a lot.

**Comment by vincentarelbundock** [comment]
@simon-lowe please try again while supplying the correct data types. `am` is logical and you are supplying strings. `vs` is numeric (binary) and you are supplying logical.
