### ISSUE TITLE
Make `by`-argument not required with `plot_predictions()` if `draw = FALSE` is specified

### ISSUE THREAD

**Issue by snhansen** [vincentarelbundock/marginaleffects#859]
Consider the following code:

```
model <- lm(mpg ~ as.factor(gear), data = mtcars)
plot_predictions(model, newdata = datagrid("gear" = c("3", "4", "5")), draw = FALSE)
# Error: The `newdata` argument requires a `by` argument.
```
In this example, it seems unintuitive to require the `by`-option since I'm not interested in plotting the result. Would it be an idea to not require this option when `draw = FALSE` is used?

**Comment by vincentarelbundock** [comment]
Thanks for the suggestion, but I'm not sure I'm convinced by the use-case. If you don't want to (eventually) plot the results, you should be using `predictions()`, not `plot_predictions()`.

I just want to add features to the latter if they clearly support the intended use, which is to plot.

**Comment by snhansen** [comment]
I see your point. Using `predictions()` in this case makes more sense. Thanks for the response.
