### ISSUE TITLE
Feature request: Use conf_level = NULL to suppress display of confidence intervals in plot_ functions

### ISSUE THREAD

**Issue by marcora** [vincentarelbundock/marginaleffects#864]
Especially when plotting predictions of models with lots of lines (e.g., random intercept and slope by country) the display of CIs gets in the way. I can set it to something like 0.001 and forget about it, but having a principled way to suppress the display (and possibly also the calculation) of it would be great!

**Comment by vincentarelbundock** [comment]
Does setting vcov to FALSE do what you need?

**Comment by marcora** [comment]
Yes! I guess I am not that savvy, but setting `vcov = FALSE` is less intuitive than setting `conf_level = 0` or `conf_level = FALSE` or `conf_level = NULL`. For example, I believe ggeffects suppresses display of CIs when `conf_level = 0`.
