### ISSUE TITLE
Adding support for nlpar - brms model

### ISSUE THREAD

**Issue by osupplisson** [vincentarelbundock/marginaleffects#868]
Hi,

First, thank you very much for this amazing package !

I am currently dealing with a brms object defined using the non-linear syntax. For context, in my case, it is a logistic model with misclassification:

```
formula_brms <- brms::bf(
          outcome ~ sens * p + (1 - spec) * (1 - p),
          nlf(p ~ inv_logit(eta)),
          lf(eta ~ 0 + Intercept + x),
          nlf(sens ~ inv_logit(exp(gammasens))),
          nlf(spec ~ inv_logit(exp(gammaspec))),
          gammasens ~ 1,
          gammaspec ~ 1,
          nl = TRUE,
          family = bernoulli("identity")
        )
```

With this kind of model, one might be interested into the effect of one variable upon one of the non-linear component (in my case the effect on the latent probability p) and not the response variable itself or the probability to observed y = 1.

The documentation says that

> The type of draws used is controlled by using the type argument of the predictions() or slopes() unctions:
> 
> type = "response": Compute posterior draws of the expected value using the [brms::posterior_epred](https://mc-stan.org/rstantools/reference/posterior_epred.html) function. 

Because the epred function takes as argument `nlpar `for draws related to some of the formula components, I was expecting the following to work:

`slopes(
  fit,
  newdata = fit$data[seq(1,100),],
  type = "response",
  nlpar = "p",
  seed = 123)`

However, I got this warning:

Warning messages:

> These arguments are not supported for models of class `brmsfit`: nlpar. Valid arguments include: ndraws, re_formula, allow_new_levels, sample_new_levels, dpar, resp. Please file a request on Github if you believe that additional arguments should be supported: https://github.com/vincentarelbundock/marginaleffects/issues

Maybe I am missed something in the documentation and the nlpar argument should be used in other way ? Otherwise, adding this feature would be awesome ! I am currently doing everything by hand and it's quite tedious. 

Cheers,
Olivier

Ps: I didn't find any related open or closed issues, sorry if I missed it!

**Comment by vincentarelbundock** [comment]
Thanks for the report.

This is a generic warning (not an error!) issued when the name of the argument is not on the internal whitelist of know arguments.

It is quite possible that this is already working as expected. 

Could you compare the results to your manual computation to see if the results are Ok?

If they are, I can suppress the warning.

**Comment by osupplisson** [comment]
Thank you very much for your quick reply.

Yes indeed, it seems to be ok based on the following example:

```
#Loading package
library(brms)
library(marginaleffects)
library(tidyverse)
library(tidybayes)

#Data and prior - from https://cran.r-project.org/web/packages/brms/vignettes/brms_nonlinear.html
b <- c(2, 0.75)
x <- rbinom(n = 100, size = 1, prob = 0.75)
y <- rnorm(100, mean = b[1] * exp(b[2] * x))
dat1 <- data.frame(x, y)
prior1 <- prior(normal(1, 2), nlpar = "b1") +
  prior(normal(0, 2), nlpar = "b2")

#Fit    
fit1 <- brm(bf(y ~ b1 * eta,
               nlf(eta ~ exp(b2 * x)),
               b1 + b2 ~ 1, 
               nl = TRUE),
            data = dat1, prior = prior1, iter = 2000, warmup = 1000)

summary(fit1)
```

> 
>  Family: gaussian 
>   Links: mu = identity; sigma = identity 
> Formula: y ~ b1 * eta 
>          eta ~ exp(b2 * x)
>          b1 ~ 1
>          b2 ~ 1
>    Data: dat1 (Number of observations: 100) 
>   Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
>          total post-warmup draws = 4000
> 
> Population-Level Effects: 
>              Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
> b1_Intercept     2.05      0.22     1.63     2.49 1.00     1296     1474
> b2_Intercept     0.74      0.11     0.54     0.97 1.00     1258     1358
> 
> Family Specific Parameters: 
>       Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
> sigma     1.06      0.08     0.92     1.23 1.00     1837     1428
> 
> Draws were sampled using sampling(NUTS). For each parameter, Bulk_ESS
> and Tail_ESS are effective sample size measures, and Rhat is the potential
> scale reduction factor on split chains (at convergence, Rhat = 1).


* Computing the marginal effect for x on b1 and b2. Expected to be 0.


```
#Marginal effect
#Should return 0 for all rpw:
slopes(fit1, newdata = fit1$data, type = "response", nlpar = "b1", seed = 123, ndraws = 100, seed = 123)

 Term Contrast Estimate 2.5 % 97.5 % x
    x    1 - 0        0     0      0 1
    x    1 - 0        0     0      0 1
    x    1 - 0        0     0      0 1
    x    1 - 0        0     0      0 1
    x    1 - 0        0     0      0 0
--- 90 rows omitted. See ?avg_slopes and ?print.marginaleffects --- 
    x    1 - 0        0     0      0 1
    x    1 - 0        0     0      0 1
    x    1 - 0        0     0      0 1
    x    1 - 0        0     0      0 1
    x    1 - 0        0     0      0 1
Columns: rowid, term, contrast, estimate, conf.low, conf.high, predicted, predicted_hi, predicted_lo, tmp_idx, y, x 

Warning messages:
1: These arguments are not supported for models of class `brmsfit`: nlpar, seed. Valid arguments include: ndraws, re_formula, allow_new_levels, sample_new_levels, dpar, resp. Please file a request on Github if you believe that additional arguments should be supported: https://github.com/vincentarelbundock/marginaleffects/issues 
2: These arguments are not supported for models of class `brmsfit`: nlpar, seed. Valid arguments include: ndraws, re_formula, allow_new_levels, sample_new_levels, dpar, resp. Please file a request on Github if you believe that additional arguments should be supported: https://github.com/vincentarelbundock/marginaleffects/issues 
> slopes(fit1, newdata = fit1$data, type = "response", nlpar = "b2", seed = 123, ndraws = 100, seed = 123)

 Term Contrast Estimate 2.5 % 97.5 % x
    x    1 - 0        0     0      0 1
    x    1 - 0        0     0      0 1
    x    1 - 0        0     0      0 1
    x    1 - 0        0     0      0 1
    x    1 - 0        0     0      0 0
--- 90 rows omitted. See ?avg_slopes and ?print.marginaleffects --- 
    x    1 - 0        0     0      0 1
    x    1 - 0        0     0      0 1
    x    1 - 0        0     0      0 1
    x    1 - 0        0     0      0 1
    x    1 - 0        0     0      0 1
Columns: rowid, term, contrast, estimate, conf.low, conf.high, predicted, predicted_hi, predicted_lo, tmp_idx, y, x 

Warning messages:
1: These arguments are not supported for models of class `brmsfit`: nlpar, seed. Valid arguments include: ndraws, re_formula, allow_new_levels, sample_new_levels, dpar, resp. Please file a request on Github if you believe that additional arguments should be supported: https://github.com/vincentarelbundock/marginaleffects/issues 
2: These arguments are not supported for models of class `brmsfit`: nlpar, seed. Valid arguments include: ndraws, re_formula, allow_new_levels, sample_new_levels, dpar, resp. Please file a request on Github if you believe that additional arguments should be supported: https://github.com/vincentarelbundock/marginaleffects/issues 
> #OK!

```

* Test for x, both the package and manual approach are expected to return the same values

```
test_package <- avg_slopes(fit1, newdata = fit1$data, type = "response", nlpar = "eta", seed = 123,  ndraws = 4000)
test_package
#Manual computation
test_manual <- tidybayes::epred_draws(
  fit1,
  newdata = fit1$data %>%  mutate(x = 1, 
                                  id_ind = row_number(), 
                                  values_x = 1) %>%  
    rbind(fit1$data %>% 
            mutate(x = 0, 
                   id_ind = row_number(),
                   values_x = 0)),
  nlpar = "eta",
  ndraws = 4000,
  seed = 123
)

test_manual %>% 
  ungroup() %>% 
  pivot_wider(values_from = ".epred",
              names_from = "values_x",
              id_cols  = c('id_ind', '.draw')) %>% 
  mutate(marginal_effect = `1` - `0`) %>% 
  summarise(median = median(marginal_effect),
            lb = quantile(marginal_effect, 0.025),
            ub = quantile(marginal_effect, 0.975)) %>% 
  cbind(test_package %>%  dplyr::select(estimate, conf.low, conf.high))
```

```
    median        lb       ub estimate  conf.low conf.high
1 1.086529 0.7106353 1.641943 1.086529 0.7106353  1.641943  

```


Sorry for the unecessary heads-up !

**Comment by vincentarelbundock** [comment]
Thanks for checking, this is very useful. I just pushed a change to the development version on Github. It should no longer issue a warning.

I'll probably release a new version to CRAN in the next couple weeks with this change.

**Comment by vincentarelbundock** [comment]
bc49f23c02373d3fc8249381a292f9b2835e4957
