### ISSUE TITLE
FR: hypothesis argument for plot_slopes

### ISSUE THREAD

**Issue by andymilne** [vincentarelbundock/marginaleffects#869]
I have a model with the following form:

`y ~ time + time : treat * x + (1 | ID)`

where `time` is an indicator for post-test versus pre-test, `treat` is a factor for the type of (educational) intervention, `x` is a continuous covariate (here, age), and `ID` is participant.

I am interested in the (non-causal) association between age and the treatment effect. I can do this numerically with:
```
avg_slopes(
  newdata = datagridcf(treat = unique),
  mdl,
  variables = "x",
  by = c("time", "treat"),
  hypothesis = lc,
)
```
where `lc` is an appropriate contrast matrix to subtract pre from post. But I cannot find a straightforward way to plot these slopes because the `hypothesis` argument is, as far as I can see, not supported by `plot_slopes`.

**Comment by vincentarelbundock** [comment]
Yeah, I think this is one of those cases where you have to take advantage of the fact that all marginaleffects output is a tidy data frame,
and the just use ggplot2.
