### ISSUE TITLE
comparisons errors when run on first model after fitting second model that has same focal variable name but different levels

### ISSUE THREAD

**Issue by eipi10** [vincentarelbundock/marginaleffects#872]
I generated a series of models using the same data frame, but with different focal variables (each a two-level factor variable, but with different levels in each one). Each time, I renamed the focal variable to `treat`, and thus `treat` contained different levels in each model. This resulted in an unexpected (to me, at least) result when I ran `comparisons` or other functions from `marginaleffects`. A reproducible example is below. 

Note that models `m1` and `m2` have the same formula and use data frames with the same name, but `treat` contains different data in each case. If `comparisons` is run on model `m1` *after* setting up and fitting model `m2`, it throws an error. The output of `datagrid(model=m1)` shows that even though I've passed model `m1`, which used a data frame where the `treat` column had levels "A" and "B", `datagrid` (and, presumably, `comparisons`) thinks the levels are "C" and "D", which is true for the data used to fit `m2`.  

In retrospect, this was probably a dumb way to set up the workflow. But still, it seemed weird that `datagrid` and `comparisons` were somehow extracting the levels from the current version of `treat` (in `m2`), even though I passed `m1` to the function. Is there some kind evaluation/environment issue going on here? Is the behavior below expected (i.e., operator error on my part) or is this a bug?

``` r
library(tidyverse)
library(marginaleffects)

set.seed(495)
fake.data = tibble(
  outcome = rnorm(100),
  f1 = factor(sample(c("A","B"), 100, replace=TRUE)),
  f2 = factor(sample(c("C","D"), 100, replace=TRUE)),
  n1 = rnorm(100, 50, 10),
  n2 = rnorm(100, 20, 4)
)

# Model m1: "treat" is the focal variable
mdat = fake.data %>% mutate(treat=f1)
form = outcome ~ treat + n1 + n2
m1 = glm(form, data=mdat)

# comparisons works as expected
comparisons(model=m1, variables="treat", newdata=datagrid(n1=50, n2=20))
#> 
#>   Term Contrast n1 n2 Estimate Std. Error     z Pr(>|z|)   S  2.5 % 97.5 %
#>  treat    B - A 50 20   0.0652      0.185 0.353    0.724 0.5 -0.297  0.427
#>  treat
#>      A
#> 
#> Columns: rowid, term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, n1, n2, predicted_lo, predicted_hi, predicted, outcome, treat

# Model m2: "treat" is still the focal variable, but now contains different data
mdat = fake.data %>% mutate(treat=f2)
m2 = lm(form, data=mdat)

# comparisons errors when run on model m1 
comparisons(model=m1, variables="treat", newdata=datagrid(n1=50, n2=20))
#> Error: Unable to compute predicted values with this model. You can try to
#>   supply a different dataset to the `newdata` argument. If this does not
#>   work, you can file a report on the Github Issue Tracker:
#>   https://github.com/vincentarelbundock/marginaleffects/issues

# But works when m1$data is explicitly supplied
comparisons(model=m1, variables="treat", newdata=datagrid(newdata=m1$data))
#> 
#>   Term Contrast Estimate Std. Error     z Pr(>|z|)   S  2.5 % 97.5 % treat   n1
#>  treat    B - A   0.0652      0.185 0.353    0.724 0.5 -0.297  0.427     A 48.3
#>  n2
#>  20
#> 
#> Columns: rowid, term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted_lo, predicted_hi, predicted, outcome, treat, n1, n2

# The model is m1, but datagrid returns a treatment value 
#  that exists only in model 2
datagrid(model=m1)
#>       outcome treat       n1       n2
#> 1 -0.03444144     C 48.29913 20.03307
```

<sup>Created on 2023-08-19 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by vincentarelbundock** [comment]
Thanks for the report.   I realize this is unintuitive, but it's a hard problem to solve. It is explains in the docs:

`?comparisons`:

> NULL (default): Unit-level contrasts for each observed value in the original dataset (empirical distribution). See insight::get_data()

`?get_data`:

> String, indicating from where data should be recovered. If source = "environment" (default), data is recovered from the environment (e.g. if the data is in the workspace). This option is usually the fastest way of getting data and ensures that the original variables used for model fitting are returned. Note that always the current data is recovered from the environment. Hence, if the data was modified after model fitting (e.g., variables were recoded or rows filtered), the returned data may no longer equal the model data.

**Comment by eipi10** [comment]
Ah, I missed that. I was assuming the data would be recovered from inside the model object. 

I think it could be helpful to spell this out in the help for the `NULL` bullet point of the `newdata` argument of `comparisons` (and similarly for any other functions where this issue might come up). Currently, the user has to realize that there's a reason to worry about the default setting for `newdata` going haywire in some possibly common situations (e.g., if you changed the data in the parent environment) in order to have a reason to click on the `insight::get_data()` link.

It also might be helpful to make the error message a bit more informative. Maybe adding something like "This error can occur if the data frame object used to fit the model was subsequently changed. See help for `insight::get_data()`, specifically, the `source` argument." (Although maybe there could be lots of reasons for this specific error to occur.)

Is it possible to include a check for whether the data frame object `comparisons` (or whatever function) is using from the external environment is the same as the data frame used to fit the model? But since `marginaleffects` supports so many different model-fitting functions with different returned-object structures, maybe that's what you meant by this being a hard problem.

**Comment by vincentarelbundock** [comment]
Yep, I agree this is not obvious. Thanks for the suggestions. The docs and error message will be clearer in the next version:

https://github.com/vincentarelbundock/marginaleffects/commit/99113dcfac1d641ad1ee81c8da37228f9317136d

Unfortunately it's not possible to check if the data frames match: `insight::get_data()` returns the listwise deleted version with different attributes, so comparison will necessarily fail. Hopefully, improved docs make it easier for people to figure out what is going on.
