### ISSUE TITLE
Feature request: multiple hypotheses

### ISSUE THREAD

**Issue by ngreifer** [vincentarelbundock/marginaleffects#889]
I'm wondering if it would be possible to supply a vector of strings containing multiple hypotheses to be tested to the `hypothesis` argument of `hypotheses()`. For example, let's say I'm using `hypotheses()` after `avg_predictions()`, I have 4 predictions, and I want to compare 1 to 2, 3 to 4, and 1 - 2 to 3 - 4. My options now are: 1) perform each of these hypotheses one at a time or 2) figure out a contrast matrix to supply that corresponds to these hypotheses.

My suggestion is to allow multiple hypotheses to be supplied to be test simultaneously, e.g., as `hypothesis = c("b1 - b2 = 0", "b3 - b4 = 0", "b1 - b2 = b3 - b4")`. Using the contrast matrix approach suggests that the possibility for a multi-line comparison already exists. Allowing this would speed up multiple comparisons when, e.g., bootstrapping because all hypothesis contrasts can be estimated within each bootstrap sample. Thanks!

**Comment by vincentarelbundock** [comment]
Very good idea, but...

Multiple contrasts in a matrix are super easy because we only need to `%*%`. 

String equations need to be parsed, modified, and evaluated, so the backend code is totally separate.

I like this feature request a lot but, realistically, I don't think I'll have the bandwidth to implement it in the short run.

**Comment by ngreifer** [comment]
That's okay, thanks for considering.

**Comment by ngreifer** [comment]
Wait... I think you already implemented this. All you need to do is change `check_string()` to `check_character()` in `sanitize_hypothesis()` and supplying multiple strings to `hypothesis` works.

**Comment by vincentarelbundock** [comment]
Haha, fun. Life is crazy right now, but I'll get to this when I find some time.
