### ISSUE TITLE
R dependency

### ISSUE THREAD

**Issue by strengejacke** [vincentarelbundock/marginaleffects#89]
I don't think this works: R (>= 3.5.0) because if I'm not mistaken, I saw the new native pipe in your code? :-)

**Comment by vincentarelbundock** [comment]
Oh right! I'm pretty sure I'm not using the pipe in the actual package, and Github Actions do run some checks on old R versions. But your point stands: If I advertise 3.5, then the vignette examples should also work on that version.

**Comment by strengejacke** [comment]
> I'm pretty sure I'm not using the pipe in the actual package

Ok, that might be. After looking again, I found in a "sandbox test" - not sure if these tests are run other systems (i.e. older R)?

**Comment by vincentarelbundock** [comment]
I see. For now, `sandbox` is just a place I keep work in progress I don't want to lose. They should probably just be in git branches, but I'm afraid I'll just purge them accidentally, and that they'll get less love if they are less visible ;)

**Comment by vincentarelbundock** [comment]
Removed the remnant in d6e406f

The only other pipes are in `testthat/stata`, where I keep testing scripts intended to run locally on the developer's machine, so I don't think this is a problem.

Thanks for the note; I'll be more careful in the future
