### ISSUE TITLE
Missing math characters in docs of `hypotheses()`

### ISSUE THREAD

**Issue by etiennebacher** [vincentarelbundock/marginaleffects#890]
Hi Vincent, the math characters are invisible in the documentation of [`hypotheses`](https://marginaleffects.com/articles/reference/hypotheses.html). It might also be the case in other places, I just noticed it there. Note that the doc is fine if I open it in RStudio.

In the book:

![image](https://github.com/vincentarelbundock/marginaleffects/assets/52219252/ff10c5ea-1282-4a0f-b811-74582743b58a)

In Rstudio:

![image](https://github.com/vincentarelbundock/marginaleffects/assets/52219252/45d996ee-d813-4c0e-89d2-72259ca4c3c4)

**Comment by vincentarelbundock** [comment]
Thanks for looking at this. I had noticed it, but it's a good idea to keep a note here as reminder.

I probably won't do anything about this until Remi and I make progress on `altdoc`.

**Comment by vincentarelbundock** [comment]
Fixed and deployed. Thanks again for the report!

https://marginaleffects.com/articles/reference/hypotheses.html
