### ISSUE TITLE
Difference in the output of `equivalence::tost()` and `hypotheses()`?

### ISSUE THREAD

**Issue by etiennebacher** [vincentarelbundock/marginaleffects#891]
Hi Vincent, in [this section](https://marginaleffects.com/articles/equivalence.html#example-6-t-test), you compare the output of `equivalence::tost()` with `marginaleffects::hypotheses()`, but `tost()` returns a confidence interval of `-1.058539  0.845747` while `hypotheses()` returns `-1.05 1.26`.

Is this a bug or am I missing something?

``` r
suppressPackageStartupMessages(library(equivalence))
library(marginaleffects)

set.seed(1024)
N <- 20
dat <- data.frame(
  y = rnorm(N),
  x = sample(c(rep(0, N / 2), rep(1, N / 2)), N))

mod <- lm(y ~ x, data = dat)

## test with the {equivalence} package
e <- tost(
  x = dat$y[dat$x == 0],
  y = dat$y[dat$x == 1],
  epsilon = 10)
e
#> 
#>  Welch Two Sample TOST
#> 
#> data:  dat$y[dat$x == 0] and dat$y[dat$x == 1]
#> df = 17.607
#> sample estimates:
#>  mean of x  mean of y 
#> -0.3788551 -0.2724594 
#> 
#> Epsilon: 10 
#> 95 percent two one-sided confidence interval (TOST interval):
#>  -1.058539  0.845747
#> Null hypothesis of statistical difference is: rejected 
#> TOST p-value: 4.248528e-13

## test with {marginaleffects} package
hypotheses(mod, equivalence = c(-10, 10), df = e$parameter)[2, ]
#> 
#>  Term Estimate Std. Error     t Pr(>|t|)   S 2.5 % 97.5 % p (NonSup) p (NonInf)
#>     x    0.106      0.548 0.194    0.848 0.2 -1.05   1.26     <0.001     <0.001
#>  p (Equiv)   Df
#>     <0.001 17.6
#> 
#> Columns: term, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, df, statistic.noninf, statistic.nonsup, p.value.noninf, p.value.nonsup, p.value.equiv
```

**Comment by vincentarelbundock** [comment]
Interesting!

Do you know what kind of interval `equivalence::tost` reports? I don’t find the documentation super clear.

`marginaleffects` reports a classical confidence interval around the coefficient, just like `t.test()` and `confint()` (with slight degrees of freedom related differences):

``` r
set.seed(1024)
N <- 20
dat <- data.frame(
    y = rnorm(N),
    x = sample(c(rep(0, N / 2), rep(1, N / 2)), N))
mod <- lm(y ~ x, data = dat)

confint(mod)
#                 2.5 %    97.5 %
# (Intercept) -1.193573 0.4358626
# x           -1.045789 1.2585806

t.test(x = dat$y[dat$x == 0], y = dat$y[dat$x == 1])
# 
#   Welch Two Sample t-test
# 
# data:  dat$y[dat$x == 0] and dat$y[dat$x == 1]
# t = -0.194, df = 17.607, p-value = 0.8484
# alternative hypothesis: true difference in means is not equal to 0
# 95 percent confidence interval:
#  -1.260425  1.047633
# sample estimates:
#  mean of x  mean of y 
# -0.3788551 -0.2724594
```

**Comment by etiennebacher** [comment]
Yeah the docs of `tost()` is quite sparse and I actually never used this package before, I just noticed this diff while reading your docs. I don't have time and expertise to find why there's this difference, but I'm curious to see if someone will be able to explain it.

Btw I quickly skimmed into the `get_ci()` function and noticed this duplicated `if` condition. I don't think it introduces a bug but I put it here just in case you want to double check:
https://github.com/vincentarelbundock/marginaleffects/blob/9aed0e18c0056a082ec040e2f0d569cf1555e0fc/R/ci.R#L67-L70

**Comment by vincentarelbundock** [comment]
good catch!

I think I'll close this. The confidence interval definition in `marginaleffects` feels unambiguous. If we want to display the TOST, we'd need a definition and a new column name. I'd be open to including it if someone comes along to propose it.

**Comment by huftis** [comment]
The confidence interval in `equivalence::tost()` seems to be a 90% confidence interval (which is equivalent to two *one-sided* 95% confidence intervals). That’s the normal way to calculate confidence intervals for equivalence testw (using the TOST methodology). If your equivalence intervals falls entirely within the 90% two-sided confidence interval, you can state that the two groups/treatments are equivalent (using a 5% significance level).

**Comment by vincentarelbundock** [comment]
Thanks for the clarification, I really appreciate it.

I don't plan to report different confidence intervals right now, so I'm going to close this issue.

If someone wants to investigate best practices and can supply references/sources, I'd be happy to merge a contributed Pull Request adding a new set of confidence intervals. If we go that way, I think the columns should be named differently than the current `conf.high` and `conf.low`, to maintain consistency. This is already what I do with the equivalence p values, which are named something like: `p.value.equiv`, `p.value.nonsup`, etc.
