### ISSUE TITLE
`inferences()` should support `hypotheses()` 

### ISSUE THREAD

**Issue by Tristan-Siegfried** [vincentarelbundock/marginaleffects#893]
I am not sure if I am missing how to do this as it seems like a natural extension of what `marginaleffects` can already do, but I thought it was worth flagging since I didn't see how to do this in the documentation.

The desired usage would be to pass `hypotheses` objects to the `inferences()` function, with the upshot of being able to use e.g. bootstrapping for hypotheses

**Comment by vincentarelbundock** [comment]
That's not currently supported, but it probably should be. If someone is interested in trying to make this work, a good place to start might be to include a call to `inferences_dispatch()` near the very top of the `hypotheses()` function definition. 

Something like this: https://github.com/vincentarelbundock/marginaleffects/blob/main/R/comparisons.R#L406

Somewhere around here: https://github.com/vincentarelbundock/marginaleffects/blob/main/R/hypotheses.R#L134
