### ISSUE TITLE
Support for untransformed risk ratio comparisons

### ISSUE THREAD

**Issue by huftis** [vincentarelbundock/marginaleffects#894]
The `comparisons()` function has built-in support for the following comparisons for risk/rate ratios:

- `"ratio"`
- `"ratioavg"`
- `"ratioavgwts"`
- `"lnratio"`
- `"lnratioavg"`
- `"lnratioavgwts"`

However for odds ratios, it only supports the log-transformed versions:

- `"lnor"`
- `"lnoravg"`
- `"lnorwts"`

Is this intential or just an oversight? If it’s the latter, I can create a PR to add support for the untransformed versions.

Of course, using the log-transformed versions and back-transforming the results is in general *better*, as you get more reliable confidence intervals. But it’s convenient to have easy access to the non-transformed versions, e.g., when comparing the two types of intervals, or when comparing your results with results in papers or textbooks.

**Comment by vincentarelbundock** [comment]
Thanks a lot for the issue and the offer of  a PR!

TBH, it was an oversight, but now I'm thinking it might not be a bad idea to avoid creating new shortcuts that encourage bad practice.

And as the docs show, it is trivial to define your own `or()` function and feed that to the argument, so I'm not sure I'm convinced by the convenience argument...

All this to say that I could possibly be convinced either way if you have strong views, but that my intuition leans toward status quo.

**Comment by huftis** [comment]
No, I don’t have very strong opinions on this issue. And for `"lnoravg"`, this is clearly the best statistic to use when calculating confidence intervals for the odds ratio of the marginal effects. For `"lnor"` and `"lnorwts"`, on the other hand, the story is a bit different. Here you’re actually estimating a different quantity than if you would use (the non-existent) `"or"` or `"orwts"`, cf. #895.

**Comment by vincentarelbundock** [comment]
What's your specific recommendation?

**Comment by huftis** [comment]
> What's your specific recommendation?

I’m not sure. But if you think it’s not necessary to add more comparisons, feel free to close this issue.

**Comment by vincentarelbundock** [comment]
Alright, since there's nothing actionable, let's keep the repo clean and close this for now.

But as I said, I'm open to counter arguments, and I am *very* interested in adding new shortcuts if we think of other useful quantities. 

So feel free to keep the discussion going or open a new issue if you have ideas.
