### ISSUE TITLE
Reconsider the default transformation for average predictions from glm and similar models

### ISSUE THREAD

**Issue by huftis** [vincentarelbundock/marginaleffects#895]
This is a request to reconsider the way average predictions are handled by default for `glm` and similar models.

I find the current behaviour confusing. The default scale is listed in `marginaleffects:::type_dictionary`. But for some models, it’s misleading. Looking at

```r
library(marginaleffects)
subset(marginaleffects:::type_dictionary, class %in% c("glm","glmerMod"))
#>       class     type
#> 61      glm response
#> 62      glm     link
#> 63 glmerMod response
#> 64 glmerMod     link
```

one would think that the default scale for both `glm` and `glmer` models is the response scale (the first row). It is for `glmer` models, but not for `glm` models, where it’s the link scale, but back-transformed.

Now, this *is* documented in the ‘Details’ section of the help file:

> For `glm()`, `MASS::glm.nb`, `gam::gam()`, and `feols::feglm` models with `type`, `transform` and `hypothesis` all equal to `NULL` (the default), `predictions()` first predicts on the link scale, and then backtransforms the estimates and confidence intervals. This implies that the `estimate` produced by `avg_predictions()` will not be exactly equal to the average of the `estimate` column produced by `predictions()`. Users can circumvent this behavior and average predictions directly on the response scale by setting `type="response"` explicitly.

But it’s still very confusing. Why can’t `marginaleffects:::type_dictionary` be trusted? Why have different behaviour for *implicit* `type = "response"` and *explicit* `type = "response"`? And why is the default scale different for, e.g., logistic models and mixed-effects logistic models?

The help file sorts of implies that the current behaviour is done (just?) to achieve better accuracy in the confidence intervals:

> With `type="response"`, the intervals are symmetric and may have undesirable properties (e.g., stretching beyond the `[0,1]` bounds for a binary outcome regression).

But the method it’s *actually* estimating a completely different quantity! Now, if there’s little variation in the probabilities in a logistic model, there’s really not much difference in the mean probabilty and the backtransformed link values:

```r
p = c(.01, .02)
mean(p)
#> [1] 0.015
plogis(mean(qlogis(p)))
#> [1] 0.01415446
```

And if all probabilities are far away from 0 and 1, there’s also little difference, even *if* you have much variation in the probabilities:

```r
p = c(.3, .6)
mean(p)
#> [1] 0.45
plogis(mean(qlogis(p)))
#> [1] 0.4449944
```

But if you have both large variation and some probabilties close to 0 or 1 (which you typically would have if you have a rare outcome, but a predictor with good predictive power, e.g., a gene strongly associated with a rare disease), there’s a *huge* difference:

```r
p = c(.01, .40)
mean(p)
#> [1] 0.205
plogis(mean(qlogis(p)))
#> [1] 0.07583768
```

Which illustrates that it’s not just a calculation to achieve better accuracy; you’re really estimating a completely different *quantity*.

My suggestion is:

1. Reconsider if you really want to have the default ‘average prediction’ for these models be ‘backtransformed mean of link predictions’. The current default behaviour is very surprising, IMHO.
2. But if you do want it to be default, consider making it *explicit*, by having the first row of `marginaleffects:::type_dictionary` be something like `backtransf_link` (I’m sure there are better names). Then the user can easily check what the default is for each model by consulting `marginaleffects:::type_dictionary`. And they can also easily use this ‘scale’ for other models, e.g., for `glmer` models. (It would also be convient to have the type/scale stored as a column in the output from `avg_predictions()`.)

**Comment by vincentarelbundock** [comment]
Thanks for engaging with this.

I don't see a specific argument against the quantity itself, so my intuition is to keep it as default.

I do agree that being more explicit is highly desirable and that the current behaviour is counterintuitive.

I line the idea of introducing an explicit `type` value. But how can we indicate that backtransformation is only possible for predictions, and not comparisons or slopes?

The type is already stored in `attr(x,"type")` so I'm not convinced we need a new column. Also, adding new columns means we forbid more column names in the original data, which is undesirable. (We should check the value of this attribute too.)

**Comment by vincentarelbundock** [comment]
Introducing an explicit type would also simplify the code, which I like.

**Comment by huftis** [comment]
> I line the idea of introducing an explicit type value. But how can we indicate that backtransformation is only possible for predictions, and not comparisons or slopes?

Hmm. One solution would to be to have completely separate `marginaleffects:::type_dictionary` objects for predictions and comparisons/slope. But that would duplicate a lot information, and you would have to keep to objects in sync.

Perhaps you could have a `marginaleffects:::type_dictionary_pred` object only for the models that actually differ in their default values. And then document in `?avg_predictions` that the default type is taken from the `marginaleffects:::type_dictionary_pred`, and if no entry exists in this object, it’s taken from `marginaleffects:::type_dictionary`.

> The type is already stored in attr(x,"type") so I'm not convinced we need a new column.

No, I agree. Having as an attribute is sufficient. (I wasn’t aware that is was stored as an attribute.)

**Comment by vincentarelbundock** [comment]
Alright, I propose 3 changes:

1. `type_dictionary` becomes undocumented for internal use only. The documented way to get a list of relevant type is to call the function with a bad type string or "help"
2. New type available called something like "invlink(link)". This is only available in `predictions()`, and only for certain models.
3. Go through the model list to see where else it makes sense to backtransform. I don't actually know all the model types super well, so I prefer to be conservative until experts can weigh in.
4. Add a print message at the bottom of the printout with the type of each call.

**Comment by vincentarelbundock** [comment]
Thanks again for the push on this. Things have been addressed in the Github dev version. We now get:

- New `invlink(link)` type when we call `type` with a bad value.
- Printout of the type on output

To support `invlink(link)` in new models, all we need to do internally is add a row to `type_dictionary.R`, and maybe minor checks in `sanitize_type()`.

Note how `invlink(link)` is available for `predictions()` but not `slopes()`:

``` r
library(marginaleffects)

mod <- glm(vs ~ mpg + hp + wt, data = mtcars, family = binomial)

predictions(mod, type = "help")
# Error in sanitize_type(model = model, type = type, calling_function = "predictions"): 
# Assertion on 'type' failed: Must be element of set {'invlink(link)','response','link'}, but is 'help'.

slopes(mod, type = "help")
# Error in sanitize_type(model = model, type = type, calling_function = "slopes"): 
# Assertion on 'type' failed: Must be element of set {'response','link'}, but is 'help'.

avg_predictions(mod)
# 
#  Estimate Pr(>|z|)   S  2.5 % 97.5 %
#     0.153    0.121 3.0 0.0204  0.612
# 
# Columns: estimate, p.value, s.value, conf.low, conf.high 
# Type:  invlink(link)
```
