### ISSUE TITLE
Is Rcpp 1.0.10 necessary?

### ISSUE THREAD

**Issue by bwiernik** [vincentarelbundock/marginaleffects#899]
Hi there, in https://github.com/vincentarelbundock/marginaleffects/commit/3713ee1a1b1b85bd3cb4daeb3a94ab88d5b2d082, Rcpp (>= 1.0.10) was added as an Imports. 

An R server I'm working with runs Rcpp 1.0.8.3 and isn't scheduled to be updated for a while. Is Rcpp 1.0.10 specifically necessary, or could the dependency be moved back to at least 1.0.8.3? If it could be moved back (or if Rcpp could be made a Suggests instead of Imports), then I could use marginaleffects on the server. Otherwise, I can't use the package in this environment.

Thanks!

**Comment by vincentarelbundock** [comment]
You're right: it is not necessary (the Rcpp skeleton inserted that and I forgot to change it). https://github.com/vincentarelbundock/marginaleffects/commit/b23d304d9f0654b58bedc08b6523fd97f900ef2b should fix the problem and I plan to release to CRAN this week.

**Comment by bwiernik** [comment]
Awesome thanks!
