### ISSUE TITLE
marginal contrasts from Cox model

### ISSUE THREAD

**Issue by tbendixen** [vincentarelbundock/marginaleffects#902]
Thanks for an awesome package!

I can't seem to get `marginaleffects` to plot predictions or fitted values from a Cox model, fitted using the `survival::coxph()` command.

Below is an IPT weighted Cox model based on the `nhefs` data available at: https://remlapmot.github.io/cibookex-r/index.html#downloading-the-datasets

Ultimately, we'd like to plot marginal contrasts in survival probability across time for `qsmk==1` and `qsmk==0` from the marginal structural model `mod`, ideally with bootstrapped confidence intervals (since intervals from a `summary()` call is not considered valid when IPT weighting).

Thanks so much in advance!

```
library(readxl)
library(survival)

# load dataset
nhefs <- read_excel("NHEFS.xls")

# 120 months, because the follow-up period was ten years (10yrs*12 months)
# yrdth ranges from 83 to 92
nhefs$survtime <- ifelse(nhefs$death==0, 120,
                         (nhefs$yrdth-83)*12+nhefs$modth)

# define event 
nhefs$event <- nhefs$death

d <- nhefs

# estimation of denominator of ip weights
p.denom <- glm(qsmk ~ sex + race + age + I(age*age) + as.factor(education)
               + smokeintensity + I(smokeintensity*smokeintensity)
               + smokeyrs + I(smokeyrs*smokeyrs) + as.factor(exercise)
               + as.factor(active) + wt71 + I(wt71*wt71), family=binomial(), data=d)
d$pd.qsmk <- predict(p.denom, d, type="response")

# estimation of numerator of ip weights
p.num <- glm(qsmk ~ 1, data=d, family=binomial())
d$pn.qsmk <- predict(p.num, d, type="response")

# computation of estimated weights
d$sw.a <- ifelse(d$qsmk==1, d$pn.qsmk/d$pd.qsmk,
                 (1-d$pn.qsmk)/(1-d$pd.qsmk))

# fit of weighted Cox model
mod <- coxph(Surv(survtime, event) ~ qsmk, weights = d$sw.a, data = d)
```

**Comment by tbendixen** [comment]
A related feature that'd be really neat is a g-computation workflow for Cox models.

For instance, fit adjusted Cox model:

```
mod <- coxph(Surv(survtime, event) ~ qsmk + sex + race + age + age:age
                              + as.factor(education) + smokeintensity 
                              + smokeintensity:smokeintensity + smkintensity82_71 
                              + smokeyrs + smokeyrs:smokeyrs + as.factor(exercise) 
                              + as.factor(active) + wt71 + wt71:wt71, data = nhefs)
``` 

And then, to plot marginal contrasts in survival probability across time for `qsmk==1` and `qsmk==0` (again, ideally with bootstrapped confidence intervals), something like:

```
marginaleffects::plot_slopes(mod, variables = "qsmk", condition = "time")
```

**Comment by tbendixen** [comment]
> There is no variable named `time` in your `coxph()` formula, so of course you cannot plot predictions over a `time` variable that doesn't exist...

Right, sorry for being unclear. That line was just to show what the call might look like. The time indicator in the `coxph()` model is `survtime`, but this variable is not recognized as a variable against which predictions can be plotted.

**Comment by vincentarelbundock** [comment]
Thanks for the clarification. I’m sorry, but I guess I still don’t understand the problem:

``` r
library(survival)
library(marginaleffects)

nhefs <- read.csv("https://vincentarelbundock.github.io/Rdatasets/csv/causaldata/nhefs.csv")
nhefs$survtime <- ifelse(nhefs$death==0, 120, (nhefs$yrdth-83)*12+nhefs$modth)
nhefs$event <- nhefs$death
d <- nhefs
p.denom <- glm(qsmk ~ sex + race + age + I(age * age) + as.factor(education)
    + smokeintensity + I(smokeintensity * smokeintensity)
    + smokeyrs + I(smokeyrs * smokeyrs) + as.factor(exercise)
    + as.factor(active) + wt71 + I(wt71 * wt71), family = binomial(), data = d)
d$pd.qsmk <- predict(p.denom, d, type = "response")
p.num <- glm(qsmk ~ 1, data = d, family = binomial())
d$pn.qsmk <- predict(p.num, d, type = "response")
d$sw.a <- ifelse(d$qsmk == 1, d$pn.qsmk / d$pd.qsmk,
    (1 - d$pn.qsmk) / (1 - d$pd.qsmk))
mod <- coxph(Surv(survtime, event) ~ qsmk, weights = d$sw.a, data = d)

plot_predictions(mod, condition = "survtime")
```

![](https://i.imgur.com/e2sLiiL.png)

**Comment by vincentarelbundock** [comment]
> How to plot predictions by `qsmk`? 

This is very well document in `?plot_predictions`

```r
plot_predictions(mod, condition = c("survtime", "qsmk"))
```

But in this case the predictions are so similar that they are nearly impossible to distinguish visually.

> And if there are other uncertainty interval options.

Please read the vignette on "Bootstrap and Simulation". I spent *a lot* of time writing the vignettes and documentation to help new users in exactly cases like this.

Note that bootstrap intervals are not supported by plotting functions, but the output of the `inferences()` and `posterior_draws()` function are "tidy", so it should be trivial to plot them.

**Comment by vincentarelbundock** [comment]
[sorry, this sounded too harsh. I'm on my way out of the office, so answering quickly.]

**Comment by tbendixen** [comment]
Amazing. Obviously should've read the excellent documentation more closely. Thanks a ton for this - and for the package, etc.!
