### ISSUE TITLE
Is `mpg` or `gear` the variable used?

### ISSUE THREAD

**Issue by lorenzoFabbri** [vincentarelbundock/marginaleffects#906]
https://github.com/vincentarelbundock/marginaleffects/blob/d74d94e0b16f23df3135b60051b49b82714a6891/book/articles/comparisons.qmd#L367

**Comment by vincentarelbundock** [comment]
thanks, this looks like a typo

**Comment by vincentarelbundock** [comment]
Fixed in add7ebce0e8590da6db8e72470c0925878fa0d2c not on the website yet but will be fixed on next update.
