### ISSUE TITLE
Comparing marginal effects

### ISSUE THREAD

**Issue by gbiele** [vincentarelbundock/marginaleffects#909]
First thanks for making this great package available!!

Is there a way to compare marginal effects in 2 groups with the package?
For instance, I can do 
```
mod = lm(mpg ~ am * vs + cyl, data = mtcars)
ames = slopes(mod, variables = "am", by = "vs")
```
and `ames` will have average marginal effects split by `vs`. Now I would like to compare the marginal effects for  `vs==0`  vs `vs==1`. 

I tried to use the `hypotheses`  function, but is seems that this allows only to compare different terms.

Any hint is appreciated!

**Comment by gbiele** [comment]
Ahh,

is it really as simple as 

```
hypotheses(ame, hypothesis = c(1,-1))
```

**Comment by vincentarelbundock** [comment]
That's one way. I wrote a whole vignette exactly to answer questions like this one. Please see the website.
