### ISSUE TITLE
Translate book to Python

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/marginaleffects#914]
@LamAdr

The "book" that I published at https://marginaleffects.com is mostly for the `R` package. I would like to make it bilingual R/Python.

I did this work for one of the pages: 

* Live: https://marginaleffects.com/articles/marginaleffects.html
* Source: https://github.com/vincentarelbundock/marginaleffects/blob/main/book/articles/marginaleffects.qmd

Near the top of the page, you'll see that there's a R/Python button that allows users to change the language on the whole page. Then, you'll see that each block of code can be switched to either language.

After you have completed the `pycountrycode` issue that we have already discussed, I'd like you to spend some time to translate the most important chapters in the book to Python. This entails:

* Add a line to the header with  `include-after-body: toggle-tabs.html` (see the examples linked above).
* Modify each code block to the `panel-inset` format, like the one I use here: https://github.com/vincentarelbundock/marginaleffects/blob/main/book/articles/marginaleffects.qmd#L18
* Whenever you encounter a command that works in `R` but not `Python`, open an issue in the `pymarginaleffects` Github with a feature request.

Does that all makes sense? Are you OK with this?

**Comment by LamAdr** [comment]
Yes, that works.

**Comment by vincentarelbundock** [comment]
Thanks again for `pycountrycode`. Nice work!

I think we can move to this when you're ready.

**Comment by vincentarelbundock** [comment]
@LamAdr For information, I'm in the process of converting the website from Quarto to MkDocs. I think this should make it easier to support multi-language presentation in the long run, but I still have to figure out how to structure the code to display "tabs". 

I'm just giving you a heads-up about this: You can still work on translation, but work in separate scripts rather than put a lot of effort to integrate it directly in the vignettes. We can then integrate your scripts to the vignettes directly when I've figured out the website tab situation.

**Comment by LamAdr** [comment]
Good to know, thanks

**Comment by vincentarelbundock** [comment]
@LamAdr OK, the new website si up. you can modify the files in `vignettes/`, ideally starting with vignettes in the "Case Studies" section of the website: marginaleffects.com

**Comment by LamAdr** [comment]
Cool! Looks great
