### ISSUE TITLE
Improve machine learning vignette

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/marginaleffects#920]
- [ ] Explicit and clear distinction between ALE and PDP, with examples
    + https://christophm.github.io/interpretable-ml-book/ale.html
    + https://hastie.su.domains/Papers/pdp_zhao.pdf (see Section 2)
    + https://arxiv.org/pdf/1612.08468.pdf
- [x] Classification task. May not work for `mlr3` or `tidymodels` when the underlying engine is not supported as a standalone model.
- [x]  Better error message when bad type for `tidymodels`

**Comment by vincentarelbundock** [comment]
https://hastie.su.domains/Papers/pdp_zhao.pdf

**Comment by etiennebacher** [comment]
Hi, there are also two typos in the last plot of the vignette:

* Celcius -> Celsius
* title is "Black: random forest predictions. Green: LOESS smoother" but the LOESS is actually in orange

**Comment by vincentarelbundock** [comment]
```r
library(tidymodels)
library(marginaleffects)

# broken
workflow(factor(gear) ~ hp * mpg, multinom_reg()) |>
  fit(data = mtcars)  |>
  get_vcov()

# works
set_engine(multinom_reg(), "nnet") |>
  fit(factor(gear) ~ mpg * hp, data = mtcars) |>
  get_vcov()

```

**Comment by vincentarelbundock** [comment]
Thanks @etiennebacher Should be fixed now
