### ISSUE TITLE
slopes() and plot_predictions() don't seem to match?

### ISSUE THREAD

**Issue by strengejacke** [vincentarelbundock/marginaleffects#921]
Hi Vincent,
not sure if this actually is a bug, but it looks strange... I cannot share the data I used here, maybe I find a reprex. But perhaps even the visuals are enough? 

When I look at the plot, I see different "slopes" for this glm, some positive, some negativ. But `slopes()` returns estimates close to 0 - is this correct? Am I missing something?

``` r
library(marginaleffects)

load("d:/mail/SynologyCloud/DL/Publikationen (Analysen)/2023 NAKO/nako.RData")

nako$phq9_dicho <- nako$a_emo_phq9_cut10
nako$SNI <- as.factor(nako$a_sn_sni)

m2 <- glm(
  phq9_dicho ~ SNI * lifetime_de + basis_age + education + gender,
  data = nako,
  family = binomial
)

focal <- c("lifetime_de", "SNI")
nd <- ggeffects::new_data(m2, focal)

plot_predictions(m2, newdata = nd, by = focal, type = "response")
```

![](https://i.imgur.com/KwQgssh.png)

``` r
slopes(m2, newdata = nd, variables = focal[1], by = focal[2], type = "response")
#> 
#>         Term    Contrast SNI  Estimate Std. Error      z Pr(>|z|)   S     2.5 %
#>  lifetime_de mean(dY/dX)   1  0.001070   0.000412  2.599  0.00934 6.7  0.000263
#>  lifetime_de mean(dY/dX)   2  0.000193   0.000211  0.914  0.36070 1.5 -0.000221
#>  lifetime_de mean(dY/dX)   3 -0.000239   0.000227 -1.055  0.29124 1.8 -0.000684
#>  lifetime_de mean(dY/dX)   4  0.000425   0.000595  0.714  0.47520 1.1 -0.000742
#>    97.5 %
#>  0.001877
#>  0.000607
#>  0.000205
#>  0.001592
#> 
#> Columns: term, contrast, SNI, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted_lo, predicted_hi, predicted 
#> Type:  response
```

<sup>Created on 2023-10-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by vincentarelbundock** [comment]
Hmmm, just eyeballing this, it looks perfectly fine to me.

Basically all the lines look flat, which means the slopes should be close to zero. The confidence interval at the extreme left covers basically all the points: an inaccurate ballpark, which suggests that predictions are never different, regardless the x-axis values.

The only difference is the top line, which clearly slopes upward. That line is associated to a factor level where the slope is significant and positive. Again that seems well reflected in the numeric results.

I'm writing this quickly on the bus, so may be missing something, but it all looks fine at first glance.

**Comment by strengejacke** [comment]
ok, the the lines / slopes are not "steep" enough to produce larger estimates for `slopes()`? Maybe the numeric results are "misleading" because we have logistic regression here... I'd say then we could close this issue.

**Comment by vincentarelbundock** [comment]
Exactly. A slope is just how we learned it at school: rise-over-run. Here, even if it's a GLM, it turns out that the prediction curves are nearly linear. So we can ballpark it easily:

There's a 100 range on the X-axis, and the estimated slope for SNI=4 is 0.000425. Multiply that by 100 and the predictions should increase by about 0.04, which is about the vertical difference between the start and the end of the purple line.

But that slope is so close to flat that it is indistinguishable from zero (which would show a perfectly flat line)

**Comment by strengejacke** [comment]
One more question: the slopes look less pronounced when plotting on the link-scale - but how is the response scale calculated? On the link scale, the 4th category has the largest slope, but no more on the response scale - is this due to transformation?

``` r
library(marginaleffects)

load("d:/mail/SynologyCloud/DL/Publikationen (Analysen)/2023 NAKO/nako.RData")

nako$phq9_dicho <- nako$a_emo_phq9_cut10
nako$SNI <- as.factor(nako$a_sn_sni)

m2 <- glm(
  phq9_dicho ~ SNI * lifetime_de + basis_age + education + gender,
  data = nako,
  family = binomial
)

focal <- c("lifetime_de", "SNI")
nd <- ggeffects::new_data(m2, focal)

plot_predictions(m2, newdata = nd, by = focal, type = "link")
```

![](https://i.imgur.com/rWtv0RS.png)

``` r

slopes(m2, newdata = nd, variables = focal[1], by = focal[2], type = "link")
#> 
#>         Term    Contrast SNI Estimate Std. Error      z Pr(>|z|)   S    2.5 %
#>  lifetime_de mean(dY/dX)   1  0.00555    0.00219  2.536   0.0112 6.5  0.00126
#>  lifetime_de mean(dY/dX)   2  0.00149    0.00165  0.906   0.3651 1.5 -0.00174
#>  lifetime_de mean(dY/dX)   3 -0.00284    0.00259 -1.096   0.2730 1.9 -0.00791
#>  lifetime_de mean(dY/dX)   4  0.01169    0.01940  0.603   0.5467 0.9 -0.02633
#>   97.5 %
#>  0.00984
#>  0.00472
#>  0.00224
#>  0.04972
#> 
#> Columns: term, contrast, SNI, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted_lo, predicted_hi, predicted 
#> Type:  link
slopes(m2, newdata = nd, variables = focal[1], by = focal[2], type = "response")
#> 
#>         Term    Contrast SNI  Estimate Std. Error      z Pr(>|z|)   S     2.5 %
#>  lifetime_de mean(dY/dX)   1  0.001070   0.000412  2.599  0.00934 6.7  0.000263
#>  lifetime_de mean(dY/dX)   2  0.000193   0.000211  0.914  0.36070 1.5 -0.000221
#>  lifetime_de mean(dY/dX)   3 -0.000239   0.000227 -1.055  0.29124 1.8 -0.000684
#>  lifetime_de mean(dY/dX)   4  0.000425   0.000595  0.714  0.47520 1.1 -0.000742
#>    97.5 %
#>  0.001877
#>  0.000607
#>  0.000205
#>  0.001592
#> 
#> Columns: term, contrast, SNI, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted_lo, predicted_hi, predicted 
#> Type:  response
```

<sup>Created on 2023-10-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by vincentarelbundock** [comment]
For `predictions()` we just call `stats::predict(model, type = "response")` internally.

For `slopes()`, we essentially do:

```r
(predict(mod, type = "response", newdata = hi) - predict(mod, type="response", newdata = lo)) / eps
```

Where the `X` variable has been incremented by `eps` in the `hi` dataset.

**Comment by strengejacke** [comment]
ok, got it. thanks!
