### ISSUE TITLE
avg_comparisons object attributes include data and original model fit

### ISSUE THREAD

**Issue by lachanskim** [vincentarelbundock/marginaleffects#924]
Hi, I am wondering if it it would be possible to add a "lean" option to the avg_comparisons function that would prevent the copying of the original code and data to the metadata of the function's output. As things stand now, it appears to copy the original model and data in its attribute metadata. It would great when using the avg_comparisons function to not have this as a default output.

**Comment by vincentarelbundock** [comment]
Thanks. This is an interesting suggestion.

I would not want this to be the default, because the metadata is essential for boostrapping, simultation-based inference, equivalence tests, and other functionality related to `hypotheses()` and `inferences()`. 

That said, I would consider adding a global option for this (we should workshop some names). Then, we could add a bit of code at the end of each of the main functions to check the global option (`getOption()`) and add --or not-- the attributes as appropriate.

TBH, this is low priority for me, but I'd be happy to review a Pull Request if you want to submit one.

**Comment by lachanskim** [comment]
Thank you. It's essentially impossible to use avg_comparisons directly in "big data" settings, e.g. when working with U.S. Censuses because the default of copying the dataset on each hypothesis test rapidly exhausts RAM. I think your approach is sensible.

**Comment by vincentarelbundock** [comment]
Ah yeah, that makes sense. This seems like a good idea.

**Comment by vincentarelbundock** [comment]
BTW, I don't actually recommend using `hypotheses()`. You should use the `hypothesis` argument instead, which should be much more memory efficient.

**Comment by lachanskim** [comment]
Yes, I have been doing that. The problem I run into is that the default behavior of avg_comparisons is to generate way more hypotheses than I need. I have a StackOverflow on this issue here:

https://stats.stackexchange.com/questions/628406/compute-standard-error-in-the-group-difference-in-marginal-effect

**Comment by vincentarelbundock** [comment]
See my response and the documentation. It takes a long time because you requested many comparisons, but you can also just request one comparison.

**Comment by lachanskim** [comment]
Thank you. I've looked at the documentation closely already and your answer is not quite what I need. See my comment. I suspect there is a solution using the matrix formulation - which I have been looking into this afternoon.

**Comment by lachanskim** [comment]
Specifically, using the `mtcars` dataset, I would like to be able to do something like the following:

```
dat <- transform(mtcars, gear = factor(gear))
mod <- lm(mpg ~ cyl * gear * am, data = dat)
avg_comparisons(mod,
            variables = "gear",
            by = "am",
            hypothesis = list("b1 = b2", "b3 = b4"))
```

**Comment by vincentarelbundock** [comment]
Got it. The latest version of `marginaleffects` can do this: You'll need to install from Github and restart R.

The only difference in your code is that you have to switch the  `list()` in your last line of code to `c()`.

**Comment by lachanskim** [comment]
now THAT is cool. Is there anything I can do to give you a cite?

**Comment by vincentarelbundock** [comment]
Great! Yeah sure, citation is always nice. You can get the bibtex of any R package with:


`citation("marginaleffects")`

**Comment by lachanskim** [comment]
One last question: is there a preferred way of stripping the attributes from the avg_comparisons object? Thus far, I have been relying on a side effect of data.table conversion to eliminate them and work only with the columns, but I was wondering if you had anything you preferred. Thanks

**Comment by vincentarelbundock** [comment]
just delete the attributes
