### ISSUE TITLE
z statistics and p values in marginaleffects

### ISSUE THREAD

**Issue by cmagelssen** [vincentarelbundock/marginaleffects#928]
Thanks for a great package.

I opened this issue to understand the differences between the t and z statistics derived from the models below. The two approaches below give the same answer but offer different answers for a model on my data. The beta coefficient is the same, but the z statistic and p values are dissimilar. Consequently, I must understand WHY they are different, if this difference is essential, and how I should proceed. I hope you can help 

Se the workflow below: 

mod <- lm(mpg ~ factor(cyl), data = mtcars)

summary(mod)

// This models reveals that the estimated difference between the reference group and factor(cyl):
//Coefficients:
//    Estimate Std. Error t value Pr(>|t|)    
//   (Intercept)   26.6636     0.9718  27.437  < 2e-16 ***
//   factor(cyl)6  -6.9208     1.5583  -4.441 0.000119 ***
//   factor(cyl)8 -11.5636     1.2986  -8.905 8.57e-10 ***

avg_comparisons(mod, variables = list(cyl = "revreference"))

// This reveals the same beta and the same p value in this case. 

//Term Contrast Estimate Std. Error    z Pr(>|z|)    S 2.5 % 97.5 %
//  cyl    4 - 6     6.92       1.56 4.44   <0.001 16.8  3.87   9.98
//  cyl    4 - 8    11.56       1.30 8.90   <0.001 60.7  9.02  14.11

**Comment by vincentarelbundock** [comment]
Yes, this is a difference between \(t\) and \(Z\). Just use the `df` argument:

``` r
library(marginaleffects)
mod <- lm(mpg ~ factor(cyl), data = mtcars)

summary(mod)$coefficients[, "Pr(>|t|)"]
#  (Intercept) factor(cyl)6 factor(cyl)8 
# 2.688358e-22 1.194696e-04 8.568209e-10

avg_comparisons(mod, df = 29)$p.value
# [1] 1.194696e-04 8.568210e-10
```

**Comment by cmagelssen** [comment]
Awesome!

So for a glmer() or lmer() model I can use the following to get the correct degrees of freedom from the model? 
slopes(model, df = insight::get_df(model))
