### ISSUE TITLE
Feature Request: Compute Effect Contrasts Across a Continuous Covariate

### ISSUE THREAD

**Issue by lachanskim** [vincentarelbundock/marginaleffects#929]
It is common for sociologists to investigate the effect of a treatment across a continuous covariate. For instance, I might be interested in the effect of free college on income at age 30 across different levels of parental wealth. Currently, when the covariate is defined dichotomously, I can do this easily via the comparisons command:

```
comparisons(model, variables = "treatment", by = "covariate")
```
But I don't see an easy way to do this with a continuous covariate. Natural comparisons would be, for instance, the 90-10 difference in effect or a 2sd command. When the treatment is continuous, there are many powerful one-liners in the documentation like "2sd" and so on, but nothing that I could find when comparing treatment effects across a continuous covariate. It might be helpful to include a `bycontrast` option when the covariate is continuous porting the same built in contrasts for continuous treatment effects when the group across which one wants to contrast treatment effects is also defined continuously.

**Comment by vincentarelbundock** [comment]
Sorry, I don't understand the specific feature requests. Could you supply a more specific example, ideally with some working code and public data?

**Comment by lachanskim** [comment]
Sure, with `mtcars`, suppose I would like to estimate the effect of `gear` on `mpg` across the interquartile range of `wt`. I would like to be able to write something like the following:

```
mod <- lm(mpg ~ gear*wt, mtcars)
comparisons(mod, variables = "gear", by = "wt", bycontrast = "iqr")
```

which would give me the effect of a unit `gear` change on `mpg` across the interquartile range of `wt`.

**Comment by vincentarelbundock** [comment]
Got it. 

You can already send this by using the `datagrid()` in the `newdata` argument.

**Comment by vincentarelbundock** [comment]
And if you want to marginalize over the empirical distribution of other variables, try `datagridcf()`

**Comment by lachanskim** [comment]
Thanks `datagridcf()` was what I was looking for.
