### ISSUE TITLE
Support: `glinternet`

### ISSUE THREAD

**Issue by connorjmccabe** [vincentarelbundock/marginaleffects#934]
Hello,

I would like to request compatibility of marginaleffects with the glinternet package (group-lasso interaction networks):

https://cran.r-project.org/web/packages/glinternet/index.html

I am able to use the predict() function successfully with glinternet output but it will not translate to marginaleffects. If this is at all possible that would be great.

Connor

**Comment by vincentarelbundock** [comment]
Thanks for the suggestion!

Does it have a formula interface or does it only accept matrices as input? From the docs, it looks like the latter, in which case direct support won't be possible.

If that's the case, then it might still be possible to use via tidymodels, which offers a formula interface to glmnet and other similar models.

See the machine learning vignette (and use the dev version of marginaleffects)

**Comment by vincentarelbundock** [comment]
closing this because I don't see anything actionable, but feel free to keep the discussion going if you have new insights/proposals.
