### ISSUE TITLE
Support for objects of class `mvgam`

### ISSUE THREAD

**Issue by nicholasjclark** [vincentarelbundock/marginaleffects#937]
Hi Vincent, thanks for such a detailed and wonderful package. I maintain a package, currently only hosted on GitHub, for fitting Bayesian GAMs and Dynamic GAMs (https://github.com/nicholasjclark/mvgam). I have implemented functions within the package that directly allow most `marginaleffects` functions to work (https://github.com/nicholasjclark/mvgam/blob/master/R/marginaleffects.mvgam.R). The only aspect that needs to be considered is that `predict.mvgam` accepts an argument `process_error`, so it would be great to add this to the library of supported arguments. If this is something you're interested in then please let me know what I can do to help expedite.

All the best

**Comment by nicholasjclark** [comment]
Thanks very much for the response @vincentarelbundock. Yes I should have specified, all of the functions work perfectly fine at the moment so I have no issues there. I am currently using the global options trick so all good there. I was just thinking it would be nice to avoid the warnings about unsupported arguments, so I was hoping you could update the `sanity_dots` when you get a chance. Thanks again for all the wonderful support, I'm very excited to have this functionality available

**Comment by nicholasjclark** [comment]
Wonderful thanks so much Vincent. Cheers

**Comment by nicholasjclark** [comment]
Hi again @vincentarelbundock, I just have another very minor request (when you have time). Is it possible to allow different prediction types for objects of class `mvgam`? In addition to `type = 'response'` and `type = 'link'`, I'd like to have the following types supported:

- `type = 'expected'`
- `type = 'detection'`
- `type = 'latent_N'`

Thanks very much for all your help and for the wonderful functionality of `marginaleffects`

**Comment by vincentarelbundock** [comment]
Thanks. I can't look into this right now, but just to be sure, those are types supplied by the original package, and they all return standard vectors?

**Comment by nicholasjclark** [comment]
No worries thanks @vincentarelbundock. Yes these are all supported and all return vectors in the package. All the best

**Comment by vincentarelbundock** [comment]
Sounds good. Should be very easy then. The start of semester is kicking my butt, so I won't get around to this in the very near term, but for reference, the only two steps need should be:

1. Add two lines in the appropriate location here (note that the order matters, the first one is always default, so typically we want "response" or something similarly standard first): https://github.com/vincentarelbundock/marginaleffects/blob/main/R/type_dictionary.R
2. Add a couple simple tests in the `inst/tinytest/test-mvgam.R` folder. 

I would happily push Merge if you put together a pull request, but can also take care of this in the coming weeks.

**Comment by nicholasjclark** [comment]
Thanks @vincentarelbundock. Ok I've gone ahead and created a PR for you to review. No rush of course!
