### ISSUE TITLE
Issues in vignettes for matching and weighting 

### ISSUE THREAD

**Issue by ngreifer** [vincentarelbundock/marginaleffects#938]
First, for matching and weighting, users MUST use robust standard errors. It isn't optional for these methods. Just add `vcov = "HC3"` for both. For matching without replacement (which I would say is more common), you need to adjust for pair membership using `vcov = ~subclass`. I don't think you need to go into great detail on this but it is important to have the right code.

For IPW, the ATE weights are actually defined as follows:
```r
w <- ifelse(treat == 1, 1/ps, 1/(1-ps))
```
and if you are estimating the ATT, the weights are
```r
w <- ifelse(treat == 1, 1, ps/(1-ps))
```
You also must not subset the dataset in computing the comparisons if you are estimating the ATE. IPW is most often used to estimate the ATE, so I would recommend using the ATE as the example with te correct formula for the weights and no subsetting (and also the robust SE as mentioned above).

This is a different scenario than we saw earlier, where IPW was used to adjust for censoring, in which case you estimate IPCW weights using the formula you used and subset the data to just those observed. You can have such an example, but it requires different syntax from the usual IPW for treatment effect estimation. Right now it looks like you combined some code used for treatment effect estimation with other code used for censoring. Users can also look at the `WeightIt` vignette for instructions on how to do analyses with weighting.

**Comment by vincentarelbundock** [comment]
Thanks a lot for the review, I really appreciate it.

This errors are a tiny bit embarrassing. Maybe I shouldn't rush so much to get stuff out. Oh well...

I think this fixes most of the issues: https://github.com/vincentarelbundock/marginaleffects/commit/eaf4b2bbc80c72f1c423d0506e2eb6dcd23d6f92

One question: Is the HT code OK:

```r
ht <- \(hi, lo, w, newdata) {
    (sum(hi * w) / nrow(newdata)) - (sum(lo * w) / nrow(newdata))
}

comparisons(mod,
    comparison = ht,
    variables = "treat",
    wts = "wts",
    vcov = "HC3")
```

**Comment by ngreifer** [comment]
Yes, the HT code looks fine to me.
