### ISSUE TITLE
Feature request: Plotting should allow a fourth variable in `condition` through `facet_grid`

### ISSUE THREAD

**Issue by Tristan-Siegfried** [vincentarelbundock/marginaleffects#939]
For ease of discussion I will only mention `plot_predictions`, but the comment generalizes to other plotting functions as well.

Currently in `plot_predictions` the `condition` argument takes a list of at most 3 variables on which to condition the predictions, which are mapped as follows: 1: x-axis. 2: color/shape. 3: facets. 
And more specifically the third is mapped to `facet_wrap`.

However, it is possible to provide a nice visualization with a fourth possible variable in `condition` if we visualize the third variable as different columns of a `facet_grid` and visualize the fourth as different rows of that `facet_grid`.

In light of this, I think the following behavior would be an improvement:

1. When 3 variables are passed to `condition` then the current approach is used of passing the third through to `facet_wrap`
2. When 4 variables are passed to `condition` then `facet_grid` is used: the 3rd variable is passed to the `cols` argument of `facet_grid` and the fourth is passed to the `rows` argument of `facet_grid`.

**Comment by vincentarelbundock** [comment]
Yeah, I think that sounds like a nice improvement. I'll be very busy at work in the near future so probably won't have time, but would gladly review a PR if you or anyone else volunteers.

**Comment by vincentarelbundock** [comment]
already merged. thanks again for this.
