### ISSUE TITLE
Check `quantreg::rq` standard errors vs. Stata

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/marginaleffects#94]
@marco-mendoza-avina 

Could you try looking at the basic `rq` coefficients and standard errors in R and Stata to see if they match? The marginal effects match, but not the standard errors, which makes me think that the baseline standard errors for coefficients might be different.

If they are indeed different, could you read through both packages' documentations to see exactly how they describe the types of standard errors they use? Perhaps there's an option we can tweak to get matching results (we're not that far off).

Thanks!

PS: Do you get notifications when I tag you here, or should I email?

**Comment by vincentarelbundock** [comment]
Also, if you have time, could you please run the same check on the `nnet::multinom` models?

**Comment by marco-mendoza-avina** [comment]
I will look into all of this. Thanks!

**Comment by marco-mendoza-avina** [comment]
Just checked, and the default SE returned by `quantreg:rq` do not match those returned by Stata.

I get the same standard errors in Stata by adding `vce(robust)`. 

However, the confidence intervals still don't match. Is this a big deal? I can direct you to the details on the rank inversion method if you need them.

If the CIs are not a problem, should I simply redo the Stata test using the robust SE?

**Comment by vincentarelbundock** [comment]
Thanks, we only need the SE, so if you could update just those it would be wonderful

**Comment by vincentarelbundock** [comment]
Thanks again for this. I updated the files, so no need to do anything about this now.

`multinom` still doesn't work, but it seems like a more complicated problem because the standard errors match for raw coefficients but not margins.
