### ISSUE TITLE
Getting warning when supplying using numeric `variables`

### ISSUE THREAD

**Issue by ngreifer** [vincentarelbundock/marginaleffects#943]
I'm getting the following message when doing G-computation:
```
## Warning: The `treat` variable is treated as a categorical (factor) variable, but the original data is of class integer. It is safer and faster to convert such variables to factor before
##   fitting the model and calling `slopes` functions.
##   
##   This warning appears once per session.
```
You can see it in the `MatchIt` [vignette](https://kosukeimai.github.io/MatchIt/articles/MatchIt.html#estimating-the-treatment-effect). Note sure what's going on, I'm not calling `slopes()`.

**Comment by vincentarelbundock** [comment]
Thanks, should be fixed in 0.16.0.9004
