### ISSUE TITLE
Support gamm4

### ISSUE THREAD

**Issue by ASKurz** [vincentarelbundock/marginaleffects#947]
Regarding https://github.com/vincentarelbundock/marginaleffects/issues/49, I saw `gamm4` models under the listing of **Supported by other packages**, but not elsewhere. In case it's necessary, I'm formally requesting support for models fit with `gamm4()`.

**Comment by vincentarelbundock** [comment]
I don't know this package, but tried to run the help file example and I get this error when calling `predict()` on the resulting object:

```r
Error in UseMethod("predict") : 
  no applicable method for 'predict' applied to an object of class "list"
```

How would one go about making predictions based on this object?

`vcov()` doesn't seem to work either. I guess it's a list of 2 models, but I'm not sure what this is.

**Comment by ASKurz** [comment]
Say my `gamm4()` model is named `my_fit`, I can get basic predictions from `predict()` like so:

```
predict(my_fit$gam)
```

**Comment by ASKurz** [comment]
I run into the same basic issue with multilevel GAMs fit with `mgcv::gamm()`. `gam()` models work; `gamm()`models don't.

**Comment by ASKurz** [comment]
To be more clear, here's a quick example of my use case with our old favorite the `ChickWeight` data.

```{r}
# load packages
library(lme4)
library(mgcv)
library(marginaleffects)

# fit conditional linear growth model
chick1 <- lmer(
  weight ~ 1 + Time + Diet + Time:Diet + (1 + Time | Chick),
  data = ChickWeight)

# fit conditional GAM growth model
chick2 <- gamm(
  weight ~ 1 + Diet + s(Time, by = Diet, k = 5),
  random = list(Chick = ~1),
  family = gaussian,
  data =  ChickWeight,
  method = "REML"
  )

# this works
avg_comparisons(chick1, variable = "Diet")

# this does not work
avg_comparisons(chick2, variable = "Diet")
```

**Comment by vincentarelbundock** [comment]
@Nadjim10 do you want to try adding support for this model. The structure of the object is a bit different than for other models, as you can see from the discussion above.

Here is the tutorial to add models: https://marginaleffects.com/articles/extensions.html
