### ISSUE TITLE
`comparisons()` for pooled and paired tests lead to identical results

### ISSUE THREAD

**Issue by MrJerryTAO** [vincentarelbundock/marginaleffects#954]
I have a conceptual mystery of whether 'comparisons()' gives pooled or paired tests. For me, `comparisons(..., comparison = "difference")` to `comparisons(..., comparison = "differenceavg")` is as `t.test(..., paired = TRUE)` to `t.test(..., paired = FALSE)`. However, `comparisons()` produces identical output in both argument settings, corresponding to the standard error of the coefficient. 
```r
summary(Model_Temp <- lm(
  Petal.Width ~ Sepal.Length + Species, data = iris))
"                  Estimate Std. Error t value Pr(>|t|)    
(Intercept)       -0.47940    0.15574  -3.078  0.00249 ** 
Sepal.Length       0.14491    0.03064   4.730 5.25e-06 ***
Speciesversicolor  0.94524    0.04769  19.820  < 2e-16 ***
Speciesvirginica   1.55076    0.06174  25.118  < 2e-16 ***
Residual standard error: 0.1912 on 146 degrees of freedom
Multiple R-squared:  0.9383,	Adjusted R-squared:  0.9371 
F-statistic: 740.5 on 3 and 146 DF,  p-value: < 2.2e-16"
comparisons(Model_Temp, variables = "Sepal.Length", by = TRUE)
"         Term Contrast Estimate Std. Error    z Pr(>|z|)    S  2.5 % 97.5 %
 Sepal.Length       +1    0.145     0.0306 4.73   <0.001 18.8 0.0849  0.205"
comparisons(Model_Temp, variables = "Sepal.Length", comparison = "differenceavg")
"         Term Contrast Estimate Std. Error    z Pr(>|z|)    S  2.5 % 97.5 %
 Sepal.Length mean(+1)    0.145     0.0306 4.73   <0.001 18.8 0.0849  0.205"
comparisons(Model_Temp, variables = "Sepal.Length", comparison = function(hi, lo) 
  mean(hi) - mean(lo))
"         Term Contrast Estimate Std. Error    z Pr(>|z|)    S  2.5 % 97.5 %
 Sepal.Length       +1    0.145     0.0306 4.73   <0.001 18.8 0.0849  0.205"
```
Paired tests shrink standard errors of the difference due to positive correlation between two measurements of the same subject. Therefore, I would expect that the second and third uses of `comparisons()` in the following case to be identical and give larger standard errors compared with the first use, as `comparison = "differenceavg"` and `comparison = function(hi, lo) mean(hi) - mean(lo)` should break subject-to-subject match and treat two versions of adjusted data as two independent samples. Yet they all give identical output. 
```r
comparisons(Model_Temp, variables = list(Sepal.Length = data.frame(
  lo = iris$Sepal.Length, high = iris$Sepal.Length + 1 + rnorm(
    n = length(iris$Sepal.Length), sd = 10))), by = TRUE)
set.seed(1)
comparisons(Model_Temp, variables = list(Sepal.Length = data.frame(
  lo = iris$Sepal.Length, high = iris$Sepal.Length + 1 + rnorm(
    n = length(iris$Sepal.Length), sd = 10))), comparison = "differenceavg")
set.seed(1)
comparisons(Model_Temp, variables = list(Sepal.Length = data.frame(
  lo = iris$Sepal.Length, high = iris$Sepal.Length + 1 + rnorm(
    n = length(iris$Sepal.Length), sd = 10))), comparison = function(hi, lo) 
      mean(hi) - mean(lo))
"         Term Contrast Estimate Std. Error    z Pr(>|z|)    S 2.5 % 97.5 %
 Sepal.Length   manual    0.176     0.0373 4.73   <0.001 18.8 0.103   0.25"
```
Is this an intended behavior? Or is it a bug that should be fixed?

**Comment by vincentarelbundock** [comment]
Yes, this is intended, and what the function does under the hood is documented with examples of manual calculation on the website.

Sorry, I don't have time to engage more on this.

**Comment by MrJerryTAO** [comment]
OK. Based on results from `avg_predictions()` built from two versions of data, I believe the output of `comparisons(..., comparison = "differenceavg")` and `comparisons(..., comparison = function(hi, lo) mean(hi) - mean(lo))` should give a standard error of `0.04330727` as below, instead of `0.0373` reported in my last comment. A two-independent-sample as `mean(hi) - mean(lo)` should have a higher uncertainty than a paired-sample test as `mean(hi - lo)`. Do you agree? 

```r
avg_predictions(Model_Temp, newdata = iris)
" Estimate Std. Error    z Pr(>|z|)   S 2.5 % 97.5 %
      1.2     0.0156 76.8   <0.001 Inf  1.17   1.23"
set.seed(1)
avg_predictions(Model_Temp, newdata = iris %>% mutate(
  Sepal.Length = Sepal.Length + 1 + rnorm(
    n = length(iris$Sepal.Length), sd = 10)))
" Estimate Std. Error  z Pr(>|z|)     S 2.5 % 97.5 %
     1.38     0.0404 34   <0.001 840.3   1.3   1.46"
sqrt(0.0156^2 + 0.0404^2) # 0.04330727
```

**Comment by vincentarelbundock** [comment]
No
