### ISSUE TITLE
Adding support for passing the "exclude" argument to `predict.gam` models from mgcv

### ISSUE THREAD

**Issue by eric-pedersen** [vincentarelbundock/marginaleffects#955]
The functions `predict.gam` and `predict.bam` in mgcv both take an argument, `exclude` that lets you specify smooth terms that you want to omit from predictions for a model (effectively setting those terms to zero). 

Currently, functions like `avg_comparisons` will pass on the `exclude` argument to `predict.gam` if the model was estimated using the `bam` function but not the `gam` function (see sample code  below demonstrating this issue; I am currently running `marginaleffects` v 0.16.0).

Would it be possible to enable passing this argument for `gam` models as well as `bam` models? There are a range of families (e.g. Gaussian location-scale models) that can only be estimated using `gam`, not `bam`. 

## Example code: 

```r
library(mgcv)
library(marginaleffects)
set.seed(1)

dat <- gamSim(1,n=50,dist="binary",scale=.33)

mod_gam <- gam(y~s(x0)+s(x1),family=binomial,
              data=dat,method="REML")
mod_bam <- bam(y~s(x0)+s(x1),family=binomial,
               data=dat,method="REML")

#this works; creates average comparisons after zeroing out the s(x0) smoother
avg_comparisons(mod_bam, exclude = "s(x0)", variables = "x1")

#this should give the same values, but does not
avg_comparisons(mod_gam, exclude = "s(x0)", variables = "x1")
```

Running the last line of code gives the following warning:
  ```
  Warning message:
  These arguments are not supported for models of class `gam`: exclude.
```

**Comment by vincentarelbundock** [comment]
Thanks for the report @eric-pedersen. Unknown arguments always trigger this warning unless they appear on the “white list”. I’ve added `exclude` to the white list in the development version of the package on Github.

But normally, all arguments — including unknown ones — are always passed to the `predict()` function, so even if an argument triggers a warning, it should still “work”.

I don’t have a ton of experience with these models, but maybe you could tell me if it works now? As you can see, the results are very slightly different:

``` r
library(mgcv)
library(marginaleffects)
set.seed(1)

dat <- gamSim(1, n = 50, dist = "binary", scale = .33)

mod_gam <- gam(y ~ s(x0) + s(x1),
    family = binomial,
    data = dat, method = "REML")

avg_comparisons(mod_gam, exclude = "s(x0)", variables = "x1") |>
    print(digits = 7)
# 
#  Term Contrast  Estimate Std. Error        z  Pr(>|z|)   S      2.5 %    97.5 %
#    x1       +1 0.2806759   0.251515 1.115941 0.2644474 1.9 -0.2122844 0.7736363
# 
# Columns: term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high 
# Type:  response

avg_comparisons(mod_gam, variables = "x1") |>
    print(digits = 7)
# 
#  Term Contrast  Estimate Std. Error        z  Pr(>|z|)   S      2.5 %    97.5 %
#    x1       +1 0.2810938  0.2509289 1.120213 0.2626231 1.9 -0.2107178 0.7729053
# 
# Columns: term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high 
# Type:  response
```

**Comment by eric-pedersen** [comment]
Thanks for the fast turnaround! Great to hear that this was working already; the differences I was observing before must just have been due to numerical differences between `bam` and `gam` estimates. I'm just playing around with the code now, but it seems to be working fine on my end.
