### ISSUE TITLE
Argument `df` has no impact for `avg_predictons()`

### ISSUE THREAD

**Issue by strengejacke** [vincentarelbundock/marginaleffects#957]
The `df` argument does not change the output - I thought this would change the CI?

``` r
data(efc, package = "ggeffects")
efc$grp <- datawizard::to_factor(efc$e15relat)
efc$e42dep <- datawizard::to_factor(efc$e42dep)
efc$c172code <- datawizard::to_factor(efc$c172code)
fit <- lme4::lmer(neg_c_7 ~ c12hour + e42dep + c161sex + c172code + (1 | grp), data = efc)
at_list <- list(
  c12hour = c(10, 20, 30, 40),
  c172code = levels(efc$c172code)
)
marginaleffects::avg_predictions(fit, variables = at_list, df = Inf)[c("conf.low", "conf.high")]
#> 
#>  CI low CI high
#>    10.7    12.2
#>    11.0    12.2
#>    11.4    12.9
#>    10.8    12.2
#>    11.1    12.2
#>    11.5    12.9
#>    10.9    12.3
#>    11.2    12.3
#>    11.6    13.0
#>    10.9    12.3
#>    11.2    12.3
#>    11.6    13.1
#> 
#> Columns: conf.low, conf.high
marginaleffects::avg_predictions(fit, variables = at_list, df = 20)[c("conf.low", "conf.high")]
#> 
#>  CI low CI high
#>    10.7    12.2
#>    11.0    12.2
#>    11.4    12.9
#>    10.7    12.2
#>    11.1    12.2
#>    11.4    13.0
#>    10.8    12.3
#>    11.1    12.3
#>    11.5    13.1
#>    10.9    12.4
#>    11.2    12.4
#>    11.6    13.1
#> 
#> Columns: conf.low, conf.high
```

<sup>Created on 2023-11-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
Same seems to be true for `vcov`:

``` r
data(efc, package = "ggeffects")
efc$grp <- datawizard::to_factor(efc$e15relat)
efc$e42dep <- datawizard::to_factor(efc$e42dep)
efc$c172code <- datawizard::to_factor(efc$c172code)
fit <- lme4::lmer(neg_c_7 ~ c12hour + e42dep + c161sex + c172code + (1 | grp), data = efc)
at_list <- list(
  c12hour = c(10, 20, 30, 40),
  c172code = levels(efc$c172code)
)
marginaleffects::avg_predictions(fit, variables = at_list, vcov = TRUE)[c("conf.low", "conf.high")]
#> 
#>  CI low CI high
#>    10.7    12.2
#>    11.0    12.2
#>    11.4    12.9
#>    10.8    12.2
#>    11.1    12.2
#>    11.5    12.9
#>    10.9    12.3
#>    11.2    12.3
#>    11.6    13.0
#>    10.9    12.3
#>    11.2    12.3
#>    11.6    13.1
#> 
#> Columns: conf.low, conf.high
marginaleffects::avg_predictions(fit, variables = at_list, vcov = "HC0")[c("conf.low", "conf.high")]
#> Warning: Unable to extract a variance-covariance matrix using this `vcov`
#>   argument. Standard errors are computed using the default variance
#>   instead. Perhaps the model or argument is not supported by the
#>   `sandwich` or `clubSandwich` packages. If you believe that the model is
#>   supported by one of these two packages, you can open a feature request
#>   on Github.
#> 
#>  CI low CI high
#>    10.7    12.2
#>    11.0    12.2
#>    11.4    12.9
#>    10.8    12.2
#>    11.1    12.2
#>    11.5    12.9
#>    10.9    12.3
#>    11.2    12.3
#>    11.6    13.0
#>    10.9    12.3
#>    11.2    12.3
#>    11.6    13.1
#> 
#> Columns: conf.low, conf.high
```

<sup>Created on 2023-11-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
> sandwich::vcovHC() does not support objects of this type:

True, not sure why that error message (that is shown in the reprex!) didn't show up interactively.

I'm using version 0.16.0, will install the dev-version to see if `df` changes anything.

**Comment by strengejacke** [comment]
> ```r
> data(efc, package = "ggeffects")
> efc$grp <- datawizard::to_factor(efc$e15relat)
> efc$e42dep <- datawizard::to_factor(efc$e42dep)
> efc$c172code <- datawizard::to_factor(efc$c172code)
> fit <- lme4::lmer(neg_c_7 ~ c12hour + e42dep + c161sex + c172code + (1 | grp), data = efc)
> at_list <- list(
>   c12hour = c(10, 20, 30, 40),
>   c172code = levels(efc$c172code)
> )
> marginaleffects::avg_predictions(fit, variables = at_list, df = Inf)[c("conf.low", "conf.high")]
> #> 
> #>  CI low CI high
> #>    10.7    12.2
> #>    11.0    12.2
> #>    11.4    12.9
> #>    10.8    12.2
> #>    11.1    12.2
> #>    11.5    12.9
> #>    10.9    12.3
> #>    11.2    12.3
> #>    11.6    13.0
> #>    10.9    12.3
> #>    11.2    12.3
> #>    11.6    13.1
> #> 
> #> Columns: conf.low, conf.high
> marginaleffects::avg_predictions(fit, variables = at_list, df = 20)[c("conf.low", "conf.high")]
> ```

Yes, I saw it later, else I probably realized that before ;-)

According to the df-issue: maybe it already worked with version 0.16.0, but `df = Inf` and `df = 20` made no difference in the output (which is rounded to 1 digit). Only after using `df = 5` I could see different values.

In either case, it seems that it indeed work and my reprex was coincidentally not well enough to show the different results.

**Comment by vincentarelbundock** [comment]
cool cool.

FYI, you can print with more digits with something like: `predictions(fit) |> print(digits=8)`

**Comment by strengejacke** [comment]
> FYI, you can print with more digits with something like: predictions(fit) |> print(digits=8)

Yeah, I should have tried this before opening an issue here, but I somehow expected larger differences than just changes in the second or later digits ;-)

**Comment by strengejacke** [comment]
Just a final note: isn't _clubSandwich_ expected to support _lme4_? (https://cran.r-project.org/web/packages/clubSandwich/index.html)

**Comment by vincentarelbundock** [comment]
Yes, but `clubSandwich` does not do HC0 (I think).

You can always feed your own vcov function or matrix...
