### ISSUE TITLE
Comparison contrast ordering

### ISSUE THREAD

**Issue by carlislerainey** [vincentarelbundock/marginaleffects#959]
I found (what I think might be) and inconsistency between the documentation and the implementation. When I switch the order of the supplied contrasts, the result does not change. The contrast seems to be `hi - lo` always. This might be desirable, but the documentation states: 

> Numeric vector of length 2: Contrast between the 2nd element and the 1st element of the x vector.

Based on the documentation above, I expected the code below to produce differences with opposite signs. Instead, they are the same.

```
library(marginaleffects)

mod <- lm(mpg ~ hp, data = mtcars)

# "low" = 90; "high" = 100
comparisons(mod, variables = list(hp = c(90, 100)), 
            newdata = "mean")

# contrast reversed: "low" = 100; "high" = 90
# - note 1: result doesn't change
# - note 2: from the ?comparisons: Numeric vector of 
#   length 2: Contrast between the 2nd element and the 
#   1st element of the x vector.
comparisons(mod, variables = list(hp = c(100, 90)), 
            newdata = "mean")
```

<img width="446" alt="image" src="https://github.com/vincentarelbundock/marginaleffects/assets/1969854/dc6ba017-2244-4c37-8325-e212bbd806db">

Screenshot of relevant documentation below.

<img width="847" alt="image" src="https://github.com/vincentarelbundock/marginaleffects/assets/1969854/5c06ef5e-bf05-4798-b6c9-ffc0ab331ba1">

**Comment by vincentarelbundock** [comment]
Thanks for spotting this. I think this is due to the `sort()` call on this line:

https://github.com/vincentarelbundock/marginaleffects/blob/main/R/get_contrast_data_numeric.R#L85

Should I remove the `sort()` to bring the behavior in line with the documentation, or modify the documentation? (I guess the first option is more flexible.)

**Comment by carlislerainey** [comment]
Some considerations: 

1. The current behavior is consistent with the `hi` and `lo` terminology in `?comparisons`. If you change the behavior, it will make `hi` and `lo` confusing, since `lo` could be larger than `hi`.
1. It seems harder for users to make mistakes with the current implementation. It will be easy for users to put the high and low values in the wrong position if you change the implementation. 
2. Changing the behavior is a breaking change.

Consider this a vote for updating the documentation, I think.

It's easy to do what I wanted with this:

```
# here's how we forced the low - high comparison
comparisons(mod, variables = list(hp = c(90, 100)), 
            newdata = "mean", 
            comparison = \(hi, lo) lo - hi)
```

**Comment by vincentarelbundock** [comment]
All good points (especially breaking change). Documentation improved here:

f38a167c1e
