### ISSUE TITLE
joint hypotheses support for models mixed models vit fia nlme::lme()

### ISSUE THREAD

**Issue by stefgehrig** [vincentarelbundock/marginaleffects#960]
Running joint hypotheses (e.g., via approximate F tests) on the fixed effects of a linear mixed model via `hypotheses()` fails, when a model from `nlme::lme()` is fed.

This can be easily reproduced:

library(nlme)
library(marginaleffects)

fm1 <- lme(distance ~ age + Sex, data = Orthodont)

hypotheses(
  fm1,
  "age = 0") # works

hypotheses(
  fm1,
  hypothesis = c(0,0),
  joint = c("SexFemale", "age")) # does not work

The reason is that `coef(object)` does not return what the internal function `joint_test()` expects. However, it works on what is returned by `fixef(object)`. This is the hack I used for my current project, overwriting the internal function `joint_test()` with a slightly modified version. There might be more generic solutions to this.

This does not yet solve some important statistical issues related to the support of joint tests for `nlme::lme()`  objects (for example the approximation used for the denimonator degrees of freedom in a joint F test with fixed effects that vary on different hierarchical levels. Not sure what to do here, as the Pinheiro & Bates, 2000, p. 91, method implemented in nlme() gives different df).

R version 4.3.2 (2023-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22621)

Matrix products: default

locale:
[1] LC_COLLATE=English_Germany.utf8  LC_CTYPE=English_Germany.utf8    LC_MONETARY=English_Germany.utf8
[4] LC_NUMERIC=C                     LC_TIME=English_Germany.utf8    

time zone: Europe/Berlin
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] marginaleffects_0.16.0 nlme_3.1-163          

loaded via a namespace (and not attached):
 [1] lme4_1.1-35.1       backports_1.4.1     numDeriv_2016.8-1.1 bbmle_1.0.25        Matrix_1.6-3       
 [6] lattice_0.21-9      coda_0.19-4         splines_4.3.2       generics_0.1.3      stats4_4.3.2       
[11] mvtnorm_1.2-3       performance_0.10.8  nloptr_2.0.3        grid_4.3.2          data.table_1.14.8  
[16] emdbook_1.3.13      compiler_4.3.2      plyr_1.8.9          boot_1.3-28.1       rstudioapi_0.15.0  
[21] tools_4.3.2         checkmate_2.3.0     minqa_1.2.6         bdsmatrix_1.3-6     Rcpp_1.0.11        
[26] MASS_7.3-60         insight_0.19.6

**Comment by vincentarelbundock** [comment]
Thanks again for raising this issue. It appears to work in the latest version of `marginaleffects` from Github.

Frankly, I don’t have enough expertise in this model type to resolve the degrees of freedom issue. If you have a specific —and actionable— recommendation with supporting literature, I’d be happy to consider it. Feel free to open a new issue if that’s the case.

``` r
library(nlme)
library(marginaleffects)
fm1 <- lme(distance ~ age + Sex, data = Orthodont)

hypotheses(
    fm1,
    hypothesis = c(0, 0),
    joint = c("SexFemale", "age")) 
# 
# 
# Joint hypothesis test:
# SexFemale = 0
# age = 0
#  
# Joint hypothesis test:
# SexFemale = 0
# age = 0
#  
#     F Pr(>|F|) Df 1 Df 2
#  58.2   <0.001    2  105
# 
# Columns: statistic, p.value, df1, df2
```

**Comment by stefgehrig** [comment]
Cool, thanks! Now the extraction of the coefficient estimates works, I tested it.
I'm not convinced all of these tests do what they are supposed to do, though. Sorry, I could have noticed that earlier before you were changing the code. Look at this, and compare the results to the `anova()` from `{nlme}`.

````
library(devtools)
install_github("vincentarelbundock/marginaleffects")
library(marginaleffects)

############
### nlme ###
############
library(nlme)
fm1 <- lme(fixed = distance ~ age + Sex, 
           random = ~ 1 | Subject,
           data = Orthodont)

hypotheses(
  fm1,
  hypothesis = c(0),
  joint = c("SexFemale")) # wrong ddf

hypotheses(
  fm1,
  hypothesis = c(0),
  joint = c("age")) # wrong ddf

hypotheses(
  fm1,
  hypothesis = c(0, 0),
  joint = c("age", "SexFemale")) # wrong ddf

anova(fm1, Terms = 2) # correct ddf
anova(fm1, Terms = 3) # correct ddf
anova(fm1, Terms = 2:3) # conflicting ddf; throws error
````
The `hypotheses()` function uses the wrong denominator df throughout all tests. It acts as if all observations were independent and gives too liberal test results. Surely there is a simple way to extract the correct df from the model object, which computes them anyway (these are exactly the df described in Pinheiro & Bates, 2000, p. 91). That will be a quick fix.

For the case that I mentioned in the original post (conflicting df when testing joint hypotheses across multiple levels), the internal function of the package apparently has a clear solution (see code chunk): do not allow it. So probably your package should overtake that behavior.

**Comment by vincentarelbundock** [comment]
Thanks for the note, I appreciate it.

I'll need to think about this a bit, but at minimum we should raise a warning. There could also be an argument to specify degrees of freedom manually. 

I'm not sure we can be smart about computing correct degrees of freedom for every kind of model supported here (100+); that would be a never ending time sink. But at least giving the option to set it manually would be useful.

**Comment by huftis** [comment]
> I'm not sure we can be smart about computing correct degrees of freedom for every kind of model supported here (100+); that would be a never ending time sink.

Even the *model fitting packages* have problems figuring out the correct degrees of freedom, even in simple cases. See for example this discussion on the calculation of degrees of freedom for (what basically amounts to) a paired *t*-test:
https://stat.ethz.ch/pipermail/r-sig-mixed-models/2015q1/023165.html

See also this FAQ: https://bbolker.github.io/mixedmodels-misc/glmmFAQ.html#why-doesnt-lme4-display-denominator-degrees-of-freedomp-values-what-other-options-do-i-have

**Comment by vincentarelbundock** [comment]
Thanks for the links. 

We already have a `df` argument elsewhere, and it should be available in `hypotheses()`, possibly allowing for a vector of length 2. But beyond that, I frankly don't really want to be making opinionated choices about how to handle every conceivable model.

**Comment by vincentarelbundock** [comment]
Thanks both for your insights into this! Sorry it took a while, but I really didn't know what to do. In the end, I chose the past of least effort:

1. Raise a warning for `lme()` models
2. Allow users to specify `df` as a vector of lenght 2 manually.

I'd be happy to discuss other approaches if someone can suggest better rules of thumb, but this is all I'm likely to do about this for the foreseeable future, due to time and expertise constraints on my end.
