### ISSUE TITLE
Support mmrm

### ISSUE THREAD

**Issue by lang-benjamin** [vincentarelbundock/marginaleffects#963]
This is referring to issue #570. There is a new release of the `mmrm` package and now there is a `predict()` method with a `newdata` argument. Can you please check, thanks.

**Comment by vincentarelbundock** [comment]
I am very interested in this but don't have the bandwidth to work on this now. I'll close this issue to keep the repo clean, but I have added `mrmm` to the consolidated list of models we want to support.

I will try to take a look eventually, but can't promise fast turnaround.

In the meantime, I'd be very happy to review code submissions.
