### ISSUE TITLE
change position_dodge(width=0.15)

### ISSUE THREAD

**Issue by MilaniC** [vincentarelbundock/marginaleffects#965]
Seeking advice on how to to change the dodge position width for ```plot_predictions()``` from the default=0.15 using ```geom_line```, ```geom_point``` or ```geom_pointrange``` etc. I cannot find a simple way to access the default setting.

**Comment by vincentarelbundock** [comment]
Unfortunately, this setting is hard-coded and there's currently no way for the user to change it. Thankfully, there is a `draw=FALSE` argument which returns the underlying data in the exact structure that `ggplot2` needs to create the plot. If you are already familiar with settins like `position_dodge(width=0.15)`, it should be trivial to reproduce the very simple plots, once you have the data with correct quantities in hand.

**Comment by MilaniC** [comment]
Thanks, that works well to create any complexity of plot directlywith ggplot2.
