### ISSUE TITLE
Example of plotting interaction with missing data

### ISSUE THREAD

**Issue by tci1** [vincentarelbundock/marginaleffects#969]
Apologies if I'm writing this in the wrong place or wrong way. I pretty unfamiliar with github.

I'm trying to apply the `mice` example here:  https://marginaleffects.com/vignettes/multiple_imputation/

library(marginaleffects)
library(mice)

dat_mice <- mice(dat, m = 20, printFlag = FALSE, .Random.seed = 1024)

Let's say my goal is plot the effect of Sepal.Length on Petal.Width as moderated by Species.

mod_mice <- with(dat_mice, lm(Petal.Width ~ Sepal.Length * Species))

I was confused by the example provided because this line ...
mfx_mice <- avg_slopes(mod_mice, by = "Species")
... had by = "Species" but Species was not a moderator in the interaction term in the example.

At any rate, what would I do next to go from this model ...
mod_mice <- with(dat_mice, lm(Petal.Width ~ Sepal.Length * Species))
... to then plotting the interaction visually?

Thanks for your amazing packages and your help.

**Comment by joshua-zh** [comment]
I have the same request. It appears that slopes and plot_predictions can not apply to mira object.

**Comment by vincentarelbundock** [comment]
Well, maybe it could make sense. Anyway, yes, I'd be happy to review a code submission.

**Comment by tci1** [comment]
Thanks for your reply once again. This helps.
