### ISSUE TITLE
`glmmTMB` not supported when `REML = TRUE`?

### ISSUE THREAD

**Issue by strengejacke** [vincentarelbundock/marginaleffects#970]
Just curious, is there a specific reason why REML-fits are not allowed?

``` r
library(glmmTMB)
library(marginaleffects)
m1 <- glmmTMB(
  count ~ mined + (1 | site),
  family = poisson,
  data = Salamanders,
  REML = TRUE
)
predictions(
  m1,
  newdata = datagrid(model = m1, by = "mined"),
  vcov = insight::get_varcov(m1)
)
#> Error: Uncertainty estimates cannot be computed for `glmmTMB` models with the
#>   `REML=TRUE` option. Either set `REML=FALSE` when fitting the model, or
#>   set `vcov=FALSE` when calling a `slopes` function to avoid this error.
```

<sup>Created on 2023-11-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by vincentarelbundock** [comment]
I can't remember exactly, but IIRC, I needed to modify `m1$fit$par$beta` for predictions to be affected by a `set_coef.glmmTMB()`, but those are not in the model object when `REML=TRUE`. I think this is one of those cases where I didn't have time to figure something out and switched the feature off until I found some time or information.

https://github.com/vincentarelbundock/marginaleffects/blob/main/R/methods_glmmTMB.R#L47

**Comment by strengejacke** [comment]
Ah, I see. It's `m1$fit$par`, which returns a vector of parameters. Can't you fallback to `fixef()` for REML-models, or just "fill in" the missing information in `m1$fit$par` with those from `fixef()`? Tagging @bbolker...

``` r
library(glmmTMB)
m1 <- glmmTMB(
  count ~ mined + (1 | site),
  family = poisson,
  data = Salamanders,
  REML = FALSE
)

fixef(m1)
#> 
#> Conditional model:
#> (Intercept)      minedno  
#>      -1.505        2.264
m1$fit$par
#>       beta       beta      theta 
#> -1.5053251  2.2644134 -0.5519004
```

<sup>Created on 2023-12-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by vincentarelbundock** [comment]
And I know there are built-in features for getting uncertainty around predictions, but we need to do something similar for slopes, contrasts, etc.

**Comment by strengejacke** [comment]
Ok. That means it would help if something is changed on the glmmTMB side, right? Unless there's a good reason why the coefficients are not saved in the `$par` slot for `REML = TRUE`.

**Comment by bbolker** [comment]
Briefly:

- the reason that `$par` doesn't have the fixed effect coefficients in the `REML=TRUE` case is that they're actually treated internally as random-effects components in this case (and are estimated in a different way).
- as has possibly been previously commented, `predict.glmmTMB` does have a `newparams=` argument.
- there may still be some surprises about prediction based on random effects or not (e.g. see `extend_re_form` branch) ...

**Comment by vincentarelbundock** [comment]
Thanks a lot for these thoughts @bbolker. Very useful.

> * as has possibly been previously commented, `predict.glmmTMB` does have a `newparams=` argument.

Right, this would certainly be the best way to approach the problem. It would require some infrastructure change (or hack), but I can probably make it work. I'll let @strengejacke know if/when I can figure this out.

**Comment by vincentarelbundock** [comment]
https://github.com/vincentarelbundock/marginaleffects/issues/810

Closing as quasi-duplicate
