### ISSUE TITLE
Vignette: Interactions

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/marginaleffects#972]
We need a full fledged on interpreting interactions. Could be a standalone page in the case study section.

**Comment by vincentarelbundock** [comment]
Ping John Kubale.

**Comment by jkubale** [comment]
Thanks for the ping! I've attached a very basic reference I threw together for some students that I have been thinking about translating to marginaleffects in case it might be a useful place to start.

[interaction_interp.pdf](https://github.com/vincentarelbundock/marginaleffects/files/13719497/interaction_interp.pdf)

**Comment by vincentarelbundock** [comment]
Thanks! Looks great. I probably won`t look at this until after the holidays, but I'm excited about this.
