### ISSUE TITLE
Negative probabilities in conf.low when using `predictions(mod, type = "response")`

### ISSUE THREAD

**Issue by sjwild** [vincentarelbundock/marginaleffects#973]
I'm using `predictions()` to generate predictions from a logistic regression model, and I noticed that I received some negative probabilities in `conf.low` when generating predictions using `predictions(mod, type = "response")`. While I caught it (always plot your data :-p), I thought I would flag it in case someone else does not.

Here is a reproducible example:

```
library(marginaleffects)


# generate data
set.seed(12345)
a <- -4.2 # intentionally generate rare events
b <- .5
N <- 1000
x <- runif(N, -1, 1)
y_star <- a + b * x
y <- rbinom(N, 1, plogis(y_star))


# logistic regression
d <- data.frame(y = y,
                x = x)
mod <- glm(y ~ x, data = d, family = binomial())


# predictions
preds <- predictions(mod, type = "response")
summary(preds$conf.low) # negative probs
#Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
#-0.001443  0.002075  0.008458  0.007476  0.012739  0.013808 

# Generate session info
sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS 13.0

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] marginaleffects_0.16.0.9017

loaded via a namespace (and not attached):
 [1] compiler_4.1.2    backports_1.4.1   cli_3.6.1         generics_0.1.3    tools_4.1.2      
 [6] rstudioapi_0.13   Rcpp_1.0.11       data.table_1.14.8 insight_0.19.7.4  checkmate_2.1.0  
[11] rlang_1.1.1  
```

**Comment by vincentarelbundock** [comment]
`type="response"` computes standard errors with the delta method directly on the probability scale, and builds intervals, and then builds symmetric intervals as 1.96 * blah blah.

What you want is probably the default for `glm()` models: `type="invlink(link)"`. This computes standard errors on the links scale, creates symmetric intervals, and then backtransforms them to the response scale.

Note that this kind of backtransformation is only available for a few specific model classes.

**Comment by sjwild** [comment]
I figured it had something to do with the delta method, but wasn't sure. After noticing the negative probabilities, I used `type="invlink(link)"` and it was fine.

I didn't notice anything about it in the standard error section of the Marginal Effects Zoo (note: the listed website when using `?predictions` is incorrect. You are directed to https://marginaleffects.com/articles/uncertainty.html, where the actual website is now https://marginaleffects.com/vignettes/uncertainty.html). Is it worth including a note in either place that you may get predictions that are out of bounds due to the method? Happy to add in a few sentences and initiate a pull request if it helps.

I may also have missed anything you wrote about it.

**Comment by vincentarelbundock** [comment]
Text of `?predictions()` now says: 

> The invlink(link) is a special type defined by marginaleffects. It is available for some (but not all) models and functions. With this link type, we first compute predictions on the link scale, then we use the inverse link function to backtransform the predictions to the response scale. This is useful for models with non-linear link functions as it can ensure that confidence intervals stay within desirable bounds, ex: 0 to 1 for a logit model. Note that an average of estimates with type=“invlink(link)” will not always be equivalent to the average of estimates with type=“response”.

I'd be happy to merge more documentation as needed, but will close this as solved for now.
