### ISSUE TITLE
Update benchmarks in "Performance" article?

### ISSUE THREAD

**Issue by etiennebacher** [vincentarelbundock/marginaleffects#975]
The benchmarks start to be a bit old, especially those comparing the performance of `marginaleffects` and `margins` (last run on 2022-04-04): https://marginaleffects.com/vignettes/performance.html#speed-comparison

FYI, when I compute the standard errors (last benchmark), I find that `marginaleffects` is 600 times faster (!) than `margins`

**Comment by vincentarelbundock** [comment]
Thanks for the nudge. I got 1000x on a single run of that last benchmark, so I'll keep that one 😂

599705052f80210a7e7f247ea3bc53c2d4470269
