### ISSUE TITLE
Feature Request - Change Comparison by Class

### ISSUE THREAD

**Issue by davidaarmstrong** [vincentarelbundock/marginaleffects#980]
Perhaps this is already possible and I haven't figured it out, but consider the following example: 

``` r
library(marginaleffects)
data(mtcars)
mtcars$cyl <- as.factor(mtcars$cyl)
mtcars$am <- as.factor(mtcars$am)
mod <- lm(qsec ~ wt + hp + drat + cyl + am, data=mtcars)

avg_comparisons(mod, variables = list(wt ="2sd", hp = "2sd", drat = "2sd", 
                                      am = "pairwise", cyl="pairwise"))
#> 
#>  Term            Contrast Estimate Std. Error      z Pr(>|z|)    S  2.5 %
#>  am   1 - 0                 -1.510      0.526 -2.869  0.00412  7.9 -2.542
#>  cyl  6 - 4                 -1.946      0.526 -3.700  < 0.001 12.2 -2.977
#>  cyl  8 - 4                 -3.377      0.869 -3.888  < 0.001 13.3 -5.079
#>  cyl  8 - 6                 -1.431      0.624 -2.295  0.02176  5.5 -2.653
#>  drat (x + sd) - (x - sd)   -0.401      0.530 -0.755  0.44999  1.2 -1.440
#>  hp   (x + sd) - (x - sd)   -1.534      0.670 -2.291  0.02194  5.5 -2.846
#>  wt   (x + sd) - (x - sd)    1.405      0.616  2.281  0.02258  5.5  0.197
#>  97.5 %
#>  -0.478
#>  -0.915
#>  -1.675
#>  -0.209
#>   0.639
#>  -0.222
#>   2.612
#> 
#> Columns: term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high 
#> Type:  response
```

<sup>Created on 2023-12-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

It would be neat if we could do the same thing, but set the contrast by class, for example: 

```r
avg_comparisons(mod, list(numeric = "2sd", factor = "pairwise"))
```

which would show the average comparison for all numeric variables at +/- 1sd and all factor variables with pairwise contrasts.

**Comment by vincentarelbundock** [comment]
Thanks a lot for raising this issue, @davidaarmstrong. It’s a fun and interesting suggestion. Part of me likes it a lot.

I don’t have a really strong argument against, but I do have a small gut reaction that there is something “unclean” about overloading the interface like this (`marginaleffects` abuses this already), with list names that could be either variables or class names. Would that lead to confusion for users? I’m not sure. What if someone names columns “factor” or “numeric”? That would of course be bad practice, but users do dumb stuff all the time... Do I want to spend time figuring out how to guard against such cases? I’m not sure.

Again, I don’t think those are super strong arguments against, but I’ll have to think about it a bit. (Open to counters!)

Also note that the beauty of accepting lists in the `variables` argument is that it’s trivial to do this:

``` r
library(marginaleffects)
data(mtcars)
mtcars$cyl <- as.factor(mtcars$cyl)
mtcars$am <- as.factor(mtcars$am)
mod <- lm(qsec ~ wt + hp + drat + cyl + am, data=mtcars)

f <- \(x) ifelse(is.numeric(mtcars[[x]]), "2sd", "pairwise")
v <- as.list(sapply(names(mtcars), f))[insight::find_variables(mod)$conditional]
avg_comparisons(mod, variables = v)
# 
#  Term            Contrast Estimate Std. Error      z Pr(>|z|)    S  2.5 % 97.5 %
#  am   1 - 0                 -1.510      0.526 -2.869  0.00412  7.9 -2.542 -0.478
#  cyl  6 - 4                 -1.946      0.526 -3.700  < 0.001 12.2 -2.977 -0.915
#  cyl  8 - 4                 -3.377      0.869 -3.888  < 0.001 13.3 -5.079 -1.675
#  cyl  8 - 6                 -1.431      0.624 -2.295  0.02176  5.5 -2.653 -0.209
#  drat (x + sd) - (x - sd)   -0.401      0.530 -0.755  0.44999  1.2 -1.440  0.639
#  hp   (x + sd) - (x - sd)   -1.534      0.670 -2.291  0.02194  5.5 -2.846 -0.222
#  wt   (x + sd) - (x - sd)    1.405      0.616  2.281  0.02258  5.5  0.197  2.612
# 
# Columns: term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high 
# Type:  response
```

**Comment by davidaarmstrong** [comment]
You make some good arguments, @vincentarelbundock, perhaps the best being that you don't want to have to build around edge cases where users do something unexpected, like name a variable "factor".  I also see the beauty of using a list like you suggest in your example - I'll stick wit that for now.  Thanks for thinking about it!
