### ISSUE TITLE
Obtaining contrasts from pre-post model with a continuous covariate

### ISSUE THREAD

**Issue by andymilne** [vincentarelbundock/marginaleffects#988]
I have the following (Bayesian) model formula: 
`Score ~ TstTm + TstTm:Cndtn * Age_sc + (1 | Ptcpnt)`

Where `Score` are pre- and post-test scores, `TstTm` is binary and indicates whether the score is pre (0) or post (1), `Cndtn` is a factor indicating the treatment (there are four different treatments). For each `Cndtn`, I want to use `avg_predictions()` to provide data to plot the average pre-post change as a function of `Age_sc` (standardized). I have tried the following:

```
avg_predictions(
  newdata = datagridcf(Age_sc = seq(-2, 2, 0.1)),
  mdl_WchslrIntl,
  variables = "Cndtn",
  by = c("Age_sc", "Cndtn", "TstTm")
)
```
which gives

```
TstTm Age_sc Cndtn Estimate 2.5 % 97.5 %
     0     -2    PC    11.41  9.54   13.4
     1     -2    PC    13.97 11.45   16.5
     0     -2    QR    11.41  9.54   13.4
     1     -2    QR    13.45  9.96   17.0
     0     -2    TK    11.41  9.54   13.4
--- 318 rows omitted. See ?print.marginaleffects --- 
     1      2    QR    10.94  7.41   14.6
     0      2    TK     8.44  6.80   10.3
     1      2    TK     9.83  6.65   13.4
     0      2    NG     8.44  6.80   10.3
     1      2    NG    13.50  9.59   17.4
Columns: Age_sc, Cndtn, TstTm, estimate, conf.low, conf.high 
Type:  response 
```

I need to subtract every odd row from the following even row to obtain the change scores. However, it seems I cannot use the hypothesis argument because it is limited to no more than 25 rows (and, even if this were possible, building the contrast matrix would not be much fun). I cannot see any other way to do this in marginaleffects. Apologies if I have missed something.

**Comment by vincentarelbundock** [comment]
I don't have time to look into this right now, but maybe something like this could work:

https://marginaleffects.com/vignettes/hypothesis.html#complex-aggregations
