### ISSUE TITLE
Some examples on the website are not run

### ISSUE THREAD

**Issue by etiennebacher** [vincentarelbundock/marginaleffects#991]
Just in case you didn't notice, some pages do not execute examples (e.g [`slopes()`](https://marginaleffects.com/man/slopes.html#examples)) and others do (e.g [`plot_slopes()`](https://marginaleffects.com/man/plot_slopes.html#examples)).

Not sure whether this is the same as #966

**Comment by vincentarelbundock** [comment]
Thanks, but yes that's a duplicate.
