### ISSUE TITLE
s.value equals to Inf when using hypotheses

### ISSUE THREAD

**Issue by StarryCatte** [vincentarelbundock/marginaleffects#993]
I'm using `hypotheses` function to test the equality between two coefficients. I have noticed that the `s.value = Inf` in some cases, while there is no warning or error occured. 
I'm very confused about why this is happened and whether it leads to the unreliable results.

Here is an example using `mtcars` dataset.
```
library(marginaleffects)
data(mtcars)

mod <- lm(mpg ~ hp + wt + factor(cyl), data = mtcars)
hypotheses(mod, hypothesis = "b* / b3 = 1")

#        Term  Estimate Std. Error         z Pr(>|z|)    S  2.5 % 97.5 %
# b1 / b3 = 1 -12.26735    2.07340   -5.9165   <0.001 28.2 -16.33 -8.204
# b2 / b3 = 1  -0.99273    0.00413 -240.5539   <0.001  Inf  -1.00 -0.985
# b3 / b3 = 1   0.00000         NA        NA       NA   NA     NA     NA
# b4 / b3 = 1   0.05583    0.58287    0.0958    0.924  0.1  -1.09  1.198
# b5 / b3 = 1   0.00141    0.82981    0.0017    0.999  0.0  -1.62  1.628

Columns: term, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high
```
The above situation occurs when testing hypothesis `b2 / b3 = 1`.

**Comment by vincentarelbundock** [comment]
Z is very very large, p is tiny, and S is absolutely massive. I don't think there's any problem here.
