### ISSUE TITLE
Weighted means with survey::svyglm or not?

### ISSUE THREAD

**Issue by tslumley** [vincentarelbundock/marginaleffects#997]
Hi!

As the `survey` package maintainer I was asked why `marginaleffects::predictions` didn't agree exactly with `survey::svypredmeans()`. I believe the reason is that `predictions` reports *unweighted* averages and `svypredmeans` reports weighted averages using sampling weights.  In `svypredmeans` I'm using what you call `counterfactual` data. That is, I have grouping variables and adjustment variables. For each value of the grouping variables I create data that's a copy of the values of the adjustment variables for the whole data set. 

Here's an example where `svypredmeans` disagrees with `predictions`, but agrees if the sampling weights are specified.

```
library(survey)
data(nhanes, package="survey")
nhanes_design <- svydesign(id=~SDMVPSU, strata=~SDMVSTRA, weights=~WTMEC2YR, nest=TRUE,data=nhanes)
agesexmodel<-svyglm(HI_CHOL~agecat+RIAGENDR, design=nhanes_design,family=quasibinomial)

## high cholesterol by race/ethnicity, adjusted for demographic differences
svypredmeans(agesexmodel, ~factor(race),predictat=as.factor(1:4))

library(marginaleffects)

agesexracemodel<-svyglm(HI_CHOL~agecat+RIAGENDR+factor(race), design=nhanes_design,family=quasibinomial)
## apparently*unweighted* average, doesn't agree with svypredmeans
predictions(agesexracemodel, by="race", newdata=datagrid(race=1:4, grid_type="counterfactual"))

w<-weights(agesexracemodel$survey.design,"sampling")
## weighted average, does agree
predictions(agesexracemodel, by="race", newdata=datagrid(race=1:4, grid_type="counterfactual"),wts=rep(w,4))
```
The point of this issue is twofold. First, it means we'll all know what's going on the next time a difference is reported.  
Second, I want to find out if the use of unweighted averages is deliberate in `marginaleffects`. If it is, I'll add a note to the help page for `svypredmeans` explaining that they are different; if you plan to change to weighted averages, I won't.

**Comment by vincentarelbundock** [comment]
Thanks for raising this issue, @tslumley, and thanks for taking the time to investigate. I appreciate it.

I'm not sure if this counts as "deliberate", but it is true that predictions are always unweighted unless the `wts` argument is used explicitly. This behavior is consistent across all object classes.

My gut reaction is to think that we probably should *not* insert the weights without user input, because such auto-magic behavior breaks the consistency with which objects are treated. However, given that `survey` users will (nearly?) always want to use weights, I can see this being a common mistake.

One thing I could do is raise a warning when the `wts` is not specified. This would only involve creating a `sanitize_model_specific.CLASSNAME()` method [like this one,](https://github.com/vincentarelbundock/marginaleffects/blob/632dfc5bb831c30c79e53fc6cfe17b17bcb9c35b/R/methods_glmmTMB.R#L62) and storing it 
in [`R/methods_survey.R`](https://github.com/vincentarelbundock/marginaleffects/blob/632dfc5bb831c30c79e53fc6cfe17b17bcb9c35b/R/methods_survey.R)

Would this be a satisfactory solution?

I'm open to counter-arguments and alternative suggestions, obviously.

**Comment by tslumley** [comment]
Yes, I think a warning might be helpful.  I'll add a note to `?svypredmeans` as well

**Comment by larmarange** [comment]
Maybe adding an example in the documentation could be also relevant. ;-)

**Comment by vincentarelbundock** [comment]
Good. The development version from Github should now raise a warning when `wts` is not supplied, but not when it is. This will be part of the next CRAN release in a few weeks.

``` r
library(survey)
data(nhanes, package="survey")
nhanes_design <- svydesign(id=~SDMVPSU, strata=~SDMVSTRA, weights=~WTMEC2YR, nest=TRUE,data=nhanes)
agesexmodel<-svyglm(HI_CHOL~agecat+RIAGENDR, design=nhanes_design,family=quasibinomial)

## high cholesterol by race/ethnicity, adjusted for demographic differences
svypredmeans(agesexmodel, ~factor(race),predictat=as.factor(1:4))
#>       mean     SE
#> 1 0.123081 0.0058
#> 2 0.114596 0.0065
#> 3 0.084718 0.0106
#> 4 0.108770 0.0304

library(marginaleffects)

agesexracemodel<-svyglm(HI_CHOL~agecat+RIAGENDR+factor(race), design=nhanes_design,family=quasibinomial)

# warning
predictions(agesexracemodel, by="race", newdata=datagrid(race=1:4, grid_type="counterfactual"))
#> Warning: With models of this class, it is normally good practice to
#> specify weights using the `wts` argument. Otherwise, weights will be
#> ignored in the computation of quantities of interest.
#> 
#>  race Estimate Std. Error     z Pr(>|z|)     S  2.5 % 97.5 %
#>     1   0.1120    0.00511 21.91   <0.001 351.0 0.1019 0.1220
#>     2   0.1042    0.00574 18.15   <0.001 242.2 0.0930 0.1155
#>     3   0.0770    0.00990  7.78   <0.001  46.9 0.0576 0.0964
#>     4   0.0989    0.02767  3.58   <0.001  11.5 0.0447 0.1531
#> 
#> Columns: race, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high 
#> Type:  response


# no warning
w<-weights(agesexracemodel$survey.design,"sampling")
predictions(agesexracemodel, by="race", newdata=datagrid(race=1:4, grid_type="counterfactual"),wts=rep(w,4))
#> 
#>  race Estimate Std. Error     z Pr(>|z|)     S  2.5 % 97.5 %
#>     1   0.1231    0.00574 21.45   <0.001 336.5 0.1118  0.134
#>     2   0.1146    0.00641 17.88   <0.001 235.1 0.1020  0.127
#>     3   0.0847    0.01054  8.04   <0.001  49.9 0.0641  0.105
#>     4   0.1088    0.03037  3.58   <0.001  11.5 0.0492  0.168
#> 
#> Columns: race, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high 
#> Type:  response
```

**Comment by kburchfiel** [comment]
This is a very helpful explanation! I myself was wondering why the output of my predictions() calls weren't matching my svypredmeans() calls. Perhaps a note about this (or, at least, a link to this thread) could be added to the marginal means documentation? That might help avoid some confusion for other newcomers to this library who are working with weighted survey datasets.
